### PR TITLE
Fix suspicious comment in SortedList

### LINKED ISSUE #7230: Suspicious code in SortedList
Reading the commit logs I find [this code](https://github.com/dotnet/corefx/blob/39a8b7dc241d536653b20066ffe69698e04f82ab/src/System.Collections/src/System/Collections/Generic/SortedList.cs#L164) suspicious:

                    Array.Sort<TKey, TValue>(keys, _values, comparer);
                    comparer = Comparer; // obtain default if this is null.

Either the assignment does nothing (which I think is the case) or the sorting and the following usage of `comparer` are using different comparer which would be a bug.

### PR DESCRIPTION
**Pull request by hughbe**
Fixes #7230

/cc @JonHanna @stephentoub @GSPP

### CODE REVIEW

File: src/System.Collections/src/System/Collections/Generic/SortedList.cs [hunk 1]
```diff
@@ -161,11 +161,11 @@ public SortedList(IDictionary<TKey, TValue> dictionary, IComparer<TKey> comparer
...
                 if (count > 1)
                 {
-                    Array.Sort<TKey, TValue>(keys, _values, comparer);
-                    comparer = Comparer; // obtain default if this is null.
+                    // Comparer is set to the default if the comparer parameter is null
+                    Array.Sort<TKey, TValue>(keys, _values, Comparer);
                     for (int i = 1; i != keys.Length; ++i)
                     {
-                        if (comparer.Compare(keys[i - 1], keys[i]) == 0)
+                        if (Comparer.Compare(keys[i - 1], keys[i]) == 0)
```
Comment (JonHanna) [inline src/System.Collections/src/System/Collections/Generic/SortedList.cs]: Will the jitter optimise this, or will it do the n-1 field accesses this suggests?

Comment (GSPP) [inline src/System.Collections/src/System/Collections/Generic/SortedList.cs]: `Comparer.Compare` could change `Comparer` so this can't be optimized.

The range checks are probably also not being optimized out. The old and new JIT differ in what range check patterns they can kill. The new JIT is better but now sure if it can work with a non-zero lower bound and a non-`<` comparison.

If you really want to optimize this further you could cache `keys[i - 1]` in a local variable across iterations so that there will not be two heap loads per iteration.

Comment (JonHanna) [inline src/System.Collections/src/System/Collections/Generic/SortedList.cs]: Are you sure about the range check?

I did have a local for `keys[i - 1]` in an earlier revision of what introduced this, but changed to the current form as it's simpler and perhaps clearer as to the intent.

Comparer isn't readonly so this definitely introduces many field reads. I wonder if they would be optimised out if it was readonly. In any case, all we really need here is to move the assignment back to the local `comparer` above the call to Sort, and perhaps expand the comment a bit.

Comment (GSPP) [inline src/System.Collections/src/System/Collections/Generic/SortedList.cs]: I'm not at all sure about the range check. I have come to recognize this as a problem area, though. The JIT has to reason that `i >= 1` and `i - 1` always `>= 0´. This would be doable in a generalized data flow framework but given the JITs current level of abilities this seems out of range.

            var array1 = GetArray(1000);

            var sum = 0;
            for (int i = 1; i < array1.Length; i++)
            {
                if (array1[i - 1] == array1[i])
                    sum++;
            }

            Sink(sum);

Here, the `i - 1` access range checks on Desktop 4.6.1. `i` is range check free.

Changing to `i != array1.Length` range checks both. Changing to `++i` does not change anything.

Comment (JonHanna) [inline src/System.Collections/src/System/Collections/Generic/SortedList.cs]: That's disconcerting. I'd satisfied myself that `index != array.Length` was okay, but that was a long time ago (framework version 1.1) so it's both possible that it changed, or that I just messed up my experimenting.

Comment (stephentoub) [inline src/System.Collections/src/System/Collections/Generic/SortedList.cs]: Can we just swap the lines as originally discussed? If someone can then demonstrate that there is a measurable impact with additional changes (caching into locals, matching JIT-recognized patterns, etc.), they can be considered then. We're doing a sort, invoking an arbitrary amount of code via an interface call per iteration, etc., and on a code path that's used once per list; until we can demonstrate there's an issue here, doesn't seem like something we need to micro optimize or contort the code for.

Comment (JonHanna) [inline src/System.Collections/src/System/Collections/Generic/SortedList.cs]: Yeah, our comment thread got side-tracked, but can we just change this to flipping the order of the lines, @hughbe?

Comment (hughbe) [inline src/System.Collections/src/System/Collections/Generic/SortedList.cs]: Yup

**Comment by stephentoub** [comment]
LGTM

**Comment by stephentoub** [comment]
Test Innerloop OSX Release Build and Test please
Test Innerloop Ubuntu Debug Build and Test please
Test Innerloop Ubuntu Release Build and Test please
