### PR TITLE
Get System.ComponentModel.Annotations tests passing with netfx

### LINKED ISSUE #17872: Compat bug in System.ComponentModel.Annotations tests for invalid RangeAttribute params
Example test:
```cs
[Theory]
[InlineData(typeof(int), "1", "3")]
[InlineData(typeof(double), "1", "3")]
public static void Validate_CantConvertValueToTargetType_ThrowsException(Type type, string minimum, string maximum)
{
    var attribute = new RangeAttribute(type, minimum, maximum);
    Assert.Throws<Exception>(() => attribute.Validate("abc", new ValidationContext(new object())));
    Assert.Throws<Exception>(() => attribute.IsValid("abc"));
}
```

On netfx this test passes - `Exception` is thrown.
On netcore this test fails - `ValidationException` is thrown.

This was introduced when porting the library to .NET core, as `TypeDescriptor` did not exist.

From the reference source (https://github.com/Microsoft/referencesource/blob/4fe4349175f4c5091d972a7e56ea12012f1e7170/System.ComponentModel.DataAnnotations/DataAnnotations/RangeAttribute.cs#L178-L182):
```cs
TypeConverter converter = TypeDescriptor.GetConverter(type);
IComparable min = (IComparable)converter.ConvertFromString((string)minimum);
IComparable max = (IComparable)converter.ConvertFromString((string)maximum);

Func<object, object> conversion = value => (value != null && value.GetType() == type) ? value : converter.ConvertFrom(value);
```

From the .NET core source (https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/RangeAttribute.cs#L200-L207):
```cs
Func<object, object> conversion =
    value =>
        (value != null && value.GetType() == type)
            ? value
            : Convert.ChangeType(value, type, CultureInfo.CurrentCulture);
var min = (IComparable)conversion(minimum);
var max = (IComparable)conversion(maximum);
Initialize(min, max, conversion);
```

I suggest this is triaged as a .NET core bug. I'm submitting a fix to align it with netfx behaviour.

### LINKED ISSUE #18542: Test: System.ComponentModel.DataAnnotations.Tests.CompareAttributeTests/Validate_Indexer_ThrowsTargetParameterCountException_Netfx failed with "Xunit.Sdk.ThrowsException"
Opened on behalf of @Jiayili1

The test `System.ComponentModel.DataAnnotations.Tests.CompareAttributeTests/Validate_Indexer_ThrowsTargetParameterCountException_Netfx` has failed.

Assert.Throws() Failure\r
    Expected: typeof(System.ArgumentException)\r
    Actual:   typeof(System.Reflection.TargetParameterCountException): Parameter count mismatch.

        Stack Trace:

           at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
       at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
       at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
       at System.ComponentModel.DataAnnotations.CompareAttribute.IsValid(Object value, ValidationContext validationContext)
       at System.ComponentModel.DataAnnotations.ValidationAttribute.GetValidationResult(Object value, ValidationContext validationContext)
       at System.ComponentModel.DataAnnotations.ValidationAttribute.Validate(Object value, ValidationContext validationContext)
       at System.ComponentModel.DataAnnotations.Tests.CompareAttributeTests.<>c__DisplayClass5_0.<Validate_Indexer_ThrowsTargetParameterCountException_Netfx>b__0() in E:\A\_work\93\s\corefx\src\System.ComponentModel.Annotations\tests\CompareAttributeTests.cs:line 50
Build : Master - 20170418.01 (Full Framework Tests)
Failing configurations:
- Windows.10.Amd64
  - x64-Debug
  - x64-Release
  - x86-Release
  - x86-Debug

Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170418.01/workItem/System.ComponentModel.Annotations.Tests/analysis/xunit/System.ComponentModel.DataAnnotations.Tests.CompareAttributeTests~2FValidate_Indexer_ThrowsTargetParameterCountException_Netfx

### PR DESCRIPTION
**Pull request by hughbe**
## Commit 1

Fixes a regression from the full .NET framework when porting the library to .net core

Fixes #17872

## Commit 2

Nerfs tests for fixed bugs and added features

See #2650, #4465 and #5203

## Commit 3

Nerfs tests for .NET core bug. I'm not sure how to fix this one, though!

See #17873

Fixes: #18149 
Fixes: #18150 
Fixes: #18148 
Fixes: #18145 
Fixes: #18146 
Fixes #18542

### CODE REVIEW

File: src/System.ComponentModel.Annotations/tests/MaxLengthAttributeTests.cs [hunk 1]
```diff
@@ -20,25 +20,53 @@ protected override IEnumerable<TestCase> ValidValues()
...
-            yield return new TestCase(new MaxLengthAttribute(15), new List<string>(new string[14]));
-            yield return new TestCase(new MaxLengthAttribute(16), new List<string>(new string[16]));
 
             yield return new TestCase(new MaxLengthAttribute(16), new int[4, 4]);
             yield return new TestCase(new MaxLengthAttribute(16), new string[3, 4]);
+
+            // MaxLengthAttribute in the full .NET framework doesn't support ICollection.Count.
+            // See https://github.com/dotnet/corefx/pull/2650".
+            if (!PlatformDetection.IsFullFramework)
+            {
```
Comment (safern) [inline src/System.ComponentModel.Annotations/tests/MaxLengthAttributeTests.cs]: This makes it a little bit confusing and when this gets fixed in Desktop then we would not be testing that and would be "hard" to find why we are not testing it. It would be better to have 2 tests one for netcore and one for netfx where each one receives its supported input and add SkipOnTargetFramework with the reason why it is skipped.

File: src/System.ComponentModel.Annotations/tests/MaxLengthAttributeTests.cs [hunk 2]
```diff
@@ -20,25 +20,53 @@ protected override IEnumerable<TestCase> ValidValues()
...
             yield return new TestCase(new MaxLengthAttribute(12), "OverMaxLength");
             yield return new TestCase(new MaxLengthAttribute(12), new byte[13]);
-            yield return new TestCase(new MaxLengthAttribute(12), new Collection<byte>(new byte[13]));
-            yield return new TestCase(new MaxLengthAttribute(12), new List<byte>(new byte[13]));
 
             yield return new TestCase(new MaxLengthAttribute(12), new int[4, 4]);
+
+            // MaxLengthAttribute in the full .NET framework doesn't support ICollection.Count.
+            // See https://github.com/dotnet/corefx/pull/2650".
+            if (!PlatformDetection.IsFullFramework)
```
Comment (safern) [inline src/System.ComponentModel.Annotations/tests/MaxLengthAttributeTests.cs]: Same here.

File: src/System.ComponentModel.Annotations/tests/MaxLengthAttributeTests.cs [hunk 3]
```diff
@@ -58,6 +86,16 @@ public static void Ctor_Int(int length)
         }
 
         [Theory]
+        [MemberData(nameof(ValidValues_ICollection))]
+        [MemberData(nameof(InvalidValues_ICollection))]
+        [SkipOnTargetFramework(~TargetFrameworkMonikers.NetFramework, "MaxLengthAttribute in the full .NET framework doesn't support ICollection.Count. See https://github.com/dotnet/corefx/pull/2650")]
+        public void Validate_ICollection_NetFx_ThrowsInvalidCastException(MaxLengthAttribute attribute, object value)
```
Comment (safern) [inline src/System.ComponentModel.Annotations/tests/MaxLengthAttributeTests.cs]: I see you have a Netfx test but I'm missing the netcoreapp tests using this collections.

File: src/System.ComponentModel.Annotations/tests/MinLengthAttributeTests.cs [hunk 4]
```diff
@@ -21,25 +21,52 @@ protected override IEnumerable<TestCase> ValidValues()
             yield return new TestCase(new MinLengthAttribute(12), new int[14]);
             yield return new TestCase(new MinLengthAttribute(16), new string[16]);
 
-            yield return new TestCase(new MinLengthAttribute(0), new Collection<int>(new int[0]));
-            yield return new TestCase(new MinLengthAttribute(12), new Collection<int>(new int[14]));
-            yield return new TestCase(new MinLengthAttribute(16), new Collection<string>(new string[16]));
+            // MinLengthAttribute in the full .NET framework doesn't support ICollection.Count.
+            // See https://github.com/dotnet/corefx/pull/2650".
+            if (!PlatformDetection.IsFullFramework)
```
Comment (safern) [inline src/System.ComponentModel.Annotations/tests/MinLengthAttributeTests.cs]: Same comment here. Can it be done the other way I mentioned earlier?

File: src/System.ComponentModel.Annotations/tests/PhoneAttributeTests.cs [hunk 5]
```diff
@@ -24,6 +24,21 @@ protected override IEnumerable<TestCase> ValidValues()
             yield return new TestCase(new PhoneAttribute(), "425-555-1212 ext.123");
             yield return new TestCase(new PhoneAttribute(), "425-555-1212 ext. 123");
             yield return new TestCase(new PhoneAttribute(), "1");
+
+            // Certain invalid phone numbers are reported as valid with .NET core.
+            // The full .NET framework considers them invalid. This is likely a bug
+            // in .NET core.
+            if (!PlatformDetection.IsFullFramework)
```
Comment (safern) [inline src/System.ComponentModel.Annotations/tests/PhoneAttributeTests.cs]: Could we instead disable the tests with ActiveIssueAttribute? since this is likely a bug in .NET Core? 

cc: @stephentoub

Comment (hughbe) [inline src/System.ComponentModel.Annotations/tests/PhoneAttributeTests.cs]: I'm not sure how to disable individual test data in MemberData, since this is part of a list of tests

File: src/System.ComponentModel.Annotations/tests/MaxLengthAttributeTests.cs (hunk 3 above)
Comment (hughbe) [inline src/System.ComponentModel.Annotations/tests/MaxLengthAttributeTests.cs]: Sorry I'm not sure I understand (this also applies to the comment about the confusion above)

It/when netfx adds the ICollection feature, then this test that is skipped on non-netfx frameworks (I.e runs for netfx) will fail.

The respective netcoreapp test uses the Invalid/Valid_ICollection_TestData in Valid/InvalidValues()

Maybe I could clarify this with a comment?

File: src/System.ComponentModel.Annotations/tests/PhoneAttributeTests.cs (hunk 5 above)
Comment (danmosemsft) [inline src/System.ComponentModel.Annotations/tests/PhoneAttributeTests.cs]: I believe we break the test into two (possibly with a shared body) so they can have different member data.

Comment (hughbe) [inline src/System.ComponentModel.Annotations/tests/PhoneAttributeTests.cs]: I think In the past we've just commented out the test and added a reference to the issue. I can do that if it helps - would also avoid us having to do a bunch of code movement.

Comment (hughbe) [inline src/System.ComponentModel.Annotations/tests/PhoneAttributeTests.cs]: @danmosemsft is that a suggestion or a comment in reply to the question?

File: src/System.ComponentModel.Annotations/tests/MaxLengthAttributeTests.cs (hunk 3 above)
Comment (safern) [inline src/System.ComponentModel.Annotations/tests/MaxLengthAttributeTests.cs]: So what I meant is that we should have to tests (one for netcoreapp and one for netfx) and split the data Enumerable into to different data sets instead of constructing this data sets in runtime depending on the target that we are running on. While building this sets in runtime it makes it confusing to know which data sets work on netcoreapp and which ones on netfx.

See: https://github.com/dotnet/corefx/pull/17618

Does this clarify my comment?

File: src/System.ComponentModel.Annotations/tests/PhoneAttributeTests.cs (hunk 5 above)
Comment (safern) [inline src/System.ComponentModel.Annotations/tests/PhoneAttributeTests.cs]: What I meant was to disable the test that is failing in netcoreapp due to bug: https://github.com/dotnet/corefx/issues/17873

Instead of making this test pass, as with doing that we would be testing a buggy behavior. So we should add [ActiveIssue(17873)] to the netcoreapp test itself instead of hacking the input to have the "expected" behavior which we claim it to be a bug.

Another approach would be skipping the test in netcoreapp and running it on netfx so that we don't loose test coverage in Desktop.

Comment (hughbe) [inline src/System.ComponentModel.Annotations/tests/PhoneAttributeTests.cs]: >Actually I think it is better to just skip this test in netcoreapp and link it to the issue tracking this bug.

I went with that

**Comment by safern** [comment]
I will wait for one of the area owners to be ok with this changes before merging.

**Comment by danmosemsft** [comment]
@divega @lajones @ajcvickers look OK?

**Comment by safern** [comment]
ping @divega @lajones @ajcvickers :)

**Comment by ajcvickers** [comment]
@safern We have some time allocated on Wednesday for Data Annotations issues.

**Comment by lajones** [comment]
I'm not sure we should follow this route. Basically what this does is accept that the NETCore and NETFx versions of this code produce different results (for the same input) and updates the tests to expect that. I think we should be fixing the code so that NETCore and NETFx always produce the same thing. the question then becomes should NETCore reflect NETFx or vice versa. To discuss in triage tomorrow.

**Comment by hughbe** [comment]
I suggest NetCore aligns with netfx - this is typically what we've gone with for issues that aren't bugs in the .NET framework. These aren't really bugs - I've fixed the first incompatability with TypeDescriptor.

For features added and bugs fixed in .NET Core (e.g. ICollection, better validation of contexts) I believe we've been OK with nerfing the tests for .NET framework.

File: src/System.ComponentModel.Annotations/tests/CustomValidationAttributeTests.cs [hunk 6]
```diff
@@ -77,7 +77,17 @@ public static void Constructor(Type validatorType, string method)
         public static void RequiresValidationContext_Get_ReturnsExpected(string method, bool expected)
         {
             CustomValidationAttribute attribute = GetAttribute(method);
-            Assert.Equal(expected, attribute.RequiresValidationContext);
+
+            // The full .NET framework has a bug where CustomValidationAttribute doesn't
+            // validate the context. See https://github.com/dotnet/corefx/pull/5203.
```
Comment (ajcvickers) [inline src/System.ComponentModel.Annotations/tests/CustomValidationAttributeTests.cs]: Please file an issue describing this difference in behavior. (#3794 and #5203 don't seem to have any associated issue.)

File: src/System.ComponentModel.Annotations/tests/CustomValidationAttributeTests.cs [hunk 7]
```diff
@@ -96,14 +106,24 @@ public static IEnumerable<object[]> BadlyFormed_TestData()
         }
 
         [Theory]
+        [SkipOnTargetFramework(TargetFrameworkMonikers.NetFramework, ".NET core fixes a bug where CustomValidationAttribute doesn't validate the context. See https://github.com/dotnet/corefx/pull/5203")]
```
Comment (ajcvickers) [inline src/System.ComponentModel.Annotations/tests/CustomValidationAttributeTests.cs]: Likewise, please file an issue for this behavior difference.

File: src/System.ComponentModel.Annotations/tests/CustomValidationAttributeTests.cs [hunk 8]
```diff
@@ -96,14 +106,24 @@ public static IEnumerable<object[]> BadlyFormed_TestData()
...
         [MemberData(nameof(BadlyFormed_TestData))]
-        public static void RequiresValidationContext_BadlyFormed_ThrowsInvalidOperationException(Type validatorType, string method)
+        public static void RequiresValidationContext_BadlyFormed_NetCore_ThrowsInvalidOperationException(Type validatorType, string method)
         {
             CustomValidationAttribute attribute = new CustomValidationAttribute(validatorType, method);
             Assert.Throws<InvalidOperationException>(() => attribute.RequiresValidationContext);
         }
 
         [Theory]
+        [SkipOnTargetFramework(~TargetFrameworkMonikers.NetFramework, "The full .NET framework has a bug where CustomValidationAttribute doesn't validate the context. See https://github.com/dotnet/corefx/pull/5203")]
```
Comment (ajcvickers) [inline src/System.ComponentModel.Annotations/tests/CustomValidationAttributeTests.cs]: And here.

File: src/System.ComponentModel.Annotations/tests/MaxLengthAttributeTests.cs [hunk 9]
```diff
@@ -58,6 +66,34 @@ public static void Ctor_Int(int length)
         }
 
         [Theory]
+        [MemberData(nameof(ValidValues_ICollection))]
+        [SkipOnTargetFramework(TargetFrameworkMonikers.NetFramework, "MaxLengthAttribute in the .NET Framework doesn't support ICollection.Count. See https://github.com/dotnet/corefx/pull/2650")]
```
Comment (ajcvickers) [inline src/System.ComponentModel.Annotations/tests/MaxLengthAttributeTests.cs]: Likewise for these behavior differences. (#2650 doesn't seem to have an issue associated, unless I missed it.)

File: src/System.ComponentModel.Annotations/tests/CustomValidationAttributeTests.cs (hunk 6 above)
Comment (hughbe) [inline src/System.ComponentModel.Annotations/tests/CustomValidationAttributeTests.cs]: #18360

File: src/System.ComponentModel.Annotations/tests/CustomValidationAttributeTests.cs (hunk 7 above)
Comment (hughbe) [inline src/System.ComponentModel.Annotations/tests/CustomValidationAttributeTests.cs]: This is the same as #18360

File: src/System.ComponentModel.Annotations/tests/CustomValidationAttributeTests.cs (hunk 8 above)
Comment (hughbe) [inline src/System.ComponentModel.Annotations/tests/CustomValidationAttributeTests.cs]: This is the same as #18360

File: src/System.ComponentModel.Annotations/tests/MaxLengthAttributeTests.cs (hunk 9 above)
Comment (hughbe) [inline src/System.ComponentModel.Annotations/tests/MaxLengthAttributeTests.cs]: #18361

File: src/System.ComponentModel.Annotations/tests/MinLengthAttributeTests.cs [hunk 10]
```diff
@@ -49,6 +56,34 @@ public static void Ctor(int length)
             Assert.Equal(length, new MinLengthAttribute(length).Length);
         }
 
+        [Theory]
+        [MemberData(nameof(ValidValues_ICollection))]
+        [SkipOnTargetFramework(TargetFrameworkMonikers.NetFramework, "MinLengthAttribute in the .NET Framework doesn't support ICollection.Count. See https://github.com/dotnet/corefx/pull/2650")]
```
Comment (hughbe) [inline src/System.ComponentModel.Annotations/tests/MinLengthAttributeTests.cs]: #18361

Comment (safern) [inline src/System.ComponentModel.Annotations/tests/MinLengthAttributeTests.cs]: Could you just please add the issue number to the SkipOnTargetFrameworkAttribute so that is easy to track when we look for the tests being skipped?

**Comment by hughbe** [comment]
Ping?

**Comment by hughbe** [comment]
Rebased to fix a merge conflict
