### PR TITLE
Fix #3290: Fix XmlWriter test issue related to non-existing file

### LINKED ISSUE #3290: XmlWriterTestModule.TCCloseOutput failing in outer loop
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_outerloop_windows_release/703/console
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_outerloop_windows_debug/705/console
```
TestCase:XmlWriterSettings: CloseOutput - 
  File Not Found: writer.out
  	Check that underlying stream is NOT CLOSED when CloseOutput = FALSE and Create(TextWriter)
  unexpected exception happend:Object reference not set to an instance of an object.
     at XmlCoreTest.Common.FilePathUtil.getStream(String filename) in d:\j\workspace\dotnet_corefx_outerloop_windows_debug\src\Common\tests\SystemXml\XmlCoreTest\FilePathUtil.cs:line 173
     at XmlWriterAPI.Test.TCCloseOutput.CloseOutput_1() in d:\j\workspace\dotnet_corefx_outerloop_windows_debug\src\System.Xml.ReaderWriter\tests\Writers\XmlWriterApi\XmlFactoryWriterTests.cs:line 2258
     at OLEDB.Test.ModuleCore.CVariation.Execute() in d:\j\workspace\dotnet_corefx_outerloop_windows_debug\src\Common\tests\SystemXml\ModuleCore\cvariation.cs:line 74
     at OLEDB.Test.ModuleCore.CTestCase.Execute() in d:\j\workspace\dotnet_corefx_outerloop_windows_debug\src\Common\tests\SystemXml\ModuleCore\ctestcase.cs:line 69
  	 FAILED
  File Not Found: writer.out
  	Check that underlying stream is NOT CLOSED when CloseOutput = FALSE and Create(Stream)
  unexpected exception happend:Object reference not set to an instance of an object.
     at XmlCoreTest.Common.FilePathUtil.getStream(String filename) in d:\j\workspace\dotnet_corefx_outerloop_windows_debug\src\Common\tests\SystemXml\XmlCoreTest\FilePathUtil.cs:line 173
     at XmlWriterAPI.Test.TCCloseOutput.CloseOutput_1() in d:\j\workspace\dotnet_corefx_outerloop_windows_debug\src\System.Xml.ReaderWriter\tests\Writers\XmlWriterApi\XmlFactoryWriterTests.cs:line 2258
     at OLEDB.Test.ModuleCore.CVariation.Execute() in d:\j\workspace\dotnet_corefx_outerloop_windows_debug\src\Common\tests\SystemXml\ModuleCore\cvariation.cs:line 74
     at OLEDB.Test.ModuleCore.CTestCase.Execute() in d:\j\workspace\dotnet_corefx_outerloop_windows_debug\src\Common\tests\SystemXml\ModuleCore\ctestcase.cs:line 69
  	 FAILED
```

### PR DESCRIPTION
**Pull request by krwq**
Instead of creating new file or stream we were reading it from the cache. The test is checking if underlying stream is closed which in this case is irrelevant and we should be creating MemoryStream.

At the same time fixed error reporting - instead of getting "FileNotFound" we were getting "object reference not set to an instance of an object" which is not really helpful

### CODE REVIEW

**Comment by stephentoub** [comment]
Do you know why this only just recently started failing?

File: src/Common/tests/SystemXml/XmlCoreTest/FilePathUtil.cs [hunk 1]
```diff
@@ -147,31 +147,27 @@ public static Stream getStream(string filename)
...
+                Stream msbak = s_XmlFileInMemoryCacheBackup[normalizedFileName];
+                MemoryStream msnew = new MemoryStream();
+                msbak.Position = 0;
+                msbak.CopyTo(msnew);
+
+                s_XmlFileInMemoryCache[normalizedFileName] = msnew;
+                msnew.Position = 0;
+                return msnew;
             }
+                return s;
```
Comment (stephentoub) [inline src/Common/tests/SystemXml/XmlCoreTest/FilePathUtil.cs]: I think it'd be cleaner if this return were moved up into the if block.

**Comment by stephentoub** [comment]
A couple of comments, otherwise LGTM.

**Comment by krwq** [comment]
I'm not sure why it started failing right now although I have a feeling that we simply did not run the test before or it was marked as ActiveIssue through some different bug (one Fact maps to multiple XML tests here). I will update formatting soon

**Comment by stephentoub** [comment]
LGTM.  Please squash this before merging.

I assume you've verified locally that it fixes the outer loop failure?  Thanks for addressing it.

**Comment by krwq** [comment]
Yes, it passes locally. Merging, since the previous build didn't have any xml changes. I already did build locally.
