### PR TITLE
Fix unprotected access to non-thread-safe IntrinsicTypeConverters dictionary

### LINKED ISSUE #7151: NullableConverterTests failed in CI due to enumerating modified collection
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_release_tst_prtest/2190/consoleFull
```
12:30:09    System.ComponentModel.Tests.NullableConverterTests.CanConvertTo_WithContext [FAIL]
12:30:09       System.TypeInitializationException : The type initializer for 'System.ComponentModel.Tests.NullableConverterTests' threw an exception.
12:30:09       ---- System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
12:30:09       Stack Trace:
12:30:09             at System.ComponentModel.Tests.NullableConverterTests.CanConvertTo_WithContext()
12:30:09          ----- Inner Stack Trace -----
12:30:09             at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
12:30:09             at System.Collections.Generic.Dictionary`2.KeyCollection.Enumerator.MoveNext()
12:30:09             at System.ComponentModel.ReflectTypeDescriptionProvider.SearchIntrinsicTable(Type callingType)
12:30:09             at System.ComponentModel.ReflectTypeDescriptionProvider.GetConverter(Type type)
12:30:09             at System.ComponentModel.NullableConverter..ctor(Type type)
12:30:09             at System.ComponentModel.Tests.NullableConverterTests..cctor()
12:30:09    System.ComponentModel.Tests.NullableConverterTests.ConvertTo_WithContext [FAIL]
12:30:09       System.TypeInitializationException : The type initializer for 'System.ComponentModel.Tests.NullableConverterTests' threw an exception.
12:30:09       ---- System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
12:30:09       Stack Trace:
12:30:09             at System.ComponentModel.Tests.NullableConverterTests.ConvertTo_WithContext()
12:30:09          ----- Inner Stack Trace -----
12:30:09             at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
12:30:09             at System.Collections.Generic.Dictionary`2.KeyCollection.Enumerator.MoveNext()
12:30:09             at System.ComponentModel.ReflectTypeDescriptionProvider.SearchIntrinsicTable(Type callingType)
12:30:09             at System.ComponentModel.ReflectTypeDescriptionProvider.GetConverter(Type type)
12:30:09             at System.ComponentModel.NullableConverter..ctor(Type type)
12:30:09             at System.ComponentModel.Tests.NullableConverterTests..cctor()
12:30:09    System.ComponentModel.Tests.NullableConverterTests.Get_UnderlyingTypeConverter [FAIL]
12:30:09       System.TypeInitializationException : The type initializer for 'System.ComponentModel.Tests.NullableConverterTests' threw an exception.
12:30:09       ---- System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
12:30:09       Stack Trace:
12:30:09             at System.ComponentModel.Tests.NullableConverterTests.Get_UnderlyingTypeConverter()
12:30:09          ----- Inner Stack Trace -----
12:30:09             at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
12:30:09             at System.Collections.Generic.Dictionary`2.KeyCollection.Enumerator.MoveNext()
12:30:09             at System.ComponentModel.ReflectTypeDescriptionProvider.SearchIntrinsicTable(Type callingType)
12:30:09             at System.ComponentModel.ReflectTypeDescriptionProvider.GetConverter(Type type)
12:30:09             at System.ComponentModel.NullableConverter..ctor(Type type)
12:30:09             at System.ComponentModel.Tests.NullableConverterTests..cctor()
12:30:09    System.ComponentModel.Tests.NullableConverterTests.Get_NullableType [FAIL]
12:30:09       System.TypeInitializationException : The type initializer for 'System.ComponentModel.Tests.NullableConverterTests' threw an exception.
12:30:09       ---- System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
12:30:09       Stack Trace:
12:30:09             at System.ComponentModel.Tests.NullableConverterTests.Get_NullableType()
12:30:09          ----- Inner Stack Trace -----
12:30:09             at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
12:30:09             at System.Collections.Generic.Dictionary`2.KeyCollection.Enumerator.MoveNext()
12:30:09             at System.ComponentModel.ReflectTypeDescriptionProvider.SearchIntrinsicTable(Type callingType)
12:30:09             at System.ComponentModel.ReflectTypeDescriptionProvider.GetConverter(Type type)
12:30:09             at System.ComponentModel.NullableConverter..ctor(Type type)
12:30:09             at System.ComponentModel.Tests.NullableConverterTests..cctor()
12:30:09    System.ComponentModel.Tests.NullableConverterTests.ConvertFrom_WithContext [FAIL]
12:30:09       System.TypeInitializationException : The type initializer for 'System.ComponentModel.Tests.NullableConverterTests' threw an exception.
12:30:09       ---- System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
12:30:09       Stack Trace:
12:30:09             at System.ComponentModel.Tests.NullableConverterTests.ConvertFrom_WithContext()
12:30:09          ----- Inner Stack Trace -----
12:30:09             at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
12:30:09             at System.Collections.Generic.Dictionary`2.KeyCollection.Enumerator.MoveNext()
12:30:09             at System.ComponentModel.ReflectTypeDescriptionProvider.SearchIntrinsicTable(Type callingType)
12:30:09             at System.ComponentModel.ReflectTypeDescriptionProvider.GetConverter(Type type)
12:30:09             at System.ComponentModel.NullableConverter..ctor(Type type)
12:30:09             at System.ComponentModel.Tests.NullableConverterTests..cctor()
12:30:09    System.ComponentModel.Tests.NullableConverterTests.CanConvertFrom_WithContext [FAIL]
12:30:09       System.TypeInitializationException : The type initializer for 'System.ComponentModel.Tests.NullableConverterTests' threw an exception.
12:30:09       ---- System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
12:30:09       Stack Trace:
12:30:09             at System.ComponentModel.Tests.NullableConverterTests.CanConvertFrom_WithContext()
12:30:09          ----- Inner Stack Trace -----
12:30:09             at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
12:30:09             at System.Collections.Generic.Dictionary`2.KeyCollection.Enumerator.MoveNext()
12:30:09             at System.ComponentModel.ReflectTypeDescriptionProvider.SearchIntrinsicTable(Type callingType)
12:30:09             at System.ComponentModel.ReflectTypeDescriptionProvider.GetConverter(Type type)
12:30:09             at System.ComponentModel.NullableConverter..ctor(Type type)
12:30:09             at System.ComponentModel.Tests.NullableConverterTests..cctor()
12:30:09    System.ComponentModel.Tests.NullableConverterTests.Get_UnderlyingType [FAIL]
12:30:09       System.TypeInitializationException : The type initializer for 'System.ComponentModel.Tests.NullableConverterTests' threw an exception.
12:30:09       ---- System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
12:30:09       Stack Trace:
12:30:09             at System.ComponentModel.Tests.NullableConverterTests.Get_UnderlyingType()
12:30:09          ----- Inner Stack Trace -----
12:30:09             at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
12:30:09             at System.Collections.Generic.Dictionary`2.KeyCollection.Enumerator.MoveNext()
12:30:09             at System.ComponentModel.ReflectTypeDescriptionProvider.SearchIntrinsicTable(Type callingType)
12:30:09             at System.ComponentModel.ReflectTypeDescriptionProvider.GetConverter(Type type)
12:30:09             at System.ComponentModel.NullableConverter..ctor(Type type)
12:30:09             at System.ComponentModel.Tests.NullableConverterTests..cctor()
```

### PR DESCRIPTION
**Pull request by stephentoub**
Lack of synchronization here can cause corruption of the dictionary, as well as causing concurrent searches to fail with exceptions due to the collection being modified concurrently.

Fixes #7151 
cc: @krwq, @ianhays

### CODE REVIEW

File: src/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectTypeDescriptionProvider.cs [hunk 1]
```diff
@@ -215,7 +218,12 @@ internal static TypeConverter GetConverter(Type type)
                     bool noTypeConstructor = true;
                     object instance = (TypeConverter)ReflectTypeDescriptionProvider.CreateInstance(converterType, type, ref noTypeConstructor);
                     if (noTypeConstructor)
-                        ReflectTypeDescriptionProvider.IntrinsicTypeConverters[type] = instance;
+                    {
+                        lock (s_syncObject)
```
Comment (stephentoub) [inline src/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectTypeDescriptionProvider.cs]: Is this the correct placement, or should it surround the entire get operation?  I put it here under the assumption that it's idempotent and the worst that happens is we end up duplicating some work... let me know if that's not the case.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@Tanya-Solyanik, could you help review this?

**Comment by krwq** [comment]
cc: @sokket

File: src/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectTypeDescriptionProvider.cs (hunk 1 above)
Comment (Tanya-Solyanik) [inline src/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectTypeDescriptionProvider.cs]: this is a correct assumption

**Comment by Tanya-Solyanik** [comment]
LGTM

**Comment by stephentoub** [comment]
Thanks, @Tanya-Solyanik.

**Comment by joshfree** [comment]
adding NetFx-port-consider

**Comment by Tanya-Solyanik** [comment]
This issue is not applicable to the full framework - we have a lock around write accesses to this table:

http://index/#System/ReflectTypeDescriptionProvider.cs,1327
