### PR TITLE
Fix InvalidCastException when accessing IAds* COM interfaces

### LINKED ISSUE #20951: Unable to dogfood corefx
I'm new to .NET and .NET Core, but am eager to test out DirectoryServices in the 2.x daily builds. However, I can't seem to get things to work. I've read through a large variety of docs, and am unable to figure out what's wrong. Are the instructions on this page accurate?

https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md

I can get coreclr to build locally, and my (very basic) test console app seems to be using it (I'm using the self-contained option). But I seem to be missing something in order to get corefx to work as well. Can someone perhaps quick check the doc? With an eye for those of us that are new to .NET...

Or maybe give us a hint as to how to verify basic corefx functionality? Maybe a short example .csproj and/or program.cs file or something...?

I'm running VS 2017 Preview (15.3.0 Preview 2.0) on 64-bit Win10.

Thanks!
Looking forward to the upcoming releases of .NET CORE!

### PR DESCRIPTION
**Pull request by pjanotti**
This fixes #20951. It required changes to some tests since they should not throw InvalidCastException anymore.

### CODE REVIEW

File: src/System.DirectoryServices/tests/System/DirectoryServices/ActiveDirectory/DomainControllerTests.cs [hunk 1]
```diff
@@ -39,10 +39,10 @@ public void GetDomainController_InvalidName_ThrowsActiveDirectoryObjectNotFoundE
 
         [ConditionalFact(nameof(PlatformDetection) + "." + nameof(PlatformDetection.IsNotWindowsNanoServer))]
         [SkipOnTargetFramework(TargetFrameworkMonikers.Uap, "Access to path is denied when in App container")]
-        public void GetDomainController_InvalidIPV6_ThrowsInvalidCastException()
+        public void GetDomainController_InvalidIPV6_ThrowsActiveDirectoryObjectNotFoundException()
         {
             var context = new DirectoryContext(DirectoryContextType.DirectoryServer, "[::1]:port");
-            Assert.Throws<InvalidCastException>(() => DomainController.GetDomainController(context));
+            Assert.Throws<ActiveDirectoryObjectNotFoundException>(() => DomainController.GetDomainController(context));
```
Comment (hughbe) [inline src/System.DirectoryServices/tests/System/DirectoryServices/ActiveDirectory/DomainControllerTests.cs]: Does this add much to the running time of the tests? You don't need to check exactly the value, but I know that sometimes it takes 5-10 seconds for trying to find a domain that doesn't exist to fail

File: src/System.DirectoryServices.AccountManagement/tests/PrincipalContextTests.cs [hunk 2]
```diff
@@ -90,7 +93,8 @@ public void Ctor_ContextType_Name_Container_Options(ContextType contextType, str
             }
             else
             {
-                Assert.Throws<InvalidCastException>(() => context.ConnectedServer);
+                Assert.NotNull(context.ConnectedServer);
```
Comment (hughbe) [inline src/System.DirectoryServices.AccountManagement/tests/PrincipalContextTests.cs]: Nit: you don't need this as it's handled by the equality check below (and actualy would make the error message a bit worse)

Comment (hughbe) [inline src/System.DirectoryServices.AccountManagement/tests/PrincipalContextTests.cs]: (Applies elsewhere too)

Comment (pjanotti) [inline src/System.DirectoryServices.AccountManagement/tests/PrincipalContextTests.cs]: Ah, just to be sure: do you mean that `Assert.Equal((string)null, (string)null)` will assert anyway? I know that it is unlikely to be a problem to have just the `Assert.Equal`, since it requires `Environment.MachineName` to be also broken, but given that `null` has a specific meaning for [`ConnectedServer`](https://msdn.microsoft.com/en-us/library/system.directoryservices.accountmanagement.principalcontext.connectedserver(v=vs.110).aspx) property I want to confirm that.

File: src/System.DirectoryServices/tests/System/DirectoryServices/ActiveDirectory/DomainControllerTests.cs (hunk 1 above)
Comment (pjanotti) [inline src/System.DirectoryServices/tests/System/DirectoryServices/ActiveDirectory/DomainControllerTests.cs]: On a non-joined machine this is fast, they do take time when the machine is domain joined. I have to measure the difference between domain joined connected and disconnected from the domain. I would like to make the tests pass on my main dev box that is domain joined when doing that we may want to skip some tests that can take a long time (~30 seconds).

File: src/System.DirectoryServices.AccountManagement/tests/PrincipalContextTests.cs (hunk 2 above)
Comment (hughbe) [inline src/System.DirectoryServices.AccountManagement/tests/PrincipalContextTests.cs]: I mean,
`Assert.Equal(Environment.MachineName, context.ConnectedServer)`

We have tests that make sure `Environment.MachineName` never returns null.

It's not important though

File: src/System.DirectoryServices/tests/System/DirectoryServices/ActiveDirectory/DomainControllerTests.cs (hunk 1 above)
Comment (stephentoub) [inline src/System.DirectoryServices/tests/System/DirectoryServices/ActiveDirectory/DomainControllerTests.cs]: If there's the potential it could take that long, let's mark the test (and any others in a similar situation) as [Outerloop].

**Comment by stephentoub** [comment]
ps When merging, please "Squash and merge".

File: src/System.DirectoryServices/tests/System/DirectoryServices/ActiveDirectory/DomainControllerTests.cs (hunk 1 above)
Comment (pjanotti) [inline src/System.DirectoryServices/tests/System/DirectoryServices/ActiveDirectory/DomainControllerTests.cs]: Marked anything taking longer than 4 seconds in the automated run as `[OuterLoop]` and as `[OuterLoop("Takes too long on domain joined machines")]` for the ones from my domain joined box, not that these tests are all passing on a domain joined box but I will track those on a separate item.

**Comment by pjanotti** [comment]
Thanks @hughbe  and @stephentoub  for the review - I need many of those until I get really used to the process. I will wait for the checks to complete and will give until around noon (PDT) for the other reviewers.

**Comment by danmosemsft** [comment]
@pjanotti can you explain why the tests were passing for at least some people?

**Comment by pjanotti** [comment]
@danmosemsft the tests were expecting InvalidCastException but that was being thrown only due to the lack of ComImport. After that was fixed the tests needed to be changed to expect different exceptions. Notice that the tests are not yet passing on domain joined boxes but I will address it in a separate change.

**Comment by pjanotti** [comment]
Per offline conversation w/ @tquerec and a debug run to validate I am adding the `ComImport` and `Guid` to `IAdsObjectOptions2` interface (it is not in the type library because it is same as `IAdsObjectOptions` w/ a slightly different signature, internal to S.DS). The fastest way for me to get the results on a non-domain machine will be to add it here, in case of test failures I will revert and commit without it.
