### PR TITLE
Fix networking test activeissues in System.Net.Http

### LINKED ISSUE #9543: Test failure: Manual_CertificateSentMatchesCertificateReceived_Success
The test as currently written fails sporadically on Windows.  If, however, `GC.Collect(); GC.WaitForPendingFinalizers();` is added inside the loop here: https://github.com/dotnet/corefx/blob/483aa5a3012fe78ea001ece1b0404b18c0b90a29/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.ClientCertificates.cs#L117
the `reuseClient==false` test fails deterministically for me with the error "The client certificate credentials were not recognized".  It appears something is getting finalized and preventing the same certificate instance from being used with subsequent HttpClientHandler instances.

### PR DESCRIPTION
**Pull request by Priya91**
addresses #9543 #8945 #10958 #10702 #13188

cc @steveharter @ianhays @karelz 

#9543 Ensure the certificate is not disposed before next client reuses it.
#8945 #10958 Make the test run only on windows version greater than insider preview.
#10702 #13188 Not able to repro these locally, and the stack trace is from very old CI or different branch. Re-enabling the test for latest CI.

### CODE REVIEW

**Comment by Priya91** [comment]
@dotnet-bot Test OuterLoop Windows_NT Debug Build and Test
@dotnet-bot Test OuterLoop CentOS7.1 Debug Build and Test

**Comment by Priya91** [comment]
The outerloop centos test run failure is known, and tracked with #12637

**Comment by steveharter** [comment]
LGTM

Good find - remove using statement on cert outside of the async code that uses the cert.

**Comment by steveharter** [comment]
Test OuterLoop CentOS7.1 Debug

File: src/Common/tests/System/PlatformDetection.cs [hunk 1]
```diff
@@ -23,6 +23,8 @@ public static class PlatformDetection
             File.Exists(Path.Combine(Environment.GetEnvironmentVariable("windir"), "regedit.exe")));
         public static bool IsWindows10Version1607OrGreater { get; } = IsWindows &&
             GetWindowsVersion() == 10 && GetWindowsMinorVersion() == 0 && GetWindowsBuildNumber() >= 14393;
+        public static bool IsWindows10VersionInsiderPreviewOrGreater { get; } = IsWindows &&
```
Comment (davidsh) [inline src/Common/tests/System/PlatformDetection.cs]: "IsWindows10VersionInsiderPreviewOrGreater" This should get renamed to something more stable.  Every build of Windows 10 that isn't an RTM version is an "Insider Preview".

It would be more accurate to at least call this "IsWindows10CreatorsUpdatePreviewOrGreater".

Comment (Priya91) [inline src/Common/tests/System/PlatformDetection.cs]: Will address in next PR.
