### PR TITLE
Test fixes for System.Net.Security

### LINKED ISSUE #4467: SslStream tests: timeout
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/6135/console
```
System.Net.Security.Tests.SslStreamStreamToStreamTest.SslStream_StreamToStream_Authentication_Success [FAIL]
        Handshake completed in the allotted time
        Expected: True
        Actual:   False
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Security\tests\FunctionalTests\SslStreamStreamToStreamTest.cs(36,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest.SslStream_StreamToStream_Authentication_Success()
     System.Net.Security.Tests.CertificateValidationClientServer.CertificateValidationClientServer_EndToEnd_Ok [FAIL]
        Client/Server Authentication timed out.
        Expected: True
        Actual:   False
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Security\tests\FunctionalTests\CertificateValidationClientServer.cs(80,0): at System.Net.Security.Tests.CertificateValidationClientServer.<CertificateValidationClientServer_EndToEnd_Ok>d__0.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_EachProtocol_Success [FAIL]
        Timed Out
        Expected: True
        Actual:   False
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Security\tests\FunctionalTests\ClientAsyncAuthenticateTest.cs(252,0): at System.Net.Security.Tests.ClientAsyncAuthenticateTest.<ClientAsyncSslHelper>d__5c.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Security\tests\FunctionalTests\ClientAsyncAuthenticateTest.cs(108,0): at System.Net.Security.Tests.ClientAsyncAuthenticateTest.<ClientAsyncAuthenticate_EachProtocol_Success>d__16.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

### PR DESCRIPTION
**Pull request by CIPop**
* Renaming/moving the `VirtualNetwork/Stream` classes.
* A few concurrency fixes for the `VirtualNetwork/Stream` classes.
* Adding VirtualNetwork/Stream tests.
* Adding the TaskTimeoutExtensions and correcting the timeout pattern within one of the S.N.Security tests.
* Moving all common test code within the System.Net.Test.Common namespace.

@davidsh @stephentoub @shrutigarg PTAL

### CODE REVIEW

File: src/Common/tests/System/Net/VirtualNetwork/VirtualNetworkStream.cs [hunk 1]
```diff
@@ -92,16 +105,15 @@ public override void Write(byte[] buffer, int offset, int count)
...
-            }
+            return Task.FromResult<int>(this.Read(buffer, offset, count));
+        }
 
-            byte[] innerBuffer;
-            _network.ReadFrame(_isServer, out innerBuffer);
-            _readStream = new MemoryStream(innerBuffer);
+        public override Task WriteAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
+        {
+            this.Write(buffer, offset, count);
```
Comment (davidsh) [inline src/Common/tests/System/Net/VirtualNetwork/VirtualNetworkStream.cs]: Should 'this' be 'base' instead?

Comment (CIPop) [inline src/Common/tests/System/Net/VirtualNetwork/VirtualNetworkStream.cs]: No, the idea is to overload WriteAsync so it doesn't go through the base (Stream) implementation. Since no actual I/O is performed, the operation is completed as for Write, synchronously and a completed Task returned.

File: src/System.Net.Security/tests/FunctionalTests/ClientAsyncAuthenticateTest.cs [hunk 2]
```diff
@@ -139,8 +139,7 @@ private Task ClientAsyncSslHelper(SslProtocols clientSslProtocols, SslProtocols
                 using (SslStream sslStream = new SslStream(client.GetStream(), false, AllowAnyServerCertificate, null))
                 {
                     Task async = sslStream.AuthenticateAsClientAsync("localhost", null, clientSslProtocols, false);
```
Comment (davidsh) [inline src/System.Net.Security/tests/FunctionalTests/ClientAsyncAuthenticateTest.cs]: Can we change the variable name from 'async' to something like 'task' or 't'?  Seeing 'async used as a variable name instead of a keyboard is confusing.  Even the code-coloring formatter thinks it is a keyword.

**Comment by davidsh** [comment]
Left small comments...otherwise LGTM.

File: src/System.Net.Security/tests/FunctionalTests/ClientAsyncAuthenticateTest.cs (hunk 2 above)
Comment (CIPop) [inline src/System.Net.Security/tests/FunctionalTests/ClientAsyncAuthenticateTest.cs]: Agreed.

**Comment by CIPop** [comment]
Test Innerloop OpenSUSE13.2 Release Build and Test

File: src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs [hunk 3]
```diff
@@ -31,14 +34,15 @@ public void ReadFrame(bool server, out byte[] buffer)
                 packetQueue = _serverWriteQueue;
             }
 
-            semaphore.Wait(TestConfiguration.PassingTestTimeoutMilliseconds);
-            buffer = packetQueue.Dequeue();
+            semaphore.Wait(WaitForReadDataTimeoutMilliseconds);
+
+            Debug.Assert(packetQueue.TryDequeue(out buffer), "Packet queue: TryDequeue failed.");
```
Comment (stephentoub) [inline src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs]: This is fine, though you could use a ```BlockingCollection<byte[]>``` instead of the ```SemaphoreSlim``` + ```ConcurrentQueue<T>```.

File: src/Common/tests/System/Net/VirtualNetwork/VirtualNetworkStream.cs [hunk 4]
```diff
@@ -92,16 +105,15 @@ public override void Write(byte[] buffer, int offset, int count)
...
         }
 
-        private void UpdateReadStream()
+        public override Task<int> ReadAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
         {
-            if (_readStream != null && (_readStream.Position < _readStream.Length))
-            {
-                return;
-            }
+            return Task.FromResult<int>(this.Read(buffer, offset, count));
```
Comment (stephentoub) [inline src/Common/tests/System/Net/VirtualNetwork/VirtualNetworkStream.cs]: Is there any way Read or Write could throw exceptions?  If so, you'd want to use a try/catch and use Task.FromException in the failure path.

File: src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs [hunk 5]
```diff
@@ -0,0 +1,24 @@
...
+/// <summary>
+/// Task timeout helper based on http://blogs.msdn.com/b/pfxteam/archive/2011/11/10/10235834.aspx
+/// </summary>
+namespace System.Threading.Tasks
+{
+    public static class TaskTimeoutExtensions
+    {
+        public static async Task TimeoutAfter(this Task task, int millisecondsTimeout)
+        {
+            if (task == await Task.WhenAny(task, Task.Delay(millisecondsTimeout)))
```
Comment (stephentoub) [inline src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs]: For our testing purposes, it's not going to matter.  To make this a bit more robust, you'd want it to be:
```C#
var cts = new CancellationTokenSource();
if (task == await Task.WhenAny(task, Task.Delay(millisecondsTimeout, cts.Token)))
{
    cts.Cancel();
    await task;
...
```
That way, if the task does complete, we cancel the delay task rather than leaving it to eventually fire and cleanup in the background.  This only matters if we expect tons of these, which we don't.

File: src/Common/tests/Tests/System/Net/VirtualNetworkTest.cs [hunk 6]
```diff
@@ -0,0 +1,79 @@
...
+                byte [] sequenceNo = BitConverter.GetBytes(i);
+                sequenceNo.CopyTo(writeFrame, 0);
+
+                uint writeChecksum = Fletcher32.Checksum(writeFrame, 0, writeFrame.Length);
+                checksums.AddOrUpdate(i, writeChecksum, (seq, checkSum) => { Debug.Fail("Attempt to update checksum."); return 0; });
+
+                network.WriteFrame(i % 2 == 0, writeFrame);
+
+                int delayMilliseconds = rnd.Next(0, 1000);
+                Task.Delay(delayMilliseconds);
```
Comment (stephentoub) [inline src/Common/tests/Tests/System/Net/VirtualNetworkTest.cs]: As written this is a nop.  Did you mean to Wait() on this?

**Comment by stephentoub** [comment]
Some minor comments, otherwise LGTM.

File: src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs (hunk 3 above)
Comment (stephentoub) [inline src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs]:
```C#
Debug.Assert(packetQueue.TryDequeue(out buffer), "Packet queue: TryDequeue failed.");
```
needs to be:
```C#
bool dequeued = packetQueue.TryDequeue(out buffer);
Debug.Assert(dequeued, "Packet queue: TryDequeue failed");
```
Otherwise, the call to TryDequeue gets removed in release builds.

File: src/Common/tests/Tests/System/Net/VirtualNetworkTest.cs (hunk 6 above)
Comment (CIPop) [inline src/Common/tests/Tests/System/Net/VirtualNetworkTest.cs]: Thanks! Yes, that was the intention. The compiler didn't catch this as the call was not made in an async context.

File: src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs (hunk 3 above)
Comment (CIPop) [inline src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs]: > This is fine, though you could use a BlockingCollection<byte[]> instead of the SemaphoreSlim + ConcurrentQueue<T>.

Thanks for pointing it out! I don't have enough time to change this now.

> Otherwise, the call to TryDequeue gets removed in release builds.

Yup, I see it failed on the Windows Ret build.

File: src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs (hunk 5 above)
Comment (CIPop) [inline src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs]: Good point. I'm making the change.

File: src/Common/tests/System/Net/VirtualNetwork/VirtualNetworkStream.cs (hunk 4 above)
Comment (CIPop) [inline src/Common/tests/System/Net/VirtualNetwork/VirtualNetworkStream.cs]: Not at this point but I'd like to evolve the virtual network to simulate those as well. Adding this and `cancellationToken` support.

**Comment by CIPop** [comment]
Looks like the fixes were not enough. I need to investigate this and gather ETW traces. 

```
MESSAGE:
Client/Server Authentication timed out.\r\nExpected: True\r\nActual: False
+++++++++++++++++++
STACK TRACE:
at System.Net.Security.Tests.CertificateValidationClientServer.<CertificateValidationClientServer_EndToEnd_Ok>d__5.MoveNext() in d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Net.Security\tests\FunctionalTests\CertificateValidationClientServer.cs:line 91 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

MESSAGE:
Handshake completed.\r\nExpected: True\r\nActual: False
+++++++++++++++++++
STACK TRACE:
at System.Net.Security.Tests.SslStreamStreamToStreamTest.SslStream_StreamToStream_Successive_ClientWrite_Sync_Success() in d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Net.Security\tests\FunctionalTests\SslStreamStreamToStreamTest.cs:line 76

MESSAGE:
Handshake completed in the allotted time\r\nExpected: True\r\nActual: False
+++++++++++++++++++
STACK TRACE:
at System.Net.Security.Tests.NegotiateStreamStreamToStreamTest.NegotiateStream_StreamToStream_Successive_ClientWrite_Sync_Success() in d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Net.Security\tests\FunctionalTests\NegotiateStreamStreamToStreamTest.cs:line 210
```

**Comment by CIPop** [comment]
This got postponed but I still think the changes make things better at least by fixing a few of the known bugs. I'm reverting the removal of `ActiveIssue` tags but leaving the rest of the code in.

A more in-depth analysis is required to properly fix the following bugs: #4467 #5283 #5284.

@shrutigarg Please integrate this with your S.N.Security private branch. It should help fix at least a few of the issues in MockNetwork (now VirtualNetwork).

**Comment by CIPop** [comment]
Fixed integration issue and updated the commit code.

**Comment by CIPop** [comment]
Test Innerloop OSX Debug Build and Test

**Comment by CIPop** [comment]
Test Innerloop Ubuntu Debug Build and Test

**Comment by CIPop** [comment]
Test Innerloop Ubuntu Release Build and Test

**Comment by stephentoub** [comment]
Test Innerloop OSX Release Build and Test please
Test Innerloop Ubuntu Release Build and Test please
Test Innerloop Ubuntu Debug Build and Test please

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please
Test Innerloop OSX Release Build and Test please
Test Innerloop Ubuntu Release Build and Test please
Test Innerloop Ubuntu Debug Build and Test please

**Comment by CIPop** [comment]
Test Innerloop OSX Debug Build and Test

**Comment by CIPop** [comment]
Test Innerloop OSX Release Build and Test

**Comment by CIPop** [comment]
Test Innerloop Ubuntu Debug Build and Test

**Comment by CIPop** [comment]
Test Innerloop Ubuntu Release Build and Test

**Comment by CIPop** [comment]
Test Innerloop OSX Debug Build and Test please
Test Innerloop OSX Release Build and Test please
Test Innerloop Ubuntu Release Build and Test please
Test Innerloop Ubuntu Debug Build and Test please

**Comment by stephentoub** [comment]
@cipop, these look like real failures:
```
TcpClientTest.cs(9,18): error CS0234: The type or namespace name 'Tests' does not exist in the namespace 'System.Net' (are you missing an assembly reference?) [d:\j\workspace\dotnet_corefx\ubuntu_debug_bld_prtest\src\System.Net.Sockets\tests\FunctionalTests\System.Net.Sockets.Tests.csproj]
```
I don't think re-running the legs is going to help.

**Comment by CIPop** [comment]
Thanks @stephentoub! I was confused by the message having a positive connotation: "Build finished" instead of "Build failed".

These are another round of integration issues as I've made the test namespaces more uniform.

File: src/Common/tests/System/Net/VirtualNetwork/VirtualNetworkStream.cs [hunk 7]
```diff
@@ -92,16 +105,32 @@ public override void Write(byte[] buffer, int offset, int count)
             _network.WriteFrame(_isServer, innerBuffer);
         }
 
-        private void UpdateReadStream()
+        public override Task<int> ReadAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
         {
-            if (_readStream != null && (_readStream.Position < _readStream.Length))
+            try
+            {
+                cancellationToken.ThrowIfCancellationRequested();
```
Comment (stephentoub) [inline src/Common/tests/System/Net/VirtualNetwork/VirtualNetworkStream.cs]: Nit: I think you said this will never be canceled at this time, so this can wait until later, but if this does have cancellation requested, it'll end up throwing a cancellation exception that's then caught by the catch block, which will return a task in the Faulted state.  Technically it'd be better for the task to be in the Canceled state.  In reality, for your testing purposes, it's unlikely to matter, as if the operation is immediately awaited, the caller won't be able to tell the difference.  If, however, a caller were to inspect the Status of the returned task once it completed (as they might if they were using ContinueWith), they could tell the difference.

File: src/Common/tests/Tests/System/Net/VirtualNetworkStreamTest.cs [hunk 8]
```diff
@@ -0,0 +1,145 @@
...
+            var checksumAndLengths = new ConcurrentDictionary<int, Tuple<uint, int>>();
+
+            object readLock = new object();
+
+            using (var client = new VirtualNetworkStream(network, isServer: false))
+            using (var server = new VirtualNetworkStream(network, isServer: true))
+            {
+                Parallel.For(0, 100000, async (int i) =>
+                {
+                    int bufferSize = rnd.Next(sizeof(int) + 1, maxFrameSize);
```
Comment (stephentoub) [inline src/Common/tests/Tests/System/Net/VirtualNetworkStreamTest.cs]: Random isn't thread-safe, so this call should be protected.  Random has a nasty habit when it's used concurrently of getting into a corrupted state where it then only ever produces zeros.

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please

**Comment by CIPop** [comment]
Thanks @stephentoub for the comments. Given how hard it was to get a full CI, I'll merge these now and fix the remaining issues later (#5991).
