### PR TITLE
Use BCrypt when possible in symmetric CNG providers

### LINKED ISSUE #7201: Use BCrypt.dll for ephemeral symmetric operations
The majority of tests failing in https://github.com/dotnet/corefx/issues/7086 are due to Windows 7 not having support for symmetric encryption through the Microsoft KSP (using NCrypt.dll).

The guidance from the Windows Cryptography team is to use BCrypt when an ephemeral key is used, and only use NCrypt when a persisted key was explicitly requested.  And that'll make Windows 7 have exactly the right support.

### PR DESCRIPTION
**Pull request by bartonjs**
Windows 7 does not support symmetric algorithms in the software key provider, which makes AesCng and TripleDESCng not function there.  Additionally, the Windows Cryptography team recommended always using BCrypt when possible, instead of the NCrypt indirection for ephemeral keys.

This change undoes the test compatibility shim, then reuses the BCrypt calls that S.S.C.Algorithms makes in S.S.C.Cng; but continues to use the NCrypt version when a keyName was given.

It also adds OuterLoop tests for dealing with persisted keys.  I've verified manually that they leak no keys on failure with their current structuring; but they could still pollute the hard drive on a process termination.

This is currently broken into multiple commits for ease of reviewing; I can squash to whatever the audience requests.

Fixes #7201.
cc: @AtsushiKan, @stephentoub

### CODE REVIEW

**Comment by bartonjs** [comment]
I need outerloop for Win7 and a Win\>7.  But the job names are eluding me...

**Comment by stephentoub** [comment]
Test Outerloop Windows 7 Debug please

**Comment by stephentoub** [comment]
Test Outerloop Windows 10 Debug please

File: src/Common/src/Interop/Windows/BCrypt/AesBCryptModes.cs [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+{
+    internal static class AesBCryptModes
+    {
+        private static readonly SafeAlgorithmHandle s_hAlgCbc = OpenAesAlgorithm(Cng.BCRYPT_CHAIN_MODE_CBC);
+        private static readonly SafeAlgorithmHandle s_hAlgEcb = OpenAesAlgorithm(Cng.BCRYPT_CHAIN_MODE_ECB);
+
+        internal static SafeAlgorithmHandle GetSharedHandle(CipherMode cipherMode)
+        {
+            // Windows 8 added support to set the CipherMode value on a key,
+            // but Windows 7 requires that it be set on the algorithm before key creation.
```
Comment (stephentoub) [inline src/Common/src/Interop/Windows/BCrypt/AesBCryptModes.cs]: I'm probably just being dense, but how does this comment apply to the following code?

File: src/System.Security.Cryptography.Cng/src/Internal/Cryptography/CngSymmetricAlgorithmCore.cs [hunk 2]
```diff
@@ -122,7 +122,12 @@ public ICryptoTransform CreateDecryptor(byte[] rgbKey, byte[] rgbIV)
 
         private ICryptoTransform CreateCryptoTransform(bool encrypting)
         {
-            return CreateCryptoTransformCore(ProduceCngKey, _outer.IV, encrypting);
+            if (KeyInPlainText)
+            {
+                return CreateCryptoTransform(_outer.BaseKey, _outer.IV, encrypting);
+            }
+
+            return CreatePersistedCryptoTransformCore(ProduceCngKey, _outer.IV, encrypting);
```
Comment (stephentoub) [inline src/System.Security.Cryptography.Cng/src/Internal/Cryptography/CngSymmetricAlgorithmCore.cs]: Purely a matter of style... if it were me, I'd use ternary syntax here, e.g.
```C#
return KeyInPlainText ?
    CreateCryptoTransform(_outer.BaseKey, _outer.IV, encrypting) :
    CreatePersistedCryptoTransform(ProduceCngKey, _outer.IV, encrypting);
```

File: src/System.Security.Cryptography.Cng/tests/AesCngTests.cs [hunk 3]
```diff
@@ -0,0 +1,96 @@
...
+{
+    public static class AesCngTests
+    {
+        private const int BlockSizeBytes = 16;
+
+        private static readonly CngAlgorithm s_cngAlgorithm = new CngAlgorithm("AES");
+
+        // The ephemeral key has already been validated by the AesCipherTests suite.
+        // Therefore we can use the ephemeral key to validate the persisted key.
+        [OuterLoop]
```
Comment (stephentoub) [inline src/System.Security.Cryptography.Cng/tests/AesCngTests.cs]: It'd be worth a comment on why these are outerloop (similar to the reasoning in the PR description)

File: src/System.Security.Cryptography.Cng/tests/AesCngTests.cs [hunk 4]
```diff
@@ -0,0 +1,96 @@
...
+            {
+                cngKey.Delete();
+            }
+        }
+
+        [OuterLoop]
+        [ConditionalFact(nameof(SupportsPersistedSymmetricKeys))]
+        public static void VerifyMachineKey()
+        {
+
```
Comment (stephentoub) [inline src/System.Security.Cryptography.Cng/tests/AesCngTests.cs]: Nit: unnecessary blank line

File: src/Common/src/Interop/Windows/BCrypt/AesBCryptModes.cs (hunk 1 above)
Comment (bartonjs) [inline src/Common/src/Interop/Windows/BCrypt/AesBCryptModes.cs]: In this specific, it just moved.  But when comparing against what it used to be (https://github.com/dotnet/corefx/pull/2673/files) it made more sense.

So this is "We're building cipher-moded algorithm handles here because that's the only pattern that works in Win7; even though the Win8 model makes more sense from a .NET Object Model perspective".  Or something like that.

**Comment by bartonjs** [comment]
* Win10 is good (the failures aren't in CNG, and the new tests all passed).
* Win7 failed due to something in msbuild
* Unixes failed because apparently the CNG test project is build on the unix builds, and it doesn't; so I need to make sure the new files appear in the $(TargetsWindows) section (which I was, actually, wondering why we had one of those)

I'll fix up the Unix builds with the OuterLoop comments and whatever other things appear before I get in, and I'll retry Win7 after that.

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@dotnet-bot test OuterLoop Windows 7 Debug

**Comment by mmitche** [comment]
@dotnet-bot OuterLoop Windows 10 Debug

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by bartonjs** [comment]
Test Outerloop Windows 7 Debug please
Test Outerloop Windows 10 Debug please

File: src/System.Security.Cryptography.Cng/tests/AesCngTests.cs (hunk 3 above)
Comment (bartonjs) [inline src/System.Security.Cryptography.Cng/tests/AesCngTests.cs]: Changed the attribute declarations to be
```C#
[OuterLoop(/* Creates/Deletes a persisted key, limit exposure to key leaking */)]
```

File: src/System.Security.Cryptography.Cng/tests/AesCngTests.cs (hunk 4 above)
Comment (bartonjs) [inline src/System.Security.Cryptography.Cng/tests/AesCngTests.cs]: Bah, missed this one.  If I have to make any other changes I'll try to hit this one again.

**Comment by stephentoub** [comment]
@bartonjs, all Win7 outer loop runs are failing due to https://github.com/dotnet/corefx/issues/7294. cc: @Priya91

**Comment by bartonjs** [comment]
> all Win7 outer loop runs are failing

Well, sadness.  I have verified it on a local Win7 machine; so I'm fairly confident:

```
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Security.Cryptography.Cng.Tests
Discovered:  System.Security.Cryptography.Cng.Tests
Starting:    System.Security.Cryptography.Cng.Tests
   System.Security.Cryptography.Cng.Tests.AesCngTests.GetKey_NonExportable [SKIP]
      "SupportsPersistedSymmetricKeys" returned false.
   System.Security.Cryptography.Cng.Tests.TripleDESCngTests.GetKey_NonExportable [SKIP]
      "SupportsPersistedSymmetricKeys" returned false.
   System.Security.Cryptography.Cng.Tests.TripleDESCngTests.VerifyPersistedKey [SKIP]
      "SupportsPersistedSymmetricKeys" returned false.
   System.Security.Cryptography.Cng.Tests.AesCngTests.VerifyPersistedKey [SKIP]
      "SupportsPersistedSymmetricKeys" returned false.
   System.Security.Cryptography.Cng.Tests.TripleDESCngTests.LoadWrongKeyType [SKIP]
      "SupportsPersistedSymmetricKeys" returned false.
   System.Security.Cryptography.Cng.Tests.AesCngTests.SetKey_DetachesFromPersistedKey [SKIP]
      "SupportsPersistedSymmetricKeys" returned false.
   System.Security.Cryptography.Cng.Tests.TripleDESCngTests.SetKey_DetachesFromPersistedKey [SKIP]
      "SupportsPersistedSymmetricKeys" returned false.
   System.Security.Cryptography.Cng.Tests.AesCngTests.LoadWrongKeyType [SKIP]
      "SupportsPersistedSymmetricKeys" returned false.
   System.Security.Cryptography.Cng.Tests.TripleDESCngTests.VerifyMachineKey [SKIP]
      "SupportsPersistedSymmetricKeys" returned false.
   System.Security.Cryptography.Cng.Tests.AesCngTests.VerifyMachineKey [SKIP]
      "SupportsPersistedSymmetricKeys" returned false.
Finished:    System.Security.Cryptography.Cng.Tests

=== TEST EXECUTION SUMMARY ===
   System.Security.Cryptography.Cng.Tests  Total: 211, Errors: 0, Failed: 0, Skipped: 10, Time: 3.591s
```

**Comment by bartonjs** [comment]
Test Innerloop Ubuntu Debug Build and Test please
Test Innerloop Ubuntu Release Build and Test please
Test Innerloop CentOS7.1 Debug Build and Test please
Test Innerloop CentOS7.1 Release Build and Test please

(CI restart)

**Comment by stephentoub** [comment]
LGTM

**Comment by stephentoub** [comment]
Test Innerloop Ubuntu Debug Build and Test please
Test Innerloop Ubuntu Release Build and Test please
Test OuterLoop Windows 7 Debug please

**Comment by bartonjs** [comment]
Test Innerloop Ubuntu Debug Build and Test please
Test Innerloop Ubuntu Release Build and Test please

**Comment by bartonjs** [comment]
Test Innerloop Ubuntu Debug Build and Test please
Test Innerloop Ubuntu Release Build and Test please
