### PR TITLE
Remove redundant check from flaky test

### LINKED ISSUE #24961: Invoke_Instance_And_Static_Method_Win32_Process failed
This is on regular Windows 8.1 (well, Server 2012)

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171030.02/workItem/System.Management.Tests/analysis/xunit/System.Management.Tests.ManagementObjectTests~2FInvoke_Instance_And_Static_Method_Win32_Process

Seems notepad did not get terminated. Is the WMI "Terminate" asynchronous possibly? Consider a loop with sleeps. Or maybe it did terminate and the bug is in WMI process.Get. Consider using the regular Process class to check whether the PID is terminated.

@pjanotti

### PR DESCRIPTION
**Pull request by pjanotti**
That check for expected exception is already present in other tests but
it is very flaky in this specific test. The point of this test is about
method invocations and as long as the target process was terminated that
is verified so I'm simply removing the problematic step of the test.

Fixes #24961

### CODE REVIEW

File: src/System.Management/tests/System/Management/ManagementObjectTests.cs [hunk 1]
```diff
@@ -87,9 +82,6 @@ public void Invoke_Instance_And_Static_Method_Win32_Process()
                 Assert.Equal(0u, resultCode);
 
                 Assert.True(targetProcess.HasExited);
-
-                ManagementException managementException = Assert.Throws<ManagementException>(() => process.Get());
-                Assert.Equal(ManagementStatus.NotFound, managementException.ErrorCode);
```
Comment (stephentoub) [inline src/System.Management/tests/System/Management/ManagementObjectTests.cs]: What makes it flaky in this specific test?

Comment (pjanotti) [reply src/System.Management/tests/System/Management/ManagementObjectTests.cs]: The suspicion is that the process Id gets re-used so the call `process.Get()` ends up succeeding. That said I don't have confirmation of that, the test never failed on local runs but had a relatively high rate of failure on CI. I am going to give the repro tool a try to see if I can get a repro (out of curiosity to understand the exact cause).
