### PR TITLE
Make wmi test with Win32_Process more reliable

### LINKED ISSUE #24912: Test: System.Management.Tests.ManagementObjectTests/Invoke_Instance_And_Static_Method_Win32_Process failed with "Xunit.Sdk.ThrowsException"
Opened on behalf of @Jiayili1

The test `System.Management.Tests.ManagementObjectTests/Invoke_Instance_And_Static_Method_Win32_Process` has failed.

Assert.Throws() Failure\r
    Expected: typeof(System.Management.ManagementException)\r
    Actual:   (No exception was thrown)

        Stack Trace:

           at System.Management.Tests.ManagementObjectTests.Invoke_Instance_And_Static_Method_Win32_Process()
Build : Master - 20171027.01 (Core Tests)
Failing configurations:
- Windows.10.Amd64.Core-x64
  - Release

Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171027.01/workItem/System.Management.Tests/analysis/xunit/System.Management.Tests.ManagementObjectTests~2FInvoke_Instance_And_Static_Method_Win32_Process

### PR DESCRIPTION
**Pull request by pjanotti**
This should fix #24912 and #24961: it seems that the process id is being re-used and the call to Get is not throwing the expected exception. This change should prevent re-use of process id while the test is running.

Windows Server Core has both WMI and notepad so the test is fine to run on it.

### CODE REVIEW

File: src/System.Management/tests/System/Management/ManagementObjectTests.cs [hunk 1]
```diff
@@ -66,13 +65,24 @@ public void Invoke_Instance_And_Static_Method_Win32_Process()
             var processId = (uint)methodArgs[3];
             Assert.True(0u != processId, $"Unexpected process ID: {processId}");
 
-            var process = new ManagementObject($"Win32_Process.Handle=\"{processId}\"");
-            resultObj = process.InvokeMethod("Terminate", new object[]{ 0 });
-            resultCode = (uint)resultObj;
-            Assert.Equal(0u, resultCode);
+            // Before terminating the process open a handle to it so the processId cannot be re-used until
```
Comment (danmosemsft) [inline src/System.Management/tests/System/Management/ManagementObjectTests.cs]: Why not just store process.StartTime, and then if the PID still exists, check that it has changed?
This is how I solved this problem in a past codebase.
No need for pinvoke.

Comment (pjanotti) [reply src/System.Management/tests/System/Management/ManagementObjectTests.cs]: That is also a good approach, but, this way I feel like we are ensuring (hopefully :smile:) that the test behaves consistently on every run instead of handling differences between runs. If this comes back I will add the StartTime check.

**Comment by maririos** [comment]
@dotnet-bot test OSX x64 Debug Build
@dotnet-bot test Windows x64 Debug Build
@dotnet-bot test Windows x86 Release Build

**Comment by pjanotti** [comment]
@dotnet-bot test OSX x64 Debug Build
@dotnet-bot test Windows x64 Debug Build
@dotnet-bot test Windows x86 Release Build

**Comment by pjanotti** [comment]
@dotnet-bot test OSX x64 Debug Build

**Comment by danmosemsft** [comment]
@dotnet/dnceng it failed to pull down the tools
https://ci3.dot.net/job/dotnet_corefx/job/master/job/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/4919/console
eg 
```
15:53:41   Restoring packages for /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/init-tools.msbuild...
15:53:41   Retrying 'FindPackagesByIdAsync' for source 'https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-buildtools/nuget/v3/flatcontainer/microsoft.dotnet.build.tasks.feed/index.json'.
15:53:41   Access to the path '/tmp/NuGet/TempCache/f27b5511-1111-4374-a8d3-33f89038cb76' is denied.
15:53:41     Permission denied
```

@dotnet-bot test OSX x64 Debug Build please
