### PR TITLE
Port UriTypeConverter source and add tests.

### LINKED ISSUE #7501: TypeConverter cannot convert from String to Uri on Core
```
TypeDescriptor.GetConverter(typeof(Uri)).ConvertFromInvariantString("http://www.bing.com");
```

Results in:

```
      System.InvalidOperationException : Failed to convert 'http://www.bing.com' to type 'System.Uri'.
      ---- System.NotSupportedException : TypeConverter cannot convert from System.String.
```

Works fine on netstandard

### PR DESCRIPTION
**Pull request by ianhays**
The first commit ports the sources from TFS by dotnet-bot.

The second commit clean ups and changes the sources to work in CoreFX. It also adds some tests. I couldn't find the existing tests so I just wrote some new ones in the style of the other tests in the project. The unusual comment style of the sources (devdoc) is to match the other sources in the TypeConverter namespace for consistency.

resolves #7501

@Tanya-Solyanik @stephentoub

### CODE REVIEW

File: src/System.ComponentModel.TypeConverter/src/System/ComponentModel/UriTypeConverter.cs [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+        /// </devdoc>
+        public override bool CanConvertFrom(ITypeDescriptorContext context, Type sourceType)
+        {
+            if (sourceType == null)
+                throw new ArgumentNullException(nameof(sourceType));
+
+            if (sourceType == typeof(string) || sourceType == typeof(Uri))
+                return true;
+
+            return false;
```
Comment (justinvp) [inline src/System.ComponentModel.TypeConverter/src/System/ComponentModel/UriTypeConverter.cs]: Nit: This could be simplified as:

```csharp
return sourceType == typeof(string) || sourceType == typeof(Uri);
```

File: src/System.ComponentModel.TypeConverter/src/System/ComponentModel/UriTypeConverter.cs [hunk 2]
```diff
@@ -0,0 +1,92 @@
...
+        /// </devdoc>
+        public override bool CanConvertTo(ITypeDescriptorContext context, Type destinationType)
+        {
+            if (destinationType == typeof(string))
+                return true;
+
+            if (destinationType == typeof(Uri))
+                return true;
+
+            return false;
```
Comment (justinvp) [inline src/System.ComponentModel.TypeConverter/src/System/ComponentModel/UriTypeConverter.cs]: Nit: The whole method could be simplified as:

```csharp
public override bool CanConvertTo(ITypeDescriptorContext context, Type destinationType) =>
    destinationType == typeof(string) || destinationType == typeof(Uri);
```

File: src/System.ComponentModel.TypeConverter/src/System/ComponentModel/UriTypeConverter.cs [hunk 3]
```diff
@@ -0,0 +1,92 @@
...
+
+        /// <devdoc>
+        ///    <para>Converts the given object to the a Uri.</para>
+        /// </devdoc>
+        public override object ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, object value)
+        {
+            string uriString = value as string;
+            if (uriString != null)
+            {
+                if (String.IsNullOrEmpty(uriString))
```
Comment (justinvp) [inline src/System.ComponentModel.TypeConverter/src/System/ComponentModel/UriTypeConverter.cs]: Nit: lowercase `string`, e.g.:

```csharp
if (string.IsNullOrEmpty(uriString))
```

File: src/System.ComponentModel.TypeConverter/src/System/ComponentModel/UriTypeConverter.cs [hunk 4]
```diff
@@ -0,0 +1,92 @@
...
+                    return null;
+
+                // Let the Uri constructor throw any informative exceptions
+                return new Uri(uriString, UriKind.RelativeOrAbsolute);
+            }
+
+            Uri valueAsUri = value as Uri;
```
Comment (justinvp) [inline src/System.ComponentModel.TypeConverter/src/System/ComponentModel/UriTypeConverter.cs]: Nit: Should this be named `uri` to be consistent the naming used below in `ConvertTo`?

File: src/System.ComponentModel.TypeConverter/src/System/ComponentModel/UriTypeConverter.cs [hunk 5]
```diff
@@ -0,0 +1,92 @@
...
+        public override object ConvertTo(ITypeDescriptorContext context, CultureInfo culture, object value, Type destinationType)
+        {
+            if (destinationType == null)
+            {
+                throw new ArgumentNullException(nameof(destinationType));
+            }
+
+            Uri uri = value as Uri;
+
+            if (uri != null)
```
Comment (justinvp) [inline src/System.ComponentModel.TypeConverter/src/System/ComponentModel/UriTypeConverter.cs]: Nit: In `ConvertFrom` above, there is no extra line between the `Uri uri = value as Uri;` and the `if (uri != null)`. Ideally both methods would be consistent.

**Comment by hughbe** [comment]
Does the `ref` folder need to be updated?

**Comment by justinvp** [comment]
#7501 mentions the following snippet:

```csharp
TypeDescriptor.GetConverter(typeof(Uri)).ConvertFromInvariantString("http://www.bing.com");
```

Does `TypeDescriptor.GetConverter` need to be wired up to support `UriTypeConverter`?

Looks like it'd need to be added [here](https://github.com/dotnet/corefx/blob/6eed3985aa246946ff66016a4972d55525098f9e/src/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectTypeDescriptionProvider.cs#L48).

**Comment by ianhays** [comment]
>Does TypeDescriptor.GetConverter need to be wired up to support UriTypeConverter? Or will it just work?

Yes, it does. Thanks, I forgot that bit. I'll add it to the tests for that as well.

>Does the ref folder need to be updated? (I don't fully understand how this folder fits in here)

For some reason I assumed that was done automatically now but I admittedly haven't added API in a while so I'm a bit out of the loop on that. @mellinoe do we still have to modify the ref file to add any new surface area?

**Comment by ianhays** [comment]
test Innerloop OSX Debug Build and Test please

**Comment by ianhays** [comment]
Update: we did have to add uritypeconverter to the ref file for the net45 build. I updated this and rebased to include that change. It also required I keep UriTypeConverter in the ```System``` namespace (rather than System.ComponentModel) so I changed that too.

**Comment by ianhays** [comment]
test Innerloop OSX Debug Build and Test please
test Innerloop OSX Release Build and Test please

**Comment by ianhays** [comment]
test Innerloop OSX Debug Build and Test please
test Innerloop OSX Release Build and Test please

**Comment by stephentoub** [comment]
LGTM

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please
Test Innerloop OSX Release Build and Test please
