### PR TITLE
Provide a low-level API for reading and writing PKCS#12 (PFX) files

### LINKED ISSUE #28249: Create an API to manipulate PKCS12 objects
https://tools.ietf.org/html/rfc7292

* Allow enumeration of contents by type (KeyBag, PKCS8ShroudedKeyBag, CertBag, CRLBag, SecretBag)
  * SafeContents is a recursive node, so maybe it needs to be part of the enumerator and not an enumeratable thing.  Or maybe it should also be enumeratable because maybe someone wants to indicate "these belong together" for its contents.
* Should allow the authenticity and integrity passwords to be different (in password mode)
* Technically, the integrity mode can also be disabled.
* P2: Support for public-key modes
  * P3: Support for { public key integrity, password authenticity } and { password integrity, public key authenticity }
* Virtuous: A method which, given an X509Certificate2 where HasPrivateKey=true adds the key and the cert and used an automatic cert/key relationship identifier.
  * Windows-style would be to add the key to a shrouded key bag, the cert to be added to a CertBag which gets encrypted, and the key identifier to be a sequence number.
    * Windows also would carry the persisted key name (as "friendly name") and an indicator of the CSP/KSP, and (if appropriate) an indication if the key was a machine key or user key.
        * Need to decide what parts of these to do by default
* Each added item needs to be capable of having properties defined on it. (And each enumerated item capable of having the properties inspected)

Gotchas:
* The spec allows for keys to be "shrouded" (PKCS8 encrypted), unencrypted KeyBag, or encrypted KeyBag.  Need a way to distinguish user intent.
* The spec allows for unencrypted and encrypted CertBags.  So we need a way to distinguish user intent.
* Technically speaking, all other bags have this same conundrum.  Only private keys are tri-state, though.

Algorithms:
* Windows 7 only supports the legacy PBES1 options.
* We definitely need to allow user expression of algorithm.  Should we require it?  Or have a default of "What Windows 7 does"?

Design:
* Maybe "build" and "read" don't need to be the same class?
  * If builder is separate, does it need "append"?
* For a separate builder, it might be easiest to require the passwords/keys at construction time, and then have an API which is AddEncryptedContents(SafeBag) and AddUnencryptedContents(SafeBag).
    * Or maybe SafeBags should have a property of whether they are (reader) or should-be (builder) encrypted.

# API Proposal

## Discussion points

* The `AuthenticatedSafe` property: This name comes from a type name in the RFC (the field name is `authSafe`), and an AuthenticatedSafe is a collection of `SafeContents`.
  * Other libraries:
    * BouncyCastle calls it `ContentInfos`
    * OpenSSL doesn't refer to the field, but has `PKCS12_unpack_authsafes` (plural) to read it, suggesting a name of `AuthSafe` in lieu of `SafeContents`.
  * Alternative Suggestions:
    * Rename `Pkcs12SafeContents` to `[Pkcs12]AuthSafe`, rename property to `Auth[enticated]Safes`
* The prefix `Pkcs12` on types: Would it be clearer (though somewhat inaccurate) to use `Pfx` instead?
* Should all of the types other than the attribute be put into a Pkcs12 sub-namespace?
* Should the two nested enums be promoted out?
* Should the `PublicKey` enum members be removed until there is support?
* Pkcs12Builder.AddSafeContentsUnencrypted can accept an encrypted SafeContents and will succeed (because no further encryption is required).  Is there a better name which still helps callers be aware that a SafeContents they just built is not going to be encrypted?

## Exception Model

* Pkcs12Info.VerifyMac will return `false` when there is no MAC to verify (alternatively, InvalidOperationException)
* `ArgumentNullException` in all the expected places.
* `InvalidOperationException`:
  * `Pkcs12Builder`
    * `IsSealed == false`
      * `Encode`
      * `TryEncode`
    * `IsSealed == true`
      * Seal\*
      * Add\*
  * `Pkcs12SafeContents`:
    * `IsReadOnly == true`
      * Add*
    * `DataConfidentialityMode != None`
      * `GetBags`
    * `DataConfidentialityMode != Password`
      * `Decrypt`
* `CryptographicException`:
  * Decode fails, Decrypt fails, Encode catches something late (like illegal OID values).
  * Pretty much every exception aside from the ones above.

## Contract Proposal

```C#
namespace System.Security.Cryptography.Pkcs
{
    public sealed partial class Pkcs9LocalKeyId : Pkcs9AttributeObject
    {
        public ReadOnlyMemory<byte> KeyId { get; }
        public Pkcs9LocalKeyId() => throw null;
        public Pkcs9LocalKeyId(ReadOnlySpan<byte> keyId) => throw null;
    }
    public sealed partial class Pkcs12Builder
    {
        public bool IsSealed { get; }
        public void AddSafeContentsEncrypted(Pkcs12SafeContents safeContents, ReadOnlySpan<byte> passwordBytes, PbeParameters pbeParameters) => throw null;
        public void AddSafeContentsEncrypted(Pkcs12SafeContents safeContents, ReadOnlySpan<char> password, PbeParameters pbeParameters) => throw null;
        public void AddSafeContentsUnencrypted(Pkcs12SafeContents safeContents) => throw null;
        public byte[] Encode() => throw null;
        public void SealAndMac(ReadOnlySpan<char> password, HashAlgorithmName hashAlgorithm, int iterationCount) => throw null;
        public void SealWithoutIntegrity() => throw null;
        public bool TryEncode(Span<byte> destination, out int bytesWritten) => throw null;
    }
    public sealed partial class Pkcs12Info
    {
        private Pkcs12Info() { }
        public ReadOnlyCollection<Pkcs12SafeContents> AuthenticatedSafe { get; }
        public IntegrityMode DataIntegrityMode { get; }
        public bool VerifyMac(ReadOnlySpan<char> password) => throw null;
        public static Pkcs12Info Decode(ReadOnlyMemory<byte> encodedBytes, out int bytesConsumed, bool skipCopy=false) => throw null;

        public enum IntegrityMode
        {
            Unknown = 0,
            None = 1,
            Password = 2,
            PublicKey = 3,
        }
    }
    public sealed partial class Pkcs12SafeContents
    {
        public ConfidentialityMode DataConfidentialityMode { get; }
        public bool IsReadOnly { get; }
        public void AddSafeBag(Pkcs12SafeBag safeBag) => throw null;
        public CertBag AddCertificate(X509Certificate2 certificate) => throw null;
        public KeyBag AddKeyUnencrypted(AsymmetricAlgorithm key) => throw null;
        public ShroudedKeyBag AddShroudedKey(AsymmetricAlgorithm key, ReadOnlySpan<char> password, PbeParameters pbeParameters) => throw null;
        public ShroudedKeyBag AddShroudedKey(AsymmetricAlgorithm key, ReadOnlySpan<byte> password, PbeParameters pbeParameters) => throw null;
        public SecretBag AddSecret(Oid secretType, ReadOnlyMemory<byte> secretValue, bool skipCopy=false) => throw null;
        public void Decrypt(ReadOnlySpan<char> password) => throw null;
        public IEnumerable<Pkcs12SafeBag> GetBags() => throw null;
        public enum ConfidentialityMode
        {
            Unknown = 0,
            None = 1,
            Password = 2,
            PublicKey = 3,
        }
    }
    public abstract partial class Pkcs12SafeBag
    {
        protected Pkcs12SafeBag(string bagIdValue) { }
        public CryptographicAttributeObjectCollection Attributes { get; }
        public byte[] Encode() => throw null;
        public Oid GetBagId() => throw null;
        public bool TryEncode(Span<byte> destination, out int bytesWritten) => throw null;
        protected abstract bool TryEncodeValue(Span<byte> destination, out int bytesWritten);
    }
    public sealed partial class CertBag : Pkcs12SafeBag
    {
        public CertBag(Oid certificateType, ReadOnlyMemory<byte> encodedCertificate, bool skipCopy=false) : base(null) => throw null;
        public bool IsX509Certificate { get; }
        public ReadOnlyMemory<byte> EncodedCertificate { get; }
        public Oid GetCertificateType() => throw null;
        public X509Certificate2 GetCertificate() => throw null;
        protected override bool TryEncodeValue(Span<byte> destination, out int bytesWritten) => throw null;
    }
    public sealed partial class KeyBag : Pkcs12SafeBag
    {
        public KeyBag(ReadOnlyMemory<byte> pkcs8PrivateKey, bool skipCopy=false) : base(null) { }
        public ReadOnlyMemory<byte> Pkcs8PrivateKey { get; }
        protected override bool TryEncodeValue(Span<byte> destination, out int bytesWritten) => throw null;
    }
    public sealed partial class SafeContentsBag : Pkcs12SafeBag
    {
        private SafeContentsBag() : base(null) { }
        protected override bool TryEncodeValue(Span<byte> destination, out int bytesWritten) => throw null;
        public Pkcs12SafeContents SafeContents { get; }
        public static SafeContentsBag CreateEncrypted(Pkcs12SafeContents safeContents, ReadOnlySpan<byte> passwordBytes, PbeParameters pbeParameters) => throw null;
        public static SafeContentsBag CreateEncrypted(Pkcs12SafeContents safeContents, ReadOnlySpan<char> password, PbeParameters pbeParameters) => throw null;
        public static SafeContentsBag CreateUnencrypted(Pkcs12SafeContents contents) => throw null;
    }
    public sealed partial class SecretBag : Pkcs12SafeBag
    {
        private SecretBag() : base(null) { }
        public Oid GetSecretType() => throw null;
        public ReadOnlyMemory<byte> SecretValue { get; }
        protected override bool TryEncodeValue(Span<byte> destination, out int bytesWritten) => throw null;
    }
    public sealed partial class ShroudedKeyBag : Pkcs12SafeBag
    {
        public ShroudedKeyBag(ReadOnlyMemory<byte> encryptedPkcs8PrivateKey, bool skipCopy=false) : base(null) { }
        public ReadOnlyMemory<byte> EncryptedPkcs8PrivateKey { get; }
        protected override bool TryEncodeValue(Span<byte> destination, out int bytesWritten) => throw null;
    }
}
```

### PR DESCRIPTION
**Pull request by bartonjs**
This change adds two top-level classes, Pkcs12Info and Pkcs12Builder, for
reading existing file blobs and creating new ones.  These classes, and the
object model they expose/consume, are very raw on top of IETF RFC 7292.
Most user interaction with a PFX file/blob will continue to be with the
X509Certificate2 constructor (and Export method) and the
X509Certificate2Collection Import and Export methods.

Fixes #28249.

### CODE REVIEW

File: src/Common/src/Microsoft/Win32/SafeHandles/SafeUnicodeStringHandle.cs [hunk 1]
```diff
@@ -24,13 +24,16 @@ public SafeUnicodeStringHandle(string s)
         public unsafe SafeUnicodeStringHandle(ReadOnlySpan<char> s)
             : base(IntPtr.Zero, ownsHandle: true)
         {
-            int cch = checked(s.Length + 1);
-            int cb = checked(cch * sizeof(char));
-            handle = Marshal.AllocHGlobal(cb);
+            if (s != default)
```
Comment (stephentoub) [inline src/Common/src/Microsoft/Win32/SafeHandles/SafeUnicodeStringHandle.cs]: Assuming you're drawing a distinction here between `s != default` and `s.Length > 0`, it'd be good to add a comment to that effect.

File: src/Common/src/System/Security/Cryptography/Pkcs12Kdf.cs [hunk 2]
```diff
@@ -107,7 +107,15 @@ internal static class Pkcs12Kdf
             int SLen = ((salt.Length - 1 + vBytes) / vBytes) * vBytes;
 
             // The password is a null-terminated UTF-16BE version of the input.
-            int passLen = (password.Length + 1) * 2;
+            int passLen = checked((password.Length + 1) * 2);
+
+            // "" will have a pointer value pointing at the terminating \0, and length 0.
+            // null will have a pointer pointing to null and length 0.
```
Comment (stephentoub) [inline src/Common/src/System/Security/Cryptography/Pkcs12Kdf.cs]: Those aren't the only two options, of course.  `"foo".AsSpan(1, 0)` will have a ref/pointer value that's not null and a length 0, but it won't be pointing at `\0`.

File: src/System.Security.Cryptography.Pkcs/src/Resources/Strings.resx [hunk 3]
```diff
@@ -241,6 +241,30 @@
...
+    <value>This operation is not valid on an encrypted or enveloped Pkcs12SafeContents.</value>
+  </data>
+  <data name="Cryptography_Pkcs12_CertBagNotX509" xml:space="preserve">
+    <value>The Pkcs12CertBag contents are not an X.509 certificate.</value>
+  </data>
+  <data name="Cryptography_Pkcs12_PfxIsSealed" xml:space="preserve">
+    <value>The Pkcs12Builder has been sealed and can no longer be modified.</value>
+  </data>
+  <data name="Cryptography_Pkcs12_PfxMustBeSealed" xml:space="preserve">
+    <value>The Pkcs12Builder must be sealed before it can be encoded.</value>
```
Comment (stephentoub) [inline src/System.Security.Cryptography.Pkcs/src/Resources/Strings.resx]: Is "sealed" the language the RFC uses?  If yes, ok.  If no, can we pick a different term?  For someone who knows C#, this makes it sounds like the class itself is or must be `sealed`.

File: src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/Pkcs12Builder.cs [hunk 4]
```diff
@@ -0,0 +1,354 @@
...
+        public bool IsSealed => !_sealedData.IsEmpty;
+
+        public void AddSafeContentsEncrypted(
+            Pkcs12SafeContents safeContents,
+            byte[] passwordBytes,
+            PbeParameters pbeParameters)
+        {
+            AddSafeContentsEncrypted(
+                safeContents,
+                // Allows null.
```
Comment (stephentoub) [inline src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/Pkcs12Builder.cs]: What does this comment mean?  Just that the ROS ctor is tolerant of null arrays, or something else?

File: src/System.Security.Cryptography.Pkcs/src/Resources/Strings.resx (hunk 3 above)
Comment (bartonjs) [reply src/System.Security.Cryptography.Pkcs/src/Resources/Strings.resx]: > Is "sealed" the language the RFC uses?

No, it's a consequence of the builder API.  It means "you need to call one of SealWithMac, SealWithoutIntegrity, or the future SealWithCertificate" (using the verb from the method name)

File: src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/Pkcs12Builder.cs (hunk 4 above)
Comment (bartonjs) [reply src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/Pkcs12Builder.cs]: Yeah, it made more sense when it was an extension method invocation.

File: src/System.Security.Cryptography.Pkcs/src/Resources/Strings.resx (hunk 3 above)
Comment (stephentoub) [reply src/System.Security.Cryptography.Pkcs/src/Resources/Strings.resx]: Should we consider an alternative to "Seal" then?  "Freeze"?

File: src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/Pkcs12Builder.cs [hunk 5]
```diff
@@ -0,0 +1,354 @@
...
+            if (IsSealed)
+                throw new InvalidOperationException(SR.Cryptography_Pkcs12_PfxIsSealed);
+
+            ContentInfoAsn[] contents = _contents?.ToArray() ?? Array.Empty<ContentInfoAsn>();
+
+            byte[] rentedAuthSafe = null;
+            Span<byte> authSafeSpan = default;
+            byte[] rentedMac = null;
+            Span<byte> macSpan = default;
+            Span<byte> salt = stackalloc byte[0];
```
Comment (stephentoub) [inline src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/Pkcs12Builder.cs]: I'm assuming the `= stackalloc byte[0]` is to avoid a compilation error about span lifetimes?  I'm curious in this case what the compiler complains about?

File: src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/Pkcs12CertBag.cs [hunk 6]
```diff
@@ -0,0 +1,125 @@
...
+
+            return EncodeBagValue(certificateType.Value, encodedCertificate);
+        }
+
+        private static byte[] EncodeBagValue(string certificateType, ReadOnlyMemory<byte> encodedCertificate)
+        {
+            // Read to ensure that there is precisely one legally encoded value.
+            AsnReader reader = new AsnReader(encodedCertificate, AsnEncodingRules.BER);
+            reader.GetEncodedValue();
+            reader.ThrowIfNotEmpty();
```
Comment (stephentoub) [inline src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/Pkcs12CertBag.cs]: The comment says "precisely one".  Naively from these method names I'd assume this was verifying >= 1 rather than == 1.

File: src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/Pkcs12SafeBag.cs [hunk 7]
```diff
@@ -0,0 +1,143 @@
...
+
+        public Oid GetBagId()
+        {
+            if (_bagOid == null)
+            {
+                _bagOid = new Oid(_bagIdValue);
+            }
+
+            return new Oid(_bagOid);
+        }
```
Comment (stephentoub) [inline src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/Pkcs12SafeBag.cs]: Why is this creating one Oid and then cloning it?  It's creating the first one to cache it to avoid multiple parsings of _bagIdValue, but then cloning to avoid potential mutation of the cached instance?

File: src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/Pkcs12CertBag.cs (hunk 6 above)
Comment (bartonjs) [reply src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/Pkcs12CertBag.cs]: `GetEncodedValue` throws if there's not a value, then consumes the value.  `ThrowIfNotEmpty` throws if there is still data.

File: src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/Pkcs12SafeBag.cs (hunk 7 above)
Comment (bartonjs) [reply src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/Pkcs12SafeBag.cs]: Yep

File: src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/Pkcs12CertBag.cs (hunk 6 above)
Comment (stephentoub) [reply src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/Pkcs12CertBag.cs]: Ah, I misread ThrowIfNotEmpty as ThrowIfEmpty.

File: src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/Pkcs12Builder.cs (hunk 5 above)
Comment (bartonjs) [reply src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/Pkcs12Builder.cs]: System\Security\Cryptography\Pkcs\Pkcs12Builder.cs(191,28): error CS8353: A result of a stackalloc expression of type 'Span<byte>' cannot be used in this context because it may be exposed outside of the containing method

You can't assign a stackalloc in a different scope than the variable declaration unless the variable declaration included a stackalloc.

Comment (stephentoub) [reply src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/Pkcs12Builder.cs]: > You can't assign a stackalloc in a different scope than the variable declaration unless the variable declaration included a stackalloc.

Yes, but that would only matter if it could possibly be returned, which doesn't appear to be the case here.  @VSadov, @jaredpar, is there a fundamental issue here, or the compiler just doesn't do the dataflow analysis to understand that this is actually safe?

File: src/System.Security.Cryptography.Pkcs/src/Resources/Strings.resx (hunk 3 above)
Comment (bartonjs) [reply src/System.Security.Cryptography.Pkcs/src/Resources/Strings.resx]: Freeze feels less concise (and "Seal" matches the vault/safe metaphor of PFX better).  Some thesaurus time turned up "Stamp" (which definitely works for MAC and Certificate, but feels wrong for "WIthoutIntegrity").  "Close" would be good, if that didn't already have implied meaning.  "Shut"?

Alternatively, if the problem is just the resource strings then the wording could be adjusted.  "One of the Seal methods must be called before calling an Encode method".

Comment (stephentoub) [reply src/System.Security.Cryptography.Pkcs/src/Resources/Strings.resx]: Ok.  Let's at least reword the resource strings. Thanks.

File: src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/Pkcs12Builder.cs (hunk 5 above)
Comment (bartonjs) [reply src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/Pkcs12Builder.cs]: Based on the last time I talked to those guys about it: The compiler doesn't do the dataflow analysis.  A variable is either "returnable" or "not", and it's "returnable" unless it can very quickly prove otherwise.  @jaredpar had talked about some friendlier syntax here, like `Span<byte> salt = stackalloc;`, but that wouldn't help for the already released compilers.

**Comment by alexkeh** [comment]
Will this feature be merged with .NET Core 2.2 or wait until .NET Core 3.0?
