### PR TITLE
Fixed System.IO.Compression FileData DST bug

### LINKED ISSUE #1326: System.IO.Compression tests need to remove a workaround for not understood DST issue
The System.IO.Comprssion tests verify the last modified metadata of zip file entries.  There is currently a workaround where the check will succeed if the entry is 1 hour earlier than expected.  This is to work around a not understood DST issue either in the test, or in the library.  I need to understand if the issue is a test or product issue, and fix.

### PR DESCRIPTION
**Pull request by ianhays**
The FileData class for testing in System.IO.Compression was initializing DateTimes using Ticks and an unspecified DateTimeKind that resulted in some times being off by an hour when the time was during Daylight Savings Time. I've fixed these times and reformatted them to use UTC times so testing is timezone independent. I also reformatted some tests to use Theories.

resolves #1326

@stephentoub @justinvp

### CODE REVIEW

File: src/Common/tests/System/IO/Compression/ZipTestHelper.cs [hunk 1]
```diff
@@ -180,13 +168,10 @@ public static void IsZipSameAsDir(Stream archiveFile, String directory, ZipArchi
...
                         {
-                            Double offBy = (file.LastModifiedDate - entry.LastWriteTime.DateTime).TotalSeconds;
-                            Assert.True(
-                                (offBy >= -2 && offBy <= 2) ||
-                                // Temporary adjustment for active issue 1326
-                                ((offBy >= 3598 && offBy <= 3602)),
-                                String.Format("{0}, {1}, {2}", file.LastModifiedDate.ToString(), entry.LastWriteTime.DateTime.ToString(), file.FullName));
-                        }
+                            DateTime lower = file.LastModifiedDate.AddSeconds(-2);
+                            DateTime upper = file.LastModifiedDate.AddSeconds(2);
```
Comment (justinvp) [inline src/Common/tests/System/IO/Compression/ZipTestHelper.cs]: I know you're just cleaning up existing code, but while you're at it, would it be worth putting `2` in a `const` and/or adding a comment explaining that the zip timestamp resolution is 2 seconds, hence the reason for the range assert?

File: src/Common/tests/System/IO/Compression/ZipTestHelper.cs [hunk 2]
```diff
@@ -198,7 +183,7 @@ public static void IsZipSameAsDir(Stream archiveFile, String directory, ZipArchi
                         if (entry == null) //entry not found
                         {
                             string entryNameOtherSlash = FlipSlashes(entryName);
-                            Boolean isEmtpy = !allFilesInDir.Any(
+                            Boolean isEmtpy = !files.Any(
```
Comment (justinvp) [inline src/Common/tests/System/IO/Compression/ZipTestHelper.cs]: Nit: `bool`. Or maybe the code formatting cleanup should be done separately since it looks like a lot of the test and product code is using type names instead of language keywords throughout.

File: src/System.IO.Compression/tests/ZipArchive/zip_ManualAndCompatibilityTests.cs [hunk 3]
```diff
@@ -8,35 +8,26 @@ namespace System.IO.Compression.Tests
...
-                ZipTest.compat("excel.xlsx")), ZipTest.compat("excel"), ZipArchiveMode.Update, true, true);
-            ZipTest.IsZipSameAsDir(await StreamHelpers.CreateTempCopyStream(
-                ZipTest.compat("powerpoint.pptx")), ZipTest.compat("powerpoint"), ZipArchiveMode.Update, true, true);
-            ZipTest.IsZipSameAsDir(await StreamHelpers.CreateTempCopyStream(
-                ZipTest.compat("word.docx")), ZipTest.compat("word"), ZipArchiveMode.Update, true, true);
-            ZipTest.IsZipSameAsDir(await StreamHelpers.CreateTempCopyStream(
-                ZipTest.compat("silverlight.xap")), ZipTest.compat("silverlight"), ZipArchiveMode.Update, true, true);
-            ZipTest.IsZipSameAsDir(await StreamHelpers.CreateTempCopyStream(
-                ZipTest.compat("packaging.package")), ZipTest.compat("packaging"), ZipArchiveMode.Update, true, true);
+            //
```
Comment (justinvp) [inline src/System.IO.Compression/tests/ZipArchive/zip_ManualAndCompatibilityTests.cs]: Nit: empty `//`

File: src/System.IO.Compression/tests/ZipArchive/zip_ReadTests.cs [hunk 4]
```diff
@@ -9,53 +9,35 @@ namespace System.IO.Compression.Tests
...
+        [InlineData("small.zip", "small")]
+        [InlineData("unicode.zip", "unicode")]
+        public static async Task TestStreamingRead(string zipFile, string zipFolder)
         {
-            using (var stream = await StreamHelpers.CreateTempCopyStream(zipFile))
+            using (var stream = await StreamHelpers.CreateTempCopyStream(ZipTest.zfile(zipFile)))
             {
                 Stream wrapped = new WrappedStream(stream, true, false, false, null);
-                ZipTest.IsZipSameAsDir(wrapped, directory, ZipArchiveMode.Read, false, false);
+                ZipTest.IsZipSameAsDir(wrapped, ZipTest.zfolder(zipFolder), ZipArchiveMode.Read, false, false);
```
Comment (justinvp) [inline src/System.IO.Compression/tests/ZipArchive/zip_ReadTests.cs]: Nit: use named parameters to improve readability of bool parameters. (Maybe done at some point later in a separate cleanup PR)

**Comment by justinvp** [comment]
I took a quick look through the changes. LGTM.

File: src/Common/tests/System/IO/Compression/ZipTestHelper.cs (hunk 1 above)
Comment (ianhays) [inline src/Common/tests/System/IO/Compression/ZipTestHelper.cs]: Good idea. Adding a _zipTimestampResolution local int const.

File: src/Common/tests/System/IO/Compression/ZipTestHelper.cs (hunk 2 above)
Comment (ianhays) [inline src/Common/tests/System/IO/Compression/ZipTestHelper.cs]: There are quite a few of these throughout System.IO.Compression. I'll fix this one but I think I'll save the rest for a PR dedicated to that purpose so the diff doesn't get too complicated.

File: src/System.IO.Compression/tests/ZipArchive/zip_ReadTests.cs (hunk 4 above)
Comment (ianhays) [inline src/System.IO.Compression/tests/ZipArchive/zip_ReadTests.cs]: As above, will save for a cleanup PR.

**Comment by ianhays** [comment]
Thanks for the review, Justin!
