### PR TITLE
Throw on duplicate key in Sorted‎List ctor from Dictionary.Tests.cs

### LINKED ISSUE #7019: SortedList dictionary initialization with case insensitive string comparer allows duplicate keys
Expected an exception when SortedList is initialized with a dictionary that contains contains keys that differ only in case and a case insensitive string comparer.

```
using System;
using System.Collections.Generic;
using static System.Diagnostics.Debug;

namespace Scratch {

    public class Program {

        public static void Main(string[] args) {

            var sortedListFromDictionary = new SortedList<string, string>(
                dictionary: new Dictionary<string, string> {
                    { "A", "A" },
                    { "a", "a" }
                },
                comparer: StringComparer.CurrentCultureIgnoreCase
            );

            var sortedListFromList = new SortedList<string, string>(StringComparer.CurrentCultureIgnoreCase);
            sortedListFromList["A"] = "A";
            sortedListFromList["a"] = "a";

            Assert(sortedListFromDictionary.Count == sortedListFromList.Count);
        }
    }
}
```

### PR DESCRIPTION
**Pull request by JonHanna**
Fixes #7019

Also include relevant tests for `Dictionary` and `SortedDictionary` as well as `SortedList` to guard against comparable regressions.

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @ellismg, @AlexGhiondea

**Comment by JonHanna** [comment]
Test Innerloop CentOS7.1 Release Build and Test
(Timeout http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/centos7.1_release_prtest/1666/)

File: src/System.Collections/src/System/Collections/Generic/SortedList.cs [hunk 1]
```diff
@@ -152,10 +152,31 @@ public SortedList(IDictionary<TKey, TValue> dictionary, IComparer<TKey> comparer
...
+            {
+                dictionary.Keys.CopyTo(_keys, 0);
+                dictionary.Values.CopyTo(_values, 0);
+                Debug.Assert(count == _keys.Length);
+                if (count > 1)
+                {
+                    Array.Sort<TKey, TValue>(_keys, _values, comparer);
+                    comparer = Comparer; // obtain default if this is null.
+                    TKey keyPrev = _keys[0];
+                    for (int i = 1; i != _keys.Length; ++i)
```
Comment (ellismg) [inline src/System.Collections/src/System/Collections/Generic/SortedList.cs]: NIT: do we have a style guideline on using postfix vs prefix?

Comment (stephentoub) [inline src/System.Collections/src/System/Collections/Generic/SortedList.cs]: Not that I'm aware of.

File: src/System.Collections/src/System/Collections/Generic/SortedList.cs [hunk 2]
```diff
@@ -152,10 +152,31 @@ public SortedList(IDictionary<TKey, TValue> dictionary, IComparer<TKey> comparer
...
+                    {
+                        TKey keyNext = _keys[i];
+                        if (comparer.Compare(keyPrev, keyNext) >= 0)
```
Comment (stephentoub) [inline src/System.Collections/src/System/Collections/Generic/SortedList.cs]: Why >= rather than just =?  We don't need to validate that Sort did the right thing, do we?

File: src/System.Collections/src/System/Collections/Generic/SortedList.cs [hunk 3]
```diff
@@ -152,10 +152,31 @@ public SortedList(IDictionary<TKey, TValue> dictionary, IComparer<TKey> comparer
...
+                        {
+                            throw new ArgumentException(SR.Format(SR.Argument_AddingDuplicate, keyNext));
+                        }
+
+                        keyPrev = keyNext;
```
Comment (stephentoub) [inline src/System.Collections/src/System/Collections/Generic/SortedList.cs]: Why copy the keys around?  Why not just iterate through comparing _keys[i-1] to _keys[i]?

File: src/System.Collections/src/System/Collections/Generic/SortedList.cs (hunk 2 above)
Comment (JonHanna) [inline src/System.Collections/src/System/Collections/Generic/SortedList.cs]: I went for `>=` as "Has incorrect value". On consideration, `==` as "Has particular incorrect value we have reason to expect" is clearer as to why it is being done, so I'll change to that.

File: src/System.Collections/src/System/Collections/Generic/SortedList.cs (hunk 3 above)
Comment (JonHanna) [inline src/System.Collections/src/System/Collections/Generic/SortedList.cs]: No strong reason, aside from I seem to be developing an instinct for pulling array elements local if they are used more than once. Again though, I think comparing `_keys[i - 1]` and `_keys[i]` will be clearer as to the intent, so I'll change. I might pull `_keys` itself local though, rather than have n-1 field accesses.

**Comment by stephentoub** [comment]
LGTM. Thanks.
