### PR TITLE
Fix Globalization tests on Alpine

### LINKED ISSUE #28189: Test failure: System.Globalization.Tests.NumberFormatInfoCurrencyNegativePattern/CurrencyNegativePattern_Get(locale: \"fa-IR\")
Opened on behalf of @Sunny-pu

The test `System.Globalization.Tests.NumberFormatInfoCurrencyNegativePattern/CurrencyNegativePattern_Get(locale: \"fa-IR\")` has failed.

Assert.Contains() Failure
    Not found: 8
    In value:  Int32[] [1, 0]

        Stack Trace:

        null
Build : Master - 20180319.01 (Core Tests)
Failing configurations:
- Alpine.36.Amd64-x64
  - Release

Details:
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180319.01/workItem/System.Globalization.Tests/analysis/xunit/System.Globalization.Tests.NumberFormatInfoCurrencyNegativePattern~2FCurrencyNegativePattern_Get(locale:%20%5C%22fa-IR%5C%22)

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes #28189 and #28190

### CODE REVIEW

**Comment by tarekgh** [comment]
CC @danmosemsft @krwq

**Comment by tarekgh** [comment]
test Alpine.3.6 x64 Debug Build please
test Windows x86 Release Build  please

**Comment by tarekgh** [comment]
test Windows x64 Debug Build please

**Comment by tarekgh** [comment]
test OSX x64 Debug Build please

File: src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs [hunk 1]
```diff
@@ -39,7 +39,7 @@ internal static int[] GetCurrencyNegativePatterns(string localeName)
                     {
                         return (PlatformDetection.WindowsVersion < 10) ? new int[] { 3 } : new int[] { 6, 3 };
                     }
-                    if (PlatformDetection.ICUVersion.Major == 59)
+                    if (PlatformDetection.ICUVersion.Major == 59 || PlatformDetection.ICUVersion.Major == 58)
```
Comment (stephentoub) [inline src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs]: Did the behavior change before these versions or after?  I'm wondering if it should be e.g.
```C#
if (PlatformDetection.ICUVersion.Major >= 58)
```
so that don't have to update this again when 60 comes out with the same behavior as 58 and 59.

**Comment by tarekgh** [comment]
@dotnet-bot test this please

File: src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs (hunk 1 above)
Comment (tarekgh) [reply src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs]: look at the else block 

```C#
                    else if (PlatformDetection.ICUVersion.Major > 59)
                    {
                        return new int[] { 1 };
                    }
```

That define the behavior after version 59.

Comment (stephentoub) [reply src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs]: I see; that was hidden in the diff.  So we didn't hit this before because no platform we tested on had version 58 until now?

Comment (tarekgh) [reply src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs]: right, it happens that Alpine image using ICU version 58.2.

**Comment by tarekgh** [comment]
Alpine failure is tracked in #28246

**Comment by tarekgh** [comment]
@danmosemsft does the following failure in Linux runs is same as other Python failures? or we need to track this one with new issue?

https://mc.dot.net/#/user/tarekgh/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/dc39a03d86ba37f443d8d4ea97873a61d2016756/workItem/System.Net.HttpListener.Tests/wilogs

```
2018-03-20 17:02:32,113: INFO: proc(54): run_and_log_output: Output: ~/dotnetbuild/work/4b698a84-f927-4802-b10b-cb0c1e7fb764/Work/027cb773-e227-498c-89c4-44554402ad10/Unzip ~/dotnetbuild/work/4b698a84-f927-4802-b10b-cb0c1e7fb764/Work/027cb773-e227-498c-89c4-44554402ad10/Unzip
2018-03-20 17:02:32,187: INFO: proc(54): run_and_log_output: Output: Traceback (most recent call last):
2018-03-20 17:02:32,188: INFO: proc(54): run_and_log_output: Output:   File "DumplingHelper.py", line 131, in <module>
2018-03-20 17:02:32,188: INFO: proc(54): run_and_log_output: Output:     main(sys.argv)
2018-03-20 17:02:32,188: INFO: proc(54): run_and_log_output: Output:   File "DumplingHelper.py", line 113, in main
2018-03-20 17:02:32,188: INFO: proc(54): run_and_log_output: Output:     install_dumpling()
2018-03-20 17:02:32,188: INFO: proc(54): run_and_log_output: Output:   File "DumplingHelper.py", line 34, in install_dumpling
2018-03-20 17:02:32,189: INFO: proc(54): run_and_log_output: Output:     print("An unexpected error was encountered while installing dumpling.py: " + sys.exc_info()[0])
2018-03-20 17:02:32,189: INFO: proc(54): run_and_log_output: Output: TypeError: cannot concatenate 'str' and 'type' objects
```

**Comment by tarekgh** [comment]
merging this one as all failures are unrelated and tracked.
