### PR TITLE
Fix Failed DirectoryServices Test

### LINKED ISSUE #26531: [Regression] DirectoryServices tests failing - The Workstation service has not been started
GetDomainController_InvalidIPV6_ThrowsActiveDirectoryObjectNotFoundException test is failing on all PRs with:

```
Message :
Assert.Throws() Failure
Expected: typeof(System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException)
Actual:   typeof(System.DirectoryServices.ActiveDirectory.ActiveDirectoryOperationException): The Workstation service has not been started.
Stack Trace :
   at System.DirectoryServices.ActiveDirectory.DirectoryContext.IsContextValid(DirectoryContext context, DirectoryContextType contextType) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.DirectoryServices\src\System\DirectoryServices\ActiveDirectory\DirectoryContext.cs:line 368
   at System.DirectoryServices.ActiveDirectory.DirectoryContext.isServer() in D:\j\workspace\windows-TGrou---f8ac6754\src\System.DirectoryServices\src\System\DirectoryServices\ActiveDirectory\DirectoryContext.cs:line 431
   at System.DirectoryServices.ActiveDirectory.DomainController.GetDomainController(DirectoryContext context) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.DirectoryServices\src\System\DirectoryServices\ActiveDirectory\DomainController.cs:line 128
 ```

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes #26531

### CODE REVIEW

**Comment by tarekgh** [comment]
CC @danmosemsft @karelz @tquerec

File: src/System.DirectoryServices/tests/System/DirectoryServices/ActiveDirectory/DomainControllerTests.cs [hunk 1]
```diff
@@ -42,7 +42,11 @@ public void GetDomainController_InvalidName_ThrowsActiveDirectoryObjectNotFoundE
         public void GetDomainController_InvalidIPV6_ThrowsActiveDirectoryObjectNotFoundException()
         {
             var context = new DirectoryContext(DirectoryContextType.DirectoryServer, "[::1]:port");
-            Assert.Throws<ActiveDirectoryObjectNotFoundException>(() => DomainController.GetDomainController(context));
+            Exception exception = Record.Exception(() => DomainController.GetDomainController(context));
+            Assert.NotNull(exception);
+            Assert.True(exception is ActiveDirectoryObjectNotFoundException ||
+                        exception is ActiveDirectoryOperationException,
+                        $"We got unrecognized exception {exception}");
```
Comment (karelz) [inline src/System.DirectoryServices/tests/System/DirectoryServices/ActiveDirectory/DomainControllerTests.cs]: There are 3 additional tests failing in nightly runs -- see [20180123.01](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180123.01/workItem/System.DirectoryServices.Tests) and [20180123.04](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180123.04/workItem/System.DirectoryServices.Tests)

Comment (tarekgh) [reply src/System.DirectoryServices/tests/System/DirectoryServices/ActiveDirectory/DomainControllerTests.cs]: will take a look and update the PR. Thanks @karelz

**Comment by tarekgh** [comment]
Merged to avoid CI failures. if anyone has any comment, we can fix it as needed. Thanks.

File: src/System.DirectoryServices/tests/System/DirectoryServices/ActiveDirectory/ForestTests.cs [hunk 2]
```diff
@@ -53,15 +53,25 @@ public void GetForest_NonNullNameAndNotRootedDomain_ThrowsActiveDirectoryObjectN
         [InlineData(DirectoryContextType.Forest, "\0")]
         [InlineData(DirectoryContextType.DirectoryServer, "server:port")]
         [SkipOnTargetFramework(TargetFrameworkMonikers.Uap, "Not approved COM object for app")]
-        public void GetForest_NonNullNameAndNotRootedDomain_ThrowsActiveDirectoryObjectNotFoundException_NonUap(DirectoryContextType type, string name)
+        public void GetForest_NonNullNameAndNotRootedDomain_NonUap(DirectoryContextType type, string name)
         {
             var context = new DirectoryContext(type, name);
             if (!PlatformDetection.IsDomainJoinedMachine)
             {
                 Assert.Throws<ActiveDirectoryObjectNotFoundException>(() => Forest.GetForest(context));
```
Comment (karelz) [inline src/System.DirectoryServices/tests/System/DirectoryServices/ActiveDirectory/ForestTests.cs]: Did you forget to remove the 1st assert? I expect it will still fail (in nightly runs) ...

**Comment by weshaggard** [comment]
@tarekgh can you please port the test fixes to release/2.1 branch as well?

File: src/System.DirectoryServices/tests/System/DirectoryServices/ActiveDirectory/ForestTests.cs (hunk 2 above)
Comment (tarekgh) [reply src/System.DirectoryServices/tests/System/DirectoryServices/ActiveDirectory/ForestTests.cs]: Thanks for the catch. I have submitted the PR https://github.com/dotnet/corefx/pull/26555

**Comment by tarekgh** [comment]
@weshaggard I'll port the fix to release/2.1 branch. should I request a permission from the shiproom?

**Comment by weshaggard** [comment]
@tarekgh just tag me on it and I will merge it.

**Comment by tarekgh** [comment]
@weshaggard I have submitted https://github.com/dotnet/corefx/pull/26558 and tagged you there.
