### PR TITLE
Accept null comparers and update docs around these parameters

### LINKED ISSUE #2036: Exposed Immutable Collections APIs should allow `null` comparers
Several immutable collections APIs throw an `ArgumentNullException` if a null `IComparer<T>` or `IEqualityComparer<T>` is provided. This is not intuitive, and deviates from a very common pattern established by the .NET framework. All publicly-exposed API methods in this assembly should be updated to ensure the following:

1. If a null value is provided for `IComparer<T>`, `Comparer<T>.Default` should be used instead.
2. If a null value is provided for `IEqualityComparer<T>`, `EqualityComparer<T>.Default` should be used instead.

### PR DESCRIPTION
**Pull request by AArnott**
Follow .NET BCL patterns more closely with regard to accepting `IEqualityComparer<T>` and `IComparer<T>` parameters that have null arguments.

Fixes #2036

### CODE REVIEW

File: src/System.Collections.Immutable/tests/ImmutableListTestBase.cs [hunk 1]
```diff
@@ -419,5 +431,20 @@ private void TrueForAllTestHelper<T>(ImmutableList<T> list, Predicate<T> test)
             var actual = this.GetListQuery(list).TrueForAll(test);
             Assert.Equal(expected, actual);
         }
+
+        private class CustomComparer<T> : IComparer<T>
```
Comment (stephentoub) [inline src/System.Collections.Immutable/tests/ImmutableListTestBase.cs]: Could you use ```Comparer<T>.Create(comparison)``` instead of defining a custom comparer?

**Comment by stephentoub** [comment]
One question, otherwise LGTM.

File: src/System.Collections.Immutable/tests/ImmutableListTestBase.cs (hunk 1 above)
Comment (AArnott) [inline src/System.Collections.Immutable/tests/ImmutableListTestBase.cs]: Cool. I didn't know about that API. :)

**Comment by stephentoub** [comment]
LGTM
