### PR TITLE
Fix Issue#7082

### LINKED ISSUE #7082: WindowAndCursorProps.Title test fails on Win7
```
14:19:45      WindowAndCursorProps.Title [FAIL]
14:19:45         Assert+WrapperXunitException : File path: d:\j\workspace\outerloop_win---9c9e7d59\src\System.Console\tests\WindowAndCursorProps.cs. Line: 121
14:19:45         ---- Assert.Equal() Failure
14:19:45                                           (pos 511)
14:19:45         Expected: úúúaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaúúú
14:19:45         Actual:   úúúaaaaaaaaaaaaaaaaaaaa
14:19:45                                           (pos 511)
14:19:45         Stack Trace:
14:19:45               at Assert.WrapException(Exception e, String callerFilePath, Int32 callerLineNumber)
14:19:45               at Assert.Equal(String expected, String actual, String path, Int32 line)
14:19:45               at WindowAndCursorProps.Title()
14:19:45            ----- Inner Stack Trace -----
14:19:45               at Assert.Equal(String expected, String actual, String path, Int32 line)
```

### PR DESCRIPTION
**Pull request by pallavit**
Fixes #7082 

GetConsoleTitle(LPTSTR lpConsoleTitle, DWORD nSize) behaves differently on different OSes. nSize at times represents the size of the buffer in bytes and at times in chars. To work-around the issue I have always assumed that the size is in bytes which has the side-effect of allocating extra buffer in case it represents chars, however this is the easiest implementation.

### CODE REVIEW

**Comment by pallavit** [comment]
/cc: @stephentoub Could you please take a look.

File: src/Common/src/Interop/Windows/mincore/Interop.GetConsoleTitle.cs [hunk 1]
```diff
@@ -20,13 +20,22 @@ internal partial class mincore
...
+        }
+
         // 1. We first try to call the GetConsoleTitle with an InitialBufferSizeInChars of 256.
         // 2. Then based on the return value either increase the capacity or return failure.
         internal static int GetConsoleTitle(out string title, out int titleLength)
         {
             int lastError = 0;
-            StringBuilder sb = new StringBuilder(InitialBufferSizeInChars);
-            int len = GetConsoleTitle(sb, InitialBufferSizeInChars);
+            StringBuilder sb = new StringBuilder(AdjustNumberOfChars(InitialBufferSizeInChars + 1));
```
Comment (stephentoub) [inline src/Common/src/Interop/Windows/mincore/Interop.GetConsoleTitle.cs]: What's the +1 for?

File: src/Common/src/Interop/Windows/mincore/Interop.GetConsoleTitle.cs [hunk 2]
```diff
@@ -20,13 +20,22 @@ internal partial class mincore
         // throw.
         private const int MaxAllowedBufferSizeInChars = 24500;
 
+        // GetConsoleTitle sometimes interprets the second parameter (nSize) as number of bytes and sometimes as the number of chars.
+        // Instead of doing complicated and dangerous logic to determine if this may or may not occur,
+        // we simply assume the worst and reserve a bigger buffer. This way we may use a bit more memory,
+        // but we will always be safe.
+        private static int AdjustNumberOfChars(int numChars)
```
Comment (stephentoub) [inline src/Common/src/Interop/Windows/mincore/Interop.GetConsoleTitle.cs]: Should this be called CharCountToByteCount, or something like that?  It's not clear otherwise what kind of "adjusting" is being done.

File: src/Common/src/Interop/Windows/mincore/Interop.GetConsoleTitle.cs [hunk 3]
```diff
@@ -20,13 +20,22 @@ internal partial class mincore
         // throw.
         private const int MaxAllowedBufferSizeInChars = 24500;
 
+        // GetConsoleTitle sometimes interprets the second parameter (nSize) as number of bytes and sometimes as the number of chars.
```
Comment (stephentoub) [inline src/Common/src/Interop/Windows/mincore/Interop.GetConsoleTitle.cs]: Do we have a bug around SetConsoleTitle as well?  I'm wondering if it does a similar interpretation.

Comment (pallavit) [inline src/Common/src/Interop/Windows/mincore/Interop.GetConsoleTitle.cs]: I ran some tests here but SetConsoleTitle works as expected. I guess this is because it directly takes LPCTSTR and computes the length itself.

File: src/Common/src/Interop/Windows/mincore/Interop.GetConsoleTitle.cs (hunk 2 above)
Comment (pallavit) [inline src/Common/src/Interop/Windows/mincore/Interop.GetConsoleTitle.cs]: Hmm sure I will update it.

**Comment by stephentoub** [comment]
Test Innerloop OSX Release Build and Test please (https://github.com/dotnet/corefx/issues/7151)
Test Innerloop Windows_NT Debug Build and Test please (https://github.com/dotnet/corefx/issues/7150)

**Comment by pallavit** [comment]
Test Innerloop OSX Release Build and Test please (#7151)
 Test Innerloop Windows_NT Debug Build and Test please (#7150)

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please

**Comment by pallavit** [comment]
@dotnet-bot test Innerloop OSX Debug Build and Test please

**Comment by pallavit** [comment]
@stephentoub  Let me know if you have any comments.

File: src/Common/src/Interop/Windows/mincore/Interop.GetConsoleTitle.cs (hunk 1 above)
Comment (pallavit) [inline src/Common/src/Interop/Windows/mincore/Interop.GetConsoleTitle.cs]: I was accounting for '\0' but the interop layer should take care of this already. So, removed it.

**Comment by pallavit** [comment]
@dotnet-bot test Innerloop CentOS7.1 Release Build and Test

File: src/Common/src/Interop/Windows/mincore/Interop.GetConsoleTitle.cs [hunk 4]
```diff
@@ -20,13 +20,22 @@ internal partial class mincore
...
+        }
+
         // 1. We first try to call the GetConsoleTitle with an InitialBufferSizeInChars of 256.
         // 2. Then based on the return value either increase the capacity or return failure.
         internal static int GetConsoleTitle(out string title, out int titleLength)
         {
             int lastError = 0;
-            StringBuilder sb = new StringBuilder(InitialBufferSizeInChars);
-            int len = GetConsoleTitle(sb, InitialBufferSizeInChars);
+            StringBuilder sb = new StringBuilder(CharCountToByteCount(InitialBufferSizeInChars + 1));
```
Comment (stephentoub) [inline src/Common/src/Interop/Windows/mincore/Interop.GetConsoleTitle.cs]: It'd be nice to have a comment explaining the need for the +1.

**Comment by stephentoub** [comment]
LGTM

File: src/Common/src/Interop/Windows/mincore/Interop.GetConsoleTitle.cs (hunk 4 above)
Comment (pallavit) [inline src/Common/src/Interop/Windows/mincore/Interop.GetConsoleTitle.cs]: Sure. I will add a comment and merge once the checks complete :). I don't want to retrigger the validation for a comment update. (BTW, is there a way to prevent the tests from retriggering for these things?)

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please
Test Innerloop OSX Release Build and Test please
