### PR TITLE
Fixing race condition in non-generic collections tests

### LINKED ISSUE #1504: Some Collections.NonGeneric tests have race conditions and ocassionally failing
( http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/963/console )
```
  Xunit.Sdk.EqualException: Assert.Equal() Failure
            Î“Ã¥Ã´ (pos 0)
  Expected: en-US
  Actual:   cs-CZ
            Î“Ã¥Ã¦ (pos 0)
     at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences)
     at Xunit.Assert.Equal(String expected, String actual)
     at Comparer_DefaultInvariant.runTest() in d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Collections.NonGeneric\tests\Comparer\Comparer_DefaultInvariant.cs:line 52
  Fail! iCountErrors==1
     Comparer_DefaultInvariant.ExecuteComparer_DefaultInvariant [FAIL]
        Assert.True() Failure
```

The tests are setting:
```csharp
CultureInfo.DefaultThreadCurrentCulture = culture;
CultureInfo.DefaultThreadCurrentUICulture = culture;
```
Which may fail when run on different threads.

### PR DESCRIPTION
**Pull request by Maxwe11**
Fixes #1504

### CODE REVIEW

File: src/System.Collections.NonGeneric/tests/Comparer/Comparer_DefaultInvariant.cs [hunk 1]
```diff
@@ -7,6 +7,7 @@
 using System.Globalization;
 using Xunit;
 
+[Collection("DefaultThreadCurrentCulture")]
```
Comment (stephentoub) [inline src/System.Collections.NonGeneric/tests/Comparer/Comparer_DefaultInvariant.cs]: I think I'd rather see parallelism disabled for this whole test suite rather than using a named collection like this.  None of these tests were written to be run in parallel, and I worry this is just one of potentially many such concurrency issues.  I think it'd make sense to disable parallelism for the library until it can be entirely rewritten (which it should be at some point).

Comment (Maxwe11) [inline src/System.Collections.NonGeneric/tests/Comparer/Comparer_DefaultInvariant.cs]: > I think it'd make sense to disable parallelism for the library until it can be entirely rewritten (which it should be at some point).

If tests will be rewritten they should also will rely on `CultureInfo.DefaultThreadCurrentCulture` and also will require deterministic execution like `[Collection]` does.

>None of these tests were written to be run in parallel, and I worry this is just one of potentially many such concurrency issues.

I think we shouldn't worry about that until it appears, but if it appear it'd be helpful for rewriting.

**Comment by Maxwe11** [comment]
@stephentoub updated

File: src/System.Collections.NonGeneric/tests/XunitAssemblyAttributes.cs [hunk 2]
```diff
@@ -0,0 +1,6 @@
+﻿// Copyright (c) Microsoft. All rights reserved.
+// Licensed under the MIT license. See LICENSE file in the project root for full license information.
+
+using Xunit;
+
+[assembly: CollectionBehavior(CollectionBehavior.CollectionPerAssembly, DisableTestParallelization = true, MaxParallelThreads = 1)]
```
Comment (stephentoub) [inline src/System.Collections.NonGeneric/tests/XunitAssemblyAttributes.cs]: Could you add a comment here explaining why this is being used?

**Comment by stephentoub** [comment]
LGTM.  Thanks for the fix.

**Comment by krwq** [comment]
:+1:
