### PR TITLE
Preserve ordering in MemberDescriptor.FilterAttributesIfNeeded

### LINKED ISSUE #8606: System.ComponentModel.Tests.MemberDescriptorTests.CopiedMemberDescriptorEqualsItsSource test failure
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu14.04_debug_prtest/1257/testReport/junit/System.ComponentModel.Tests/MemberDescriptorTests/CopiedMemberDescriptorEqualsItsSource/

> Stacktrace
> 
> MESSAGE:
Assert.True() Failure
Expected: True
Actual: False
+++++++++++++++++++
STACK TRACE:
at System.ComponentModel.Tests.MemberDescriptorTests.CopiedMemberDescriptorEqualsItsSource()

### PR DESCRIPTION
**Pull request by chlowell**
Prior code used `Hashtable` to remove duplicates in the `_attributes` array, then reassigned that array with `Hashtable.Values`, sometimes changing the ordering of elements and causing `Equals` to erroneously return false. With this change, duplicates are removed without affecting the order of elements.

This fixes #8606.

@stephentoub @Tanya-Solyanik @twsouthwick

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM ;)

**Comment by stephentoub** [comment]
Test Innerloop Windows_NT Debug Build and Test please

File: src/System.ComponentModel.TypeConverter/src/System/ComponentModel/MemberDescriptor.cs [hunk 1]
```diff
@@ -421,18 +422,24 @@ private void FilterAttributesIfNeeded()
...
-                    hash[attr.GetTypeId()] = attr;
+                    if (set.Add(list[i].GetTypeId()))
+                    {
+                        ++i;
+                    }
+                    else
+                    {
+                        list.RemoveAt(i);
+                    }
                 }
```
Comment (twsouthwick) [inline src/System.ComponentModel.TypeConverter/src/System/ComponentModel/MemberDescriptor.cs]: @stephentoub Is there guidance in .NET Core about using LINQ? Using `list.Distinct().ToArray()` would be a lot more readable, but I've seen some debate about using LINQ due to some perf concerns.

Comment (stephentoub) [inline src/System.ComponentModel.TypeConverter/src/System/ComponentModel/MemberDescriptor.cs]: This code already doesn't appear to be particularly optimized. If the library is already referencing System.Linq, seems reasonable to use it, assuming performance here isn't critical. For now, though, I'd suggest leaving it as is, to get the behavioral fix in place.

**Comment by k0st1x** [comment]
this fix broke the scenario
https://github.com/dotnet/corefx/issues/26600
:(
