### PR TITLE
Fix some of the failing tests on full framework net46 helix runs.

### LINKED ISSUE #10836: Test failure: System.Collections.Specialized.Tests.NameValueCollectionCopyToTests/CopyTo_Invalid fail with "Xunit.Sdk.EqualException"
Opened on behalf of @Jiayili1

The test `System.Collections.Specialized.Tests.NameValueCollectionCopyToTests/CopyTo_Invalid` has failed.

    Assert.Equal() Failure\r
    Expected: dest\r
    Actual:   (null)

Stack Trace:

       at System.Collections.Specialized.Tests.NameValueCollectionCopyToTests.CopyTo_Invalid(Int32 count) in D:\A\_work\2\s\src\System.Collections.Specialized\tests\NameValueCollection\NameValueCollection.CopyToTests.cs:line 62

Failing configurations:

- Windows.10.Amd64
 - AnyCPU-Debug
 - AnyCPU-Release

link: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20160816.02/workItem/System.Collections.Specialized.Tests/analysis/xunit/System.Collections.Specialized.Tests.NameValueCollectionCopyToTests~2FCopyTo_Invalid

### PR DESCRIPTION
**Pull request by Priya91**
On desktop, the implementation assembly from GAC is loaded to memory, and
the tests specific to corefx implementation fail on Desktop run. Or in some cases, the tests were not compiled against the supported netstandard contracts for net46.

cc @danmosemsft @weshaggard @karajas 

fixes #10836 #10837 #10831 #10782 #10774 #10876

### CODE REVIEW

File: src/System.Collections.NonGeneric/tests/ArrayListTests.cs [hunk 1]
```diff
@@ -813,7 +813,7 @@ public static void CopyTo_Int_Invalid()
                 var arrCopy = new int[arrList2.Count];
 
                 Assert.Throws<ArgumentNullException>(() => arrList2.CopyTo(null)); // Array is null
-                Assert.Throws<ArgumentException>("array", () => arrList2.CopyTo(new object[10, 10])); // Array is multidimensional
+                Assert.Throws<ArgumentException>(Helpers.IsDesktopJob? null : "array", () => arrList2.CopyTo(new object[10, 10])); // Array is multidimensional
```
Comment (danmosemsft) [inline src/System.Collections.NonGeneric/tests/ArrayListTests.cs]: >? [](start = 69, length = 1)

nit, space before ? perhaps

**Comment by danmosemsft** [comment]
>> On desktop, the implementation assembly from GAC is loaded to memory
This is what we expect, right? It would be failing to test desktop otherwise. Just making sure I'm not misunderstanding this comment

File: src/System.Collections.Specialized/tests/HybridDictionary/HybridDictionary.KeysTests.cs [hunk 2]
```diff
@@ -56,12 +61,51 @@ public override void ICollection_NonGeneric_CopyTo_NonZeroLowerBound(int count)
...
         }
+
+        [Theory]
+        [MemberData(nameof(ValidCollectionSizes))]
+        public override void ICollection_NonGeneric_CopyTo_IndexEqualToArrayCount_ThrowsArgumentException(int count)
+        {
+            ICollection collection = NonGenericICollectionFactory(count);
+            object[] array = new object[count];
+            if (count > 0)
+                Assert.Throws(Helpers.IsDesktopJob && count < 10 ? typeof(IndexOutOfRangeException) : typeof(ArgumentException), () => collection.CopyTo(array, count));
```
Comment (danmosemsft) [inline src/System.Collections.Specialized/tests/HybridDictionary/HybridDictionary.KeysTests.cs]: >IsDesktopJob [](start = 38, length = 12)

Rather than magic number 10 is it better to use an expression on collection.Count?  
Although in this case maybe no expression is needed since the CopyTo will always fail.

Comment (danmosemsft) [inline src/System.Collections.Specialized/tests/HybridDictionary/HybridDictionary.KeysTests.cs]: Same magic number comment elsewhere

---
In reply to: [76623975](https://github.com/dotnet/corefx/pull/11219#discussion_r76623975) [](ancestors = 76623975)

File: src/System.Diagnostics.Debug/tests/DebugTests.cs [hunk 3]
```diff
@@ -22,14 +25,14 @@ public void Asserts()
             VerifyAssert(() => { Debug.Assert(false, "assert passed", "nothing is wrong {0} {1}", 'a', 'b'); }, "assert passed", "nothing is wrong a b");      
         }
 
-        [Fact]
+        [ConditionalFact(nameof(IsNotDesktopJob))]
```
Comment (danmosemsft) [inline src/System.Diagnostics.Debug/tests/DebugTests.cs]: >))] [](start = 47, length = 3)

Where you conditionalize on desktop, can you add a comment expalining what the behavior difference is, for the benefit of future devs? What changed in Debug.Fail?

File: src/System.Diagnostics.Debug/tests/DebugTests.cs [hunk 4]
```diff
@@ -3,12 +3,15 @@
...
 
 using Xunit;
+using System.Runtime.InteropServices;
 
 namespace System.Diagnostics.Tests
 {
     public class DebugTests
     {
-        [Fact]
+        public static bool IsNotDesktopJob = !RuntimeInformation.FrameworkDescription.Contains(".NET Framework");
```
Comment (danmosemsft) [inline src/System.Diagnostics.Debug/tests/DebugTests.cs]: "System.InvalidOperationException : An appropriate member "IsNotDesktopJob" could not be found. The conditional method needs to be a static method or property on this or any ancestor type, of any visibility, accepting zero arguments, and having a return type of Boolean."

Looks like it needs to be a property

**Comment by danmosemsft** [comment]
Thanks for doing this cleanup @Priya91

**Comment by danmosemsft** [comment]
@karajas could you please look at the *Proj changes? 
/cc @ericstj

File: src/System.Collections.NonGeneric/tests/Helpers.cs [hunk 5]
```diff
@@ -3,11 +3,14 @@
 // See the LICENSE file in the project root for more information.
 
 using System.Globalization;
+using System.Runtime.InteropServices;
 
 namespace System.Collections.Tests
 {
     internal static class Helpers
     {
+        public static bool IsDesktopJob = RuntimeInformation.FrameworkDescription.Contains(".NET Framework");
```
Comment (weshaggard) [inline src/System.Collections.NonGeneric/tests/Helpers.cs]: This isn't the best way to do this check. We need the following fixed https://github.com/dotnet/buildtools/issues/960, and instead should use the TFM.

**Comment by weshaggard** [comment]
I would like to fix https://github.com/dotnet/buildtools/issues/960 before we go down this path an expect all the test projects to detect this themselves.

On top of that the number of places you had to use it in these tests point out to me that we should consider fixing the .NET Core versions to match that of desktop. @stephentoub what is your thoughts?

File: src/System.Diagnostics.Process/tests/System.Diagnostics.Process.Tests.csproj [hunk 6]
```diff
@@ -10,7 +10,9 @@
     <AssemblyName>System.Diagnostics.Process.Tests</AssemblyName>
     <NuGetPackageImportStamp>b62eec4b</NuGetPackageImportStamp>
     <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
-    <NugetTargetMoniker>.NETStandard,Version=v1.4</NugetTargetMoniker>
+    <NugetTargetMoniker Condition="'$(TestTFM)' != 'net46'">.NETStandard,Version=v1.4</NugetTargetMoniker>
```
Comment (weshaggard) [inline src/System.Diagnostics.Process/tests/System.Diagnostics.Process.Tests.csproj]: I'm not sure I understand why this change is needed.

**Comment by stephentoub** [comment]
> On top of that the number of places you had to use it in these tests point out to me that we should consider fixing the .NET Core versions to match that of desktop. @stephentoub what is your thoughts?

Which differences in particular?  From a quick skim I see two main kinds:
- A different exception type is being thrown (not a subclass) in core
- An exception parameter name is included in an argument exception in core but not in desktop

For the first category, we should fix core to match the exception type from desktop; I don't see a lot of value in, for example, changing an argument exception to be an index out of range exception for an invalid collection index, not enough value to overcome the difference between platforms.

For the second category, I think it's good that we added a parameter name for core.  We should do the same for desktop, and in the meantime either special-case the test or remove the parameter verification from the test.

**Comment by weshaggard** [comment]
>For the first category, we should fix core to match the exception type from desktop
Agreed we should fix the implementations.

>For the second category, I think it's good that we added a parameter name for core. We should do the same for desktop, and in the meantime either special-case the test or remove the parameter verification from the test.
I think we should just remove the parameter name validation instead of complicating the test code as I don't think it adds much value

File: src/System.Diagnostics.Debug/tests/DebugTests.cs (hunk 3 above)
Comment (Priya91) [inline src/System.Diagnostics.Debug/tests/DebugTests.cs]: The implementation assembly on desktop and corefx is different, and the tests here are testing the corefx behavior. These tests are not valid on desktop.. Will add a comment.

Comment (weshaggard) [inline src/System.Diagnostics.Debug/tests/DebugTests.cs]: These APIs do exist on desktop and I would expect them to behave the same. I could imagine cases that are different when running on debug builds of the product but that should be a different pivot. 

In any case if we need to condition based on desktop we should use the TestTFM approach I called out elsewhere.

**Comment by Priya91** [comment]
Depends on dotnet/buildtools#992 to address PR comments.

File: src/System.Diagnostics.Debug/tests/DebugTests.cs [hunk 7]
```diff
@@ -9,6 +9,7 @@ namespace System.Diagnostics.Tests
     public class DebugTests
     {
         [Fact]
+        [SkipOnTargetFramework(TargetFrameworkMonikers.Net46)]
         public void Asserts()
         {
             VerifyLogged(() => { Debug.Assert(true); }, "");
```
Comment (weshaggard) [inline src/System.Diagnostics.Debug/tests/DebugTests.cs]: Do you know why Debug.Assert doesn't work the same? Is it because we are running on a release build of the framework? 

If this is a netfx issue you should probably mark this as TargetFrameworkMonikers.NetFramework

**Comment by weshaggard** [comment]
Other then the one comment LGTM.

@Priya91 Thanks for attacking this problem and making the necessary changes to get this moving forward.

File: src/System.Diagnostics.Debug/tests/DebugTests.cs (hunk 7 above)
Comment (Priya91) [inline src/System.Diagnostics.Debug/tests/DebugTests.cs]: These tests are not working on desktop, because we have added an internal class WindowsDebugLogger that's not there in desktop implementation.. the tests are using an internal field of this class type to test, and the product lib is allowing InternalsVisibleTo to enable testing..

Comment (weshaggard) [inline src/System.Diagnostics.Debug/tests/DebugTests.cs]: We should consider changing the project then to be netcoreapp1.0 specific and add another flavor that is net46 specific so we can run the same tests but the one library will setup the WindowsDebugLogger and the other doesn't. That allows us to still use the same test to verify both. 

Rant: This is why I don't like InternalsVisibleTo :(

**Comment by Priya91** [comment]
@Priya91 Thanks for attacking this problem and making the necessary changes to get this moving forward.

Sure :)

File: src/System.Diagnostics.Debug/tests/DebugTests.cs (hunk 7 above)
Comment (Priya91) [inline src/System.Diagnostics.Debug/tests/DebugTests.cs]: Will file a follow up issue on this.. Currently have other failures to unblock, the lib owner should be able to do this..

**Comment by Priya91** [comment]
@dotnet-bot test  Innerloop CentOS7.1 Release Build and Test

File: src/System.Diagnostics.Debug/tests/DebugTests.cs (hunk 7 above)
Comment (stephentoub) [inline src/System.Diagnostics.Debug/tests/DebugTests.cs]: > Rant: This is why I don't like InternalsVisibleTo :(

This is why I don't like that we removed members like Debug.Listeners; this hack wouldn't have been necessary with that.

**Comment by Priya91** [comment]
@dotnet-bot Innerloop Windows_NT Release Build and Test

**Comment by Priya91** [comment]
@dotnet-bot test Innerloop Ubuntu14.04 Debug Build and Test

**Comment by Priya91** [comment]
@dotnet-bot test Innerloop Windows_NT Release Build and Test

File: dir.traversal.targets [hunk 8]
```diff
@@ -154,15 +154,15 @@
       <!-- include the projects have TestTFM value match FilterToTestTFM -->
       <ProjectsToTest Include="@(Project)" Condition="'%(Project.Extension)'=='.csproj' And $([System.String]::new('%(Project.TestTFMs)').Contains(';$(FilterToTestTFM);'))" /> 
 
-      <!-- For net46 we include projects with TestTFM values net461 and net462 and net463-->
```
Comment (weshaggard) [inline dir.traversal.targets]: @joperezr  FYI this is where I mentioned the netfx test runs were fixed.

Comment (joperezr) [inline dir.traversal.targets]: @weshaggard I see, thanks!
