### PR TITLE
Bug fix: Add Assembly.LoadFrom() fallback attempt

### LINKED ISSUE #27433: NETCore System.ComponentModel.Composition (MEF1) fails
Hi. Could you help me to make a simple example with mef1? Thank you in advance.
My system is Archlinux x64. I'm using component from myget.org (dotnet add package System.ComponentModel.Composition --version 4.5.0-preview2-26223-06 --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json).
My code is here:

```
dotnet --version
2.1.4
```
```
pwd
/at/c#
```
Contract (in /at/c#/example_console_mef_contract):
```csharp
cat /at/c#/example_console_mef_contract/Class1.cs
using System;
namespace example_console_mef_contract
{
    public interface IHelloWorld
    {
        string HelloWorld();
    }
}
```
Library aka plugin (in /at/c#/example_console_mef_lib). Csproj file includes a reference to contract project.
```csharp
cat /at/c#/example_console_mef_lib/Class1.cs
using System;
using System.ComponentModel.Composition;
using System.ComponentModel.Composition.Hosting;
using System.Reflection;
using example_console_mef_contract;
namespace example_console_mef_lib
{
    [Export(typeof(example_console_mef_contract.IHelloWorld))]
    public class MefHelloWorld : IHelloWorld
    {
        public string HelloWorld()
        {
            return "Hello world";
        }
    }
}
```
```
cat /at/c#/example_console_mef_lib/example_console_mef_lib.csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Composition" Version="4.5.0-preview2-26223-06" />
  </ItemGroup>
  <ItemGroup>
  **<ProjectReference Include="/at/c#/example_console_mef_contract/example_console_mef_contract.csproj" />**
  </ItemGroup>
</Project>
```
Main application (in /at/c#/example_console_mef). Csproj file includes a reference to contract project.
```csharp
cat /at/c#/example_console_mef/Program.cs
using System;
using System.ComponentModel.Composition;
using System.ComponentModel.Composition.Hosting;
using System.Reflection;
using example_console_mef_contract;
namespace example_console_mef
{
    class Program
    {
        private CompositionContainer _container;
        [Import(typeof(example_console_mef_contract.IHelloWorld))]
        private example_console_mef_contract.IHelloWorld helloWorld;
        private Program()
        {
            var catalog = new AggregateCatalog();
            catalog.Catalogs.Add(new AssemblyCatalog(typeof(Program).Assembly));
            catalog.Catalogs.Add(new DirectoryCatalog(@"/at/c#/example_console_mef_lib/bin/Debug/netstandard2.0"));
            _container = new CompositionContainer(catalog);
            try
            {
                this._container.ComposeParts(this);
            }
            catch (CompositionException compositionException)
            {
                Console.WriteLine(compositionException.ToString());
            }
        }
        static void Main(string[] args)
        {
            Program p = new Program();
//            Console.WriteLine(p.helloWorld.HelloWorld());
//            Console.ReadKey();
        }
    }
}
```
```
cat /at/c#/example_console_mef/example_console_mef.csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Composition" Version="4.5.0-preview2-26223-06" />
  </ItemGroup>
  <ItemGroup>
  **<ProjectReference Include="/at/c#/example_console_mef_contract/example_console_mef_contract.csproj" />**
  </ItemGroup>
</Project>
```
Contract and library projects compiled without errors. 
Now I try run main application but it fails:
```
cd  /at/c#/example_console_mef
dotnet run
System.ComponentModel.Composition.ChangeRejectedException: The composition remains unchanged. The changes were rejected because of the following error(s): The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.

1) No exports were found that match the constraint:
        ContractName    example_console_mef_contract.IHelloWorld
        RequiredTypeIdentity    example_console_mef_contract.IHelloWorld

Resulting in: Cannot set import 'example_console_mef.Program.helloWorld (ContractName="example_console_mef_contract.IHelloWorld")' on part 'example_console_mef.Program'.
Element: example_console_mef.Program.helloWorld (ContractName="example_console_mef_contract.IHelloWorld") -->  example_console_mef.Program

   at System.ComponentModel.Composition.CompositionResult.ThrowOnErrors(AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ComposablePartExportProvider.Compose(CompositionBatch batch)
   at example_console_mef.Program..ctor() in /at/c#/example_console_mef/Program.cs:line 26
```

### PR DESCRIPTION
**Pull request by MarcoRossignoli**
Fixes #27433 

I did a test with https://github.com/superriva/MEF_examples.

I don't know if we need to write a "custom test" for this(create an assembly on the fly and try to load etc..).

I attach "debug result".

```csharp
 var catalog = new DirectoryCatalog(@"D:\JOB\Repos\MEF_examples\MEF1-bug\ExportComponents\Components", "*.dll");
```
Before
nofix
After
fix
(the exception on Parts is due to missing interface lib)
No more log on debug console.

cc: @weshaggard @safern

### CODE REVIEW

**Comment by safern** [comment]
We have some tests where we have a dummy assembly referenced from the test csproj so that it is bin placed in the same folder as the test assembly and we can load it. 

https://github.com/dotnet/corefx/blob/c4fea4df2bbfed6df6f469ed4f9a550d561d9780/src/System.Runtime.Loader/tests/RefEmitLoadContext/RefEmitLoadContextTest.cs#L40
https://github.com/dotnet/corefx/blob/664ca9508a03483a7fb2714b55b9cba885593d90/src/System.Runtime.Loader/tests/DefaultContext/System.Runtime.Loader.DefaultContext.Tests.csproj#L16

I think we should have a test for this bug fix checked in.

**Comment by MarcoRossignoli** [comment]
@safern can i use same assembly and via reflection check for assemblies.count = 1?

File: src/System.ComponentModel.Composition/tests/System/ComponentModel/Composition/Hosting/DirectoryCatalogTests.cs [hunk 1]
```diff
@@ -343,6 +343,19 @@ public void LoadedFiles_ContainsMultipleDllsAndSomeNonDll_ShouldOnlyContainDlls(
                     cat.LoadedFiles);
         }
 
+        [Fact]
+        public void LoadedFiles_NonStaticallyReferencedAssembly()
+        {
```
Comment (MarcoRossignoli) [inline src/System.ComponentModel.Composition/tests/System/ComponentModel/Composition/Hosting/DirectoryCatalogTests.cs]: @safern i added a test

File: src/System.ComponentModel.Composition/tests/System.ComponentModel.Composition.Test.Assembly/Configurations.props [hunk 2]
```diff
@@ -0,0 +1,9 @@
+﻿<?xml version="1.0" encoding="utf-8"?>
```
Comment (safern) [inline src/System.ComponentModel.Composition/tests/System.ComponentModel.Composition.Test.Assembly/Configurations.props]: Would you mind renaming to System.ComponentModel.Composition.Noop.Assembly?

Comment (MarcoRossignoli) [reply src/System.ComponentModel.Composition/tests/System.ComponentModel.Composition.Test.Assembly/Configurations.props]: you right

Comment (MarcoRossignoli) [reply src/System.ComponentModel.Composition/tests/System.ComponentModel.Composition.Test.Assembly/Configurations.props]: @safern done

**Comment by MarcoRossignoli** [comment]
@dotnet-bot test Alpine.3.6 x64 Debug Build please
@dotnet-bot test OSX x64 Debug Build please

File: src/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/DirectoryCatalog.cs [hunk 3]
```diff
@@ -664,12 +664,22 @@ public override string ToString()
...
+                try
+                {
+                    return (_reflectionContext != null)
+                        ? new AssemblyCatalog(assemblyFilePath, _reflectionContext, this)
+                        : new AssemblyCatalog(assemblyFilePath, this);
+                }
+                //fallback attempt issue https://github.com/dotnet/corefx/issues/27433
+                catch (FileNotFoundException)
+                {
+                    var loadedAssembly = Assembly.LoadFrom(assemblyFilePath);
```
Comment (weshaggard) [inline src/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/DirectoryCatalog.cs]: While this may address this specific scenario in DirectoryCatalog I think it is better to address it in more scenarios in AssemblyCatalog itself. I suggest adding the logic around https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/AssemblyCatalog.cs#L553.

Comment (MarcoRossignoli) [reply src/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/DirectoryCatalog.cs]: good point

Comment (MarcoRossignoli) [reply src/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/DirectoryCatalog.cs]: @weshaggard done

File: src/System.ComponentModel.Composition/tests/System/ComponentModel/Composition/Hosting/DirectoryCatalogTests.cs (hunk 1 above)
Comment (weshaggard) [reply src/System.ComponentModel.Composition/tests/System/ComponentModel/Composition/Hosting/DirectoryCatalogTests.cs]: Could you add a similar test for AssemblyCatalog now that you moved the code there?

File: src/System.ComponentModel.Composition/System.ComponentModel.Composition.sln [hunk 4]
```diff
@@ -1,6 +1,6 @@
 Microsoft Visual Studio Solution File, Format Version 12.00
-# Visual Studio 14
-VisualStudioVersion = 14.0.25420.1
```
Comment (weshaggard) [inline src/System.ComponentModel.Composition/System.ComponentModel.Composition.sln]: Could you please normalize the solution/projects by running https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/project-guidelines.md#updating-configurations?

File: src/System.ComponentModel.Composition/tests/System/ComponentModel/Composition/Hosting/AssemblyCatalogTests.cs [hunk 5]
```diff
@@ -1078,5 +1078,18 @@ public void ToString_ShouldReturnICompositionElementDisplayName()
                 Assert.Equal(catalog.DisplayName, catalog.ToString());
             }
         }
+
+        [Fact]        
+        public void NonStaticallyReferencedAssembly()
```
Comment (MarcoRossignoli) [inline src/System.ComponentModel.Composition/tests/System/ComponentModel/Composition/Hosting/AssemblyCatalogTests.cs]: @weshaggard i added test

File: src/System.ComponentModel.Composition/System.ComponentModel.Composition.sln (hunk 4 above)
Comment (MarcoRossignoli) [reply src/System.ComponentModel.Composition/System.ComponentModel.Composition.sln]: sln normalized

**Comment by MarcoRossignoli** [comment]
@dotnet-bot test this please

**Comment by MarcoRossignoli** [comment]
@dotnet-bot test this please

**Comment by weshaggard** [comment]
@dotnet-bot test this please

(There was a break in master that is now fixed that was causing the build failures)

**Comment by MarcoRossignoli** [comment]
@weshaggard @safern fixed tests, ci fail not related to this PR.

**Comment by weshaggard** [comment]
Thanks @MarcoRossignoli I agree. Let's try to get CI green though. 

test Linux x64 Release Build
test OSX x64 Debug Build

**Comment by MarcoRossignoli** [comment]
@dotnet-bot test test OSX x64 Debug Build please

**Comment by weshaggard** [comment]
The OSX test failure is https://github.com/dotnet/corefx/issues/20069 which hits randomly.

**Comment by weshaggard** [comment]
Thanks for the contribution @MarcoRossignoli
