### PR TITLE
Remove caching from ImmutableSortedSet.Builder.DebuggerProxy

### LINKED ISSUE #16007: ImmutableSortedSet.Builder.DebuggerProxy incorrectly caches contents
https://github.com/dotnet/corefx/blob/master/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableSortedSet_1.Builder.DebuggerProxy.cs#L42-L45

`ImmutableSortedSet<T>.Builder` is probably a mutable type, so it's incorrect to cache the contents for display to the debugger. The code was probably copied-and-pasted from the proxy for a collection that actually is immutable, where it would be legal to cache the contents.

### PR DESCRIPTION
**Pull request by jimparsley**
Fix #16007

### CODE REVIEW

File: src/System.Collections.Immutable/tests/ImmutableSortedSetBuilderDebuggerProxyTest.cs [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+{
+    public class ImmutableSortedSetBuilderDebuggerProxyTest : ImmutablesTestBase
+    {
+        [Fact]
+        public void DoesNotCacheContents()
+        {
+            var set = ImmutableSortedSet<int>.Empty.Add(1);
+            var builder = set.ToBuilder();
+            var debuggerProxy = new ImmutableSortedSetBuilderDebuggerProxy<int>(builder);
+            var contents = debuggerProxy.Contents; // view the contents to trigger caching
```
Comment (stephentoub) [inline src/System.Collections.Immutable/tests/ImmutableSortedSetBuilderDebuggerProxyTest.cs]: Nit: when the type isn't explicit on the right-hand side (i.e. a ctor or a cast), please use the type name instead of var

**Comment by stephentoub** [comment]
cc: @AArnott

File: src/System.Collections.Immutable/tests/ImmutableSortedSetBuilderDebuggerProxyTest.cs (hunk 1 above)
Comment (jimparsley) [inline src/System.Collections.Immutable/tests/ImmutableSortedSetBuilderDebuggerProxyTest.cs]: OK, will do.

File: src/System.Collections.Immutable/tests/System.Collections.Immutable.Tests.csproj [hunk 2]
```diff
@@ -124,5 +125,8 @@
   <ItemGroup>
     <EmbeddedResource Include="Resources\$(AssemblyName).rd.xml" />
   </ItemGroup>
+  <ItemGroup>
+    <Reference Include="System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=MSIL" />
```
Comment (joperezr) [inline src/System.Collections.Immutable/tests/System.Collections.Immutable.Tests.csproj]: You shouldn't need to add references at all for test projects since they add references automatically so please remove this itemgroup.

Comment (safern) [inline src/System.Collections.Immutable/tests/System.Collections.Immutable.Tests.csproj]: Test projects shouldn't include references as they are added automatically.

**Comment by karelz** [comment]
Thank you @jimparsley. Let me know if you need help picking up another up-for-grabs issue ;)
