### PR TITLE
Remove [Out] by-value string parameter usage from System.Management.

### LINKED ISSUE #34083: System.Management uses in-place string modification in interop
While working to block users from intentionally using interop to modify the internal buffer of a `string` to avoid corrupting interned strings and crashing during ALC unloading, I discovered that the `IWbemPath` interface in `System.Management`'s `GetPath_` method has a `[In][Out][MarshalAs(UnmanagedType.LPWStr)] string path` parameter that modifies the string value in-place. We should change this to use an `[In][Out][MarshalAs(UnmanagedType.LPWStr)] StringBuilder path` parameter so we aren't modifying a `string`s internal buffer from native code.

See dotnet/coreclr#21513
cc: @AaronRobinsonMSFT, @janvorli

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fixes #34083.

### CODE REVIEW

File: src/System.Management/src/System/Management/InteropClasses/WMIInterop.cs [hunk 1]
```diff
@@ -949,13 +949,13 @@ interface IWbemPathKeyList
         [PreserveSig] int GetCount_([Out] out uint puKeyCount);
         [PreserveSig] int SetKey_([In][MarshalAs(UnmanagedType.LPWStr)]  string   wszName, [In] uint uFlags, [In] uint uCimType, [In] IntPtr pKeyVal);
         [PreserveSig] int SetKey2_([In][MarshalAs(UnmanagedType.LPWStr)]  string   wszName, [In] uint uFlags, [In] uint uCimType, [In] ref object pKeyVal);
-        [PreserveSig] int GetKey_([In] uint uKeyIx, [In] uint uFlags, [In][Out] ref uint puNameBufSize, [In][Out][MarshalAs(UnmanagedType.LPWStr)]  StringBuilder   pszKeyName, [In][Out] ref uint puKeyValBufSize, [In][Out] IntPtr pKeyVal, [Out] out uint puApparentCimType);
-        [PreserveSig] int GetKey2_([In] uint uKeyIx, [In] uint uFlags, [In][Out] ref uint puNameBufSize, [In][Out][MarshalAs(UnmanagedType.LPWStr)]  StringBuilder   pszKeyName, [In][Out] ref object pKeyValue, [Out] out uint puApparentCimType);
+        [PreserveSig] int GetKey_([In] uint uKeyIx, [In] uint uFlags, [In][Out] ref uint puNameBufSize, [Out][MarshalAs(UnmanagedType.LPArray, ArraySubType = UnmanagedType.U2)]  char[]   pszKeyName, [In][Out] ref uint puKeyValBufSize, [In][Out] IntPtr pKeyVal, [Out] out uint puApparentCimType);
```
Comment (AaronRobinsonMSFT) [inline src/System.Management/src/System/Management/InteropClasses/WMIInterop.cs]: Since we have the length of the array as an argument is there any reason _not_ to provide the `SizeParamIndex` attribute for all these signatures?

Comment (jkoritzinsky) [reply src/System.Management/src/System/Management/InteropClasses/WMIInterop.cs]: Nope. I'll go add that.

File: src/System.Management/src/System/Management/ManagementPath.cs [hunk 2]
```diff
@@ -322,9 +322,9 @@ private static string GetWbemPath(IWbemPath wbemPath)
 
                     if (status >= 0 && 0 < bufLen)
                     {
-                        StringBuilder pathBuilder = new StringBuilder((int)bufLen - 1);
-                        status = wbemPath.GetText_(flags, ref bufLen, pathBuilder);
-                        pathStr = pathBuilder.ToString();
+                        char[] pathChars = new char[(int)bufLen - 1];
+                        status = wbemPath.GetText_(flags, ref bufLen, pathChars);
+                        pathStr = new string(pathChars);
```
Comment (stephentoub) [inline src/System.Management/src/System/Management/ManagementPath.cs]: This isn't quite right (same for the other ctor uses).  It'll need to instead be something like:
```C#
new string(pathChars, 0, Array.IndexOf(pathChars, '\0'));
```

File: src/System.Management/src/System/Management/ManagementPath.cs [hunk 3]
```diff
@@ -324,7 +324,7 @@ private static string GetWbemPath(IWbemPath wbemPath)
                     {
                         char[] pathChars = new char[(int)bufLen - 1];
                         status = wbemPath.GetText_(flags, ref bufLen, pathChars);
-                        pathStr = new string(pathChars);
+                        pathStr = new string(pathChars, 0, Array.IndexOf(pathChars, '\0'));;
```
Comment (stephentoub) [inline src/System.Management/src/System/Management/ManagementPath.cs]: That said, if bufLen ends up being valid (I'm not familiar with the semantics of these calls), that value might be usable instead of the IndexOf call.  Basically we just need to pass in the actual length of the string (not including the null terminator).

File: src/System.Management/src/System/Management/InteropClasses/WMIInterop.cs [hunk 4]
```diff
@@ -948,13 +949,13 @@ interface IWbemPathKeyList
         [PreserveSig] int GetCount_([Out] out uint puKeyCount);
         [PreserveSig] int SetKey_([In][MarshalAs(UnmanagedType.LPWStr)]  string   wszName, [In] uint uFlags, [In] uint uCimType, [In] IntPtr pKeyVal);
         [PreserveSig] int SetKey2_([In][MarshalAs(UnmanagedType.LPWStr)]  string   wszName, [In] uint uFlags, [In] uint uCimType, [In] ref object pKeyVal);
-        [PreserveSig] int GetKey_([In] uint uKeyIx, [In] uint uFlags, [In][Out] ref uint puNameBufSize, [In][Out][MarshalAs(UnmanagedType.LPWStr)]  string   pszKeyName, [In][Out] ref uint puKeyValBufSize, [In][Out] IntPtr pKeyVal, [Out] out uint puApparentCimType);
-        [PreserveSig] int GetKey2_([In] uint uKeyIx, [In] uint uFlags, [In][Out] ref uint puNameBufSize, [In][Out][MarshalAs(UnmanagedType.LPWStr)]  string   pszKeyName, [In][Out] ref object pKeyValue, [Out] out uint puApparentCimType);
+        [PreserveSig] int GetKey_([In] uint uKeyIx, [In] uint uFlags, [In][Out] ref uint puNameBufSize, [Out][MarshalAs(UnmanagedType.LPArray, ArraySubType = UnmanagedType.U2, SizeParamIndex = 1)]  char[]   pszKeyName, [In][Out] ref uint puKeyValBufSize, [In][Out] IntPtr pKeyVal, [Out] out uint puApparentCimType);
```
Comment (AaronRobinsonMSFT) [inline src/System.Management/src/System/Management/InteropClasses/WMIInterop.cs]: Based on the signature, `GetKey_` and `GetKey2_` should have length index of 2 no?

Comment (jkoritzinsky) [reply src/System.Management/src/System/Management/InteropClasses/WMIInterop.cs]: Yep. Copy-paste error. Fixing now.

**Comment by danmosemsft** [comment]
The tests for this library are essentially manual. We should do a sanity test.

**Comment by jkoritzinsky** [comment]
@stephentoub can you take another look at this PR when you have a chance?

File: src/System.Management/src/System/Management/InteropClasses/WMIInterop.cs [hunk 5]
```diff
@@ -948,13 +949,13 @@ interface IWbemPathKeyList
         [PreserveSig] int GetCount_([Out] out uint puKeyCount);
         [PreserveSig] int SetKey_([In][MarshalAs(UnmanagedType.LPWStr)]  string   wszName, [In] uint uFlags, [In] uint uCimType, [In] IntPtr pKeyVal);
         [PreserveSig] int SetKey2_([In][MarshalAs(UnmanagedType.LPWStr)]  string   wszName, [In] uint uFlags, [In] uint uCimType, [In] ref object pKeyVal);
-        [PreserveSig] int GetKey_([In] uint uKeyIx, [In] uint uFlags, [In][Out] ref uint puNameBufSize, [In][Out][MarshalAs(UnmanagedType.LPWStr)]  string   pszKeyName, [In][Out] ref uint puKeyValBufSize, [In][Out] IntPtr pKeyVal, [Out] out uint puApparentCimType);
-        [PreserveSig] int GetKey2_([In] uint uKeyIx, [In] uint uFlags, [In][Out] ref uint puNameBufSize, [In][Out][MarshalAs(UnmanagedType.LPWStr)]  string   pszKeyName, [In][Out] ref object pKeyValue, [Out] out uint puApparentCimType);
+        [PreserveSig] int GetKey_([In] uint uKeyIx, [In] uint uFlags, [In][Out] ref uint puNameBufSize, [Out][MarshalAs(UnmanagedType.LPArray, ArraySubType = UnmanagedType.U2, SizeParamIndex = 2)]  char[]   pszKeyName, [In][Out] ref uint puKeyValBufSize, [In][Out] IntPtr pKeyVal, [Out] out uint puApparentCimType);
```
Comment (stephentoub) [inline src/System.Management/src/System/Management/InteropClasses/WMIInterop.cs]: Is this MarshalAs necessary?  What impact does it have on behavior?

File: src/System.Management/src/System/Management/ManagementPath.cs [hunk 6]
```diff
@@ -321,8 +322,9 @@ private static string GetWbemPath(IWbemPath wbemPath)
 
                     if (status >= 0 && 0 < bufLen)
                     {
-                        pathStr = new string ('0', (int) bufLen-1);
-                        status = wbemPath.GetText_(flags, ref bufLen, pathStr);
+                        char[] pathChars = new char[(int)bufLen];
+                        status = wbemPath.GetText_(flags, ref bufLen, pathChars);
+                        pathStr = new string(pathChars, 0, Array.IndexOf(pathChars, '\0'));
```
Comment (stephentoub) [inline src/System.Management/src/System/Management/ManagementPath.cs]: This is functionally the same as what was being done previously with StringBuilder, in that StringBuilder marshaling will search for the '\0' and use that when copying back the data.  We could make this more efficient presumably by using `bufLen-1` instead if `status` indicates success, but I'm guessing we're not particularly concerned with performance in this code, and our testing isn't great around this stuff, so it's probably fine as-is.

File: src/System.Management/src/System/Management/InteropClasses/WMIInterop.cs (hunk 5 above)
Comment (jkoritzinsky) [reply src/System.Management/src/System/Management/InteropClasses/WMIInterop.cs]: The `MarshalAs` makes it explicit that we're using Unicode characters. Without it, it was marshalling the array as an ANSI array.

**Comment by jkoritzinsky** [comment]
I've done some sanity checks locally. I'm going to merge this in.
