### PR TITLE
Use generic test handling for remote server failures.

### LINKED ISSUE #25878: Test failure: System.Net.Http.Functional.Tests.HttpClientHandler_SslProtocols_Test
Opened on behalf of @karelz

Failed tests:
* `GetAsync_SupportedSSLVersion_Succeeds` - 75 failures per run (all executions on Windows/Linux/Mac)
* `GetAsync_UnsupportedSSLVersion_Throws` - 22 failures per run (all executions on Linux-only)

Affected (4) runs: [20171211.01](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171211.01/workItem/System.Net.Http.Functional.Tests), [20171210.03](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171210.03/workItem/System.Net.Http.Functional.Tests), [20171210.01](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171210.01/workItem/System.Net.Http.Functional.Tests), [20171209.03](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171209.03/workItem/System.Net.Http.Functional.Tests)

### GetAsync_SupportedSSLVersion_Succeeds

* [test source code](https://github.com/dotnet/corefx/blob/4bf90198c5e7710ea67b7c1b467e859ec8bb78e5/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.SslProtocols.cs#L133-L161)

Windows:
```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.WinHttpException : The operation timed out
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext() in E:\A\_work\1955\s\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 464
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.Functional.Tests.HttpClientHandler_SslProtocols_Test.<GetAsync_SupportedSSLVersion_Succeeds>d__6.MoveNext() in E:\A\_work\1955\s\corefx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.SslProtocols.cs:line 158
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult() in E:\A\_work\1955\s\corefx\src\Common\src\System\Threading\Tasks\RendezvousAwaitable.cs:line 62
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext() in E:\A\_work\1955\s\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs:line 856
```

Mac:
```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.CurlException : SSL connect error
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext() in /Users/buildagent/agent/_work/320/s/corefx/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 464
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.Functional.Tests.HttpClientHandler_SslProtocols_Test.<GetAsync_SupportedSSLVersion_Succeeds>d__6.MoveNext() in /Users/buildagent/agent/_work/320/s/corefx/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.SslProtocols.cs:line 158
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error) in /Users/buildagent/agent/_work/320/s/corefx/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.cs:line 663
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult) in /Users/buildagent/agent/_work/320/s/corefx/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.MultiAgent.cs:line 883
```

Linux:
```
System.Threading.Tasks.TaskCanceledException : A task was canceled.
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext() in /root/corefx-1211504/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 464
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.Functional.Tests.HttpClientHandler_SslProtocols_Test.<GetAsync_SupportedSSLVersion_Succeeds>d__6.MoveNext() in /root/corefx-1211504/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.SslProtocols.cs:line 158
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
```

### GetAsync_UnsupportedSSLVersion_Throws

* [test source code](https://github.com/dotnet/corefx/blob/4bf90198c5e7710ea67b7c1b467e859ec8bb78e5/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.SslProtocols.cs#L169-L194)

Linux (only):
```
Assert.Throws() Failure
Expected: typeof(System.Net.Http.HttpRequestException)
Actual:   typeof(System.Threading.Tasks.TaskCanceledException): A task was canceled.
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext() in /root/corefx-1210954/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 464
--- End of stack trace from previous location where exception was thrown ---
```

### LINKED ISSUE #25892: Use consistent test reporting api to record remote server failure in networking tests.
One such method was proposed in this PR: #25879 

Several opinions on the thread was voiced:

1. What's the motivation of doing this, does this add value or only adds more clutter - @davidsh  @wfurt 
2. Use xunit apis for the same - proposed by @wfurt

### PR DESCRIPTION
**Pull request by Priya91**
cc @karelz @wfurt @davidsh 

fixes #25878 
fixes #25892 

When any test with remote server dependency fails, it will output something like this:

```
System.Net.Http.Functional.Tests.HttpClientHandler_SslProtocols_Test.GetAsync_UnsupportedSSLVersion_Throws(name: \"SSLv2\", url: \"https://www.ssllabs.com:10200/\") [FAIL]
System.Net.Test.Common.RemoteServerException : Likely external issue with remote server : https://www.ssllabs.com:10200/
---- System.Net.Http.HttpRequestException : An error occurred while sending the request.
-------- System.Net.Http.WinHttpException : A connection with the server could not be established
Stack Trace:
   E:\corefx\src\Common\tests\System\Net\RemoteServerQuery.cs(65,0): at System.Net.Test.Common.RemoteServerQuery.<ThrowsAsync>d__1`1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
   E:\corefx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.SslProtocols.cs(220,0): at System.Net.Http.Functional.Tests.HttpClientHandler_SslProtocols_Test.<GetAsync_UnsupportedSSLVersion_Throws>d__9.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
   --- End of stack trace from previous location where exception was thrown ---
   --- End of stack trace from previous location where exception was thrown ---
   ----- Inner Stack Trace -----
   E:\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs(464,0): at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
   E:\corefx\src\Common\tests\System\Net\RemoteServerQuery.cs(56,0): at System.Net.Test.Common.RemoteServerQuery.<ThrowsAsync>d__1`1.MoveNext()
   ----- Inner Stack Trace -----
   E:\corefx\src\System.Runtime.Extensions\src\System\Environment.cs(176,0): at System.Environment.get_StackTrace()
   E:\corefx\src\Common\src\System\Runtime\ExceptionServices\ExceptionStackTrace.cs(23,0): at System.Runtime.ExceptionServices.ExceptionStackTrace.AddCurrentStack(Exception exception)
   E:\corefx\src\Common\src\System\Net\Http\WinHttpException.cs(56,0): at System.Net.Http.WinHttpException.CreateExceptionUsingError(Int32 error)
   E:\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpRequestCallback.cs(324,0): at System.Net.Http.WinHttpRequestCallback.OnRequestError(WinHttpRequestState state, WINHTTP_ASYNC_RESULT asyncResult)
   E:\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpRequestCallback.cs(104,0): at System.Net.Http.WinHttpRequestCallback.RequestCallback(IntPtr handle, WinHttpRequestState state, UInt32 internetStatus, IntPtr statusInformation, UInt32 statusInformationLength)
   E:\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpRequestCallback.cs(47,0): at System.Net.Http.WinHttpRequestCallback.WinHttpCallback(IntPtr handle, IntPtr context, UInt32 internetStatus, IntPtr statusInformation, UInt32 statusInformationLength)
   --- End of stack trace from AddCurrentStack ---
   E:\corefx\src\Common\src\System\Threading\Tasks\RendezvousAwaitable.cs(62,0): at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   E:\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs(856,0): at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
```

### CODE REVIEW

**Comment by Priya91** [comment]
@dotnet-bot test outerloop linux x64 debug build please
@dotnet-bot test outerloop windows x64 debug build please
@dotnet-bot test outerloop osx x64 debug build please

**Comment by Priya91** [comment]
@dotnet-bot test outerloop linux x64 debug build please
@dotnet-bot test outerloop windows x64 debug build please
@dotnet-bot test outerloop osx x64 debug build please

**Comment by Priya91** [comment]
The test failures are not related to this PR.

**Comment by wfurt** [comment]
It looks ok to me. With "Likely external issue with remote server", would it make sense to claim it only on specific underlying exceptions e.g. timeout and reset?

**Comment by Priya91** [comment]
>  would it make sense to claim it only on specific underlying exceptions e.g. timeout and reset?

Yes, that's what the lambda you pass in to the API is for, only when the lambda returns true, the remoteserverexception is thrown.

File: src/Common/tests/System/Net/RemoteServerQuery.cs [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+namespace System.Net.Test.Common
+{
+    internal class RemoteServerException : Exception
+    {
+        private const string Description = "Likely external issue with remote server";
+
+        public RemoteServerException()
+            : this(null, null) { }
+
+        public RemoteServerException(string server)
```
Comment (karelz) [inline src/Common/tests/System/Net/RemoteServerQuery.cs]: Can we remove this overload? - to force everyone to use the original exception as well?

File: src/Common/tests/System/Net/RemoteServerQuery.cs [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+            : this(server, null) { }
+
+        public RemoteServerException(string server, Exception inner)
+            : base(GetMessage(server), inner) { }
+
+        public static string GetMessage(string server)
```
Comment (karelz) [inline src/Common/tests/System/Net/RemoteServerQuery.cs]: Looks like helper method, do we need it public?

File: src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.SslProtocols.cs [hunk 3]
```diff
@@ -189,7 +205,7 @@ public void DisabledProtocols_SetSslProtocols_ThrowsException(SslProtocols disab
 
             using (HttpClient client = CreateHttpClient())
             {
-                await Assert.ThrowsAsync<HttpRequestException>(() => client.GetAsync(url));
+                await RemoteServerQuery.ThrowsAsync<HttpRequestException>(() => client.GetAsync(url), remoteServerExceptionWrapper, url);
```
Comment (karelz) [inline src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.SslProtocols.cs]: What if we just wrap the exception around the call?
```c#
await Assert.ThrowsAsync<HttpRequestException>(() => RemoteServerQuery.Run(() => client.GetAsync(url), remoteServerExceptionWrapper, url));
```

File: src/Common/tests/System/Net/RemoteServerQuery.cs [hunk 4]
```diff
@@ -0,0 +1,75 @@
...
+                    throw new RemoteServerException(serverName, actualException);
+                }
+
+                throw;
+            }
+        }
+
+        internal static async Task ThrowsAsync<T>(Func<Task> testCode, Func<Exception, bool> remoteExceptionWrapper, string serverName)
+            where T : Exception
+        {
```
Comment (karelz) [inline src/Common/tests/System/Net/RemoteServerQuery.cs]: We're now playing the role of XUnit a bit by comparing the exception type and not its subtypes (it may be xunit default behavior). Do we really need it? What if we stick to just wrapping the exception? (see next comment)

File: src/Common/tests/System/Net/RemoteServerQuery.cs (hunk 2 above)
Comment (Priya91) [reply src/Common/tests/System/Net/RemoteServerQuery.cs]: This is not exposed in any api or anything, the whole class in internal. But yeah it can be private.

File: src/Common/tests/System/Net/RemoteServerQuery.cs (hunk 1 above)
Comment (Priya91) [reply src/Common/tests/System/Net/RemoteServerQuery.cs]: sure

**Comment by Priya91** [comment]
the desktop run failed with 

```
15:27:30 D:\j\workspace\windows-TGrou---2a8f9c29\Tools\tests.targets(484,5): warning MSB3073: The command "D:\j\workspace\windows-TGrou---2a8f9c29\bin/tests/System.IO.Compression.Tests/netfx-Windows_NT-Release-x86//RunTests.cmd D:\j\workspace\windows-TGrou---2a8f9c29\bin/testhost/netfx-Windows_NT-Release-x86/" exited with code 1. [D:\j\workspace\windows-TGrou---2a8f9c29\src\System.IO.Compression\tests\System.IO.Compression.Tests.csproj]
15:27:30 D:\j\workspace\windows-TGrou---2a8f9c29\Tools\tests.targets(492,5): error : One or more tests failed while running tests from 'System.IO.Compression.Tests' please check D:\j\workspace\windows-TGrou---2a8f9c29\bin/tests/System.IO.Compression.Tests/netfx-Windows_NT-Release-x86/testResults.xml for details! [D:\j\workspace\windows-TGrou---2a8f9c29\src\System.IO.Compression\tests\System.IO.Compression.Tests.csproj]
```
