### PR TITLE
Reenable EnumeratePastEndThenModify collection test

### LINKED ISSUE #1170: IEnumerator.Current does not throw after hitting the end of the collection.
This issue is in the `List<T>.Enumerator` class. When the collection is enumerated to then end and then modified, accessing `IEnumerator.Current` returns `default(T)` rather than throwing. According to the [documentation](https://msdn.microsoft.com/en-us/library/vstudio/system.collections.ienumerator.current%28v=vs.100%29.aspx) it should throw.

Simple Test case:

``` CSharp
var list = new List<int>{0,1};
var enumerator = ((IEnumerable)list).GetEnumerator();
while (enumerator.MoveNext()){}
list.Add(2);
Assert.Throws<InvalidOperationException>(() => enumerator.Current);
```

This test fails currently with `enumerator.Current` returning 0.

### PR DESCRIPTION
**Pull request by ViktorHofer**
Fixes #1170 (is already closed but the code was never cleaned up)

According to the changes in MSDN accessing the `Enumerator.Current` after the collection is modified does not result in an exception. Therefore changing the test.

### CODE REVIEW

**Comment by danmosemsft** [comment]
I can't see the code right now but now msdn says ". If the last call to MoveNext returned false, calling Current throws an exception."

**Comment by ViktorHofer** [comment]
Not sure where you are looking. @mairaw fixed the Remarks passage here https://msdn.microsoft.com/en-US/library/khfze649(VS.110).aspx. https://github.com/dotnet/corefx/issues/1170#issuecomment-283541437

**Comment by ViktorHofer** [comment]
@dotnet-bot test Windows x86 Release Build

wow the x86 release leg is already running for more than 7 hours. That's a new record I guess.

**Comment by danmosemsft** [comment]
@ViktorHofer I was looking here https://msdn.microsoft.com/en-us/library/system.collections.ienumerator(v=vs.110).aspx

**Comment by ViktorHofer** [comment]
Yes that's absolutely a docs issue. I will send a PR out for it in the docs repo.

**Comment by ViktorHofer** [comment]
> Yes that's absolutely a docs issue. I will send a PR out for it in the docs repo.

I have never said that and state the opposite ;) I've just tested it and verified in the docs.

`If MoveNext passes the end of the collection, the enumerator is positioned after the last element in the collection and MoveNext returns false. When the enumerator is at this position, subsequent calls to MoveNext also return false. If the last call to MoveNext returned false, calling Current throws an exception.`

This is absolutely correct and is proven by this test which passes on master:
```
var list = new List<int> { 0, 1 };
var enumerator = ((IEnumerable)list).GetEnumerator();
while (enumerator.MoveNext())
{ }
Assert.Throws<InvalidOperationException>(() => enumerator.Current);
```

But I'm talking about something different. Modifying the collection after the cursor has reached the end and then accessing the Current property does not result in an exception but in an "undefined" cursor:

```
var list = new List<int> { 0, 1 };
var enumerator = ((IEnumerable)list).GetEnumerator();
while (enumerator.MoveNext())
{ }
list.Add(2);
Assert.Equals(0, enumerator.Current);
```

File: src/Common/tests/System/Collections/IEnumerableTest.cs [hunk 1]
```diff
@@ -354,7 +353,7 @@ public void EnumeratePastEndThenModify()
             VerifyModifiedEnumerator(
                 enumerator,
                 DefaultValue,
-                true,
+                false,
```
Comment (danmosemsft) [inline src/Common/tests/System/Collections/IEnumerableTest.cs]: nit, for bools we prefer to name them eg 
```C#
expectCurrentThrow: false,
atEnd: false
```

Comment (danmosemsft) [inline src/Common/tests/System/Collections/IEnumerableTest.cs]: since typically you have to go find the callee otherwise

Comment (danmosemsft) [inline src/Common/tests/System/Collections/IEnumerableTest.cs]: This this isn't new though, so I'll merge.
