### PR TITLE
Fixing WindowsIdentity.IsAuthenticated for UWP and removing test workarounds.

### LINKED ISSUE #21282: WindowsIdentity.IsAuthenticated is false when running in an AppContainer
Tracking special-casing UWP in NegotiateStream_StreamToStream_Authentication_Success and NegotiateStream_StreamToStream_Authentication_TargetName_Success.
Since UAPAOT tests are not running in an AppContainer testing it will not exhibit the same problems. Fixing this is tracked by #18760.

I've narrowed the behavior difference to WindowsIdentity.IsAuthenticated when running in UAP mode, within an AppContainer.

### PR DESCRIPTION
**Pull request by CIPop**
Apps running in a container need to call [CheckTokenMembershipEx ](https://msdn.microsoft.com/en-us/library/windows/desktop/hh448479(v=vs.85).aspx) instead of CheckTokenMembership passing the `CTMF_INCLUDE_APPCONTAINER` flag for authentication validation to work.

A potential Windows SDK issue is misplacing the new API. I'm tracking the temporary workaround with #22128. (/cc @danmosemsft @AlexGhiondea )

Fixes #21282.

### CODE REVIEW

**Comment by CIPop** [comment]
@dotnet-bot Test Outerloop Windows x86 Release Build
@dotnet-bot Test Outerloop UWP CoreCLR x64 Debug Build
@dotnet-bot test Outerloop UWP NETNative x86 Release Build

**Comment by brentschmaltz** [comment]
:shipit

File: src/Common/src/Interop/Windows/kernel32/Interop.CheckTokenMembershipEx.cs [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+
+using Microsoft.Win32.SafeHandles;
+using System;
+using System.Runtime.InteropServices;
+
+internal static partial class Interop
+{
+    internal static partial class Kernel32
+    {
+		internal const uint CTMF_INCLUDE_APPCONTAINER = 0x00000001;
```
Comment (jkotas) [inline src/Common/src/Interop/Windows/kernel32/Interop.CheckTokenMembershipEx.cs]: Nit: indentation

File: src/System.Security.Principal.Windows/src/System.Security.Principal.Windows.csproj [hunk 2]
```diff
@@ -8,6 +8,15 @@
     <IsPartialFacadeAssembly Condition="'$(TargetGroup)' == 'netfx'">true</IsPartialFacadeAssembly>
     <ResourcesSourceOutputDirectory Condition="'$(TargetGroup)' == 'netfx'">None</ResourcesSourceOutputDirectory>
     <GeneratePlatformNotSupportedAssemblyMessage Condition="'$(TargetsWindows)' != 'true'">SR.PlatformNotSupported_Principal</GeneratePlatformNotSupportedAssemblyMessage>
+    <!-- 
+      TODO: #22128
+      Getting error BCL0015: kernel32.dll!CheckTokenMembershipEx is not supported on one\more targeted platforms.Consider using advapi32.dll!CheckTokenMembershipEx instead which doesn't exist.
+      Using advapi32.dll!CheckTokenMembershipEx will give out a runtime error: System.EntryPointNotFoundException : Unable to find an entry point named 'CheckTokenMembershipEx' in DLL 'advapi32.dll'.
+    -->
+    <UWPCompatible>false</UWPCompatible>
```
Comment (danmosemsft) [inline src/System.Security.Principal.Windows/src/System.Security.Principal.Windows.csproj]: Instead of doing this can you please just add the specific APi to a baseline file, so the build proceeds?

Eg like src/System.IO.FileSystem.Watcher/src/PinvokeAnalyzerExceptionList.analyzerdata.uap

Comment (danmosemsft) [inline src/System.Security.Principal.Windows/src/System.Security.Principal.Windows.csproj]: Setting UWPCompatible is a blunt instrument, it will mean other checks are disabled.

Comment (danmosemsft) [inline src/System.Security.Principal.Windows/src/System.Security.Principal.Windows.csproj]: This will also make it trivial for me to remove the exclusion when it's fxied witout changing your code.

Comment (CIPop) [inline src/System.Security.Principal.Windows/src/System.Security.Principal.Windows.csproj]: Sure. I copied this from your PR on System.Net.HttpListener which switched from the baseline to this method so I thought it was the preferred one.

**Comment by CIPop** [comment]
@dotnet-bot Test Outerloop Windows x86 Release Build
@dotnet-bot Test Outerloop UWP CoreCLR x64 Debug Build
@dotnet-bot test Outerloop UWP NETNative x86 Release Build

**Comment by CIPop** [comment]
Tizen has an unrelated CI problem: /cc @mmitche @MattGal 

```
Build timed out (after 120 minutes). Marking the build as aborted.
12:40:32 
Build was aborted
12:40:32 [Current build status] check if current [ABORTED] is worse or equals then [SUCCESS] and better or equals then [SUCCESS]
```
