### PR TITLE
Fix 31687 on netfx: escape Correlation-Context keys and values

### LINKED ISSUE #31687: System.Net.Http.DiagnosticsHandler.SendAsync throws if Activity.Current.Baggage contains values that can't be parsed by NameValueHeaderValue
See this line https://github.com/dotnet/corefx/blob/1a9aa57627a7d173adc1c7ccff6a9471aecc7235/src/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs#L92

Running a basic github oauth authentication flow on netcoreapp2.1 causes the following exception
```
System.FormatException: The format of value '/signin/github' is invalid.
   at System.Net.Http.Headers.NameValueHeaderValue.CheckValueFormat(String value)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.AspNetCore.Authentication.OAuth.OAuthHandler`1.ExchangeCodeAsync(String code, String redirectUri)
   at Microsoft.AspNetCore.Authentication.OAuth.OAuthHandler`1.HandleRemoteAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
```
This happens when the baggage item "RequestPath" with value "/signin/github" is processed.

This issue does not happen on net461.

### PR DESCRIPTION
**Pull request by lmolkova**
Fixes #31687

See #35906

### CODE REVIEW

File: src/System.Diagnostics.DiagnosticSource/tests/HttpHandlerDiagnosticListenerTests.cs [hunk 1]
```diff
@@ -421,6 +421,37 @@ public async Task TestActivityIsCreated()
...
+                using (var client = new HttpClient())
+                {
+                    (await client.GetAsync(Configuration.Http.RemoteEchoServer)).Dispose();
+                }
+
+                Assert.Equal(1, eventRecords.Records.Count(rec => rec.Key.EndsWith("Start")));
+                Assert.Equal(1, eventRecords.Records.Count(rec => rec.Key.EndsWith("Stop")));
+
+                WebRequest thisRequest = ReadPublicProperty<WebRequest>(eventRecords.Records.First().Value, "Request");
+                var correlationContext = thisRequest.Headers["Correlation-Context"].Split(',');
```
Comment (stephentoub) [inline src/System.Diagnostics.DiagnosticSource/tests/HttpHandlerDiagnosticListenerTests.cs]: Nit: var => whatever type this is (string[] I assume)

File: src/System.Diagnostics.DiagnosticSource/tests/HttpHandlerDiagnosticListenerTests.cs [hunk 2]
```diff
@@ -421,6 +421,37 @@ public async Task TestActivityIsCreated()
...
+
+                Assert.Equal(3, correlationContext.Count());
```
Comment (stephentoub) [inline src/System.Diagnostics.DiagnosticSource/tests/HttpHandlerDiagnosticListenerTests.cs]: Assuming correlationContext is a  string[], this should be .Length rather than .Count()

Comment (stephentoub) [reply src/System.Diagnostics.DiagnosticSource/tests/HttpHandlerDiagnosticListenerTests.cs]: @terrajobst, here's another example about why var makes code reviews harder... it's not easy for me to determine what the type of correlationContext is, so I don't know whether Count() is the most appropriate thing to use here. cc: @ahsonkhan.  This is just a trivial example... there are lots in more impactful places that show up all the time when var is used and the type isn't obvious.

Comment (ahsonkhan) [reply src/System.Diagnostics.DiagnosticSource/tests/HttpHandlerDiagnosticListenerTests.cs]: Agreed :)
