### PR TITLE
Move CultureInfoConverter to the new test base and fix NRE

### LINKED ISSUE #38979: CultureInfoConverter.GetCultureName(null) throws NRE
Should return null

```cs
public static IEnumerable<object[]> GetCultureName_TestData()
{
    yield return new object[] { new CultureInfo("fr-FR"), new CultureInfo("fr-FR").Name };
    yield return new object[] { new CultureInfo("es-MX"), new CultureInfo("es-MX").Name };
    yield return new object[] { null, null };
}

[Theory]
[MemberData(nameof(GetCultureName_TestData))]
public void GetCultureName_Invoke_ReturnsExpected(CultureInfo culture, string expected)
{
    var converter = new SubCultureInfoConverter();
    Assert.Equal(expected, converter.GetCultureName(culture));
}

private class SubCultureInfoConverter : CultureInfoConverter
{
    public new string GetCultureName(CultureInfo culture)
    {
        return base.GetCultureName(culture);
    }
}
```

### LINKED ISSUE #39121: new CultureInfoConverter.ConvertTo(1, typeof(string)) throws InvalidCastException
Should fallthrough and convert to string

### PR DESCRIPTION
**Pull request by hughbe**
Fixes #38979
Fixes #39121

### CODE REVIEW

File: src/System.ComponentModel.TypeConverter/src/System/ComponentModel/CultureInfoConverter.cs [hunk 1]
```diff
@@ -28,7 +28,7 @@ public class CultureInfoConverter : TypeConverter
         /// <summary>
         /// Retrieves the Name for a input CultureInfo.
         /// </summary>
-        protected virtual string GetCultureName(CultureInfo culture) => culture.Name;
+        protected virtual string GetCultureName(CultureInfo culture) => culture?.Name;
```
Comment (hughbe) [inline src/System.ComponentModel.TypeConverter/src/System/ComponentModel/CultureInfoConverter.cs]: Opted to return null instead of throwing ANE

Comment (hughbe) [reply src/System.ComponentModel.TypeConverter/src/System/ComponentModel/CultureInfoConverter.cs]: @maryamariyan this is the fix for the NRE bug. I think it is worth fixing. We don’t consider this breaking (the guidelines say exception -> no exception is not breaking)

**Comment by hughbe** [comment]
azp run corefx-ci

File: src/System.ComponentModel.TypeConverter/src/System/ComponentModel/CultureInfoConverter.cs [hunk 2]
```diff
@@ -151,23 +151,20 @@ public override object ConvertTo(ITypeDescriptorContext context, CultureInfo cul
...
-                else
+                if (value is CultureInfo c)
                 {
-                    retVal = GetCultureName(((CultureInfo)value));
+                    return GetCultureName(c);
                 }
-
-                return retVal;
             }
             if (destinationType == typeof(InstanceDescriptor) && value is CultureInfo)
```
Comment (tarekgh) [inline src/System.ComponentModel.TypeConverter/src/System/ComponentModel/CultureInfoConverter.cs]: >value is CultureInfo [](start = 65, length = 20)

nit: may be you can make this as

value is CultureInfo c

and then remove the line 

CultureInfo c = (CultureInfo)value;

File: src/System.ComponentModel.TypeConverter/tests/CultureInfoConverterTests.cs [hunk 3]
```diff
@@ -1,206 +1,180 @@
 // Licensed to the .NET Foundation under one or more agreements.
 // See the LICENSE file in the project root for more information. 
 
-//
```
Comment (tarekgh) [inline src/System.ComponentModel.TypeConverter/tests/CultureInfoConverterTests.cs]: I am not sure if we need to remove this author comment because originally the test is picked from external source.

File: src/System.ComponentModel.TypeConverter/src/System/ComponentModel/CultureInfoConverter.cs (hunk 2 above)
Comment (hughbe) [reply src/System.ComponentModel.TypeConverter/src/System/ComponentModel/CultureInfoConverter.cs]: Sadly we can't do this, as we use it in the check for `destinationType == typeof(string)` - therefore we'd have to nest both the `destinationType` check statements to avoid build errors. However, this would be breaking, as it changes the behavior for `ConvertTo(null, typeof(string))`

File: src/System.ComponentModel.TypeConverter/tests/CultureInfoConverterTests.cs (hunk 3 above)
Comment (tarekgh) [reply src/System.ComponentModel.TypeConverter/tests/CultureInfoConverterTests.cs]: @safern may remember the details about that.

---
In reply to: [299625654](https://github.com/dotnet/corefx/pull/38980#discussion_r299625654) [](ancestors = 299625654)

Comment (hughbe) [reply src/System.ComponentModel.TypeConverter/tests/CultureInfoConverterTests.cs]: Having cleaned it up it isn't the same anymore - everything has basically been rewritten. But probably better to keep it tho to keep the lawyers happy!

File: src/System.ComponentModel.TypeConverter/src/System/ComponentModel/CultureInfoConverter.cs (hunk 2 above)
Comment (tarekgh) [reply src/System.ComponentModel.TypeConverter/src/System/ComponentModel/CultureInfoConverter.cs]: Is this true even using different name? something like 

value is CultureInfo culture?

---
In reply to: [299625897](https://github.com/dotnet/corefx/pull/38980#discussion_r299625897) [](ancestors = 299625897)

**Comment by tarekgh** [comment]
@hughbe looks the tests are failing 

https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38980~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190702.35/workItem/System.ComponentModel.TypeConverter.Tests

**Comment by maryamariyan** [comment]
More detail on failures:

**System.ComponentModel.Tests.CultureInfoConverterTests** (Windows failures)

ConvertFrom_String_InvalidCulture(cultureName: \" \")
```
Unhandled Exception of Type Xunit.Sdk.EqualException
Message :
Assert.Equal() Failure
Expected: (null)
Actual:   value

Stack Trace :
   at System.AssertExtensions.Throws[T](String paramName, Func`1 testCode) in /_/src/Common/tests/CoreFx.Private.TestUtilities/System/AssertExtensions.cs:line 83
   at System.ComponentModel.Tests.CultureInfoConverterTests.ConvertFrom_String_InvalidCulture(String cultureName) in /_/src/System.ComponentModel.TypeConverter/tests/CultureInfoConverterTests.cs:line 73
```

ConvertFrom_String_InvalidCulture(cultureName: \"(default)\")
```
Unhandled Exception of Type Xunit.Sdk.EqualException
Message :
Assert.Equal() Failure
Expected: (null)
Actual:   value

Stack Trace :
   at System.AssertExtensions.Throws[T](String paramName, Func`1 testCode) in /_/src/Common/tests/CoreFx.Private.TestUtilities/System/AssertExtensions.cs:line 83
   at System.ComponentModel.Tests.CultureInfoConverterTests.ConvertFrom_String_InvalidCulture(String cultureName) in /_/src/System.ComponentModel.TypeConverter/tests/CultureInfoConverterTests.cs:line 73
```

ConvertFrom_String_InvalidCulture(cultureName: \"Dutch (Bel\")
```
Unhandled Exception of Type Xunit.Sdk.EqualException
Message :
Assert.Equal() Failure
Expected: (null)
Actual:   value

Stack Trace :
   at System.AssertExtensions.Throws[T](String paramName, Func`1 testCode) in /_/src/Common/tests/CoreFx.Private.TestUtilities/System/AssertExtensions.cs:line 83
   at System.ComponentModel.Tests.CultureInfoConverterTests.ConvertFrom_String_InvalidCulture(String cultureName) in /_/src/System.ComponentModel.TypeConverter/tests/CultureInfoConverterTests.cs:line 73
```

ConvertFrom_String_InvalidCulture(cultureName: \"\\r\\n\")
```
Unhandled Exception of Type Xunit.Sdk.EqualException
Message :
Assert.Equal() Failure
Expected: (null)
Actual:   value

Stack Trace :
   at System.AssertExtensions.Throws[T](String paramName, Func`1 testCode) in /_/src/Common/tests/CoreFx.Private.TestUtilities/System/AssertExtensions.cs:line 83
   at System.ComponentModel.Tests.CultureInfoConverterTests.ConvertFrom_String_InvalidCulture(String cultureName) in /_/src/System.ComponentModel.TypeConverter/tests/CultureInfoConverterTests.cs:line 73
```

**System.ComponentModel.Tests.DateTimeOffsetConverterTests**

ConvertTo_DestinationType_Success
```
Unhandled Exception of Type Xunit.Sdk.AllException
Message :
Assert.All() Failure: 1 out of 13 items in the collection did not pass.
[3]: Item: System.ComponentModel.Tests.TypeConverterTestBase+ConvertTest
     Xunit.Sdk.EqualException: Assert.Equal() Failure
     Expected: 12/5/1998 10:30 PM +00:00
     Actual:   05/12/1998 22:30 +00:00
        at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\EqualityAsserts.cs:line 41
        at Xunit.Assert.Equal[T](T expected, T actual) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\EqualityAsserts.cs:line 25
        at System.ComponentModel.Tests.TypeConverterTestBase.AssertEqualInstanceDescriptor(Object expected, Object actual) in /_/src/System.ComponentModel.TypeConverter/tests/TypeConverterTestBase.cs:line 173
        at System.ComponentModel.Tests.TypeConverterTestBase.<ConvertTo_DestinationType_Success>b__13_0(ConvertTest convertTest) in /_/src/System.ComponentModel.TypeConverter/tests/TypeConverterTestBase.cs:line 42
        at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\CollectionAsserts.cs:line 36

Stack Trace :
   at System.ComponentModel.Tests.TypeConverterTestBase.ConvertTo_DestinationType_Success() in /_/src/System.ComponentModel.TypeConverter/tests/TypeConverterTestBase.cs:line 31
```

**Comment by hughbe** [comment]
`System.ComponentModel.Tests.DateTimeOffsetConverterTests` has been fixed in #39123 but I pushed a fix to the others. Forgot that running `BuildAndTest` doesn't cause the source to rebuild
