### PR TITLE
Fix issue #20609 - RemoveAll on ImmutableList<T>.Builder removes wrong elements.

### LINKED ISSUE #20609: ImmutableList<T>.Builder.RemoveAll removes elements for which the Predicate is false
Repro: `\\fsu\shares\MsEng\MSBuild\micodoba\ImmutableListBuilderRepro.zip`

0. open a VS 2017 terminal and navigate to repro dir
1. terminal: `start .\msbuild\src\MSBuild.sln`
2. VS: set breakpoint in Microsoft.Build.Evaluation.LazyItemEvaluator.RemoveOperation.SaveItems at line 34 (with contents `listBuilder.RemoveAll(itemData => items.Contains(itemData.Item));`)
3. terminal: `set MSBUILDDEBUGONSTART=2`
4. terminal: `.\msbuild\bin\Bootstrap\MSBuild\15.0\Bin\MSBuild.exe .\GlobbingProblem\GlobbingProblem\GlobbingProblem.csproj`
5. VS: attach to msbuild process ID and hit any key in terminal
6. VS: breakpoint is hit and the following state exists:
  - items has 5 elements in it:
```
+		[0]	"Compile"="C:\\Users\\micodoba\\.nuget\\packages\\nservicebus.acceptancetests.sources\\6.3.0-alpha0113\\contentFiles\\cs\\any\\NSB.AcceptanceTests\\Audit\\When_audit_is_overridden_in_code.cs" #DirectMetadata=5)	Microsoft.Build.Execution.ProjectItemInstance
+		[1]	"Compile"="C:\\Users\\micodoba\\.nuget\\packages\\nservicebus.acceptancetests.sources\\6.3.0-alpha0113\\contentFiles\\cs\\any\\NSB.AcceptanceTests\\Audit\\When_a_replymessage_is_audited.cs" #DirectMetadata=5)	Microsoft.Build.Execution.ProjectItemInstance
+		[2]	"Compile"="C:\\Users\\micodoba\\.nuget\\packages\\nservicebus.acceptancetests.sources\\6.3.0-alpha0113\\contentFiles\\cs\\any\\NSB.AcceptanceTests\\Audit\\When_auditing_message_with_TimeToBeReceived.cs" #DirectMetadata=5)	Microsoft.Build.Execution.ProjectItemInstance
+		[3]	"Compile"="C:\\Users\\micodoba\\.nuget\\packages\\nservicebus.acceptancetests.sources\\6.3.0-alpha0113\\contentFiles\\cs\\any\\NSB.AcceptanceTests\\Audit\\When_a_message_is_audited.cs" #DirectMetadata=5)	Microsoft.Build.Execution.ProjectItemInstance
+		[4]	"Compile"="C:\\Users\\micodoba\\.nuget\\packages\\nservicebus.acceptancetests.sources\\6.3.0-alpha0113\\contentFiles\\cs\\any\\NSB.AcceptanceTests\\Audit\\When_auditing.cs" #DirectMetadata=5)	Microsoft.Build.Execution.ProjectItemInstance
```
  - listBuilder has 190 items in it
7. step over line 34 so the list builder performs the RemoveAll.

Expected: 5 elements are removed, the ones from `items`.
Actual: 6 elements are removed. The unexpected removed element is an item with the value: `C:\Users\micodoba\.nuget\packages\nservicebus.acceptancetests.sources\6.3.0-alpha0113\contentFiles\cs\any\NSB.AcceptanceTests\ConfigureEndpointLearningTransport.cs`.

If you replace the `RemoveAll` with `Remove`, then only the expected items are removed.

MSBuild issue: https://github.com/Microsoft/msbuild/issues/2069

### PR DESCRIPTION
**Pull request by kellypleahy**
This pull request resolves #20609.

### CODE REVIEW

File: src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs [hunk 1]
```diff
@@ -2205,19 +2205,22 @@ internal Node RemoveAll(Predicate<T> match)
                 Contract.Ensures(Contract.Result<Node>() != null);
 
                 var result = this;
-                int index = 0;
-                foreach (var item in this)
-                {
+                var index = 0;
+                var count = this.Count;
+                var removed = 0;
+                for(;;)
```
Comment (sharwell) [inline src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs]: :bulb: Unlike C++, in C# the customary infinite loop is `while (true)`

File: src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs [hunk 2]
```diff
@@ -2205,19 +2205,22 @@ internal Node RemoveAll(Predicate<T> match)
...
+                    if (index + removed >= count)
+                        break;
+                    var item = result[index];
                     if (match(item))
                     {
                         result = result.RemoveAt(index);
+                        removed++;
                     }
                     else
-                    {
```
Comment (sharwell) [inline src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs]: :bulb: Either omit braces for all clauses, or include them for all clauses. In this case since the `if` condition is two statements that means include for all.

File: src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs [hunk 3]
```diff
@@ -2205,19 +2205,22 @@ internal Node RemoveAll(Predicate<T> match)
...
-                foreach (var item in this)
-                {
+                var index = 0;
+                var count = this.Count;
+                var removed = 0;
+                for(;;)
+                {
+                    if (index + removed >= count)
+                        break;
+                    var item = result[index];
```
Comment (sharwell) [inline src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs]: :memo: Indexing is O(log n), where `MoveNext()` on the enumerator is O(1), hence the noted change in complexity.

Comment (kellypleahy) [inline src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs]: OK.  gotcha.  The RemoveAt is also O(log n), right?  so really this operation was O(n log n) anyway, or am I missing something?

File: src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs (hunk 2 above)
Comment (kellypleahy) [inline src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs]: Will fix.  Missed this one in the coding style guidelines.

File: src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs (hunk 1 above)
Comment (kellypleahy) [inline src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs]: OK... I've seen quite a mix, but I'll switch to while (true).  Actually, can move it to a while loop with a condition given the break is the first thing in the body.  Will fix.

File: src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs (hunk 3 above)
Comment (sharwell) [inline src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs]: In my evaluation, I was referring to best-case performance where *n* is the size of the list and the predicate is `x => false`. You would have a separate input to this *m* which is the number of items actually removed, with the original complexity being close to O(n log m) - best case O(n), worst case something close to O(n log n). Since the increase in *m* directly causes a reduction in the size of the list, someone would have to remind me what the worst case impact actually is (O(n log n) is an upper bound).

Comment (kellypleahy) [inline src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs]: OK... it is certainly possible to do this without a n-log-n best case, and I appreciate that point of view.  The complexity of the code would be considerably worse, I think, due to the fact that you need a way to basically the same thing the iterator is doing (either using it or using separate code) and a way to sync that up with the new result when the nodes are mutated.  I can think about what that might look like.  Are you opposed to a public method on the Enumerator that would allow it to "adapt" to a removal of an item?

**Comment by kellypleahy** [comment]
This latest round of changes should make the algorithm be O(n) if nothing gets removed.  Hopefully I didn't make any other style faux-pas.

**Comment by kellypleahy** [comment]
OK... I believe this is ready for review again.  Please let me know any other concerns you have.  I believe the complexity is now unchanged from the original complexity although there is an extra log2(n) operation in there that wasn't there before (rebuilding the enumerator appears at my best guess to be log2(n)).

File: src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs (hunk 3 above)
Comment (sharwell) [inline src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs]: Keep in mind I have somewhat limited exposure to this code, since I spend essentially all of my time over in a different project (in other words I don't know :smile:). @stephentoub or @AArnott would be better able to answer your question here.

**Comment by kellypleahy** [comment]
Thanks.  I welcome the review.  I was not particularly happy myself when I saw what the worst case performance of this `RemoveAll` operation was, as there's a lot of tree manipulation happening for each removal (not even considering the reinitialization / recreation question for the enumerator).

Basically, for each removal there is:
1. tree walking to find the node in question,
2. tree manipulation to remove the node in question
3. potentially tree rebalancing

Each of these are potentially quite expensive if done for, say, a List of 1mm items with a high percentage of removals.  Of course, they are O(log N) so that is nice (rather than O(N) which would make this algorithm an abysmal O(N^2) worst case).

It seems like there are a several alternatives:
1. consider "copying" a filtered list in `RemoveAll` to new nodes (this could also be quite expensive if not done well)
2. consider moving rebalancing to the end so at least that is less painful (see `AddRange`'s use of `BalanceMany()`)
3. consider an adaptive algorithm that detects a percentage of things being removed and if that percentage is high, switches to a copy with filtering of the tree once some threshold has been met.
4. add another API for clearing a high percentage of the tree and document it (I really don't like this one)

As to the complexity of the reinitialization / recreation question re: enumerator posed above, I'd say the main cost there is the fact that there will be a new `Stack` allocated (at least I think so.  not 100% sure how the boxed reference stuff with `this` really works here).  I could address this if we think it is warranted.  It does add a bit of unpleasantness to the code if we add it as it would mean the ctor would need to be factored into a `Reinit(...)` function or something of the like that can be called instead of my recreating the enumerator - either way, it does need to rewalk the tree and rebuild the stack of internal state it uses (this was my first attempt and I backed away upon seeing how unpleasant the code was turning out).

File: src/System.Collections.Immutable/tests/ImmutableListBuilderTest.cs [hunk 4]
```diff
@@ -178,6 +178,17 @@ public void Remove()
         }
 
         [Fact]
+        public void RemoveAllBugTest()
+        {
+            var builder = ImmutableList.CreateBuilder<int>();
+            var elemsToRemove = new[]{0, 1, 2, 3, 4, 5}.ToImmutableHashSet();
+            foreach(var elem in new[]{0, 1, 2, 3, 4, 5, 6})
+                builder.Add(elem);
```
Comment (AArnott) [inline src/System.Collections.Immutable/tests/ImmutableListBuilderTest.cs]: Does this loops of Add calls do something different than just calling `builder.AddRange`? I'm curious why you chose to write a loop in the test.

**Comment by ianhays** [comment]
I'm not as much worried about the performance of RemoveAll after this PR as long as it's similar or better than the existing implementation. It may be better to focus on providing a fix in this PR with as little of a performance impact as possible, then provide another PR with perf improvements and measured perf increases afterwards.

To that end, the important question is: what is the complexity of enumerator construction and can we avoid constructing a new enumerator on each removal?

**Comment by sharwell** [comment]
> To that end, the important question is: what is the complexity of enumerator construction and can we avoid constructing a new enumerator on each removal?

Maybe provide an internal `Enumerator.ResetToIndex(int)` method?

File: src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs [hunk 5]
```diff
@@ -2205,18 +2205,28 @@ internal Node RemoveAll(Predicate<T> match)
...
 
                 var result = this;
-                int index = 0;
-                foreach (var item in this)
+                var enumerator = new Enumerator(result);
+                try
                 {
-                    if (match(item))
+                    var startIndex = 0;
+                    while(enumerator.MoveNext())
```
Comment (AArnott) [inline src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs]: stylecop: If you run a Format Document on this file, I think you'll find a space is inserted after the `while`.

File: src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs [hunk 6]
```diff
@@ -2205,18 +2205,28 @@ internal Node RemoveAll(Predicate<T> match)
...
                     {
-                        result = result.RemoveAt(index);
-                    }
-                    else
-                    {
-                        index++;
+                        if (match(enumerator.Current))
+                        {
+                            result = result.RemoveAt(startIndex);
+                            enumerator.Dispose();
```
Comment (AArnott) [inline src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs]: Strictly speaking, if after disposal, an exception is thrown (say, from the `Enumerator` constructor) then there's a danger that `enumerator` will be disposed *twice*, which might be bad if we're pooling enumerator objects internally. So perhaps it would be best if after your `Dispose()` call, you explicitly clear the struct with `enumerator = default(Enumerator)` before calling the constructor.

File: src/System.Collections.Immutable/tests/ImmutableListBuilderTest.cs (hunk 4 above)
Comment (kellypleahy) [inline src/System.Collections.Immutable/tests/ImmutableListBuilderTest.cs]: I just stole the code from the original repro given in the bug.  I can test the AddRange approach, I suspect it is consistent.

File: src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs (hunk 5 above)
Comment (kellypleahy) [inline src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs]: ah... running on linux.  Is there a cli way to run the stylecop stuff on this via the build tooling?

File: src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs (hunk 6 above)
Comment (kellypleahy) [inline src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs]: ok... I had that at one point and removed it as it felt unnecessary, given the rule that calling Dispose twice should never have adverse impact (see https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/dispose-pattern)
```✓ DO allow the Dispose(bool) method to be called more than once. The method might choose to do nothing after the first call.```

If you prefer we clear it, we can do so.  I can also look into removing the likelihood of the new stack allocation (though it seems that shouldn't be a problem since we're just putting the object back into the pool and pulling it back out ;)

**Comment by kellypleahy** [comment]
> Maybe provide an internal Enumerator.ResetToIndex(int) method? I believe that would make it O(log n) with no allocations as opposed to O(log n) with an O(log n) allocation.

I'm afraid that would suffer from the same issue, as you have to rebuild the internal stack of nodes in _stack if you modify the tree topology and that's the expensive part of the operation (see `ResetStack`).

File: src/System.Collections.Immutable/tests/ImmutableListBuilderTest.cs (hunk 4 above)
Comment (kellypleahy) [inline src/System.Collections.Immutable/tests/ImmutableListBuilderTest.cs]: On further investigation, AddRange does not exhibit the issue.  I suspect it is related to how the tree gets built up in that case.  I suppose I could figure out the right incantations to do this correctly, or add a comment that indicates why Add is used.  I would hate for someone to "optimize" this later and end up with a dud test.

Comment (AArnott) [inline src/System.Collections.Immutable/tests/ImmutableListBuilderTest.cs]: My best suspicion is that there is more than one 'balanced' tree given the number of elements you have. Perhaps with a different data set, you'd find one that fails for `AddRange`. Perhaps a larger collection?

File: src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs (hunk 6 above)
Comment (AArnott) [inline src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs]: If the struct's Dispose method is indeed implemented so it is safe to call twice, then I have no concern and you don't have to worry about clearing the struct.
As for the cycling through the pool, that might actually be a cause for a small perf hit that would be nice if we could avoid. But again, I'm inclined to only perf tune when traces show it's worthwhile.

**Comment by AArnott** [comment]
> I'm afraid that would suffer from the same issue, as you have to rebuild the internal stack of nodes in _stack if you modify the tree topology and that's the expensive part of the operation (see ResetStack)

I agree. But if that method avoids the need to cycle through the pool of `Stack<T>` objects, that may make it worthwhile.

File: src/System.Collections.Immutable/tests/ImmutableListBuilderTest.cs (hunk 4 above)
Comment (kellypleahy) [inline src/System.Collections.Immutable/tests/ImmutableListBuilderTest.cs]: Is this important enough to try to find that case?  If so I can put in the time to do it.  It didn't seem important enough to me at the moment.

**Comment by kellypleahy** [comment]
>>I'm afraid that would suffer from the same issue, as you have to rebuild the internal stack of nodes in _stack if you modify the tree topology and that's the expensive part of the operation (see ResetStack)

>I agree. But if that method avoids the need to cycle through the pool of Stack<T> objects, that may make it worthwhile.

I'm with you there - I'd definitely be of the opinion that the code complexity should take precedence on this one unless we find a real trace showing a perf issue, given that the perf of the lookup in the resource pool would be dwarfed, IMHO by the cost of the stack being rebuilt (via the tree walk).

So does this mean we're good to go with this one?

File: src/System.Collections.Immutable/tests/ImmutableListBuilderTest.cs (hunk 4 above)
Comment (AArnott) [inline src/System.Collections.Immutable/tests/ImmutableListBuilderTest.cs]: The most I would do if I were you is add a code comment in the test explaining that it's important to leave it using `Add` and a loop to guard against someone "optimizing" the test.

**Comment by karelz** [comment]
@kellypleahy please do not forget to sign the CLA - see https://github.com/dotnet/corefx/pull/20796#issuecomment-306981584

**Comment by ianhays** [comment]
@kellypleahy let me know when you're done responding to Andrew's feedback and I'll squash/merge this pr.

**Comment by AArnott** [comment]
@karelz do you want to remove the blocked tag from the PR, if you added it due to the CLA that has been signed?

**Comment by karelz** [comment]
@AArnott yep, done. Just noticed it myself :) ... sorry for the confusion with the (un)signed CLA. The new green color will help avoid such mistakes in future.

**Comment by kellypleahy** [comment]
@ianhays I think this latest commit addresses all open review comments.

File: src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs (hunk 6 above)
Comment (kellypleahy) [inline src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs]: I have confirmed that `ImmutableList<T>.Enumerator.Dispose()` is safe for multiple calls.

**Comment by safern** [comment]
Thanks @kellypleahy for the fix and addressing PR feedback so quickly :)

**Comment by kellypleahy** [comment]
@safern No problem!  Looking forward to more.
