### PR TITLE
Fix some issues in RowConfigReader

### LINKED ISSUE #8890: Parsing /etc/resolv.conf throws exception when iterating network interfaces
The default generated /etc/resolve.conf for a docker container causes enumeration of network interfaces to throw because the file does not end with a newline.

```
hexdump -C /etc/resolv.conf
00000000  0a 6e 61 6d 65 73 65 72  76 65 72 20 38 2e 38 2e  |.nameserver 8.8.|
00000010  38 2e 38 0a 6e 61 6d 65  73 65 72 76 65 72 20 38  |8.8.nameserver 8|
00000020  2e 38 2e 34 2e 34                                 |.8.4.4|
00000026
```

stacktrace

```
Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.String.LastIndexOf(Char value, Int32 startIndex, Int32 count)
   at System.IO.RowConfigReader.TryGetNextValue(String key, String& value)
   at System.Net.NetworkInformation.StringParsingHelpers.ParseDnsAddressesFromResolvConfFile(String filePath)
   at System.Net.NetworkInformation.UnixIPInterfaceProperties.GetDnsAddresses()
   at System.Net.NetworkInformation.UnixIPInterfaceProperties..ctor(UnixNetworkInterface uni)
   at System.Net.NetworkInformation.LinuxIPInterfaceProperties..ctor(LinuxNetworkInterface lni)
   at System.Net.NetworkInformation.LinuxNetworkInterface..ctor(String name)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetOrCreate(Dictionary`2 interfaces, String name)
   at System.Net.NetworkInformation.LinuxNetworkInterface.<>c__DisplayClass5_0.<GetLinuxNetworkInterfaces>b__2(String name, LinkLayerAddressInfo* llAddr)
   at Interop.Sys.EnumerateInterfaceAddresses(IPv4AddressDiscoveredCallback ipv4Found, IPv6AddressDiscoveredCallback ipv6Found, LinkLayerAddressDiscoveredCallback linkLayerFound)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()

```
/cc @mellinoe

### PR DESCRIPTION
**Pull request by mellinoe**
Fixes #8890 

Previously, I had made the assumption that files parsed by the `RowConfigReader` would always end in a newline. There are some places where this is not true. Now, if we hit the end of the file in this codepath and don't see a newline, we just try to parse the value through the end of the file.

I've added some validation tests into the Common test project which covers some basic scenarios, as well as ensuring that different numbers of newlines are handled by `RowConfigReader` properly. I've also augmented the /etc/resolv.conf parsing tests to parse a file which both does and does not have a trailing newline.

@tmds, @stephentoub 

EDIT: Changes were expanded to enforce these two additional constraints:
* Keys are only matched if they start a line with no preceding whitespace.
* Keys are not matched if they are part of a larger string.

### CODE REVIEW

File: src/Common/tests/Tests/System/IO/RowConfigReaderTests.cs [hunk 1]
```diff
@@ -0,0 +1,107 @@
...
+            Assert.Equal("3", rcr.GetNextValue("value3"));
+
+            string unused;
+            Assert.False(rcr.TryGetNextValue("Any", out unused));
+        }
+
+        private const string BasicData =
+@"stringKey stringVal
+intKey 12
+";
```
Comment (stephentoub) [inline src/Common/tests/Tests/System/IO/RowConfigReaderTests.cs]: Using string verbatims like this is going to embed the newline character of the machine on which the test is compiled.  That's not always going to be what you want, especially for a test that's explicitly doing stuff with searching for newlines.  I'd suggest explicitly using Environment.NewLine in these strings rather than using verbatim strings.

File: src/Common/src/System/IO/RowConfigReader.cs [hunk 2]
```diff
@@ -82,7 +82,11 @@ public bool TryGetNextValue(string key, out string value)
             // after. This is the format of most "row-based" config files in /proc/net, etc.
             int afterKey = keyIndex + key.Length;
             int endOfLine = _buffer.IndexOf(Environment.NewLine, afterKey, _comparisonKind);
-            Debug.Assert(endOfLine != -1, "RowConfigReader needs a newline after the key, and one was not found.");
+            if (endOfLine == -1)
+            {
+                // There may not be a newline after this key, if we've reached the end of the file.
+                endOfLine = _buffer.Length - 1;
+            }
```
Comment (stephentoub) [inline src/Common/src/System/IO/RowConfigReader.cs]: What would happen if you had the string " key"... would it end up saying that the value was the same as the key, because it would search back and find the space before the key?

File: src/Common/src/System/IO/RowConfigReader.cs [hunk 3]
```diff
@@ -82,7 +82,11 @@ public bool TryGetNextValue(string key, out string value)
...
 
             int valueIndex = _buffer.LastIndexOf('\t', endOfLine);
```
Comment (stephentoub) [inline src/Common/src/System/IO/RowConfigReader.cs]: I didn't notice... do any of your new tests use tabs?

File: src/Common/tests/Tests/System/IO/RowConfigReaderTests.cs (hunk 1 above)
Comment (mellinoe) [inline src/Common/tests/Tests/System/IO/RowConfigReaderTests.cs]: Hmm, good point, I hadn't considered that.

File: src/Common/src/System/IO/RowConfigReader.cs (hunk 3 above)
Comment (mellinoe) [inline src/Common/src/System/IO/RowConfigReader.cs]: They do not, I will add some.

File: src/Common/src/System/IO/RowConfigReader.cs (hunk 2 above)
Comment (mellinoe) [inline src/Common/src/System/IO/RowConfigReader.cs]: Yeah, it will behave badly in that scenario. Right now I'm assuming a base level of "well-formatted-ness", since the files we are parsing are either OS-generated or assumed to be in a particular format by the OS if edited by hand. But I would prefer if this type could handle such cases, since it should be usable in general cases.

I think we can avoid your particular issue by using a different overload of `LastIndexOf`. We can error out if it turns out there's not actually a value present for that particular key.

Comment (mellinoe) [inline src/Common/src/System/IO/RowConfigReader.cs]: I added another commit which has better handling for this sort of case. This method will return false when trying to get the value of "key" in any of these strings:

"key"
" key"
"key "
etc.

**Comment by mellinoe** [comment]
There's still a couple of issues with RowConfigReader I am also going to try to fix now:

* Ignore commented-out lines
* Only match keys if they start the line, and are not contained in another word.

**Comment by mellinoe** [comment]
I made some more substantial changes so that the following things are enforced in the reader:

* Keys are only matched if they start a line with no preceding whitespace.
  * This is true for all of the file formats we use `RowConfigReader` with.
* Keys are not matched if they are part of a larger string.

**Comment by stephentoub** [comment]
Thanks, Eric. LGTM.
