### PR TITLE
Try to fix failing UWP ActiveDirectorySecurity tests on UWP

### LINKED ISSUE #21338: Test: System.DirectoryServices.Tests.ActiveDirectorySecurityTests/Ctor_Default failed with "System.PlatformNotSupportedException"
Opened on behalf of @Jiayili1

The test `System.DirectoryServices.Tests.ActiveDirectorySecurityTests/Ctor_Default` has failed.

System.PlatformNotSupportedException : Access Control List (ACL) APIs are part of resource management on Windows and are not supported on this platform.

        Stack Trace:

           at System.Security.AccessControl.DirectoryObjectSecurity..ctor()
       at System.DirectoryServices.Tests.ActiveDirectorySecurityTests.Ctor_Default()
Build : Master - 20170622.01 (UWP F5 Tests)
Failing configurations:
- Windows.10.Amd64.ClientRS3-x86
  - Release
  - Debug
- Windows.10.Amd64.ClientRS3-x64
  - Debug
  - Release

Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fuwp~2F/build/20170622.01/workItem/System.DirectoryServices.Tests/analysis/xunit/System.DirectoryServices.Tests.ActiveDirectorySecurityTests~2FCtor_Default

### PR DESCRIPTION
**Pull request by hughbe**
Fixes #21338

### CODE REVIEW

File: src/System.DirectoryServices/tests/System/DirectoryServices/ActiveDirectorySecurityTests.cs [hunk 1]
```diff
@@ -6,6 +6,7 @@
 
 namespace System.DirectoryServices.Tests
 {
+    [SkipOnTargetFramework(TargetFrameworkMonikers.Uap | TargetFrameworkMonikers.UapAot, "DirectoryObjectSecurity is not supported.")]
```
Comment (danmosemsft) [inline src/System.DirectoryServices/tests/System/DirectoryServices/ActiveDirectorySecurityTests.cs]: This is redundant
https://github.com/dotnet/buildtools/blob/master/src/xunit.netcore.extensions/TargetFrameworkMonikers.cs#L25
But, harmless

**Comment by danmosemsft** [comment]
Thanks Hugh.
