### PR TITLE
Propagate exceptions from ServiceBase.OnStart

### LINKED ISSUE #26280: ServiceBase doesn't propagate exceptions from OnStart
When a service fails to start, ServiceBase doesn't inform SCM and doesn't propagate the exception to the caller of ServiceBase.Run.

This bug has already been fixed in the full .NET Framework v4.7.1.

### PR DESCRIPTION
**Pull request by Anipik**
Fixes #26280.
Related PR-  https://github.com/dotnet/corefx/pull/26282

### CODE REVIEW

**Comment by Anipik** [comment]
@dotnet-bot test this please

File: src/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs [hunk 1]
```diff
@@ -215,6 +215,18 @@ public void LogWritten_AutoLog_False()
             }
         }
 
+        [ConditionalFact(nameof(IsProcessElevated))]
+        public void PropagateExceptionFromOnStart()
+        {
+            var controller = new ServiceController(_testService.TestServiceName);
```
Comment (danmosemsft) [inline src/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs]: did you verify this test fails without the fix above?

**Comment by danmosemsft** [comment]
cc @davidmatson fyi

File: src/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs (hunk 1 above)
Comment (davidmatson) [reply src/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs]: (In case I need to write one of these in the future)
I'm not sure I follow what this test does. Does this test assert somehow that the exception gets propagated to the caller? (Is that the intent of this test?)

Comment (Anipik) [reply src/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs]: @davidmatson I am still working on how to test the propagation of exception correctly.

**Comment by Anipik** [comment]
@davidmatson can you tell how you tested these changes locally ?

**Comment by davidmatson** [comment]
@Anipik, I tested previously by having a service always throw an exception on startup, verified by putting a try/catch around ServiceBase.Run to see if the exception propagated.


I wrote up a quick standalone test case for you - the following code writes "FAIL" on .NET 4.7 and "PASS" on .NET 4.7.1.

```c#
using System;
using System.ComponentModel;
using System.IO;
using System.ServiceProcess;

class Program
{
    static void Main()
    {
        Exception expectedException = new InvalidOperationException("Fail on startup.");
        bool pass = false;

        try
        {
            ServiceBase.Run(new ThrowOnStartService(expectedException));
        }
        catch (Exception actualException)
        {
            if (object.ReferenceEquals(expectedException, actualException))
            {
                pass = true;
            }
        }

        File.WriteAllText(@"C:\testresult.log", pass ? "PASS" : "FAIL");
    }
}

class ThrowOnStartService : ServiceBase
{
    readonly Exception startupException;

    public ThrowOnStartService(Exception startupException)
    {
        this.startupException = startupException;
    }

    protected override void OnStart(string[] args)
    {
        throw startupException;
    }
}

[RunInstaller(true)]
public class ProjectInstaller : ServiceProcessInstaller
{
    public ProjectInstaller()
    {
        Account = ServiceAccount.LocalService;

        Installers.Add(new ServiceInstaller
        {
            ServiceName = "teststartupexception",
            DisplayName = "Test Startup Exception"
        });
    }
}
```

The other part is testing that the exit code is passed correctly to SCM - this part I tested by using service.msc and seeing that the dialog comes back differently. Per @danmosemsft, there's probably no good way to test this part automatically with the existing harness.

Before (.NET 4.7):
image

After (.NET 4.7.1):
image

The same behavior can also be seen via sc.exe:

Before (.NET 4.7):
```
PS C:\> sc.exe query teststartupexception

SERVICE_NAME: teststartupexception
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```

After (.NET 4.7.1):
```
PS C:\> sc.exe query teststartupexception

SERVICE_NAME: teststartupexception
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 1064  (0x428)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```

David

**Comment by Anipik** [comment]
@danmosemsft I have verified the behavior after and before this change in .netCore. Its exactly the same as Described by david and matches with .netFramework 4.7.1
https://github.com/Anipik/corefx/tree/ExceptionTesting link to the local file for registering services on .netCore. I suggest Merging this PR and opening an issue to track that the test is not added for this.

**Comment by Anipik** [comment]
@dotnet-bot test NETFX x86 Release Build

**Comment by danmosemsft** [comment]
@Anipik I don't feel strongly, but generally there isn't much advantage in merging a change and then following up separately with tests, usually the reverse. Why not clean up https://github.com/dotnet/corefx/compare/master...Anipik:ExceptionTesting and roll it in?

**Comment by Anipik** [comment]
okay @danmosemsft. I will clean that up and try to add test in this.

**Comment by Anipik** [comment]
The test fails without this change

File: src/System.ServiceProcess.ServiceController/tests/System.ServiceProcess.ServiceController.TestService/Program.cs [hunk 2]
```diff
@@ -15,8 +15,28 @@ static int Main(string[] args)
...
+                TestService testService;
+                if (args[0].StartsWith("PropagateExceptionFromOnStart"))
+                {
+                    Exception expectedException = new InvalidOperationException("Fail on startup.");
+                    testService = new TestService(args[0], expectedException);
+                    try
+                    {
+                        ServiceBase.Run(testService);
+                    }
+                    catch(Exception actualException)
```
Comment (danmosemsft) [inline src/System.ServiceProcess.ServiceController/tests/System.ServiceProcess.ServiceController.TestService/Program.cs]: nit, space after catch before paren.

File: src/System.ServiceProcess.ServiceController/tests/System.ServiceProcess.ServiceController.TestService/Program.cs [hunk 3]
```diff
@@ -15,8 +15,28 @@ static int Main(string[] args)
...
+                    {
+                        if (object.ReferenceEquals(expectedException, actualException))
+                        {
+                            testService.WriteStreamAsync(PipeMessageByteCode.ExceptionThrown).Wait();
```
Comment (danmosemsft) [inline src/System.ServiceProcess.ServiceController/tests/System.ServiceProcess.ServiceController.TestService/Program.cs]: if it's not expectedExceptoin maybe it should rethrow it?

File: src/System.ServiceProcess.ServiceController/tests/System.ServiceProcess.ServiceController.TestService/Program.cs [hunk 4]
```diff
@@ -15,8 +15,28 @@ static int Main(string[] args)
         {
             if (args.Length == 1 || args.Length == 2)
             {
-                TestService testService = new TestService(args[0]);
-                ServiceBase.Run(testService);
+                TestService testService;
+                if (args[0].StartsWith("PropagateExceptionFromOnStart"))
+                {
+                    Exception expectedException = new InvalidOperationException("Fail on startup.");
```
Comment (danmosemsft) [inline src/System.ServiceProcess.ServiceController/tests/System.ServiceProcess.ServiceController.TestService/Program.cs]: nit: as the RHS is a constructor the type is obvious and you can use 'var'

File: src/System.ServiceProcess.ServiceController/tests/System.ServiceProcess.ServiceController.TestService/Program.cs (hunk 3 above)
Comment (Anipik) [reply src/System.ServiceProcess.ServiceController/tests/System.ServiceProcess.ServiceController.TestService/Program.cs]: Rethrowing won’t affect the test as it is in other process.
