### PR TITLE
Make ImmutableArray's SyncRoot throw NotSupportedException

### LINKED ISSUE #1390: Consider making ImmutableArray<T>.SyncRoot throw NotSupportedException
Currently `ImmutableArray<T>` (a value type) returns `this` in its implementation of `ICollection.SyncRoot`. I believe a more appropriate implementation would be to throw `NotSupportedException`, a behavior which would match the collections in `System.Collections.Concurrent`.

### PR DESCRIPTION
**Pull request by stephentoub**
ImmutableArray<T>'s ICollection.SyncRoot implementation currently does "return this;".  Unfortunately, this will result in returning a new object each time, which means that any attempts to use the resulting object to synchronize blocks of arbitrary code will silently result in race conditions as different objects end up being used.  With ImmutableArray<T> being a single-field struct, and with it being a violation of its design to return the underlying array as the sync root, the best available option is to simply throw a NotSupportedException.

Fixes #1390.

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @AArnott, @terrajobst

File: src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray`1.cs [hunk 1]
```diff
@@ -1414,14 +1414,7 @@ bool ICollection.IsSynchronized
...
         {
-            get
-            {
-                // As a struct, this instance will be boxed in order to call this property getter.
-                // We will return the boxed instance. If the caller boxes and reboxes repeatedly,
-                // they'll get a different SyncRoot each time.
-                // No real alternative, but we don't anticipate this will be much problem anyway.
-                return this;
-            }
+            get { throw new NotSupportedException(); }
```
Comment (sharwell) [inline src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray`1.cs]: :exclamation: Can we not use `SR.ConcurrentCollection_SyncRoot_NotSupported` (either directly, or by copying that resource to this assembly and naming it `Immutable[Collection|Array]_SyncRoot_NotSupported`?

Comment (stephentoub) [inline src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray`1.cs]: It can't be used directly, and I don't think the text of concurrent collection's exception makes sense for this immutable one ("The SyncRoot property may not be used for the synchronization of concurrent collections.").  I also don't think rewritten text would add much value over the default text associated with NotSupportedException ("Specified method is not supported"), which is why I didn't add another resource to customize the message.  But my care factor is fairly low on this one. :)

**Comment by sharwell** [comment]
I'm obviously in favor of this change. :+1:

**Comment by AArnott** [comment]
:+1:

File: src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray`1.cs (hunk 1 above)
Comment (terrajobst) [inline src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray`1.cs]: +1 The default text is good enough in my opinion.

**Comment by terrajobst** [comment]
LGTM

**Comment by nguerrera** [comment]
:+1:
