### PR TITLE
Bug fix: Force properties reload

### LINKED ISSUE #23127: DesignerOptionService.DesignerOptionCollection.Properties does not update cached version when children update
In System.ComponentModel.TypeConverters, DesignerOptionCollection caches the value of the `Properties` field. The cached value never updates, even if the properties would be different. 
In the example below, accessing `Properties` before adding a child causes the value of Properties to be cached and be out of date. Accessing `Properties` after adding a child causes the value to be correct

```cps
        [Fact]
        public void Properties_GetBeforeAddingChild_ReturnsEmpty()
        {
            var service = new TestDesignerOptionService();
            Assert.Empty(service.Options.Properties);

            DesignerOptionService.DesignerOptionCollection options = service.DoCreateOptionCollection(service.Options, "name", "value");
            Assert.Empty(service.Options.Properties);
        }

        [Fact]
        public void Properties_GetAfterAddingChild_ReturnsNonEmpty()
        {
            var service = new TestDesignerOptionService();

            DesignerOptionService.DesignerOptionCollection options = service.DoCreateOptionCollection(service.Options, "name", "value");
            Assert.NotEmpty(service.Options.Properties);
        }

        private class TestDesignerOptionService : DesignerOptionService
        {
            public object ShowDialogValue { get; set; } = "Default";

            public DesignerOptionCollection DoCreateOptionCollection(DesignerOptionCollection parent, string name, object value)
            {
                return CreateOptionCollection(parent, name, value);
            }

            protected override bool ShowDialog(DesignerOptionCollection options, object optionObject)
            {
                ShowDialogValue = optionObject;
                return true;
            }

            public bool DoShowDialog(DesignerOptionCollection options, object optionObject)
            {
                return base.ShowDialog(options, optionObject);
            }
        }
```

@safern (from #23013)

### PR DESCRIPTION
**Pull request by MarcoRossignoli**
Fixes #23127

I think this should be fixed also on [netfx](https://referencesource.microsoft.com/#System/compmod/system/componentmodel/design/DesignerOptionService.cs,156).

cc: @safern

### CODE REVIEW

File: src/System.ComponentModel.TypeConverter/tests/Design/DesignerOptionServiceTests.cs [hunk 1]
```diff
@@ -180,13 +180,14 @@ public void Indexer_InvalidIndex_ThrowsIndexOutOfRangeException(int index)
         }
 
         [Fact]
+        [SkipOnTargetFramework(TargetFrameworkMonikers.NetFramework)]
```
Comment (MarcoRossignoli) [inline src/System.ComponentModel.TypeConverter/tests/Design/DesignerOptionServiceTests.cs]: Skip tests on [netfx](https://referencesource.microsoft.com/#System/compmod/system/componentmodel/design/DesignerOptionService.cs,156)

File: src/System.ComponentModel.TypeConverter/tests/Design/DesignerOptionServiceTests.cs [hunk 2]
```diff
@@ -180,13 +180,14 @@ public void Indexer_InvalidIndex_ThrowsIndexOutOfRangeException(int index)
         }
 
         [Fact]
-        public void Properties_GetBeforeAddingChild_ReturnsEmpty()
+        [SkipOnTargetFramework(TargetFrameworkMonikers.NetFramework)]
```
Comment (MarcoRossignoli) [inline src/System.ComponentModel.TypeConverter/tests/Design/DesignerOptionServiceTests.cs]: Skip test on [netfx](https://referencesource.microsoft.com/#System/compmod/system/componentmodel/design/DesignerOptionService.cs,156)

**Comment by MarcoRossignoli** [comment]
@dotnet-bot test OSX x64 Debug Build please

File: src/System.ComponentModel.TypeConverter/src/System/ComponentModel/Design/DesignerOptionService.cs [hunk 3]
```diff
@@ -154,6 +154,7 @@ internal DesignerOptionCollection(DesignerOptionService service, DesignerOptionC
 
                 if (Parent != null)
                 {
+                    parent._properties = null;
```
Comment (safern) [inline src/System.ComponentModel.TypeConverter/src/System/ComponentModel/Design/DesignerOptionService.cs]: Do we have a test that ensures this will continue caching the children afterwards? It should, but just want to make sure we don't regress any behavior.

**Comment by safern** [comment]
Thanks @MarcoRossignoli
