### PR TITLE
[Arm64] Fix CI tar path

### LINKED ISSUE #28247: CI Build step 'Execute shell' marked build as failure
09:35:37 [ubuntu16.04_arm64_cross_debug_prtest] $ /bin/sh -xe /tmp/jenkins6999066973616382871.sh
09:35:37 + tar -czf bin/build.tar.gz --directory=bin/runtime/netcoreapp-Linux-Debug-arm64 .
09:35:37 tar: bin/runtime/netcoreapp-Linux-Debug-arm64: Cannot open: No such file or directory
09:35:37 tar: Error is not recoverable: exiting now
09:35:37 
Build step 'Execute shell' marked build as failure

https://ci.dot.net/job/dotnet_corefx/job/master/job/ubuntu16.04_arm64_cross_debug_prtest/11/consoleFull#-8536224876a086b3e-df04-41d2-bc4d-43e8f9406d07

### PR DESCRIPTION
**Pull request by sdmaclea**
@stephentoub PTAL  Fixes #28247

Built in the docker image, and tested the tar path.  Matches tar path used for x86 below.

### CODE REVIEW

File: netci.groovy [hunk 1]
```diff
@@ -364,7 +364,7 @@ def targetGroupOsMapInnerloop = ['netcoreapp': ['Windows_NT', 'Ubuntu14.04', 'Ub
                     shell(script)
 
                     // Tar up the appropriate bits.
-                    shell("tar -czf bin/build.tar.gz --directory=\"bin/runtime/${targetGroup}-${osGroup}-${configurationGroup}-arm64\" .")
+                    shell("tar -czf bin/build.tar.gz --directory=\"bin/Linux.${archGroup}.${configurationGroup}/native\" .")
```
Comment (sdmaclea) [inline netci.groovy]: Copied from https://github.com/dotnet/corefx/blob/master/netci.groovy#L419

**Comment by sdmaclea** [comment]
@stephentoub In order to confirm this fixes things, I need someone to trigger "@dotnet-bot test ci please"

**Comment by danmosemsft** [comment]
@dotnet-bot test ci please

**Comment by sdmaclea** [comment]
@danmosemsft @stephentoub Please trigger ci again

**Comment by danmosemsft** [comment]
@dotnet-bot test ci please

**Comment by sdmaclea** [comment]
@mmitche arm64 legs have machine affinity set for ubuntu1404-20170120 like x86, arm, and armel.  Looks like there is a fairly long queue.  The only reason to restrict the affinity is for docker support.  You mentioned earlier dropping the restriction.  What is required to drop the restriction?

**Comment by mmitche** [comment]
@sdmaclea It's just that docker doesn't initialize properly a good portion of the time.  I am investigating solutions.

**Comment by sdmaclea** [comment]
The initial runs picked up used tip netci.groovy.  Failed because of the old code.
@dotnet-bot test Ubuntu16.04 arm64 Debug Build
@dotnet-bot test Ubuntu16.04 arm64 Release Build

File: netci.groovy [hunk 2]
```diff
@@ -353,6 +353,7 @@ def targetGroupOsMapInnerloop = ['netcoreapp': ['Windows_NT', 'Ubuntu14.04', 'Ub
     ['netcoreapp'].each { targetGroup ->
         ['Debug', 'Release'].each { configurationGroup ->
```
Comment (weshaggard) [inline netci.groovy]: Can we scope this to just debug or release by default? We want to try and keep our CI leg count minimum so we use a sparse matrix. 

Also I'm not sure if we can but ideally we would put these in https://github.com/dotnet/corefx/blob/master/buildpipeline/pipelinejobs.groovy.

Comment (sdmaclea) [reply netci.groovy]: @weshaggard I added to pipelinejobs.groovy already.

This is blocking official builds, so I 'll drop one leg in a separate PR

Comment (weshaggard) [reply netci.groovy]: >This is blocking official builds

Yes please unblock the builds.

>@weshaggard I added to pipelinejobs.groovy already.

Perhaps I missed it but it would seem as though you added it to netci.groovy and not pipelinejobs.groovy. Can you point me at that change?

**Comment by weshaggard** [comment]
@sdmaclea lets watch this to make sure it works in current PRs.

File: netci.groovy (hunk 2 above)
Comment (sdmaclea) [reply netci.groovy]: @weshaggard #27656

Comment (weshaggard) [reply netci.groovy]: I know it is confusing but pipelines.json isn't the same as pipelines.groovy. pipelines.json is for our official builds and pipelines.groovy is our newer jenkins CI scripts. netci.groovy is our older CI scripts we are trying to phase out.

**Comment by sdmaclea** [comment]
> @sdmaclea Is there a reason these got implemented in netci.groovy vs. pipelinejobs.groovy

Ignorance.  
I copied the Linux arm, armel, x86 jobs in `netci.groovy`
