### PR TITLE
Fix behaviour of TreeSubSet Min and Max

### LINKED ISSUE #16760: Regression in SortedSet::Max
introduced in https://github.com/dotnet/corefx/pull/11968

```c#
using System;
using System.Collections.Generic;

class X
{
	public static void Main ()
	{

		var set = new SortedSet<int> { 1, 3, 5, 7, 9 };
		var view = set.GetViewBetween (4, 8);

		Console.WriteLine (view.Max); // Prints 9 instead of 7
	}
}
```

### PR DESCRIPTION
**Pull request by mjp41**
Fixes #16760.

Provide correct override in TreeSubSet for Min and Max, they now take
account of the range of the subset.

As the root is guaranteed to be in the range, then the code does not
need to check something is in the range, if _root is not null.

This makes Min and Max virtual. Is that an acceptable change?  Previously, they hid the virtual behaviour inside the implementation. 
cc @stephentoub @marek-safar @ianhays

### CODE REVIEW

**Comment by stephentoub** [comment]
> This makes Min and Max virtual. Is that an acceptable change?

Not without an API review. cc: @terrajobst 
How about instead having:
```C#
public T Min => MinInternal;
internal virtual T MinInternal { get { /* code previously in Min */ } }
```
and then override MinInternal in TreeSubSet (and the same for Max)?

I'm not very familiar with the situations in which Min and Max would be used.  Is an extra virtual call on such code paths going to be problematic for performance?

**Comment by danmosemsft** [comment]
A change here would require test coverage.

**Comment by stephentoub** [comment]
> A change here would require test coverage.

https://github.com/dotnet/corefx/pull/16763

**Comment by mjp41** [comment]
I rebased on top of the tests, and made it use an Internal virtual call.

**Comment by danmosemsft** [comment]
Shouldn't I see the [ActiveIssue] being removed?

**Comment by stephentoub** [comment]
> Shouldn't I see the [ActiveIssue] being removed?

It is.

**Comment by mjp41** [comment]
I have extended with a more exhaustive test of a small tree, so that I believe all the corner cases should be covered now.

**Comment by stephentoub** [comment]
@dotnet-bot test code coverage please

File: src/System.Collections/src/System/Collections/Generic/SortedSet.TreeSubSet.cs [hunk 1]
```diff
@@ -124,6 +124,54 @@ internal override bool IsWithinRange(T item)
...
+                            result = current.Item;
+                            if (comp == 0)
+                                break;
+                            current = current.Left;
+                        }
+                    }
+
+                    return result;
+                }
+            }
```
Comment (stephentoub) [inline src/System.Collections/src/System/Collections/Generic/SortedSet.TreeSubSet.cs]: Nits:
- Could you move the opening braces from the end of the lines to the beginning of the next?
- Could you move the else to its own line?
- Could you surround the break with braces (on their own lines)?

Same in MaxInternal below.

File: src/System.Collections/tests/Generic/SortedSet/SortedSet.Generic.cs [hunk 2]
```diff
@@ -63,6 +62,27 @@ public void SortedSet_Generic_IntersectWith_SupersetEnumerableWithDups()
...
+                {
+                    SortedSet<int> view = set.GetViewBetween(i, j);
+
+                    if (j < i || (j == i && i % 2 == 0) ){
+                        Assert.Equal(default(int), view.Min);
+                        Assert.Equal(default(int), view.Max);
+                    } else {
+                        Assert.Equal(i + ((i+1) % 2), view.Min);
+                        Assert.Equal(j - ((j+1) % 2), view.Max);
+                    }
```
Comment (stephentoub) [inline src/System.Collections/tests/Generic/SortedSet/SortedSet.Generic.cs]: Nit: same style nits, e.g. braces

**Comment by mjp41** [comment]
@stephentoub thanks for the feedback. I have addressed the comments. Do you want me to collapse to a single commit?

**Comment by stephentoub** [comment]
Thanks, @mjp41.  No need; I'll just squash it when merging once CI is green.
