### PR TITLE
Test cleanup for System.Net.Security

### LINKED ISSUE #3144: Remove references to TaskAPMExtensions in System.Net tests
Remove Common\tests\System.Net\TaskAPMExtensions.cs and rewrite tests using TPL instead.

### LINKED ISSUE #7825: Kerberos to ntlm fallback is not happening with the ntlmssp plugin when passed valid ntlm creds.
There is a bug in ntlmssp package .If we try spnego with valid ntlm creds, it first tries Kerberos and since the creds are not present in Kerberos database it should fallback to ntlm. Which is not happening in the current verison. 
The issue is discussed with ntlmssp plugin developer (simo sorce) .He will look into this.

### LINKED ISSUE #8744: failure in ServerAsyncAuthenticate_AllClientVsIndividualServerSupportedProtocols_Success
Details in http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/1552/console  
on a [PR](https://github.com/dotnet/corefx/pull/8707) that could not possibly cause the issue
 System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_AllClientVsIndividualServerSupportedProtocols_Success(serverProtocol: Tls11) [FAIL]
        System.ComponentModel.Win32Exception : The credentials supplied to the package were not recognized
        Stack Trace:
           D:\j\workspace\windows_nt_re---37265eab\src\Common\src\Interop\Windows\sspicli\SSPIWrapper.cs(232,0): at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface secModule, String package, CredentialUse intent, SecureCredential scc)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\SslStreamPal.Windows.cs(330,0): at System.Net.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SecureCredential secureCredential)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\SslStreamPal.Windows.cs(126,0): at System.Net.SslStreamPal.AcquireCredentialsHandle(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\SecureChannel.cs(769,0): at System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\SecureChannel.cs(901,0): at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\SecureChannel.cs(805,0): at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\SecureProtocols\SslState.cs(749,0): at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\SecureProtocols\SslState.cs(955,0): at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\SecureProtocols\SslState.cs(1131,0): at System.Net.Security.SslState.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
           --- End of stack trace from previous location where exception was thrown ---
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\SecureProtocols\SslState.cs(742,0): at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\SecureProtocols\SslState.cs(710,0): at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
              at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
           --- End of stack trace from previous location where exception was thrown ---

### LINKED ISSUE #9130: System.Net.Security: Authentication failed because the remote party has closed the transport stream.
In #9115:

On a `Standard_D3_v2` Azure machine:

Windows_NT Debug Build and Test failed because:

```
System.Net.Security.Tests.ServerNoEncryptionTest.ServerNoEncryption_ClientAllowNoEncryption_ConnectWithNoEncryption [FAIL] failed.

MESSAGE:
System.IO.IOException : Authentication failed because the remote party has closed the transport stream.
+++++++++++++++++++
STACK TRACE:
at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest) in D:\j\workspace\windows_nt_de---494cfe0d\src\System.Net.Security\src\System\Net\SecureProtocols\SslState.cs:line 870 
at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest) in D:\j\workspace\windows_nt_de---494cfe0d\src\System.Net.Security\src\System\Net\SecureProtocols\SslState.cs:line 1098 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult) in D:\j\workspace\windows_nt_de---494cfe0d\src\System.Net.Security\src\System\Net\SecureProtocols\SslState.cs:line 740 
at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result) in D:\j\workspace\windows_nt_de---494cfe0d\src\System.Net.Security\src\System\Net\SecureProtocols\SslState.cs:line 710 
at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult) in D:\j\workspace\windows_nt_de---494cfe0d\src\System.Net.Security\src\System\Net\SecureProtocols\SslStream.cs:line 125 
at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at System.Net.Security.Tests.ServerNoEncryptionTest.<ServerNoEncryption_ClientAllowNoEncryption_ConnectWithNoEncryption>d__4.MoveNext() in D:\j\workspace\windows_nt_de---494cfe0d\src\System.Net.Security\tests\FunctionalTests\ServerNoEncryptionTest.cs:line 63 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

### LINKED ISSUE #10909: Test failure: System.Net.Security.Tests.ClientAsyncAuthenticateTest/ClientAsyncAuthenticate_EachClientUnsupportedProtocol_Fail with "System.IO.IOException"
Opened on behalf of @Jiayili1

The test `System.Net.Security.Tests.ClientAsyncAuthenticateTest/ClientAsyncAuthenticate_EachClientUnsupportedProtocol_Fail` has failed.

```
Assert.Throws() Failure\r
Expected: typeof(System.NotSupportedException)\r
Actual:   typeof(System.IO.IOException): Authentication failed because the remote party has closed the transport stream.
```

Stack Trace:

```
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskTimeoutExtensions.<TimeoutAfter>d__0.MoveNext() in D:\A\_work\4\s\src\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs:line 19
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Security.Tests.ClientAsyncAuthenticateTest.<ClientAsyncSslHelper>d__14.MoveNext() in D:\A\_work\4\s\src\System.Net.Security\tests\FunctionalTests\ClientAsyncAuthenticateTest.cs:line 142
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

Failing configurations:
- Windows.10.Amd64
  - AnyCPU-Release
  - AnyCPU-Debug

link: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20160816.08/workItem/System.Net.Security.Tests/analysis/xunit/System.Net.Security.Tests.ClientAsyncAuthenticateTest~2FClientAsyncAuthenticate_EachClientUnsupportedProtocol_Fail

Failed tests:
ClientAsyncAuthenticate_EachClientUnsupportedProtocol_Fail
ClientAsyncAuthenticate_UnsuportedAllClient_Fail

### LINKED ISSUE #11170: ServerAsyncAuthenticate_MismatchProtocols_Fails failing in CI
```
System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_MismatchProtocols_Fails(serverProtocol: Tls, clientProtocol: Tls11, expectedException: typeof(System.Security.Authentication.AuthenticationException)) [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.Security.Authentication.AuthenticationException)
        Actual:   typeof(System.TimeoutException): The operation has timed out.
        Stack Trace:
              at System.Threading.Tasks.TaskTimeoutExtensions.<TimeoutAfter>d__0.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
              at System.Net.Security.Tests.ServerAsyncAuthenticateTest.<ServerAsyncSslHelper>d__11.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

### LINKED ISSUE #11345: Re-enable more networking tests for innerloop
PR #11341 moved the majority of networking tests to outerloop due to infrastructure issues. This issue will track putting back tests as we strengthen the test infrastructure to allow more networking tests to run as innerloop.

### LINKED ISSUE #11624: Test failure: System.Net.Security.Tests.ServerNoEncryptionTest/ServerNoEncryption_ClientNoEncryption_ConnectWithNoEncryption
Opened on behalf of @jiangzeng

The test `System.Net.Security.Tests.ServerNoEncryptionTest/ServerNoEncryption_ClientNoEncryption_ConnectWithNoEncryption` has failed.

```
Assert.Throws() Failure
Expected: typeof(System.Security.Authentication.AuthenticationException)
Actual:   (No exception was thrown)
```

Stack Trace:

```
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Security.Tests.ServerNoEncryptionTest.<ServerNoEncryption_ClientNoEncryption_ConnectWithNoEncryption>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

Failing configurations:
- OSX.1011.Amd64
  - AnyCPU-Release

Details:
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20160910.01/workItem/System.Net.Security.Tests/analysis/xunit/System.Net.Security.Tests.ServerNoEncryptionTest~2FServerNoEncryption_ClientNoEncryption_ConnectWithNoEncryption

### LINKED ISSUE #12107: kdc-setup.sh failed on Ubuntu 16.10
In some of the outerloop runs of Ubuntu 16.10, the [setup-kdc.sh script](https://github.com/dotnet/corefx/blob/master/src/System.Net.Security/tests/Scripts/Unix/setup-kdc.sh) is failing during `apt-get` with a 404 error. This appears to be intermittent because some runs have succeeded or at least not failed on these particular tests.

Here is an example failure log:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_ubuntu16.10_debug/13/consoleText
Search for `Installing krb5-kdc..`

This whole process seems fragile to me, is there anything we could do to improve this? An option would be to require this package to be installed on a machine before the test is permitted to run, and just skip them if it is not. For our official outerloop runs, we could require that they run, and thus require that the package be pre-installed (like all our other dependencies).

### LINKED ISSUE #12683: SslStreamAlertsTest failure in CI
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/1647/consoleText

```
System.Net.Security.Tests.SslStreamAlertsTest.SslStream_StreamToStream_ServerInitiatedCloseNotify_Ok [FAIL]
        System.ComponentModel.Win32Exception : The credentials supplied to the package were not recognized
        Stack Trace:
              at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface secModule, String package, CredentialUse intent, SCHANNEL_CRED scc)
  Finished running tests.  End time= 1:45:19.12, Exit code = 0
  Finished:    System.Reflection.TypeExtensions.Tests
              at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCHANNEL_CRED secureCredential)
              at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)

              at System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint)
              at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
              at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
              at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
              at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
              at System.Net.Security.SslState.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
              at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           D:\j\workspace\windows_nt_re---37265eab\src\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs(19,0): at System.Threading.Tasks.TaskTimeoutExtensions.<TimeoutAfter>d__0.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\tests\FunctionalTests\SslStreamAlertsTest.cs(76,0): at System.Net.Security.Tests.SslStreamAlertsTest.<SslStream_StreamToStream_ServerInitiatedCloseNotify_Ok>d__3.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

### LINKED ISSUE #12706: Flaky test : SslStream_StreamToStream_DataAfterShutdown_Fail
`https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/1676/testReport/junit/System.Net.Security.Tests/SslStreamAlertsTest/SslStream_StreamToStream_DataAfterShutdown_Fail/`

```
MESSAGE:
System.ComponentModel.Win32Exception : The credentials supplied to the package were not recognized
+++++++++++++++++++
STACK TRACE:
at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface secModule, String package, CredentialUse intent, SCHANNEL_CRED scc) at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCHANNEL_CRED secureCredential) at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer) at System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint) at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output) at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count) at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.ReadFrameCallback(AsyncProtocolRequest asyncRequest) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result) at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Threading.Tasks.TaskTimeoutExtensions.<TimeoutAfter>d__0.MoveNext() in D:\j\workspace\windows_nt_re---37265eab\src\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs:line 19 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Net.Security.Tests.SslStreamAlertsTest.<SslStream_StreamToStream_DataAfterShutdown_Fail>d__5.MoveNext() in D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\tests\FunctionalTests\SslStreamAlertsTest.cs:line 143 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

### LINKED ISSUE #14177: Failure in ClientAsyncAuthenticate_AllServerAllClient_Success in CI
```
     System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_AllServerAllClient_Success [FAIL]
        System.IO.IOException : Authentication failed because the remote party has closed the transport stream.
        Stack Trace:
           D:\j\workspace\outerloop_win---7ad0ce03\src\System.Net.Security\src\System\Net\Security\SslState.cs(884,0): at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
           D:\j\workspace\outerloop_win---7ad0ce03\src\System.Net.Security\src\System\Net\Security\SslState.cs(1094,0): at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           D:\j\workspace\outerloop_win---7ad0ce03\src\System.Net.Security\src\System\Net\Security\SslState.cs(752,0): at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
           D:\j\workspace\outerloop_win---7ad0ce03\src\System.Net.Security\src\System\Net\Security\SslState.cs(722,0): at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
           D:\j\workspace\outerloop_win---7ad0ce03\src\System.Net.Security\src\System\Net\Security\SslStream.cs(132,0): at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
              at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
           D:\j\workspace\outerloop_win---7ad0ce03\src\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs(19,0): at System.Threading.Tasks.TaskTimeoutExtensions.<TimeoutAfter>d__0.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
           D:\j\workspace\outerloop_win---7ad0ce03\src\System.Net.Security\tests\FunctionalTests\ClientAsyncAuthenticateTest.cs(151,0): at System.Net.Security.Tests.ClientAsyncAuthenticateTest.<ClientAsyncSslHelper>d__14.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
           D:\j\workspace\outerloop_win---7ad0ce03\src\System.Net.Security\tests\FunctionalTests\ClientAsyncAuthenticateTest.cs(75,0): at System.Net.Security.Tests.ClientAsyncAuthenticateTest.<ClientAsyncAuthenticate_AllServerAllClient_Success>d__7.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  Using D:\j\workspace\outerloop_win---7ad0ce03\packages\ as folder for resolving package dependencies.
  Executing in D:\j\workspace\outerloop_win---7ad0ce03\bin\tests\AnyOS.AnyCPU.Debug\System.Threading.Performance.Tests\default.netcoreapp1.1\ 
  Hard linking dependent files... 
  Finished:    System.Net.Security.Tests
```
Does not seem related to the PR https://github.com/dotnet/corefx/pull/14158 
Similar to https://github.com/dotnet/corefx/issues/10909

@davidsh @CIPop

### LINKED ISSUE #14505: Test failure: System.Threading.Tasks.Dataflow.Tests.ActionBlockTests/TestFaulting
Opened on behalf of @jiangzeng

The test `System.Threading.Tasks.Dataflow.Tests.ActionBlockTests/TestFaulting` has failed.

Assert.Equal() Failure
    Expected: 0
    Actual:   1

        Stack Trace:

           at System.Threading.Tasks.Dataflow.Tests.ActionBlockTests.<TestFaulting>d__14.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Build : Master - 20161214.01 (Core Tests)
Failing configurations:
- Suse.132.Amd64
  - AnyCPU-Release

Details:
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20161214.01/workItem/System.Threading.Tasks.Dataflow.Tests/analysis/xunit/System.Threading.Tasks.Dataflow.Tests.ActionBlockTests~2FTestFaulting

### PR DESCRIPTION
**Pull request by ianhays**
Enabling and moving a bunch of disabled/outerlooped System.Net.Security tests to innerloop. I did extensive testing on Windows, RHEL, and Ubuntu machines and ensured the tests are stable (at least locally) and hit no errors. The next step is to re-enable them and watch to see if any of the failures resurface and disable them as needed.

resolves #3144 - Removed TODO because Begin/End were added back in #8358 and the issue is closed
resolves #7825 - Original issue from April 2016. Cannot repro today. Re-enabling to watch for future failures.
resolves #11170 - Can't repro failures on multiple OSs. Re-enabling to watch for future failures.
resolves #11345 - Outerloop tests are passing and stable for thousands of iterations. Tentatively moving to innerloop to watch for potential future failures.
resolves #12107 - removed TODO because issue is closed
resolves #9130  - duplicate issues failing because of an intermittent error (remote party closed transport stream) not exclusive to the test which occurs in Outerloop runs for other NetSecurity tests. Re-enabling them and leaving them in innerloop to get more data.
resolves #10909 - duplicate issues failing because of an intermittent error (remote party closed transport stream) not exclusive to the test which occurs in Outerloop runs for other NetSecurity tests. Re-enabling them and leaving them in innerloop to get more data.
resolves #11624 - duplicate issues failing because of an intermittent error (remote party closed transport stream) not exclusive to the test which occurs in Outerloop runs for other NetSecurity tests. Re-enabling them and leaving them in innerloop to get more data.
resolves #14177 - duplicate issues failing because of an intermittent error (remote party closed transport stream) not exclusive to the test which occurs in Outerloop runs for other NetSecurity tests. Re-enabling them and leaving them in innerloop to get more data.
resolves #14505 - duplicate issues failing because of an intermittent error (remote party closed transport stream) not exclusive to the test which occurs in Outerloop runs for other NetSecurity tests. Re-enabling them and leaving them in innerloop to get more data.
resolves #8744  - duplicate issues failing because of an intermittent error (credentials package not recognized) not exclusive to the test which occurs in Outerloop runs for other NetSecurity tests. Re-enabling them and leaving them in innerloop to get more data.
resolves #12683 - duplicate issues failing because of an intermittent error (credentials package not recognized) not exclusive to the test which occurs in Outerloop runs for other NetSecurity tests. Re-enabling them and leaving them in innerloop to get more data.
resolves #12706 - duplicate issues failing because of an intermittent error (credentials package not recognized) not exclusive to the test which occurs in Outerloop runs for other NetSecurity tests. Re-enabling them and leaving them in innerloop to get more data.
resolves #12728 - duplicate issues failing because of an intermittent error (credentials package not recognized) not exclusive to the test which occurs in Outerloop runs for other NetSecurity tests. Re-enabling them and leaving them in innerloop to get more data.

@steveharter @Priya91 @davidsh

### CODE REVIEW

File: src/Common/tests/System/Threading/Tasks/TaskAPMExtensions.cs [hunk 1]
```diff
@@ -6,8 +6,6 @@
 /// Task APM helper based on http://blogs.msdn.com/b/pfxteam/archive/2011/06/27/10179452.aspx
 /// </summary>
 
-// TODO: #3144 - Remove this class and rewrite tests to work directly with TPL.
```
Comment (stephentoub) [inline src/Common/tests/System/Threading/Tasks/TaskAPMExtensions.cs]: We should still be able to delete this helper, as we have a production version the tests can also use:
https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Threading/Tasks/TaskToApm.cs
