### PR TITLE
HTTP2: Respect SETTINGS_INITIAL_WINDOW_SIZE and rework SendAsync code structure

### LINKED ISSUE #31296: HTTP2: Handle SETTINGS_MAX_CONCURRENT_STREAMS from server
Per RFC, this setting:

> Indicates the maximum number
      of concurrent streams that the sender will allow.

When this is set, we need to add a semaphore or equivalent to throttle the number of active streams. Note that it can change at any time and we need to handle this as well.

### LINKED ISSUE #31514: HTTP2: Receiving a frame on a closed stream should not close the connection
According to the spec, any (non-priority) frame received after a RST_STREAM frame should be treated as a (recoverable) _stream_ error:
```
An endpoint MUST NOT send frames other than PRIORITY on a closed stream. An endpoint that 
receives any frame other than PRIORITY after receiving a RST_STREAM MUST treat that as a
stream error (Section 5.4.2) of type STREAM_CLOSED.
```
The current implementation treats this error as a _connection_ error, and closes the underlying socket. For reliability reasons we should consider this error recoverable, and allow the other streams on the connection to continue.

### LINKED ISSUE #31812: [HTTP2] loopback server is not sending valid RstStreamFrame()
[The tests](https://github.com/dotnet/corefx/blob/66649ff5862c7b723fded40c505942de19bdb107/src/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.Http2.cs) related to sending RST_FRAME seem not right: 

1. When do `new RstStreamFrame()`, the `frameHeader.Length` will set to 13 -> `Frame.FrameHeaderLength + 4`: https://github.com/dotnet/corefx/blob/66649ff5862c7b723fded40c505942de19bdb107/src/Common/tests/System/Net/Http/Http2Frames.cs#L244
2. SocketsHttpHandler is expecting `RstStreamLength` is 4: https://github.com/dotnet/corefx/blob/eedddac1bd10a7c8629a9db7f46fc8afc7385d63/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L441

Therefore, `Http2ProtocolException(Http2ProtocolErrorCode.FrameSizeError)` will always be thrown. We are actually testing the case for invalid RST_FRAME, not testing RST_FRAME functionality.

### LINKED ISSUE #31813: [HTTP2] loopback server is not correctly reading RstStreamFrame
This issue may related to general loopback server frame reading. (I have only verified RstStreamFrame case)

When HTTP/2 loopback server is sending a malformed frame to SocketsHttpHandler, so that SocketsHttpHandler will send back a RstStreamFrame, the loopback server side is not correctly reading the RstStreamFrame:

```
System.IndexOutOfRangeException : Index was outside the bounds of the array.
        Stack Trace:
           E:\A\_work\104\s\src\System.Private.CoreLib\shared\System\ReadOnlySpan.Fast.cs(145,0): at System.ReadOnlySpan`1.get_Item(Int32 index)
           D:\corefx\src\Common\tests\System\Net\Http\Http2Frames.cs(252,0): at System.Net.Test.Common.RstStreamFrame.ReadFrom(Frame header, ReadOnlySpan`1 buffer)
           D:\corefx\src\Common\tests\System\Net\Http\Http2LoopbackServer.cs(124,0): at System.Net.Test.Common.Http2LoopbackServer.ReadFrameAsync(TimeSpan timeout)
           // This line is not important, my new test D:\corefx\src\System.Net.Http\tests\FunctionalTests\SocketsHttpHandlerTest.Http2.cs(208,0): at System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHan
  dler_Http2_Test.DataFrame_PaddingOnly_ResetsStream()
           --- End of stack trace from previous location where exception was thrown ---
```

### LINKED ISSUE #34059: HTTP2: Respect SETTINGS_INITIAL_WINDOW_SIZE setting from peer
Separating this from #31297 since it requires some additional implementation and refactoring to support properly.

### PR DESCRIPTION
**Pull request by geoffkizer**
Fixes #34059 

Update: I pushed another commit that also implements SETTINGS_MAX_CONCURRENT_STREAMS.

Fixes #31296 
Fixes #31514 
Fixes #31812
Fixes #31813

@dotnet/ncl

### CODE REVIEW

**Comment by geoffkizer** [comment]
@dotnet-bot test outerloop linux x64 build
@dotnet-bot test outerloop windows x64 build
@dotnet-bot test outerloop osx x64 build

**Comment by geoffkizer** [comment]
@dotnet-bot test outerloop linux x64 debug build
@dotnet-bot test outerloop windows x64 debug build
@dotnet-bot test outerloop osx x64 debug build

**Comment by geoffkizer** [comment]
@dotnet-bot test outerloop linux x64 debug build
@dotnet-bot test outerloop windows x64 debug build
@dotnet-bot test outerloop osx x64 debug build

File: src/Common/tests/System/Net/Http/Http2LoopbackServer.cs [hunk 1]
```diff
@@ -182,6 +188,21 @@ public async Task<string> AcceptConnectionAsync()
...
+        {
+            // The timing of when we receive the settings ack is not guaranteed.
+            // To simplify frame processing, just record that we are expecting one,
+            // and then filter it out in ReadFrameAsync above.
+
+            Assert.False(_ignoreSettingsAck);
+            _ignoreSettingsAck = true;
+        }
+
+        public void IngoreWindowUpdates()
```
Comment (rmkerr) [inline src/Common/tests/System/Net/Http/Http2LoopbackServer.cs]: nit: Ignore

**Comment by geoffkizer** [comment]
@dotnet-bot test outerloop linux x64 debug build
@dotnet-bot test outerloop windows x64 debug build
@dotnet-bot test outerloop osx x64 debug build

File: src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs [hunk 2]
```diff
@@ -436,6 +442,35 @@ private void ProcessSettingsFrame(FrameHeader frameHeader)
...
+        {
+            Debug.Assert(newSize >= 0);
+
+            lock (_syncObject)
+            {
+                int delta = newSize - _initialWindowSize;
+                _initialWindowSize = newSize;
+
+                // Adjust existing streams
+                foreach (Http2Stream http2Stream in _httpStreams.Values)
```
Comment (stephentoub) [inline src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs]: Consider instead foreach'ing over _httpStreams and then access the resulting pair's .Value.  That will be allocation free, whereas this will force the dictionary's Values collection to be instantiated.

File: src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs [hunk 3]
```diff
@@ -436,6 +442,35 @@ private void ProcessSettingsFrame(FrameHeader frameHeader)
...
+                {
+                    http2Stream.OnWindowUpdate(delta);
```
Comment (stephentoub) [inline src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs]: I assume there's no risk of OnWindowUpdate throwing and preventing some streams from receiving the new delta?

File: src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs [hunk 4]
```diff
@@ -742,12 +779,20 @@ private void WriteHeaders(HttpRequestMessage request)
             }
         }
 
-        private async ValueTask SendHeadersAsync(int streamId, HttpRequestMessage request)
+        private async ValueTask<Http2Stream> SendHeadersAsync(HttpRequestMessage request)
         {
+            // Ensure we don't exceed the max conurrent streams setting.
```
Comment (stephentoub) [inline src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs]: Nit: conurrent => concurrent

File: src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs [hunk 5]
```diff
@@ -785,11 +830,18 @@ private async ValueTask SendHeadersAsync(int streamId, HttpRequestMessage reques
                     await FlushOutgoingBytesAsync().ConfigureAwait(false);
                 }
             }
+            catch (Exception)
```
Comment (stephentoub) [inline src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs]: Nit: `catch (Exception)` => `catch`

File: src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs [hunk 6]
```diff
@@ -1053,22 +1107,51 @@ private enum SettingId : ushort
...
             }
-            catch (Exception)
+            catch (Exception e)
             {
-                http2Stream.Dispose();
-                throw;
+                if (http2Stream != null)
+                {
+                    http2Stream.Dispose();
+                }
```
Comment (stephentoub) [inline src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs]: Nit: `http2Stream?.Dispose();`

File: src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs [hunk 7]
```diff
@@ -22,121 +22,83 @@ sealed class Http2Stream : IDisposable
             private readonly int _streamId;
             private readonly object _syncObject;
 
+            private readonly TaskCompletionSource<bool> _responseHeadersAvailable;
```
Comment (stephentoub) [inline src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs]: Do we have an open issue around improving perf/allocations related to this TCS usage?  We should be able to switch now to using `ValueTask<T>` and `ManualResetValueTaskSourceCore<T>`.  We could also do that as part of a general perf push on the HTTP/2 support, which I assume we'll do once we're closer to being functionally complete.

File: src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs [hunk 8]
```diff
@@ -22,121 +22,83 @@ sealed class Http2Stream : IDisposable
...
 
                 _responseBuffer = new ArrayBuffer(InitialBufferSize);
 
-                _streamWindow = new CreditManager(InitialWindowSize);
+                _streamWindow = new CreditManager(initialWindowSize);
+
+                _responseHeadersAvailable = new TaskCompletionSource<bool>(TaskCreationOptions.RunContinuationsAsynchronously);
+
+                // TODO: ISSUE 31313: Avoid allocating a TaskCompletionSource repeatedly by using a resettable ValueTaskSource.
+                // See: https://github.com/dotnet/corefx/blob/master/src/Common/tests/System/Threading/Tasks/Sources/ManualResetValueTaskSource.cs
```
Comment (stephentoub) [inline src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs]: Ah, that answers my question :)

File: src/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.Http2.cs [hunk 9]
```diff
@@ -370,5 +506,222 @@ public async Task Http2_FlowControl_ClientDoesNotExceedWindows()
...
+
+                    bytesReceived += frame.Length;
+                }
+
+                Assert.Equal(DefaultInitialWindowSize, bytesReceived);
+
+                // Issue another read. It shouldn't complete yet. Wait a brief period of time to ensure it doesn't complete.
+                Task<Frame> readFrameTask = server.ReadFrameAsync(TimeSpan.FromSeconds(30));
+
+                await Task.Delay(500);
```
Comment (stephentoub) [inline src/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.Http2.cs]: What's the purpose of all of these Task.Delays?  If it's necessary for correctness, we should instead use synchronization between this and the loopback server to guarantee the needed ordering.  If it's for something else, what is that? :)  And if we must have these, the test should be made Outerloop.

File: src/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.Http2.cs [hunk 10]
```diff
@@ -370,5 +506,222 @@ public async Task Http2_FlowControl_ClientDoesNotExceedWindows()
...
+                Assert.Equal(FrameType.Settings, settingsAckFrame.Type);
+                Assert.Equal(FrameFlags.Ack, settingsAckFrame.Flags);
+
+                // Issue two more requests. We shouldn't send either of them.
+                sendTask = client.GetAsync(server.Address);
+                Task<HttpResponseMessage> sendTask2 = client.GetAsync(server.Address);
+
+                // Issue another read. It shouldn't complete yet. Wait a brief period of time to ensure it doesn't complete.
+                Task<Frame> readFrameTask = server.ReadFrameAsync(TimeSpan.FromSeconds(30));
+                await Task.Delay(500);
```
Comment (stephentoub) [inline src/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.Http2.cs]: Same question/comment.

File: src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs (hunk 3 above)
Comment (geoffkizer) [reply src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs]: OnWindowUpdate should never throw.

File: src/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.Http2.cs (hunk 9 above)
Comment (geoffkizer) [reply src/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.Http2.cs]: It's for correctness. We're trying to ensure that the client isn't sending frames when it's not supposed to. So the problem isn't synchronizing with the server, it's synchronizing with the client, and I don't see any better way to do that... thoughts?

I'm happy to move these to Outerloop.

Comment (stephentoub) [reply src/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.Http2.cs]: Ah, this is a "make sure that something we expect not to happen doesn't happen" test... yeah, those are notorious for needing timeouts, where in theory you want to do the equivalent of wait forever, but obviously can't, so pick some long-ish timeout that's effectively the same as "forever" for good-enough testing purposes.  Ok.  But yeah, please make it [Outerloop].

**Comment by geoffkizer** [comment]
@dotnet-bot test outerloop linux x64 debug build
@dotnet-bot test outerloop windows x64 debug build
@dotnet-bot test outerloop osx x64 debug build
