### PR TITLE
Fixing some of the tests throwing different expected exceptions

### LINKED ISSUE #4083: Socket ArgumentValidation test failures
See the discussion in https://github.com/dotnet/corefx/pull/4079#issuecomment-150347175.  I am disabling the failing tests in order to get changes from TFS in.

### PR DESCRIPTION
**Pull request by josguil**
A method CreateArraySegment for correctly throw
ArgumentOutOfRangeException instead of ArgumentException is added to fix
the Tests in ArgumentValidationTests.

Fix #4083

### CODE REVIEW

**Comment by josguil** [comment]
@CIPop  @davidsh @pgavlin 

These files were not correctly synced from Chris repo. I'm taking a second look to see if other files were affected, but it seems these were the only 2. It may have been that at the time of doing the git pull some program had a lock over those two files.

File: src/Common/src/System/Net/Sockets/SocketAPMExtensions.cs [hunk 1]
```diff
@@ -829,6 +829,24 @@ public static int EndSendTo(this Socket socket, IAsyncResult asyncResult)
...
+                throw new ArgumentNullException("buffer");
+            }
+
+            try
+            {
+                return new ArraySegment<byte>(buffer, offset, size);
+            }
+            catch (ArgumentException ae)
+            {
+                throw new ArgumentOutOfRangeException(ae.Message, ae);
```
Comment (stephentoub) [inline src/Common/src/System/Net/Sockets/SocketAPMExtensions.cs]: Can you help me to understand why we're doing this translation?  Is it that we used to throw ArgumentOutOfRange for this case, but the code was changed to use ArraySegment and its validation, and that validation is throwing a different exception type than we used to?  Seems like unfortunate additional overhead (e.g. the non-inlineable CreateArraySegment method, the try/catch block, etc.) for this, but I guess these methods are considered legacy and there's already so much overhead this will be a drop in the bucket.

File: src/Common/src/System/Net/Sockets/SocketAPMExtensions.cs [hunk 2]
```diff
@@ -829,6 +829,24 @@ public static int EndSendTo(this Socket socket, IAsyncResult asyncResult)
...
+            if (buffer == null)
+            {
+                throw new ArgumentNullException("buffer");
+            }
+
+            try
+            {
+                return new ArraySegment<byte>(buffer, offset, size);
+            }
+            catch (ArgumentException ae)
```
Comment (stephentoub) [inline src/Common/src/System/Net/Sockets/SocketAPMExtensions.cs]: ArgumentOutOfRangeException is an ArgumentException, so you could add a catch block before this that just propagates rather than creating a new exception, e.g.
```C#
catch (ArgumentOutOfRangeException)
{
    throw;
}
catch (ArgumentException ae)
{
    ...
}
```

**Comment by stephentoub** [comment]
A few comments, but LGTM.

File: src/Common/src/System/Net/Sockets/SocketAPMExtensions.cs (hunk 2 above)
Comment (davidsh) [inline src/Common/src/System/Net/Sockets/SocketAPMExtensions.cs]: +1

File: src/Common/src/System/Net/Sockets/SocketAPMExtensions.cs (hunk 1 above)
Comment (bartonjs) [inline src/Common/src/System/Net/Sockets/SocketAPMExtensions.cs]: You're losing the ParamName value in this translation.  It's a little unfortunate that you have to decide which is worse:
* Losing ParamName
* Discarding InnerException (which might have had more InnerException-ness)
* Rolling back the code to maintain exception parity
* Losing the ArgumentOutOfRangeException

Comment (stephentoub) [inline src/Common/src/System/Net/Sockets/SocketAPMExtensions.cs]: > You're losing the ParamName value in this translation

While technically true, at least with the current ArraySegment implementation, there is no param name supplied when it's creating an ArgumentException, which it only does when array.Length - offset < count.

File: src/Common/src/System/Net/Sockets/SocketAPMExtensions.cs (hunk 2 above)
Comment (stephentoub) [inline src/Common/src/System/Net/Sockets/SocketAPMExtensions.cs]: For that matter, the same thing could be done for the argumet null:
```C#
private static ArraySegment<byte> CreateArraySegment(byte[] buffer, int offset, int size)
{
    try
    {
        return new ArraySegment<byte>(buffer, offset, size);
    }
    catch (ArgumentNullException) { throw; }
    catch (ArgumentOutOfRangeException) { throw; }
    catch (ArgumentException ae)
    {
        throw new ArgumentOutOfRangeException(ae.Message, ae);
    }
}
```

**Comment by josguil** [comment]
Thanks for the comments.

It's exactly as @stephentoub said, we're doing this because with the new ArraySegment we are using to substitute the 3-tuple array, offset and count, we were getting a different behavior on type of error. For now now the best of the bad cases seems to be losing the ParamName.  

I added the feedback and submitted a new PR. I'll merge when the checks finish passing.

**Comment by CIPop** [comment]
@stephentoub 
> These files were not correctly synced from Chris repo. I'm taking a second look to see if other files were affected, but it seems these were the only 2. It may have been that at the time of doing the git pull some program had a lock over those two files.

We've investigated the issue and potentially found a root cause. Guillermo will start an offline thread on how to improve the internal process to avoid future issues.

File: src/Common/src/System/Net/Sockets/SocketAPMExtensions.cs [hunk 3]
```diff
@@ -829,6 +829,21 @@ public static int EndSendTo(this Socket socket, IAsyncResult asyncResult)
         {
             return TaskToApm.End<int>(asyncResult);
         }
+
+        // Behavior adapter.
+        private static ArraySegment<byte> CreateArraySegment(byte[] buffer, int offset, int size)
```
Comment (CIPop) [inline src/Common/src/System/Net/Sockets/SocketAPMExtensions.cs]: Missing a part:

``` C#

        // Behavior adapter.
        private static ArraySegment<byte> CreateArraySegment(byte[] buffer, int offset, int size)
        {
            if (buffer == null)
            {
                throw new ArgumentNullException("buffer");
            }

            try
            {
                return new ArraySegment<byte>(buffer, offset, size);
            }
            catch (ArgumentException ae)
            {
                throw new ArgumentOutOfRangeException(ae.Message, ae);
            }
        }
```

Comment (stephentoub) [inline src/Common/src/System/Net/Sockets/SocketAPMExtensions.cs]: @cipop, I'm not understanding the comment; can you elaborate on what's missing?

Comment (CIPop) [inline src/Common/src/System/Net/Sockets/SocketAPMExtensions.cs]: @stephentoub @josguil  Taking a second look, to correctly match the APM behavior, the code should actually be.
Please note that we're not trying to have the best performance for the adapter but existing code should work with small or little modification (except for cases where it was hard or impossible to achieve the old behavior, as outlined in the test changes).

```C#
            // Validate input parameters.
            if (buffer == null)
            {
                throw new ArgumentNullException("buffer");
            }
            if (offset < 0 || offset > buffer.Length)
            {
                throw new ArgumentOutOfRangeException("offset");
            }
            if (size < 0 || size > buffer.Length - offset)
            {
                throw new ArgumentOutOfRangeException("size");
            }

           return new ArraySegment<byte>(buffer, offset, size);
```

Comment (stephentoub) [inline src/Common/src/System/Net/Sockets/SocketAPMExtensions.cs]: Given the situation, I'm fine with redoing the checks like this.

**Comment by josguil** [comment]
I added Chris feedback.

File: src/Common/src/System/Net/Sockets/SocketAPMExtensions.cs [hunk 4]
```diff
@@ -829,6 +829,24 @@ public static int EndSendTo(this Socket socket, IAsyncResult asyncResult)
...
+            }
+            if (offset < 0 || offset > buffer.Length)
+            {
+                throw new ArgumentOutOfRangeException("offset");
+            }
+            if (size < 0 || size > buffer.Length - offset)
+            {
+                throw new ArgumentOutOfRangeException("size");
+            }
+            return new ArraySegment<byte>(buffer, offset, size);
```
Comment (CIPop) [inline src/Common/src/System/Net/Sockets/SocketAPMExtensions.cs]: Nit: new line after all }.

**Comment by CIPop** [comment]
LGTM

**Comment by pgavlin** [comment]
LGTM as well. Thanks for fixing this!
