### PR TITLE
Fixes relative path at configSource on linux

### LINKED ISSUE #29279: configSource with relative path does not work on Linux
I am using System.Configuration.ConfigurationManager 4.4.1 and have a configuration file which references external files as follows:

```xml
    <appSettings file="Config\appSettings.config>
    </appSettings>
    <connectionStrings configSource="Config\connectionStrings.config" />
```

I've tried running the application on both Windows and in a Linux docker container, and observed the following behavior.

1. On Windows, both external files are read successfully.
2. In a Linux docker container, the external appSettings file is read successfully
3. In a Linux docker container, when I attempt to access `System.Configuration.ConfigurationManager.ConnectionStrings` I get the following exception:

```
System.Configuration.ConfigurationErrorsException
  HResult=0x80131902
  Message=Unable to open configSource file 'Config\connectionStrings.config'. (/app/bin/Debug/netcoreapp2.0/DockerExample.dll.config line 6)
  Source=System.Configuration.ConfigurationManager
  StackTrace:
   at System.Configuration.BaseConfigurationRecord.EvaluateOne(String[] keys, SectionInput input, Boolean isTrusted, FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult)
   at System.Configuration.BaseConfigurationRecord.Evaluate(FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult, Boolean getLkg, Boolean getRuntimeObject, Object& result, Object& resultRuntimeObject)
... etc ...
```

I tried replacing the \ separator in the configuration file by a forward slash /, this being the default path separator on Linux.  This time I get the following exception.

```
System.Configuration.ConfigurationErrorsException
  HResult=0x80131902
  Message=Configuration system failed to initialize
  Source=System.Configuration.ConfigurationManager
  StackTrace:
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   at System.Configuration.ClientConfigurationSystem.PrepareClientConfigSystem(String sectionName)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.get_AppSettings()
```

Inner Exception 1:
```
ConfigurationErrorsException: The configSource attribute must be a relative physical path, so the '/' character is not allowed. (/app/bin/Debug/netcoreapp2.0/DockerExample.dll.config line 6)
... etc ...
```

This error message is nonsensical, as / or \ should be treated as being interchangeable.  The same error happens with the .NET Framework.

[EDIT] Add formatting by @karelz

### PR DESCRIPTION
**Pull request by jimdemis**
Allows `/` to be used to imitate `file` attribute behavior, but disallows non-relative paths.
Fixes #29279

Description:
On linux/osx `System.Configuration.ConfigurationManager` is unable to load config files using `configSource` when those files are located at subfolders.
For example the following works:
`<appSettings file="Config/appSettings.config">`
`<appSettings configSource="appSettings.config">`
But this does not:
`<appSettings configSource="Config/appSettings.config">`

The proposed fix is to allow `/` and check if the path is valid to allow config load.

/cc @maryamariyan, @safern

### CODE REVIEW

**Comment by maryamariyan** [comment]
@jimdemis Thanks for your PR.

In order to get more detail on the CI failures you can click on Details>Error link>Send To Helix Link>Then on mc.dot.net links containing results:

https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F37146~2Fmerge/test~2Ffunctional~2Fcli~2F/20190424.20/workItem/System.Configuration.ConfigurationManager.Tests

Shows a couple of inline data items failing for AppSettingsInvalidConfigSourcePath_Throws on Unix distros and AppSettingsCannotLoadFromConfigSource failing on almost all.

File: src/System.Configuration.ConfigurationManager/src/System/Configuration/BaseConfigurationRecord.cs [hunk 1]
```diff
@@ -3218,12 +3218,16 @@ internal static string NormalizeConfigSource(string configSource, IConfigErrorIn
             if (trimmedConfigSource.Length != configSource.Length)
                 throw new ConfigurationErrorsException(SR.Config_source_invalid_format, errorInfo);
 
-            if (configSource.IndexOf('/') != -1) // string.Contains(char) is .NetCore2.1+ specific
-                throw new ConfigurationErrorsException(SR.Config_source_invalid_chars, errorInfo);
-
             if (string.IsNullOrEmpty(configSource) || Path.IsPathRooted(configSource))
                 throw new ConfigurationErrorsException(SR.Config_source_invalid_format, errorInfo);
```
Comment (maryamariyan) [inline src/System.Configuration.ConfigurationManager/src/System/Configuration/BaseConfigurationRecord.cs]: Why did you move the condition below `if (string.IsNullOrEmpty(configSource) || Path.IsPathRooted(configSource))`

Comment (jimdemis) [reply src/System.Configuration.ConfigurationManager/src/System/Configuration/BaseConfigurationRecord.cs]: Matter of preference I suppose. I thought it will better to first check if `Path.IsPathRooted` and then `ConfigPathUtility.IsValid`. Do you want me to move it?

**Comment by maryamariyan** [comment]
LGTM, thanks.
@safern do you also approve?
