### PR TITLE
Load execution assembly for System.ServiceModel.Primitives.dll instead of reference assembly in Sgen

### LINKED ISSUE #32017: .NET Core Xml Serialization Generation Utility 2.0.0-rtm
Hello, 

I have a WCF client proxy that use XmlSerializer in a .NET Standard 2.0 project called SHB.FORI.IncaProxy and thought the tool would improve my startup time but the tool fail. The SHB.FORI.IncaProxy project contain classes like this:

 [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.itello.se/Inca/IncaWebServices/messages")]
    public partial class GetAccountingAccountBalance
    {
        
        private RequestInfo requestInfoField;
        
        private AccountingAccountBalance[] accountingAccountBalanceField;
        
        private Options optionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RequestInfo requestInfo
...

Generation of the serialization assembly fail:

1>------ Build started: Project: SHB.FORI.IncaProxy, Configuration: Debug Any CPU ------
1>SHB.FORI.IncaProxy -> C:\CCShare\snap\toso06_ss_hpfi\fori\csharpkod\Resource Access\SHB.FORI.IncaProxy\bin\Debug\netstandard2.0\SHB.FORI.IncaProxy.dll
1>[Microsoft (R) .NET Core Xml Serialization Generation Utility, Version 2.0.0-rtm]
1>Copyright (C) Microsoft Corporation. All rights reserved.
1>SGEN : warning SGEN1: Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.5.0.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
1>SGEN : warning SGEN1: Cannot load a reference assembly for execution.
1>A BadImageFormatException has been thrown while parsing the signature. This is likely due to lack of a generic context. Ensure genericTypeArguments and genericMethodArguments are provided and contain enough context.
1>Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.5.0.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
1>Cannot load a reference assembly for execution.
1>C:\Users\TOSO06\.nuget\packages\microsoft.xmlserializer.generator\2.0.0\build\Microsoft.XmlSerializer.Generator.targets(15,5): warning MSB3073: The command "dotnet Microsoft.XmlSerializer.Generator "obj\Debug\netstandard2.0\SHB.FORI.IncaProxy.dll" --force --quiet --reference "C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\netstandard.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\Microsoft.Win32.Primitives.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.AppContext.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Collections.Concurrent.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Collections.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Collections.NonGeneric.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Collections.Specialized.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.ComponentModel.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.ComponentModel.EventBasedAsync.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.ComponentModel.Primitives.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.ComponentModel.TypeConverter.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Console.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Data.Common.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Diagnostics.Contracts.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Diagnostics.Debug.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Diagnostics.FileVersionInfo.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Diagnostics.Process.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Diagnostics.StackTrace.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Diagnostics.TextWriterTraceListener.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Diagnostics.Tools.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Diagnostics.TraceSource.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Diagnostics.Tracing.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Drawing.Primitives.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Dynamic.Runtime.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Globalization.Calendars.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Globalization.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Globalization.Extensions.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.IO.Compression.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.IO.Compression.ZipFile.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.IO.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.IO.FileSystem.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.IO.FileSystem.DriveInfo.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.IO.FileSystem.Primitives.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.IO.FileSystem.Watcher.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.IO.IsolatedStorage.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.IO.MemoryMappedFiles.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.IO.Pipes.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.IO.UnmanagedMemoryStream.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Linq.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Linq.Expressions.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Linq.Parallel.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Linq.Queryable.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Net.Http.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Net.NameResolution.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Net.NetworkInformation.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Net.Ping.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Net.Primitives.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Net.Requests.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Net.Security.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Net.Sockets.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Net.WebHeaderCollection.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Net.WebSockets.Client.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Net.WebSockets.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.ObjectModel.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Reflection.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Reflection.Extensions.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Reflection.Primitives.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Resources.Reader.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Resources.ResourceManager.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Resources.Writer.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Runtime.CompilerServices.VisualC.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Runtime.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Runtime.Extensions.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Runtime.Handles.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Runtime.InteropServices.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Runtime.InteropServices.RuntimeInformation.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Runtime.Numerics.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Runtime.Serialization.Formatters.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Runtime.Serialization.Json.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Runtime.Serialization.Primitives.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Runtime.Serialization.Xml.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Security.Claims.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Security.Cryptography.Algorithms.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Security.Cryptography.Csp.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Security.Cryptography.Encoding.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Security.Cryptography.Primitives.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Security.Cryptography.X509Certificates.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Security.Principal.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Security.SecureString.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Text.Encoding.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Text.Encoding.Extensions.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Text.RegularExpressions.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Threading.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Threading.Overlapped.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Threading.Tasks.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Threading.Tasks.Parallel.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Threading.Thread.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Threading.ThreadPool.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Threading.Timer.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.ValueTuple.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Xml.ReaderWriter.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Xml.XDocument.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Xml.XmlDocument.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Xml.XmlSerializer.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Xml.XPath.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Xml.XPath.XDocument.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\mscorlib.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.ComponentModel.Composition.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Core.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Data.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Drawing.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.IO.Compression.FileSystem.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Net.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Numerics.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Runtime.Serialization.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.ServiceModel.Web.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Transactions.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Web.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Windows.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Xml.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Xml.Linq.dll;C:\Users\TOSO06\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Xml.Serialization.dll;C:\Users\TOSO06\.nuget\packages\microsoft.xmlserializer.generator\2.0.0\lib\netstandard2.0\dotnet-Microsoft.XmlSerializer.Generator.dll;C:\Users\TOSO06\.nuget\packages\system.servicemodel.duplex\4.5.3\ref\netstandard2.0\System.ServiceModel.Duplex.dll;C:\Users\TOSO06\.nuget\packages\system.servicemodel.http\4.5.3\ref\netstandard2.0\System.ServiceModel.Http.dll;C:\Users\TOSO06\.nuget\packages\system.servicemodel.primitives\4.5.3\ref\netstandard2.0\System.ServiceModel.Primitives.dll;C:\Users\TOSO06\.nuget\packages\system.servicemodel.primitives\4.5.3\ref\netstandard2.0\System.ServiceModel.dll;C:\Users\TOSO06\.nuget\packages\system.servicemodel.security\4.5.3\ref\netstandard2.0\System.ServiceModel.Security.dll"" exited with code 1.
1>C:\Users\TOSO06\.nuget\packages\microsoft.xmlserializer.generator\2.0.0\build\Microsoft.XmlSerializer.Generator.targets(16,5): warning : SGEN: Fail to generate the serializer for SHB.FORI.IncaProxy.dll. Please follow the instructions at https://go.microsoft.com/fwlink/?linkid=858594 and try again.
1>Done building project "SHB.FORI.IncaProxy.csproj".
========== Build: 1 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========

### PR DESCRIPTION
**Pull request by yujayee**
Fixes #32017
@mconnew @huanwu @Lxiamail

### CODE REVIEW

File: src/Microsoft.XmlSerializer.Generator/src/Sgen.cs [hunk 1]
```diff
@@ -565,9 +565,14 @@ private static Assembly SgenAssemblyResolver(object source, ResolveEventArgs e)
                     return null;
                 }
 
-                if(s_referencedic.ContainsKey(assemblyname))
+                if (s_referencedic.ContainsKey(assemblyname))
                 {
                     string reference = s_referencedic[assemblyname];
+
+                    //for System.ServiceModel.Primitives, we need to load its execution assembly rather than reference assembly
+                    if (assemblyname.Equals("System.ServiceModel.Primitives"))
```
Comment (Lxiamail) [inline src/Microsoft.XmlSerializer.Generator/src/Sgen.cs]: What if there is third party assembly having the same name as System.ServiceModel.Primitives?

File: src/Microsoft.XmlSerializer.Generator/src/Sgen.cs [hunk 2]
```diff
@@ -565,9 +565,14 @@ private static Assembly SgenAssemblyResolver(object source, ResolveEventArgs e)
                     return null;
                 }
 
-                if(s_referencedic.ContainsKey(assemblyname))
+                if (s_referencedic.ContainsKey(assemblyname))
                 {
                     string reference = s_referencedic[assemblyname];
+
+                    //for System.ServiceModel.Primitives, we need to load its execution assembly rather than reference assembly
```
Comment (krwq) [inline src/Microsoft.XmlSerializer.Generator/src/Sgen.cs]: more common term for this is "runtime assembly"

File: src/Microsoft.XmlSerializer.Generator/src/Sgen.cs [hunk 3]
```diff
@@ -565,9 +565,14 @@ private static Assembly SgenAssemblyResolver(object source, ResolveEventArgs e)
                     return null;
                 }
 
-                if(s_referencedic.ContainsKey(assemblyname))
+                if (s_referencedic.ContainsKey(assemblyname))
```
Comment (krwq) [inline src/Microsoft.XmlSerializer.Generator/src/Sgen.cs]: I do not know much about the context when this is executed, but would it be possible that nuget has downloaded and added reference to the project? (or if runtime load is needed then perhaps at least some library nuget perhaps provides)

File: src/Microsoft.XmlSerializer.Generator/src/Sgen.cs (hunk 1 above)
Comment (krwq) [inline src/Microsoft.XmlSerializer.Generator/src/Sgen.cs]: who's providing this assembly name? couldn't they pass the path themselves? i.e. AssemblyName provides Codebase for that (see: https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assemblyname?view=netcore-2.1)

File: src/Microsoft.XmlSerializer.Generator/src/Sgen.cs (hunk 2 above)
Comment (AlexGhiondea) [inline src/Microsoft.XmlSerializer.Generator/src/Sgen.cs]: Do we understand why we were trying to load the reference assembly before?

File: src/Microsoft.XmlSerializer.Generator/src/Sgen.cs (hunk 1 above)
Comment (mconnew) [reply src/Microsoft.XmlSerializer.Generator/src/Sgen.cs]: I don't think this is a concern as it's understood that only framework libraries start with System. Even Microsoft will often release packages beginning with "Microsoft." to indicate that while it's created by Microsoft, it's not a core system library. Basically it's a reserved namespace by well understood convention. We only stuck with System for WCF because of the pre-existence of the code on .NET Framework and it would end up being a rename. Otherwise we likely wouldn't have used System as a prefix.

---
In reply to: [219902748](https://github.com/dotnet/corefx/pull/32403#discussion_r219902748) [](ancestors = 219902748)

File: src/Microsoft.XmlSerializer.Generator/src/Sgen.cs (hunk 2 above)
Comment (mconnew) [reply src/Microsoft.XmlSerializer.Generator/src/Sgen.cs]: Yes. We need to reflect over the developers classes to generate the code for the serializer. A serializer needed for a WCF service needs to examine attributes which are defined in S.SM.Primitives. The reflection API's for attributes cause the attribute to be instantiated which means we can't load the reference assembly. For the rest of the data types referenced, a reference assembly is sufficient as there's no instantiation required.

---
In reply to: [220660138](https://github.com/dotnet/corefx/pull/32403#discussion_r220660138) [](ancestors = 220660138)

File: src/Microsoft.XmlSerializer.Generator/src/Sgen.cs (hunk 1 above)
Comment (mconnew) [reply src/Microsoft.XmlSerializer.Generator/src/Sgen.cs]: This code is a custom Assembly resolver, the whole point is that the CLR needs to load the assembly and it doesn't know where to find it. If it did know where to find it, it wouldn't be calling this event handler. So the AssemblyName is coming from the CLR coming across a type which lives in that assembly. In other words, the IL in an assembly references a type and says what assembly that type was found in at compile time and the CLR can't find it so is asking our handler.

---
In reply to: [220474266](https://github.com/dotnet/corefx/pull/32403#discussion_r220474266) [](ancestors = 220474266)
