### PR TITLE
Fix and enable Globalization tests that differ based on OS and culture

### LINKED ISSUE #3243: Some tests failing due to changes in Globalization data
We need to pay down some test debt here.  There are a lot of places where we hard code expected values for tests which can change depending on the underlying OS which provides the data.

We should figure out the right way to detect what OS we are on so we can provide the correct expected data.

### PR DESCRIPTION
**Pull request by eerhardt**
There were a few tests that were disabled and/or had TODO comments in them to clean their handling of culture and OS differences.  I've cleaned them up following the established pattern in other tests.

Fix #3243

@ellismg @tarekgh

### CODE REVIEW

File: src/System.Globalization/tests/DateTimeFormatInfo/DateTimeFormatInfoData.cs [hunk 1]
```diff
@@ -41,11 +44,144 @@ public static string GetAbbreviatedEraName(CultureInfo cultureInfo)
...
+                osvi.dwOSVersionInfoSize = (uint)Marshal.SizeOf(osvi);
+                Assert.Equal(0, RtlGetVersion(out osvi));
+                return (int)osvi.dwMajorVersion;
+            }
+
+            return -1;
+        }
+
+        [DllImport("ntdll.dll")]
+        private static extern int RtlGetVersion(out RTL_OSVERSIONINFOEX lpVersionInformation);
```
Comment (tarekgh) [inline src/System.Globalization/tests/DateTimeFormatInfo/DateTimeFormatInfoData.cs]: I think this API intended to be kernel mode and it is not nice to call it from the user mode even if it is working. I would suggest you use IsWindowsVersionOrGreater instead

**Comment by tarekgh** [comment]
beside my comment, everything else LGTM

File: src/System.Globalization/tests/DateTimeFormatInfo/DateTimeFormatInfoData.cs (hunk 1 above)
Comment (eerhardt) [inline src/System.Globalization/tests/DateTimeFormatInfo/DateTimeFormatInfoData.cs]: This is the function that the new OSDescription API is going to use, according to https://github.com/dotnet/corefx/pull/4334. 

If the function will work for the product, then it should be OK to call in the tests, right?

Comment (tarekgh) [inline src/System.Globalization/tests/DateTimeFormatInfo/DateTimeFormatInfoData.cs]: Interesting. I didn't know that. I am fine then.

File: src/System.Globalization/tests/DateTimeFormatInfo/DateTimeFormatInfoCalendarWeekRule.cs [hunk 2]
```diff
@@ -45,33 +45,18 @@ public void TestInvalidValue()
...
-        }
-
-        // TestLocaleFirstFourDayWeek: Verify value of property CalendarWeekRule for specific locale
-        [Fact]
-        public void TestLocaleFirstFourDayWeek()
+        // Verify value of property CalendarWeekRule for specific locales
+        [Theory]
+        [InlineData("en-US")]
+        [InlineData("br-FR")]
+        public void TestLocale(string localeName)
```
Comment (bartonjs) [inline src/System.Globalization/tests/DateTimeFormatInfo/DateTimeFormatInfoCalendarWeekRule.cs]: While I appreciate the complexities of br-FR's calendar rule, I'm wondering if we couldn't help clarity by having some more fixed points called out in something like

```C#
[Theory]
[InlineData("en-US", CalendarWeekRule.FirstDay)]
[InlineData("fr-FR", CalendarWeekRule.SomeConst)]
[InlineData("ja-JP", CalendarWeekRule.SomeConst)]
public void VerifyCalendarWeekRule(string localeName, CalendarWeekRule expected)
{
...
```

just so that we can get breadth-at-a-glance.

Then have br-FR and maybe a couple other complex cases in another test method group.

File: src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs [hunk 3]
```diff
@@ -0,0 +1,85 @@
...
+
+                throw DateTimeFormatInfoData.GetCultureNotSupportedException(cultureInfo);
+            }
+            else
+            {
+                return "-\u221E";
+            }
+        }
+
+        internal static int[] GetCurrencyNegativePatterns(CultureInfo cultureInfo)
```
Comment (bartonjs) [inline src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs]: None of the values returns more than one element... why is this returning an array?

If it's for future expansion, can you try to find one that needs it now?

File: src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoNumberGroupSizes.cs [hunk 4]
```diff
@@ -67,21 +67,15 @@ public void NegTest3()
 
         // TestNumberGroupSizesLocale: Verify value of property NumberGroupSizes for specific locales
         [Theory]
-        [InlineData("en-US", 3, 0)]
-        [InlineData("ur-IN", 3, 2)]
-        [ActiveIssue(3243)]
-        public void TestNumberGroupSizesLocale(string locale, int primaryGroupSize, int secondaryGroupSize)
+        [InlineData("en-US")]
+        [InlineData("ur-IN")]
+        public void TestNumberGroupSizesLocale(string locale)
```
Comment (bartonjs) [inline src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoNumberGroupSizes.cs]: I liked this better the other way, since it showed at a glance why these two cultures are both good test cases.

File: src/System.Globalization/tests/DateTimeFormatInfo/DateTimeFormatInfoCalendarWeekRule.cs (hunk 2 above)
Comment (eerhardt) [inline src/System.Globalization/tests/DateTimeFormatInfo/DateTimeFormatInfoCalendarWeekRule.cs]: @steveharter added this test, so he can comment as he wants.

IMO, adding more cultures won't really help increase the coverage since we are getting this data from ICU. We just need to test that we are getting the values correctly from ICU. Also, adding more cultures increases the chance that we will get conflicting values between all the differing systems we are testing on.

I think the two cultures are sufficient for testing coverage, so the question becomes, should I split the test back out into 2 separate Facts instead of using a Theory.

File: src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs (hunk 3 above)
Comment (eerhardt) [inline src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs]: It was for future expansion - the CentOS support - which is what I was working on today getting a machine setup.  I've pushed a new change that needs this to be an array.

File: src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoNumberGroupSizes.cs (hunk 4 above)
Comment (eerhardt) [inline src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoNumberGroupSizes.cs]: It isn't possible to have differing InlineData between Windows8.1 and Windows10 (which is causing problems with the ur-IN culture).  And so we have to do runtime checks in the test code.  And once you do that, then [@tarekgh's comment](https://github.com/ellismg/corefx/pull/6#discussion-diff-39179342) comes in to play where we pull all the "differing data" into a centralized place instead of having "if (s_isWindows)" everywhere in the test code.

Comment (bartonjs) [inline src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoNumberGroupSizes.cs]: Ah, I missed that ur-IN had OS-variant data.  My comments were about making sure that we can see that different types of things are being decoded from ICU/Windows correctly. (Asymmetric number groups, an example of each kind of calendar week rule, etc).  Then the OS-variant ones are just about compat verification.

Comment (eerhardt) [inline src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoNumberGroupSizes.cs]: I'm not certain it will be possible to ensure that we can find a set of cultures that meet the following requirements:
1. They cover the different types of things being decoded (i.e. an example of each kind of calendar week rule)
2. Their culture data doesn't differ between the 5 different sets of culture data we currently support.
3. They aren't going to differ in a set of culture data we will support in the future.

Given this, I don't feel it is worth it to try to find a set of cultures that meet #1 and #2 now.  I think just finding #1 is good enough, and dealing with the differing culture data as appropriate.
