### PR TITLE
Extensions for immutable collection builders (#21055)

### LINKED ISSUE #21055: Proposal: Specialize IA.Builder.ToImmutableArray, IHS.Builder.ToImmutableHashSet
A while ago I was working on a project and whenever I wanted an `ImmutableArray` I would just call `ToImmutableArray()` on the enumerable. I got so used to doing this, in fact, that I did it for `ImmutableArray.Builder`s without realizing there was a `ToImmutable()` method for a long time.

## Update 8/13/17

Instead of making the new facades instance methods, they will be extension methods. Rationale is given in [this comment](https://github.com/dotnet/corefx/issues/21055#issuecomment-317918406).

```cs
public static class ImmutableArray
{
    public static ImmutableArray<T> ToImmutableArray<T>(this ImmutableArray<T>.Builder source);
}

public static class ImmutableDictionary
{
    public static ImmutableDictionary<TKey, TValue> ToImmutableDictionary<TKey, TValue>(this ImmutableDictionary<TKey, TValue>.Builder source);
}

public static class ImmutableHashSet
{
    public static ImmutableHashSet<T> ToImmutableHashSet<T>(this ImmutableHashSet<T>.Builder source);
}

public static class ImmutableList
{
    public static ImmutableList<T> ToImmutableList<T>(this ImmutableList<T>.Builder source);
}

public static class ImmutableSortedDictionary
{
    public static ImmutableSortedDictionary<TKey, TValue> ToImmutableSortedDictionary<TKey, TValue>(this ImmutableSortedDictionary<TKey, TValue>.Builder source);
}

public static class ImmutableSortedSet
{
    public static ImmutableSortedSet<T> ToImmutableSortedSet<T>(this ImmutableSortedSet<T>.Builder source);
}
```

## Update 6/16/17

We can add `IA<T>.Builder.ToIA()`, `IHS<T>.Builder.ToIHS()`, etc. instance methods that are simply wrappers for `ToImmutable()`, preventing people who make silly mistakes like me from degrading the performance of their app.

```cs
public struct ImmutableArray<T>
{
    public class Builder { public ImmutableArray<T> ToImmutableArray(); }
}

public class ImmutableHashSet<T>
{
    public class Builder { public ImmutableHashSet<T> ToImmutableHashSet(); }
}

// ...
```

## Original content

It might be a good idea to add `ToImmutableArray()` to `ImmutableArray.Builder` and mark it `[Obsolete]`, for the sake of enforcing consistency. Similar for all of the other builder types. The `[Obsolete]` should not have `error: true` because we don't want to break existing code, but it will advise the user to use `ToImmutable()`.

```cs
public struct ImmutableArray<T>
{
    public class Builder { [EditorBrowsable(Never)] [Obsolete("Use ToImmutable() instead.")] public ImmutableArray<T> ToImmutableArray(); }
}

public class ImmutableHashSet<T>
{
    public class Builder { [EditorBrowsable(Never)] [Obsolete("Use ToImmutable() instead.")] public ImmutableHashSet<T> ToImmutableHashSet(); }
}

// ...
```

/cc @AArnott, what do you think?

### PR DESCRIPTION
**Pull request by davidkaya**
Added extensions for immutable builders, which should be prefered over the extensions on IEnumerable because of performance benefits.

Fixes #21055.

### CODE REVIEW

**Comment by Wraith2** [comment]
No null checks?

File: src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray.cs [hunk 1]
```diff
@@ -395,6 +395,19 @@ public static ImmutableArray<TSource> ToImmutableArray<TSource>(this IEnumerable
             return CreateRange(items);
         }
 
+        /// <summary>
+        /// Returns an immutable copy of the current contents of the builder's collection.
+        /// </summary>
+        /// <param name="builder">The builder to create the immutable array from.</param>
+        /// <returns>An immutable array.</returns>
+        [Pure]
```
Comment (AArnott) [inline src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray.cs]: Given that `[Pure]` has no runtime impact, why isn't the attribute included in the ref assemblies so that analyzers can do their work based on it?

**Comment by AArnott** [comment]
Thanks for preparing this change. My only concern with this approach is what I just added to the discussion over [here](https://github.com/dotnet/corefx/issues/21055#issuecomment-411409273).

File: src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray.cs (hunk 1 above)
Comment (Wraith2) [reply src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray.cs]: Looking at it (and not the author) I'd guess that it's because none of the other definitions in the ref assembly have them and he followed the existing pattern on the assumption that someone in the past had good reason to do this.

Adding them in ref would require a dependency on `System.Diagnostics.Contracts` which would seem an odd thing to do.

Comment (AArnott) [reply src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray.cs]: Agreed: this PR itself looks consistent with precedent. So my question was perhaps more directed at the authors of the ref assemblies in general. @danmosemsft @csharpfritz perhaps?

**Comment by karelz** [comment]
@safern @ianhays is the PR ready for merge?

File: src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray.cs (hunk 1 above)
Comment (csharpfritz) [reply src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray.cs]: I think I was included incorrectly on this...

Comment (danmosemsft) [reply src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray.cs]: `[Pure]` is part of Contracts, right? We don't use or enforce those and generally have been removing contract annotations. I believe we discussed this before in the context of immutable collections in fact and @AArnott did you indicate you didn't believe in them either? In which case I guess these can all be removed unless they are somehow still useful to .NET Framework consumers even though they're not on the ref assembly and probably not consistent either.

Comment (AArnott) [reply src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray.cs]: @danmosemsft  I think `PureAttribute` preceded Code Contracts. And ya, I don't use Code Contracts at all any more nor hear of anyone else using them.
But `[Pure]` is useful because one can write analyzers that will flag a warning when a `[Pure]` method is executed without doing anything with the result. Particularly on the immutable collections that's relevant since someone may simply right:

```cs
set.Add(a);
```

And be confused when `set` doesn't contain `a`. But if `Add` were decorated with `[Pure]` an analyzer could say "hey, aren't you supposed to do something with the return value?" which would guide the user to fixing it to be: `set = set.Add(a);`.

So I am in favor of correctly applying `[Pure]` in many places, *especially* ref assemblies since that's what analyzers would have visibility into.

Comment (safern) [reply src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray.cs]: From a quick search we don't have any `[Pure]` attributes in ref contracts so far in corefx - but we do have it in several places in collections: https://github.com/dotnet/corefx/search?p=3&q=Pure&unscoped_q=Pure

So it doesn't seem we use them at all, or enforce them to be applied in the ref contracts.

Comment (AArnott) [reply src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray.cs]: I suspect .NET doesn't define many pure methods anyway (regardless whether they are tagged as `[Pure]`). Immutable types are a relatively new area and the collections are a significant step in that direction, so I'd love to see this attribute thoroughly applied to that library, at least. Would you accept a PR? 
Maybe I'd even combine it with an analyzer assembly that the immutable collections package depends on that will scan for Pure calls as I mentioned.

Comment (danmosemsft) [reply src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray.cs]: Would it go on eg `String.Replace`, etc? 

@jkotas is this something we want to start doing? It seems to me we likely want an analyzer proving it adds value first. @jaredpar is this something that CSC might start using (eg built in analyzer to spot dropped return codes)

Comment (jkotas) [reply src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray.cs]: > It seems to me we likely want an analyzer proving it adds value first. 

Right. Based on the past experiments with Code Contracts, it is very hard to get a return on investment with this. The annotations do catch a few bugs, but they require a prohibitive amount of manual work to do that.

Comment (AArnott) [reply src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray.cs]: > Based on the past experiments with Code Contracts, it is very hard to get a return on investment with this.

Code Contracts preceded roslyn analyzers, and required custom build steps, VS extensions, and/or post-compilation IL-rewriting . Roslyn analyzers are proven to be effective and popular. Let's not let Code Contracts' failure deter us from tapping Analyzers for solving this simple issue.

**Comment by safern** [comment]
@davidkaya would you mind fixing the merge conflicts?

**Comment by davidkaya** [comment]
@safern Should be fine now.

**Comment by safern** [comment]
> @safern Should be fine now.

Thanks.

File: src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray.cs (hunk 1 above)
Comment (Grauenwolf) [reply src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray.cs]: The Pure attribute is checked by Rule CA1806 in Microsoft.CodeQuality.Analyzers.

Comment (AArnott) [reply src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray.cs]: Thanks for redrawing attention to this, @Grauenwolf. I've filed a separate issue to track the issue: https://github.com/dotnet/corefx/issues/34778
