### PR TITLE
WMI: make DMTF and DateTime match netfx behavior

### LINKED ISSUE #29712: System.Management.ManagementDateTimeConverter fail parsing on DateTime.MinValue
The conversion from DateTime to Dmtf works fine even with DateTime.MinValue but if we parse the value back ( in my case "00010101000000.000000+060") it raise:

System.ArgumentOutOfRangeException: 'The added or subtracted value results in an un-representable DateTime.'

Step to reproduce the bug:

            var date = ManagementDateTimeConverter.ToDmtfDateTime(DateTime.MinValue);
            var parsed = ManagementDateTimeConverter.ToDateTime(date);

### PR DESCRIPTION
**Pull request by pjanotti**
Fixes #29712 the idea here is to match netfx behavior for ManagementDateTimeConverter. A prior PR (#27683) introduced some slight differences: 

* Started to return a DateTime of Kind Local while netfx returns Unspecified
* Switched ToDateTime from TimeZone to TimeZoneInfo but didn't do the same for the symmetrical ToDmtfDateTime (TimeZoneInfo is the correct one, so this change does the same for TimeZoneInfo)
* Delegated part of the calculation of the offset to ToLocalTime, while this is preferable in general, it can cause out-of-range for values near DateTime.MinValue depending on the current time zone.

### CODE REVIEW

File: src/System.Management/src/System/Management/ManagementDateTime.cs [hunk 1]
```diff
@@ -195,16 +195,13 @@ public static DateTime ToDateTime(string dmtfDate)
...
-            // Construct a new System.DateTime object
-            var datetime = new DateTime(year, month, day, hour, minute, second, 0, DateTimeKind.Utc);
+            // Construct a new System.DateTime object, netfx uses date kind unspecified so use the same
+            var datetime = new DateTime(year, month, day, hour, minute, second, 0, DateTimeKind.Unspecified);
             // Then add the ticks calculated from the microseconds
             datetime = datetime.AddTicks(ticks);
-            // Then subtruct offset in minutes
-            datetime = datetime.AddMinutes(-utcOffset);
+            // Then adjust the offset, using a manual calulation to keep the same possible range as netfx
+            datetime = datetime.AddMinutes(-(utcOffset - TimeZoneInfo.Local.GetUtcOffset(datetime).Ticks / TimeSpan.TicksPerMinute));
```
Comment (pjanotti) [inline src/System.Management/src/System/Management/ManagementDateTime.cs]: @tarekgh in the end I had to go back to the manual calculation since in the typical case of same time zone this can lead to out-of-range for values near DateTime.MinValue (granted that this is a corner case, but anyway then we succeed in the same cases as netfx).

Comment (tarekgh) [reply src/System.Management/src/System/Management/ManagementDateTime.cs]: I am wondering why this happened. your calculations should produce the same result as ToLocalTime(). do you have some example of such case?

Comment (pjanotti) [reply src/System.Management/src/System/Management/ManagementDateTime.cs]: The issue is with values near DateTime.MinValue, if we AddMinutes(-utcOffset) from a time zone ahead of UTC then we can get an out-of-range error before we can call ToLocalTime to make the proper adjustment. The test added is an example of that, without the manual calculation, it will fail depending on the time zone.

**Comment by pjanotti** [comment]
Test failures are not related to this change.
