### PR TITLE
Fix output buffer assumptions in CSP symmetric transforms.

### LINKED ISSUE #23311: Array bounds error with CryptoStream.Write using DESCryptoServiceProvider
We have a simple text decryption function that uses classes in System.Security.Cryptography that works fine when targeting the full framework but throws an ArgumentException `Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.` on the `CryptoStream.Write` method.

Here is the full extent of a console app recreating the error:

```c#
using System;
using System.IO;
using System.Security.Cryptography;
using System.Text;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var textToDecrypt = "oZYdrxMbPKav5xewuT1PUw=="; // an encrypted form of "test string 1"
            var key = "Test Encryption Key";

            byte[] initializationVector = {
                0x12,
                0x34,
                0x56,
                0x78,
                0x90,
                0xab,
                0xcd,
                0xef
            };

            byte[] byKey = Encoding.UTF8.GetBytes(key.Substring(0, 8));
            DESCryptoServiceProvider des = new DESCryptoServiceProvider();
            inputByteArray = Convert.FromBase64String(textToDecrypt);
            MemoryStream ms = new MemoryStream();
            CryptoStream cs = new CryptoStream(ms, des.CreateDecryptor(byKey, initializationVector), CryptoStreamMode.Write);
            cs.Write(inputByteArray, 0, inputByteArray.Length); // <---  ERROR IS THROWN HERE
            cs.FlushFinalBlock();
            Encoding encoding = Encoding.UTF8;
            Console.WriteLine(encoding.GetString(ms.ToArray())); // <--- Expected to see "test string 1" in the console.
        }
    }
}
```

The inputByteArray contains 16 elements (0-15), the offset is 0 and the length is 16.  Not sure why I would get an index error here.

Here is the stack trace from the error:

```
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at Internal.NativeCrypto.CapiHelper.DecryptData(SafeKeyHandle hKey, Byte[] input, Int32 inputOffset, Int32 inputCount, Byte[] output, Int32 outputOffset, Int32 outputCount)
   at Internal.Cryptography.BasicSymmetricCipherCsp.Transform(Byte[] input, Int32 inputOffset, Int32 count, Byte[] output, Int32 outputOffset, Boolean isFinal)
   at Internal.Cryptography.BasicSymmetricCipherCsp.Transform(Byte[] input, Int32 inputOffset, Int32 count, Byte[] output, Int32 outputOffset)
   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount, Byte[] outputBuffer, Int32 outputOffset)
   at Internal.Cryptography.UniversalCryptoTransform.TransformBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount, Byte[] outputBuffer, Int32 outputOffset)
   at System.Security.Cryptography.CryptoStream.<WriteAsyncCore>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Security.Cryptography.CryptoStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\dslinn\Desktop\ConsoleApp1\ConsoleApp1\Program.cs:line 32
```

[EDIT] Add C# syntax highlight by @karelz

### PR DESCRIPTION
**Pull request by bartonjs**
The CAPI DecryptData and EncryptData methods made assumptions about the
calling patterns, in particular that the output buffer would be perfectly sized for
the desired output.

This change adds tests which violate those assumptions, but work on netfx and
with the corefx CNG implementation. Then follows up on making the tests pass.

Fixes #23311.

### CODE REVIEW

**Comment by ericstj** [comment]
test UWP CoreCLR x64 Debug Build 
https://github.com/dotnet/corefx/issues/23614

**Comment by bartonjs** [comment]
Looks like NetFX did some things slightly differently.

AESCryptoServiceProvider:

> 11:40:59       System.Security.Cryptography.Encryption.Aes.Tests.AesCipherTests.TransformWithTooShortOutputBuffer(encrypt: False, blockAlignedOutput: True) [FAIL]
11:40:59         System.Security.Cryptography.CryptographicException : Decrypting a value requires that a key be set on the algorithm object.

TripleDESCryptoServiceProvider:

> 11:40:59       System.Security.Cryptography.Encryption.TripleDes.Tests.TripleDESCipherTests.TransformWithTooShortOutputBuffer(encrypt: True, blockAlignedOutput: True) [FAIL]
11:40:59         Assert.Throws() Failure
11:40:59         Expected: typeof(System.ArgumentOutOfRangeException)
11:40:59         Actual:   typeof(System.Security.Cryptography.CryptographicException): Bad Data.

File: src/Common/tests/System/Security/Cryptography/AlgorithmImplementations/AES/AesCipherTests.cs [hunk 1]
```diff
@@ -629,5 +630,83 @@ private static byte[] AesDecryptDirectKey(Aes aes, byte[] key, byte[] iv, byte[]
...
+                Assert.Equal(new byte[output.Length], output);
+            }
+        }
+
+        [Theory]
+        [InlineData(true)]
+        [InlineData(false)]
+        public static void MultipleBlockDecryptTransform(bool blockAlignedOutput)
+        {
+            const string expectedOutput = "This is a 128-bit block test";
```
Comment (stephentoub) [inline src/Common/tests/System/Security/Cryptography/AlgorithmImplementations/AES/AesCipherTests.cs]: Nit: ExpectedOutput

File: src/Common/tests/System/Security/Cryptography/AlgorithmImplementations/TripleDES/TripleDESCipherTests.cs [hunk 2]
```diff
@@ -288,5 +289,83 @@ public static void TripleDESRoundTripPKCS7CBC(int keySize, string expectedCipher
...
+                Assert.Equal(new byte[output.Length], output);
+            }
+        }
+
+        [Theory]
+        [InlineData(true)]
+        [InlineData(false)]
+        public static void MultipleBlockDecryptTransform(bool blockAlignedOutput)
+        {
+            const string expectedOutput = "This is a test";
```
Comment (stephentoub) [inline src/Common/tests/System/Security/Cryptography/AlgorithmImplementations/TripleDES/TripleDESCipherTests.cs]: Nit: same nit

**Comment by bartonjs** [comment]
Now that OSX and Linux have finished clean I'll make the changes to make NetFx pass.  I've done Windows locally, so feel pretty good about that one :smile:.

**Comment by ericstj** [comment]
Test UWP CoreCLR x64 Debug Build
