### PR TITLE
SocketException improvements

### LINKED ISSUE #7853: Decide whether InternalSocketException from Socket.Connect is an acceptable behavioral difference
From the TODO in DnsEndPointTest.cs:

```
                // TODO: Behavior difference from .Net Desktop. This will actually throw InternalSocketException.
                SocketException ex = Assert.ThrowsAny<SocketException>(() =>
                {
                    sock.Connect(new DnsEndPoint("notahostname.invalid.corp.microsoft.com", UnusedPort));
                });
```

### LINKED ISSUE #7873: Expose SocketException(int, EndPoint) to maintain exception Message compatibility.
From the TODO in SocketExceptionFactory.cs:

```csharp
        public static SocketException CreateSocketException(int socketError, EndPoint endPoint)
        {
            // TODO: expose SocketException(int, EndPoint) to maintain exception Message compatibility.
            return new SocketException(socketError);
        }
```

### PR DESCRIPTION
**Pull request by ericeil**
- Move all instantiation of InternalSocketException into SocketExceptionFactory.  Rename InternalSocketException to ExtendedSocketException, and encapsulate it in SocketExceptionFactory to prevent a proliferation of dependencies on this type.

- Add support for adding an EndPoint to the exception message in ExtendedSocketException (fixes #7873).

- Remove the TODOs around #7853.  I don't believe it's worth complicating the public contracts just in case someone does an exact type equality comparison on a SocketException.  (Fixes #7853)

### CODE REVIEW

**Comment by ericeil** [comment]
@stephentoub @CIPop

File: src/Common/src/System/Net/Internals/SocketExceptionFactory.cs [hunk 1]
```diff
@@ -6,12 +6,41 @@
 
 namespace System.Net.Internals
 {
-    internal class SocketExceptionFactory
+    internal static partial class SocketExceptionFactory
     {
+        private class ExtendedSocketException : SocketException
```
Comment (justinvp) [inline src/Common/src/System/Net/Internals/SocketExceptionFactory.cs]: Nit: `sealed`?

File: src/Common/src/System/Net/Internals/SocketExceptionFactory.cs [hunk 2]
```diff
@@ -6,12 +6,41 @@
...
+                get
+                {
+                    if (_endPoint != null)
+                    {
+                        return base.Message + " " + _endPoint.ToString();
+                    }
+
+                    return base.Message;
+                }
+            }
```
Comment (justinvp) [inline src/Common/src/System/Net/Internals/SocketExceptionFactory.cs]: Nit: This could be simplified, e.g.:

```csharp
public override string Message
{
    get
    {
        return _endPoint != null ?
            base.Message + " " + _endPoint.ToString() :
            base.Message;
    }
}
```

Or even more with an expression-bodied member, e.g.:

```csharp
public override string Message => _endPoint != null ?
    base.Message + " " + _endPoint.ToString() :
    base.Message;
```

File: src/System.Net.NameResolution/src/System/Net/DNS.cs [hunk 3]
```diff
@@ -112,8 +112,11 @@ internal static IPHostEntry InternalGetHostByAddress(IPAddress address, bool inc
 
                     if (NetEventSource.Log.IsEnabled())
                     {
-                        NetEventSource.Exception(NetEventSource.ComponentType.Socket, "DNS",
-                        "InternalGetHostByAddress", new InternalSocketException(errorCode, nativeErrorCode));
+                        NetEventSource.Exception(
+                            NetEventSource.ComponentType.Socket, 
+                            "DNS",
+                            "InternalGetHostByAddress",
```
Comment (stephentoub) [inline src/System.Net.NameResolution/src/System/Net/DNS.cs]: Nit: As long as you're changing things here, you could use nameof to avoid the hardcoded strings.

**Comment by stephentoub** [comment]
LGTM

**Comment by stephentoub** [comment]
Test Innerloop Ubuntu14.04 Debug Build and Test  please

File: src/Common/src/System/Net/Internals/SocketExceptionFactory.cs [hunk 4]
```diff
@@ -6,12 +6,41 @@
...
+                HResult = platformError;
+            }
+
+            public override string Message
+            {
+                get
+                {
+                    if (_endPoint != null)
+                    {
+                        return base.Message + " " + _endPoint.ToString();
```
Comment (CIPop) [inline src/Common/src/System/Net/Internals/SocketExceptionFactory.cs]: This seems to create a different message compared with the original. Apps that took dependencies on the messages will have issues with this change.
I propose leaving this as is and changing it only if there are app-compat issues with apps that are getting ported..

Comment (CIPop) [inline src/Common/src/System/Net/Internals/SocketExceptionFactory.cs]: Never-mind: I was only reviewing by looking at the CoreFX code. This is identical to Desktop.

**Comment by CIPop** [comment]
LGTM

File: src/System.Net.NameResolution/src/System/Net/DNS.cs (hunk 3 above)
Comment (ericeil) [inline src/System.Net.NameResolution/src/System/Net/DNS.cs]: I could do that for "InternalGetHostByAddress", but not for "DNS", which would change casing to "Dns".  That might be OK, but I'd rather not fold that into this change.

File: src/Common/src/System/Net/Internals/SocketExceptionFactory.cs (hunk 1 above)
Comment (ericeil) [inline src/Common/src/System/Net/Internals/SocketExceptionFactory.cs]: Done.

File: src/Common/src/System/Net/Internals/SocketExceptionFactory.cs (hunk 2 above)
Comment (ericeil) [inline src/Common/src/System/Net/Internals/SocketExceptionFactory.cs]: Good idea.  Done.
