### PR TITLE
Reduce memory allocations on read performance counters.

### LINKED ISSUE #31639: PerformanceCounter.NextValue() generates memory allocations
`PerformanceCounter.NextValue()` generates memory allocations.
OS: Windows

To reproduce:
```c#
var counter = new PerformanceCounter(".NET CLR Memory", "Allocated Bytes/sec", instance);

while (true)
{
       var current = counter.NextValue();
       var gc0 = GC.CollectionCount(0); //Grows endlessly (not on every iteration, but grows)

       Console.WriteLine($"Allocated bytes/sec: {current:0}, GC0 count: {gc0}");
       Thread.Sleep(500);
 }
```

Windows implementation of `PerformanceCounter` uses method `object RegistryKey.GetValue(string name)`  which is internally [allocate at least ~64Kb on every call](https://github.com/dotnet/corefx/blob/b492409b4a1952cda4b078f800499d382e1765fc/src/Microsoft.Win32.Registry/src/Microsoft/Win32/RegistryKey.Windows.cs#L557)

I expect that `PerformanceCounter.NextValue()` will not generate memory allocations on each call. It is significant if we ask about next value several performance counters  (100, 200, etc).

### PR DESCRIPTION
**Pull request by MaxShoshin**
Fixes #31639 

I've created own internal wrapper to read data from registry (simplified copy from `Microsoft.Win32.Registry`). 

This wrapper is used to read performance data to `byte[]` rented from `ArrayPool`. 

For correctly release the byte array `CategorySample` (internal) class is now `IDisposable`.

### CODE REVIEW

**Comment by Wraith2** [comment]
If CategorySample is only used internally and never passed as an argument (didn't see anywhere) it might reduce allocations to make it a struct. Do you have some DenchmarkDotNet summary for the memory improvement on these changes?

**Comment by danmosemsft** [comment]
Can we instead improve/augment the implementation of our registry API, rather than writing new code against native registry APIs?

**Comment by karelz** [comment]
@wtgodbe @krwq this fell off the radar. Can you please review it?

**Comment by wtgodbe** [comment]
@MaxShoshin do you have feelings on:

> Can we instead improve/augment the implementation of our registry API, rather than writing new code against native registry APIs?

**Comment by jkotas** [comment]
> Can we instead improve/augment the implementation of our registry API

This is a problem in the registry API public surface, not in the registry API implementation. This would require new public APIs in Microsoft.Win32.Registry.

**Comment by MaxShoshin** [comment]
> This would require new public APIs in Microsoft.Win32.Registry.

If we add something like `bool RegistryKey.TryReadBytes(byte[] buffer, out int? size)`:
This method should notify about these situation:
* Successfully read n-bytes in buffer. Returns true, size will contain count of read bytes.
* Not enough buffer length, need k -bytes buffer. It returns false, size will contain necessary buffer length)
* Not enough buffer length, don't know the buffer size (can be applicable in perf data). It will return false, size will be null.
* It will throws exceptions (as standard `RegistryKey.GetData` method).

I think it is rather complicated and contrintuitive method API. Do you have any ideas regarding this?

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs [hunk 1]
```diff
@@ -0,0 +1,119 @@
...
+        public static PerformanceDataRegistryKey OpenRemoteBaseKey(string machineName)
+        {
+            // // connect to the specified remote registry
+            SafeRegistryHandle foreignHKey = null;
+            int ret = Interop.Advapi32.RegConnectRegistry(machineName, new SafeRegistryHandle(new IntPtr(PerformanceData), false), out foreignHKey);
+
+            if (ret == Interop.Errors.ERROR_DLL_INIT_FAILED)
+            {
+                // return value indicates an error occurred
+                throw new ArgumentException(SR.Arg_DllInitFailure);
```
Comment (danmosemsft) [inline src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: maybe include machine name in the message?

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs [hunk 2]
```diff
@@ -0,0 +1,119 @@
...
+        private const int PerformanceData = unchecked((int)0x80000004);
+
+        private PerformanceDataRegistryKey(SafeRegistryHandle hkey)
+        {
+            _hkey = hkey;
+        }
+
+        public static PerformanceDataRegistryKey OpenRemoteBaseKey(string machineName)
+        {
+            // // connect to the specified remote registry
```
Comment (danmosemsft) [inline src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: nit, extra //

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs [hunk 3]
```diff
@@ -835,7 +836,7 @@ private CategorySample GetCategorySample(string category)
                 return null;
 
             CategorySample sample = null;
-            byte[] dataRef = GetPerformanceData(entry.NameIndex.ToString(CultureInfo.InvariantCulture));
+            byte[] dataRef = GetPerformanceData(entry.NameIndex.ToString(CultureInfo.InvariantCulture), true);
```
Comment (danmosemsft) [inline src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs]: nit , named parameter is a little more readable
`byte[] dataRef = GetPerformanceData(entry.NameIndex.ToString(CultureInfo.InvariantCulture), usePool:true);`

Comment (danmosemsft) [reply src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs]: Or maybe just remove the bool and make all code paths use the pool.

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs [hunk 4]
```diff
@@ -0,0 +1,119 @@
...
+using Internal.Win32.SafeHandles;
+
+namespace System.Diagnostics
+{
+    internal class PerformanceDataRegistryKey
+    {
+        private const int MaxArrayPoolLength = 1024 * 1024;
+        private readonly SafeRegistryHandle _hkey;
+
+        private const int PerformanceData = unchecked((int)0x80000004);
```
Comment (danmosemsft) [inline src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: replace with RegistryHive.PerformanceData ?

**Comment by stephentoub** [comment]
> Reduce memory allocations on read performance counters

Can you share the resulting perf data highlighting why it's important to do this?  It's great to improve performance, but I don't love some of the complications and duplication this adds to the code.

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs [hunk 5]
```diff
@@ -0,0 +1,119 @@
+﻿using System.Buffers;
+using System.IO;
+using Internal.Win32.SafeHandles;
+
+namespace System.Diagnostics
+{
+    internal class PerformanceDataRegistryKey
+    {
+        private const int MaxArrayPoolLength = 1024 * 1024;
```
Comment (stephentoub) [inline src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: Why is this needed?  It seems like if you exceed this you just fall back to allocating, which is exactly what the shared array pool does when its max size is exceeded.

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs [hunk 6]
```diff
@@ -0,0 +1,119 @@
...
+
+        public void ReleaseBlob(byte[] blob, bool usePool = true)
+        {
+            if (usePool && blob.Length < MaxArrayPoolLength)
+            {
+                ArrayPool<byte>.Shared.Return(blob);
+            }
+        }
+
+        private byte[] CreateBlob(in int size, in bool usePool)
```
Comment (stephentoub) [inline src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: Why are you passing in int and bool with "in"?  These are primitive value types copied by value, so there's nothing the callee could do to modify the caller's data anyway, and using "in" results in passing them by ref which is going to be slower than passing by value.  Same question below.

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs [hunk 7]
```diff
@@ -1636,6 +1655,24 @@ internal InstanceDataCollectionCollection ReadCategory()
 
             return data;
         }
+
+        public void Dispose()
+        {
+            if (Interlocked.Exchange(ref _disposed, 1) == 1)
```
Comment (stephentoub) [inline src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs]: Why the Interlocked.Exchange?  If we're concerned about concurrent misuse, then we should similarly be concerned about other members (like GetInstanceNamesFromIndex and GetCounterDefinitionSample) being used concurrently with Dispose... this Exchange won't help with the race conditions there, even with the CheckDisposed calls.

**Comment by danmosemsft** [comment]
@MaxShoshin we would like to take this change, with feedback above and some perf measurements. do you have time to finish it?

**Comment by MaxShoshin** [comment]
@danmosemsft, give me 1 week, i'll fix it and provide perf measurement result.

**Comment by danmosemsft** [comment]
Sounds good @maxshoshin

**Comment by MaxShoshin** [comment]
@stephentoub, Please find my benchmark results:

``` ini

BenchmarkDotNet=v0.11.3, OS=Windows 10.0.17134.472 (1803/April2018Update/Redstone4)
Intel Core i7-7500U CPU 2.70GHz (Kaby Lake), 1 CPU, 4 logical and 2 physical cores
.NET Core SDK=2.1.402
  [Host]     : .NET Core 2.1.4 (CoreCLR 4.6.26814.03, CoreFX 4.6.26814.02), 64bit RyuJIT
  Job-* : .NET Core {Some Guid} (CoreCLR 4.6.27226.01, CoreFX 4.7.19.5201), 64bit RyuJIT

Runtime=Core  Toolchain=CoreRun  

```
|  Method       |     Mean |     Error |   StdDev | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|-------------- |---------:|----------:|---------:|------------:|------------:|------------:|--------------------:|
| ReadCpuAfter  | 39.56 us | 0.7832 us | 2.077 us |      1.8311 |           - |           - |             3.86 KB |
| ReadCpuBefore | 80.48 us | 1.600 us  | 4.130 us |     32.2266 |           - |           - |            67.35 KB |

Test:
```C#
    [MemoryDiagnoser]
    public class PerformanceCounterRead
    {
        private PerformanceCounter _cpu = new PerformanceCounter("Processor", "% Processor Time", "_Total");

        [Benchmark]
        public void ReadCpu()
        {
            _cpu.NextValue();
        }
    }
```

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs (hunk 3 above)
Comment (MaxShoshin) [reply src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs]: named parameter added. I don't think that all code paths should use the pool - we need release rented bytes - i think it is not actual for global perf counter configuration reading.

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs (hunk 4 above)
Comment (MaxShoshin) [reply src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: ok

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs (hunk 5 above)
Comment (MaxShoshin) [reply src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: Many thanks!

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs (hunk 6 above)
Comment (MaxShoshin) [reply src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: Removed. Many thanks!

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs (hunk 7 above)
Comment (MaxShoshin) [reply src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs]: Removed. Using simple bool. Thanks!

**Comment by danmosemsft** [comment]
Nice improvement. But am I reading right that it  is still allocating 3KB on every read of an int? Can that be further improved?

File: src/System.Diagnostics.PerformanceCounter/src/System.Diagnostics.PerformanceCounter.csproj [hunk 8]
```diff
@@ -52,6 +53,18 @@
     <Compile Include="$(CommonPath)\Interop\Windows\advapi32\Interop.ConvertStringSecurityDescriptorToSecurityDescriptor.cs">
       <Link>Common\Interop\Windows\advapi32\Interop.ConvertStringSecurityDescriptorToSecurityDescriptor.cs</Link>
     </Compile>
+    <Compile Include="$(CommonPath)\CoreLib\Interop\Windows\Kernel32\Interop.FormatMessage.cs">
```
Comment (danmosemsft) [inline src/System.Diagnostics.PerformanceCounter/src/System.Diagnostics.PerformanceCounter.csproj]: Nit, not worth resetting the PR, but we try to keep lists of sources in alphabetical order.

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs [hunk 9]
```diff
@@ -0,0 +1,119 @@
...
+        {
+            if (errorCode == Interop.Errors.ERROR_ACCESS_DENIED)
+            {
+                throw new UnauthorizedAccessException(SR.Format(SR.UnauthorizedAccess_RegistryKeyGeneric_Key, name));
+            }
+
+            throw new IOException(Interop.Kernel32.GetMessage(errorCode), errorCode);
+        }
+
+        public void Close()
```
Comment (danmosemsft) [inline src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: Should this class be disposable, like a regular registry key, and this be Dispose()?

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs [hunk 10]
```diff
@@ -0,0 +1,119 @@
...
+                    // at this point in the loop "size * 2" would cause an overflow
+                    size = int.MaxValue;
+                }
+                else
+                {
+                    size *= 2;
+                }
+                sizeInput = size;
+
+                ReleaseBlob(blob, usePool);
```
Comment (danmosemsft) [inline src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: Whoa, this is returning `blob` to the pool, then returning `blob` from this function. At this point `blob` could contain arbitrary data. It should not be read after it is returned.

Comment (danmosemsft) [reply src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: You could temporarily modify ConfigurableArrayPool.cs to wipe the buffer on return (or fill with `0xBAADFOOD` perhaps) which would make your tests fail.

Some discussion was in https://github.com/dotnet/coreclr/issues/9885

Comment (danmosemsft) [reply src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: You coudl potentially add `#if DEBUG` code just before `ArrayPool<byte>.Shared.Return`  to clear it first.

Comment (danmosemsft) [reply src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: My bad, I misread. It is not reusing after return. Still, potentially a useful check to add.

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs [hunk 11]
```diff
@@ -1366,6 +1372,11 @@ internal byte[] GetData(string item)
             throw new Win32Exception(error);
         }
 
+        internal void ReleaseData(byte[] data)
+        {
+            perfDataKey.ReleaseBlob(data);
```
Comment (danmosemsft) [inline src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs]: `blob` and `data` seem used for essentially the same stuff. Would it be better to use `data` consistently? At least this place should be `ReleaseData` because it's being passed `data`

**Comment by danmosemsft** [comment]
I think this is OK aside from comments above. @stephentoub , any further comments from you?

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs (hunk 9 above)
Comment (danmosemsft) [reply src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: I think it should.

**Comment by danmosemsft** [comment]
When implementing `Dispose` I believe (@stephentoub ? ) we try to always follow the [dispose pattern](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose), ie., with the virtual method as well. It may be easiest instead to just make these internal disposable classes `sealed` and then only the simple `Dispose()` is needed.

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs (hunk 9 above)
Comment (danmosemsft) [reply src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: It should also be explicitly disposing `_hkey` and not leaving it to the finalizer.

Comment (danmosemsft) [reply src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: Instead of explicitly calling `RegCloseKey`. Wouldn't the handle end up getting closed twice?

Comment (danmosemsft) [reply src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: Ah, you pass false to `ownsHandle` when creating the SafeHandle. If you pass true, can you dispose it explicitly here?

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs (hunk 10 above)
Comment (MaxShoshin) [reply src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: I've added such check, also i've added `ReleaseData` for all exceptional exits.

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs (hunk 9 above)
Comment (MaxShoshin) [reply src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: I'll implement `IDisposable` here, but, as I understand, current behavior (even before my changes) don't call `Close`/`Dispose` on `RegistryKey` even on dispose remote `PerformanceCounter`. This method called only when Create/Remove category or `PerofrmanceCounter.CloseSharedResources()`. I think we should create another issue related with it?

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs [hunk 12]
```diff
@@ -0,0 +1,142 @@
...
+#if DEBUG
+                // Fill array by garbage to detect early situations when this array is used after return
+                MemoryMarshal.Cast<byte, uint>(data.AsSpan()).Fill(0xBAADF00D);
+#endif
+
+                ArrayPool<byte>.Shared.Return(data);
+            }
+        }
+
+        public void Close()
```
Comment (jkotas) [inline src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: This method is dead code.

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs [hunk 13]
```diff
@@ -0,0 +1,142 @@
...
+
+            return data;
+        }
+
+        public void ReleaseData(byte[] data, bool usePool = true)
+        {
+            if (usePool)
+            {
+#if DEBUG
+                // Fill array by garbage to detect early situations when this array is used after return
```
Comment (jkotas) [inline src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: I do not think we should be adding ad-hoc fills like this under ifdef. If we want to make this diagnosable, it should be

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs [hunk 14]
```diff
@@ -0,0 +1,142 @@
+﻿using System;
```
Comment (jkotas) [inline src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: Add license header.

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs (hunk 13 above)
Comment (danmosemsft) [reply src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: @jkotas did you comment get cut off?

Comment (danmosemsft) [reply src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: Do you prefer to have this under `#if DEBUG` in the ConfigurableArrayPool itself -- the danger of course is release-only bugs, but it seems hard to imagine in this case? Or behind `#if DEBUG` as well as some environment variable a dev could set?

Comment (jkotas) [reply src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: Ignore this. I started writing this, but then I have decided that it is probably worth it here given the complexity of the code. I thought I have hit cancel, but apparently not.

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs (hunk 12 above)
Comment (MaxShoshin) [reply src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: Sorry?

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs (hunk 13 above)
Comment (jkotas) [reply src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: > Do you prefer to have this under #if DEBUG

The array pool diagnostic - once we feel enough pain to add it - should in the release builds, controlled by environment variable. No different from how malloc diagnostic works https://www.bing.com/search?q=MALLOC_CHECK_ .

Comment (MaxShoshin) [reply src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: @danmosemsft, do you mean such kind of check? or i've done something wrong?

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs (hunk 12 above)
Comment (jkotas) [reply src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: I do not think anybody calls this method and it is internal. Or is this called from somewhere?

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs [hunk 15]
```diff
@@ -74,23 +82,42 @@ public byte[] GetValue(string name, bool usePool)
...
+        }
+
+        public void Close()
+        {
+            Dispose();
+        }
+
+        public void Dispose()
+        {
+            if (!_hkey.IsInvalid)
```
Comment (danmosemsft) [inline src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: @jkotas it seems (from safehandle.cpp) that Dispose() only does anything if the handle is not invalid, and it sets the handle to invalid. Is it safe to rely on that, and eliminate the IsInvalid check here? It doesn't seem to be documented.

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs (hunk 12 above)
Comment (MaxShoshin) [reply src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: It is called when `PerformanceCategory` created/renamed or inside of `PerformanceCounter.CloseSharedResources()` call.

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs (hunk 15 above)
Comment (jkotas) [reply src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: Yes. The contract of all Dispose methods is that it is safe to call them multiple times.

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs (hunk 9 above)
Comment (danmosemsft) [reply src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: @jkotas if a type owns a disposable resource, and has a `Close()` method to dispose it (as here) is it important that we make that type actually disposable (and presumably rename `Close()`) or does it not matter? From the GC point of view, it does not matter -- if `Close()` is called, the resource is disposed, if it isn't, the finalizer cleans it up, either way. Perhaps it is just a style issue.

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs (hunk 12 above)
Comment (jkotas) [reply src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: ok, I have missed that.

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs (hunk 15 above)
Comment (danmosemsft) [reply src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: Ah, of course that's a general contract pointed out on IDisposable docs.

File: src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs (hunk 13 above)
Comment (danmosemsft) [reply src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceDataRegistryKey.cs]: @MaxShoshin please remove this `#if DEBUG` block. My bad. @jkotas suggests we do this centrally. That would be a separate PR by someone, tracked in dotnet/coreclr#9885.

**Comment by MaxShoshin** [comment]
@danmosemsft , do I need something else to do to complete this PR?

**Comment by danmosemsft** [comment]
I didn't see this wasn't merged yet. Thanks @maxshoshin for this work. Do you have interest in any other changes in the repo? We have many up for grabs opportunities.
