### PR TITLE
Make AsnSerializer resiliant to ILC reflection rules

### LINKED ISSUE #26123: Test failure: System.Security.Cryptography.Tests.Asn1.SimpleDeserialize/Choice_CycleRoot_Throws
Opened on behalf of @Sunny-pu

The test `System.Security.Cryptography.Tests.Asn1.SimpleDeserialize/Choice_CycleRoot_Throws` has failed.

Assert.Throws() Failure\r
    Expected: typeof(System.Security.Cryptography.Asn1.AsnSerializationConstraintException)\r
    Actual:   typeof(System.InvalidOperationException): There is no metadata token available for the given member.

        Stack Trace:

           at System.Reflection.Runtime.EventInfos.NativeFormat.NativeFormatRuntimeEventInfo.get_MetadataToken() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Reflection.Core\src\System\Reflection\Runtime\TypeInfos\RuntimeNoMetadataNamedTypeInfo.cs:line 119
       at System.Security.Cryptography.Asn1.AsnSerializer.<>c.<PopulateChoiceLookup>b__7_0(FieldInfo fi) in E:\A\_work\668\s\corefx\src\Common\src\System\Security\Cryptography\Asn1V2.Serializer.cs:line 118
       at System.Linq.EnumerableSorter$2<System.__Canon,System.Int32>.ComputeKeys(__Canon[] elements, Int32 count) in E:\A\_work\668\s\corefx\src\System.Linq\src\System\Linq\OrderedEnumerable.cs:line 557
       at System.Linq.EnumerableSorter$1<System.__Canon>.ComputeMap(__Canon[] elements, Int32 count) in E:\A\_work\668\s\corefx\src\System.Linq\src\System\Linq\OrderedEnumerable.cs:line 498
       at System.Linq.OrderedEnumerable$1<System.__Canon>.<GetEnumerator>d__3.MoveNext() in E:\A\_work\668\s\corefx\src\System.Linq\src\System\Linq\OrderedEnumerable.cs:line 24
       at System.Security.Cryptography.Asn1.AsnSerializer.PopulateChoiceLookup(Dictionary$2<ValueTuple$2<$TagClass,Int32>,$LinkedList$1<FieldInfo>> lookup, Type typeT, $LinkedList$1<FieldInfo> currentSet) in E:\A\_work\668\s\corefx\src\Common\src\System\Security\Cryptography\Asn1V2.Serializer.cs:line 118
       at System.Security.Cryptography.Asn1.AsnSerializer.DeserializeChoice($AsnReader reader, Type typeT) in E:\A\_work\668\s\corefx\src\Common\src\System\Security\Cryptography\Asn1V2.Serializer.cs:line 257
       at System.Security.Cryptography.Asn1.AsnSerializer.<>c__DisplayClass19_0.<GetSimpleDeserializer>b__0($AsnReader reader) in E:\A\_work\668\s\corefx\src\Common\src\System\Security\Cryptography\Asn1V2.Serializer.cs:line 780
       at System.Security.Cryptography.Tests.Asn1.SimpleDeserialize.<>c__DisplayClass8_0.<Choice_CycleRoot_Throws>b__0() in E:\A\_work\668\s\corefx\src\System.Security.Cryptography.Encoding\tests\Asn1\Serializer\SimpleDeserialize.cs:line 326
    
Build : Master - 20180103.02 (UWP ILC Tests)
Failing configurations:
- Windows.10.Amd64.ClientRS3-x64
  - Release

Details:
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Filc~2F/build/20180103.02/workItem/System.Security.Cryptography.Encoding.Tests

### PR DESCRIPTION
**Pull request by bartonjs**
AsnSerializer had two different paths which checked for ordered fields, one
which used the MetadataToken and one which didn't.  The MetadataToken
method is more reliable, but is not available on ILC.

With this change

* MetadataToken is used when available, and we hope for the best otherwise.
* The two paths now use the same resolution, so future algorithms apply evenly
* The results are cached, so we only sort once per type

Fixes #26123.

### CODE REVIEW

File: src/Common/src/System/Security/Cryptography/Asn1V2.Serializer.cs [hunk 1]
```diff
@@ -70,6 +74,52 @@ private static Deserializer TryOrFail<T>(TryDeserializer<T> tryDeserializer)
...
+                    catch (InvalidOperationException)
+                    {
+                        // If MetadataToken isn't available (like in ILC) then just hope that
+                        // the fields are returned in declared order.  For the most part that
+                        // will result in data misaligning to fields and deserialization failing,
+                        // thus a CryptographicException.
+                        return fieldInfos;
+                    }
+
+                    return fieldInfos.OrderBy(fi => fi.MetadataToken).ToArray();
```
Comment (stephentoub) [inline src/Common/src/System/Security/Cryptography/Asn1V2.Serializer.cs]: Could we just sort the original array instead, e.g.
```C#
Array.Sort(fieldInfos, (x, y) => x.MetadataToken.CompareTo(y.MetadataToken));
return fieldInfos;
```
?

Comment (bartonjs) [reply src/Common/src/System/Security/Cryptography/Asn1V2.Serializer.cs]: That seems way too sensible :smile:.

**Comment by bartonjs** [comment]
@dotnet-bot Test Linux arm Release Build please
Test Tizen armel Debug Build please

(Jobs look aborted)
