### PR TITLE
System.Net.Security test stabilization

### LINKED ISSUE #4467: SslStream tests: timeout
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/6135/console
```
System.Net.Security.Tests.SslStreamStreamToStreamTest.SslStream_StreamToStream_Authentication_Success [FAIL]
        Handshake completed in the allotted time
        Expected: True
        Actual:   False
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Security\tests\FunctionalTests\SslStreamStreamToStreamTest.cs(36,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest.SslStream_StreamToStream_Authentication_Success()
     System.Net.Security.Tests.CertificateValidationClientServer.CertificateValidationClientServer_EndToEnd_Ok [FAIL]
        Client/Server Authentication timed out.
        Expected: True
        Actual:   False
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Security\tests\FunctionalTests\CertificateValidationClientServer.cs(80,0): at System.Net.Security.Tests.CertificateValidationClientServer.<CertificateValidationClientServer_EndToEnd_Ok>d__0.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_EachProtocol_Success [FAIL]
        Timed Out
        Expected: True
        Actual:   False
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Security\tests\FunctionalTests\ClientAsyncAuthenticateTest.cs(252,0): at System.Net.Security.Tests.ClientAsyncAuthenticateTest.<ClientAsyncSslHelper>d__5c.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Security\tests\FunctionalTests\ClientAsyncAuthenticateTest.cs(108,0): at System.Net.Security.Tests.ClientAsyncAuthenticateTest.<ClientAsyncAuthenticate_EachProtocol_Success>d__16.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

### PR DESCRIPTION
**Pull request by CIPop**
* Adding generic parallel test execution script.
* Address several System.Net.Security test issues found using the script.

The following tests have been used:
* 100 parallel test processes on a 12CPU/16GB machine for 1hr
* 20 parallel test processes on a 8CPU/3GB machine (leaving this to run overnight)
* 20 parallel test processes on a 2CPU/2GB machine (leaving this to run overnight)

Most of below bugs were potentially fixed by #7800 at least in part. Other test-code fixes to issues discovered during stress tests have been added to this PR.

Fixes #4467 #5283 #5284 #5991.

@davidsh @stephentoub @ericeil PTAL
/cc @himadrisarkar

### CODE REVIEW

**Comment by CIPop** [comment]
Unix tests failed as I forgot to change the test unix/project.json file.

**Comment by CIPop** [comment]
The OSX package restore failed, potentially caused by #7902:

```
16:46:06 EXEC : error : Could not find file '/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/tempHome/.local/share/NuGet/v3-cache/0b99e17097bea891c4215989667b88d90c9f7540$_F_dotnet-core_api_v3_index.json/nupkg_System.Runtime.InteropServices.4.1.0-rc3-24018-00.dat'. [/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/build.proj]
16:46:06 
/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/build.proj(80,5): error MSB3073: The command ""/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/Tools/dotnetcli/dotnet" restore --packages "/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/packages" --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json --source https://www.nuget.org/api/v2/ --infer-runtimes "/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src" "/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/pkg"" exited with code -1.
16:46:06 
16:46:06     0 Warning(s)
16:46:06     2 Error(s)
```

**Comment by CIPop** [comment]
@dotnet-bot Test Innerloop OSX Debug Build and Test

**Comment by davidsh** [comment]
LGTM

File: src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs [hunk 1]
```diff
@@ -36,7 +36,24 @@ public void ReadFrame(bool server, out byte[] buffer)
 
             semaphore.Wait(WaitForReadDataTimeoutMilliseconds);
 
-            bool dequeueSucceeded = packetQueue.TryDequeue(out buffer);
+            bool dequeueSucceeded = false;
+            int remainingRetries = 3;
```
Comment (stephentoub) [inline src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs]: Nit: since this appears to be the total number of tries rather than retries, maybe ```remainingTries```

File: src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs [hunk 2]
```diff
@@ -36,7 +36,24 @@ public void ReadFrame(bool server, out byte[] buffer)
...
+            {
+                dequeueSucceeded = packetQueue.TryDequeue(out buffer);
+                if (dequeueSucceeded)
+                {
+                    break;
+                }
+
+                remainingRetries--;
+                backOffDelayMilliseconds *= backOffDelayMilliseconds;
+                Thread.Sleep(backOffDelayMilliseconds);
```
Comment (stephentoub) [inline src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs]: This math doesn't seem quite right.  After the first try, we're going to sleep for 10*10 == 100 milliseconds, that's fine.  The second time we're going to sleep for 100*100 == 10,000 millseconds = 10 seconds... a bit long, but maybe ok.  The third time we're going to sleep for 10000*10000 milliseconds == 27 hours?

Did you mean to be multiplying by 10 each time rather than by backoffDelayMilliseconds?

File: src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs [hunk 3]
```diff
@@ -36,7 +36,24 @@ public void ReadFrame(bool server, out byte[] buffer)
...
             semaphore.Wait(WaitForReadDataTimeoutMilliseconds);
 
-            bool dequeueSucceeded = packetQueue.TryDequeue(out buffer);
+            bool dequeueSucceeded = false;
+            int remainingRetries = 3;
+            int backOffDelayMilliseconds = 10;
+
+            do
+            {
+                dequeueSucceeded = packetQueue.TryDequeue(out buffer);
```
Comment (stephentoub) [inline src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs]: In what situation is this going to fail?  Rather than looping around the TryDequeue, should we be looping around the semaphore.Wait?  If the Wait completes successfully and there's nothing to take from the queue, that's a serious problem.

File: src/Common/tests/System/Net/VirtualNetwork/VirtualNetworkStream.cs [hunk 4]
```diff
@@ -114,16 +114,9 @@ public override Task<int> ReadAsync(byte[] buffer, int offset, int count, Cancel
...
-                Write(buffer, offset, count);
-                return Task.CompletedTask;
-            }
-            catch (Exception e)
-            {
-                return Task.FromException(e);
-            }
+            return cancellationToken.IsCancellationRequested ?
+                Task.FromCanceled<int>(cancellationToken) :
+                Task.Run(() => Write(buffer, offset, count));
```
Comment (stephentoub) [inline src/Common/tests/System/Net/VirtualNetwork/VirtualNetworkStream.cs]: This is fine.  FWIW, I didn't do this when I changed the ReadAsync because, whereas Read blocks waiting for data, Write completes quickly and without blocking.

File: src/Common/tests/Tests/System/Net/VirtualNetworkStreamTest.cs [hunk 5]
```diff
@@ -17,17 +17,25 @@ public class VirtualNetworkStreamTest
...
                 for (int i = 0; i < 100000; i++)
                 {
-                    int bufferSize = rnd.Next(1, 2048);
-
-                    byte[] writeFrame = new byte[bufferSize];
-                    rnd.NextBytes(writeFrame);
+                    int bufferSize;
+                    byte[] writeFrame;
+                    
+                    lock (rndLock)
```
Comment (stephentoub) [inline src/Common/tests/Tests/System/Net/VirtualNetworkStreamTest.cs]: Why is this lock needed?  rnd isn't exposed to any other threads and is only used by this function locally.

File: src/Common/tests/Tests/System/Net/VirtualNetworkStreamTest.cs [hunk 6]
```diff
@@ -109,10 +119,19 @@ public void VirtualNetworkStream_MultiThreadIntegrityTest_Ok()
             {
                 Parallel.For(0, 100000, async (int i) =>
```
Comment (stephentoub) [inline src/Common/tests/Tests/System/Net/VirtualNetworkStreamTest.cs]: This is problematic and isn't doing what you're hoping it is.  The delegate is an Action<int>, which means this async method is void-returning.  The moment the body awaits on something that's not yet completed, the delegate will return, and as far as the Parallel.For is concerned, that delegate finished its work.  See http://blogs.msdn.com/b/pfxteam/archive/2012/02/08/10265476.aspx for more details.  You'll need to either change the awaits in the delegate to be blocking waits, or use something other than Parallel.For.

File: src/System.Net.Security/tests/FunctionalTests/TestConfiguration.cs [hunk 7]
```diff
@@ -14,7 +14,7 @@ namespace System.Net.Security.Tests
 {
     internal static class TestConfiguration
     {
-        public const int PassingTestTimeoutMilliseconds = 15 * 1000;
+        public const int PassingTestTimeoutMilliseconds = 5 * 60 * 1000;
```
Comment (stephentoub) [inline src/System.Net.Security/tests/FunctionalTests/TestConfiguration.cs]: 5 minutes?

File: src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs (hunk 1 above)
Comment (CIPop) [inline src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs]: Fixing.

File: src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs (hunk 2 above)
Comment (CIPop) [inline src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs]: Thanks for catching this. Changing initial delay of 2 ms and rerunning tests.

File: src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs (hunk 3 above)
Comment (CIPop) [inline src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs]: The assert that got removed was the first thing that failed under stress after the test got switched to proper async/await.

The wait is on a semaphore, not a lock. It's acceptable to have multiple threads adding while multiple other threads are reading.

TryDequeue is, by contract, allowed to fail: http://stackoverflow.com/questions/5645348/under-what-conditions-can-trydequeue-and-similar-system-collections-concurrent-c

With this fix, the second TryDequeue always seems to pass. (Given the issue above I would have seen tests hanging for >27hrs which didn't happen overnight.)

File: src/Common/tests/System/Net/VirtualNetwork/VirtualNetworkStream.cs (hunk 4 above)
Comment (CIPop) [inline src/Common/tests/System/Net/VirtualNetwork/VirtualNetworkStream.cs]: Changed per #5991 - the cancellationToken was not honored correctly.

File: src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs (hunk 3 above)
Comment (stephentoub) [inline src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs]: I'm not following.

The reason TryDequeue might return false is if there's nothing in the collection.  And the only reason that might happen is if the semaphore.Wait(timeout) returned false due to hitting the timeout (if it returned true, that meant that there was count in the semaphore that could be taken, and that would only happen if there was a corresponding item to be taken from the queue).

So I'm suggesting that instead of wrapping TryDequeue in a loop, you wrap the Wait in a loop.  If the Wait returns true, TryDequeue should never return false, and if the Wait returns false, there's no reason to even try calling TryDequeue.

File: src/Common/tests/Tests/System/Net/VirtualNetworkStreamTest.cs (hunk 5 above)
Comment (CIPop) [inline src/Common/tests/Tests/System/Net/VirtualNetworkStreamTest.cs]: Removed.

File: src/Common/tests/Tests/System/Net/VirtualNetworkStreamTest.cs (hunk 6 above)
Comment (CIPop) [inline src/Common/tests/Tests/System/Net/VirtualNetworkStreamTest.cs]: Thanks for pointing that out! This is not obvious at all.
Looks like this test was not doing anything before. I'm now seeing the perf impact caused by Task.Run() used in the ReadAsync/WriteAsync.

File: src/System.Net.Security/tests/FunctionalTests/TestConfiguration.cs (hunk 7 above)
Comment (CIPop) [inline src/System.Net.Security/tests/FunctionalTests/TestConfiguration.cs]: Will try again with the original 15s.

**Comment by CIPop** [comment]
Overnight test results. One test failed:

``` 
System.Net.Security.Tests.CertificateValidationRemoteServer.CertificateValidationRemoteServer_EndToEnd_Ok [FAIL]
      System.Net.Sockets.SocketException : A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
      Stack Trace:
            at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
            at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
            at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
         C:\corefx\src\System.Net.Security\tests\FunctionalTests\CertificateValidationRemoteServer.cs(21,0): at System.Net.Security.Tests.CertificateValidationRemoteServer.<CertificateValidationRemoteServer_EndToEnd_Ok>d__0.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Finished:    System.Net.Security.Tests

=== TEST EXECUTION SUMMARY ===
   System.Net.Security.Tests  Total: 102, Errors: 0, Failed: 1, Skipped: 0, Time: 24.210s
Test execution failed!
```

* 20 parallel test processes on a 8CPU/3GB machine (leaving this to run overnight): 2/20 test processes failed with above error.
* 20 parallel test processes on a 2CPU/2GB machine (leaving this to run overnight): 15/20 test processes failed with above error.

/cc @davidsh This particular test is the only one having a dependency on Azure. What we might have seen was either downtime or automatic DoS countermeasure implemented on the remote server.

Tracking with #3697.

File: src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs (hunk 3 above)
Comment (CIPop) [inline src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs]: I now see what you mean. The reason I didn't think that was possible because the tests were executing in <10s (about 7-8sec) and the semaphore wait timeout was 10s. 

Retrying on the semaphore wait doesn't make the code better as the idea was to eventually time out.
Increasing the timeout to 30sec and throwing a TimeoutException if the semaphore wait returns false.

**Comment by CIPop** [comment]
Same failures on both OSX boxes (#7902).

**Comment by CIPop** [comment]
No failures on both the VMs so far with the current configuration. 
Changing the positive test timeout back to 15s now.

**Comment by CIPop** [comment]
> Changing the positive test timeout back to 15s now.

@stephentoub  No-go: tests failed within the first minute of 100 parallel executions on my 12 CPU machine. It appears that the tests do run longer than 10s for the first time if a lot of processes are created. After a while they enter a steady-state where tests run fast (7-8s).

I've changed the timeout to 1 minute to avoid the timeouts in CI.

**Comment by CIPop** [comment]
Overnight tests failed the same way: `System.Net.Security.Tests.CertificateValidationRemoteServer.CertificateValidationRemoteServer_EndToEnd_Ok [FAIL]`. 
@stephentoub please let me know if there are any other changes that I should make before merging.

**Comment by CIPop** [comment]
Ubuntu test failed because of #7234

**Comment by CIPop** [comment]
Test Innerloop Ubuntu14.04 Debug Build and Test please
