### PR TITLE
Fix instantiating PrincipleContext  with Domain type

### LINKED ISSUE #23605: System.DirectoryServices.AccountManagement.PrincipalContext support in .NET Core 2.0
Hello,

I have tried to download the latest version of preview `System.DirectoryServices.AccountManagement` from myget - https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.DirectoryServices.AccountManagement

And I have tried to use the `PrincipalContext`:

```
using(var context = new PrincipalContext(ContextType.Domain))
            {
//code
            }
```

And I get the `System.NullReferenceException`:
```
 {System.NullReferenceException: Object reference not set to an instance of an object.
   at System.DirectoryServices.Protocols.LdapConnection.ConstructEntry(IntPtr entryMessage)
   at System.DirectoryServices.Protocols.LdapConnection.ConstructResponse(Int32 messageId, LdapOperation operation, ResultAll resultType, TimeSpan requestTimeOut, Boolean exceptionOnTimeOut)
   at System.DirectoryServices.Protocols.LdapConnection.SendRequest(DirectoryRequest request, TimeSpan requestTimeout)
   at System.DirectoryServices.AccountManagement.PrincipalContext.ReadServerConfig(String serverName, ServerProperties& properties)
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoServerVerifyAndPropRetrieval()
   at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name, String container, ContextOptions options, String userName, String password)
   at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType)
   at CoreADcko.Controllers.HomeController.Index() in C:\Projects\CoreADcko\CoreAD\CoreAD\Controllers\HomeController.cs:line 17
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()}
```

I have used the WebApplication .NET Core template with windows authentication enabled and these dependecies:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <MvcRazorCompileOnPublish>true</MvcRazorCompileOnPublish>
    <AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0-preview2-final" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="4.5.0-preview2-25628-01" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0-preview2-final" />
  </ItemGroup>

</Project>
```

How can I solve this error?

Thank you.

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes #23605

### CODE REVIEW

**Comment by tarekgh** [comment]
@danmosemsft could you please have a quick look? Thanks.

File: src/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/common/SearchResults.cs [hunk 1]
```diff
@@ -71,17 +71,18 @@ public class SearchResultReferenceCollection : ReadOnlyCollectionBase
     public class SearchResultEntry
     {
         private DirectoryControl[] _resultControls = null;
+        private SearchResultAttributeCollection _attributes = new SearchResultAttributeCollection();
```
Comment (danmosemsft) [inline src/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/common/SearchResults.cs]: Oops. I see this was introduced by 9b4ef7f8a3955798a225577a7baddfca2e10c8c7

Can you add a test? Clearly we don't have one. Even if it would only actually do anything when we run tests locally (since no domain in automated runs)

Comment (stephentoub) [reply src/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/common/SearchResults.cs]: Why not just fix it by changing:
```C#
public SearchResultAttributeCollection Attributes { get; }
```
to be:
```C#
public SearchResultAttributeCollection Attributes { get; } = new SearchResultAttributeCollection();
```
?

Comment (stephentoub) [reply src/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/common/SearchResults.cs]: Or, better yet, by changing the constructors to be:
```C#
internal SearchResultEntry(string dn) : this(dn, new SearchResultAttributeCollection()) { }

internal SearchResultEntry(string dn, SearchResultAttributeCollection)
{
    DistinguishedName = dn;
    Attributes = attrs;
}
```
?  Then we're not allocating a collection that's just going to get overwritten if one is provided to the ctor, and we still get to keep the (implicit) field as readonly.

**Comment by danmosemsft** [comment]
After this, can you eye ball the coverage we have for S.DS.* in general? Our covearge (except of Protocols) is very small. Where do we need tests to get it to a reasonably shippable state? Is there stuff from Mono we can reuse? perhaps we need a tracking issue and some other folks might want to pitch in? 

https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/Code_Coverage_Report/

**Comment by tarekgh** [comment]
I have applied @stephentoub suggestion. 

@danmosemsft I'll look later at adding a reliable test for the issue caught here. if the test machine joined a domain then the issue is exercised. if the machine is not a domain joint, I'll need to figure an easy way to query and exercise SearchResultEntry.

**Comment by tarekgh** [comment]
https://github.com/dotnet/corefx/issues/2089
