### PR TITLE
Fix #14961 and tweak perf in ImmutableArray

### LINKED ISSUE #14961: Remove silent boxing/make exceptions consistent in ImmutableArray
Tracking issue for changes to the source of `ImmutableArray` to be made after the test changes in #14798. All of these will be fixed in a subsequent PR.

- [ ] Remove silent boxing in `Remove` / `Replace`
  - Relevant lines: [`Replace`](https://github.com/jamesqo/corefx/blob/38b28ed31c9a6620fbbfd6c3822bc1a2ea6c3c9f/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray_1.cs#L731-L734), [`Remove`](https://github.com/jamesqo/corefx/blob/38b28ed31c9a6620fbbfd6c3822bc1a2ea6c3c9f/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray_1.cs#L771)
  - There exists no `IndexOf(T, IEqualityComparer<T>)` method on ImmutableArray, so it is boxed to an IImmutableList and the ImmutableList extension method is called
  - These should be trivial to fix (just pass in `0` and `self.Length`)
- [ ] Make exceptions thrown by `RemoveRange` / `Remove` consistent
  - Relevant diffs: https://github.com/dotnet/corefx/pull/14798/files#diff-5c35677b4c2163f273b62555ee2cc97bR731, https://github.com/dotnet/corefx/pull/14798/files#diff-5c35677b4c2163f273b62555ee2cc97bR797

### PR DESCRIPTION
**Pull request by jamesqo**
Follow-up for https://github.com/dotnet/corefx/pull/14798 and https://github.com/dotnet/corefx/pull/13158. Specializes `InsertRange` for arrays, uses `TryCopyTo` in `ImmutableArray.Builder`, removes some unnecessary boxing in `Remove` / `Replace`, makes exceptions consistent in `SetItem` / `Replace` / `Remove`, and reenables corresponding tests.

Fixes #14961, https://github.com/dotnet/corefx/issues/13695

### CODE REVIEW

File: src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray.cs [hunk 1]
```diff
@@ -106,14 +106,18 @@ public static ImmutableArray<T> CreateRange<T>(IEnumerable<T> items)
...
             if (immutableArray != null)
             {
-                immutableArray.ThrowInvalidOperationIfNotInitialized();
+                Array array = immutableArray.Array;
+                if (array == null)
+                {
+                    throw new InvalidOperationException(SR.InvalidOperationOnDefaultArray);
+                }
 
                 // immutableArray.Array must not be null at this point, and we know it's an
```
Comment (AArnott) [inline src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray.cs]: Do you want to update the comment so it discusses the `array` variable instead of `immutableArray.Array`, now that the code beneath it deals with `array`?

File: src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableExtensions.cs [hunk 2]
```diff
@@ -106,6 +106,10 @@ internal static int GetCount<T>(ref IEnumerable<T> sequence)
         /// </remarks>
         internal static bool TryCopyTo<T>(this IEnumerable<T> sequence, T[] array, int arrayIndex)
         {
+            Debug.Assert(sequence != null);
+            Debug.Assert(array != null);
+            Debug.Assert(arrayIndex >= 0 && arrayIndex < array.Length);
```
Comment (jamesqo) [inline src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableExtensions.cs]: > Also, it appears this method simply returned false when sequence was null before. Now it will throw NullReferenceException. Are we sure no callers pass a null 1st argument (perhaps as a result of an as cast that fails)?

@AArnott I double-checked and there are no callers doing that.

> Are we certain this last assert is correct? I seem to recall some APIs allowing arrayIndex == array.Length when the number of elements to be copied was 0.

I did that intentionally because I thought this method was only being called in scenarios where count > 0. However, I just realized I introduced a usage in this PR where count can be 0. I'll change this to `<=`.

File: src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray.cs (hunk 1 above)
Comment (jamesqo) [inline src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray.cs]: Sure.

File: src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray.cs [hunk 3]
```diff
@@ -106,14 +106,18 @@ public static ImmutableArray<T> CreateRange<T>(IEnumerable<T> items)
             var immutableArray = items as IImmutableArray;
             if (immutableArray != null)
             {
-                immutableArray.ThrowInvalidOperationIfNotInitialized();
+                Array array = immutableArray.Array;
+                if (array == null)
+                {
+                    throw new InvalidOperationException(SR.InvalidOperationOnDefaultArray);
+                }
```
Comment (jamesqo) [inline src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray.cs]: @AArnott Interface calls are relatively expensive, and this one was in a commonly-used codepath and trivial to remove. Plus, it let us delete code. I'll see if I can post some stats on how/if this improves perf.

File: src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableExtensions.cs (hunk 2 above)
Comment (AArnott) [inline src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableExtensions.cs]: Do we have a missing test case then to exercise the count==0 case?

File: src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray.cs (hunk 3 above)
Comment (AArnott) [inline src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray.cs]: No need to get numbers for me. Avoiding interface dispatch sounds worthy. Thanks.

File: src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableExtensions.cs (hunk 2 above)
Comment (jamesqo) [inline src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableExtensions.cs]: @AArnott Just added one.

**Comment by karelz** [comment]
Merged, @ianhays please review post-mortem if you want to ...
