### PR TITLE
Add skip for BitArray.CopyTo bug test on desktop.

### LINKED ISSUE #13241: Test failure: System.Collections.Tests.BitArray_GetSetTests/CopyTo_Byte_Hidden(label: \"Constructor\", bits: [True, True, True, True, True, ...])
Opened on behalf of @jiangzeng

The test `System.Collections.Tests.BitArray_GetSetTests/CopyTo_Byte_Hidden(label: \"Constructor\", bits: [True, True, True, True, True, ...])` has failed.

Assert.Equal() Failure\r
    Expected: 31\r
    Actual:   255

        Stack Trace:

           at System.Collections.Tests.BitArray_GetSetTests.CopyTo_Byte_Hidden(String label, BitArray bits) in D:\A\_work\32\s\corefx\src\System.Collections\tests\BitArray\BitArray_GetSetTests.cs:line 375
Build : Master - 20161031.01 (Full Framework Tests)
Failing configurations:
- Windows.10.Amd64
  - AnyCPU-Debug
  - AnyCPU-Release

Fail for tests:
CopyTo_Byte_Hidden
CopyTo_Int_Hidden

Details:
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20161031.01/workItem/System.Collections.Tests/analysis/xunit/System.Collections.Tests.BitArray_GetSetTests~2FCopyTo_Byte_Hidden(label:%20%5C%22Constructor%5C%22,%20bits:%20%5BTrue,%20True,%20True,%20True,%20True,%20...%5D)

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20161031.01/workItem/System.Collections.Tests/analysis/xunit/System.Collections.Tests.BitArray_GetSetTests~2FCopyTo_Int_Hidden(label:%20%5C%22Constructor%5C%22,%20bits:%20%5BTrue,%20True,%20True,%20True,%20True,%20...%5D)

### PR DESCRIPTION
**Pull request by Clockwork-Muse**
Fixes #13241 

Adds Skip for test on desktop framework.

cc @danmosemsft , @ianhays

### CODE REVIEW

File: src/System.Collections/tests/BitArray/BitArray_GetSetTests.cs [hunk 1]
```diff
@@ -379,6 +380,24 @@ public static void CopyTo_Int_Hidden(string label, BitArray bits)
...
+
+            int[] data = new int[arrayLength];
+            ((ICollection)bits).CopyTo(data, 0);
+
+            Assert.All(data, d => Assert.Equal(allBitsSet, d));
+            
+        }
+
+        [Theory]
+        [SkipOnTargetFramework(~TargetFrameworkMonikers.NetFramework, "Desktop Framework hasn't received the fix yet.")]
```
Comment (danmosemsft) [inline src/System.Collections/tests/BitArray/BitArray_GetSetTests.cs]: I'm probably spacing but aren't these backwards -- we want CopyTo_Byte_Hidden to skip on .NetFramwework (which is desktop) and vice versa.

File: src/System.Collections/tests/BitArray/BitArray_GetSetTests.cs [hunk 2]
```diff
@@ -359,6 +359,7 @@ public static IEnumerable<object> CopyTo_Hidden_Data()
         }
 
         [Theory]
+        [SkipOnTargetFramework(~TargetFrameworkMonikers.NetFramework, "Desktop Framework hasn't received the fix yet.")]
```
Comment (danmosemsft) [inline src/System.Collections/tests/BitArray/BitArray_GetSetTests.cs]: instead of 'the fix' how about 'the fix for 9838'

File: src/System.Collections/tests/BitArray/BitArray_GetSetTests.cs (hunk 1 above)
Comment (Clockwork-Muse) [inline src/System.Collections/tests/BitArray/BitArray_GetSetTests.cs]: Yes.... yes it is.  I guess I was more tired than I thought.

**Comment by danmosemsft** [comment]
Thanks for doing this. For what its worth, I wouldn't personally have written tests to verify that desktop continues to have the bug unless we've decided we want to make sure it keeps the bug ... doesn't hurt though.

**Comment by Clockwork-Muse** [comment]
ehh..... :shrug: - it's more I put them in so there's visibility to when/if the bug does disappear.
