### PR TITLE
Fix Japanese First Year Formatting Test

### LINKED ISSUE #32450: Enable first year of Japanese era test on full framework
It seems the fix for it will be serviced. We should re-enable the disabled test when the servicing fix is delivered to most clients. To be absolutely sure we can also add a version check for netfx.

Disabled test: System.Globalization.Tests.DateTimeFormatInfoMiscTests.TestFirstYearOfJapaneseEra

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes #32450

### CODE REVIEW

**Comment by tarekgh** [comment]
@krwq, could you please have a look?

File: src/System.Globalization/tests/DateTimeFormatInfo/DateTimeFormatInfoTests.cs [hunk 1]
```diff
@@ -171,16 +171,17 @@ public void TestFirstYearOfJapaneseEra()
...
-            {
-                Assert.True(formattedDate.IndexOf("\u5143" /* 元 */, StringComparison.Ordinal) >= 0,
-                    "Expected the first year of the era be formatted with 元");
-            }
 
             Assert.True(DateTime.TryParseExact(formattedDate, pattern, jpnFormat, DateTimeStyles.None, out DateTime parsedDate));
             Assert.Equal(dt, parsedDate);
+
+            // If the formatting with Gan-nen is supported, then parsing should succeed. otherwise parsing should fail.
+            Assert.True(formattedDate.IndexOf("\u5143" /* 元 */, StringComparison.Ordinal) >= 0 ==
```
Comment (krwq) [inline src/System.Globalization/tests/DateTimeFormatInfo/DateTimeFormatInfoTests.cs]: looks good but I'd go with Assert.Equal since you're comparing bools
