### PR TITLE
LoopbackProxyServer cleanup

### LINKED ISSUE #32808: UseCallback_HaveCredsAndUseAuthenticatedCustomProxyAndPostToSecureServer_Success failing in CI
This test is failing a lot of outerloop runs in CI, e.g.
```
Windows.10.Nano.Amd64.Open-x64-Debug
Get Repro environment
Unhandled Exception of Type System.Net.Http.HttpRequestException
Message :
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.IO.IOException : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
-------- System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host.
Stack Trace :
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnection.cs:line 683
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\AuthenticationHelper.NtAuth.cs:line 43
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 496
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 467
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\AuthenticationHelper.cs:line 220
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnel(CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 620
   at System.Threading.Tasks.ValueTask`1.get_Result() in E:\A\_work\164\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\ValueTask.cs:line 849
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 567
   at System.Threading.Tasks.ValueTask`1.get_Result() in E:\A\_work\164\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\ValueTask.cs:line 849
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 595
   at System.Threading.Tasks.ValueTask`1.get_Result() in E:\A\_work\164\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\ValueTask.cs:line 849
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 671
   at System.Threading.Tasks.ValueTask`1.get_Result() in E:\A\_work\164\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\ValueTask.cs:line 849
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 454
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\RedirectHandler.cs:line 33
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 475
   at System.Net.Http.Functional.Tests.HttpClientHandler_ServerCertificates_Test.UseCallback_HaveCredsAndUseAuthenticatedCustomProxyAndPostToSecureServer_Success() in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.ServerCertificates.cs:line 118
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Net.Http.HttpConnection.FillAsync() in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnection.cs:line 1293
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnection.cs:line 1245
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnection.cs:line 512
----- Inner Stack Trace -----
```

### PR DESCRIPTION
**Pull request by scalablecory**
This makes `LoopbackProxyServer` behave more properly as a server should.

- Ensure all connections are finished prior to `LoopbackProxyServer.Dispose()` returning.
- `Shutdown()` CONNECT sessions properly, and don't leave tasks hanging.
- `Dispose()` sockets rather than relying on finalizers.
- Eat fewer errors automatically, and expose uneaten errors via event to assist with troubleshooting.

Resolves #32808. Thanks @davidsh reminding me `~Socket()` without shutdown will not flush buffers and instead RST immediately -- confirmed with Wireshark. Above fixes resolve this.

### CODE REVIEW

File: src/Common/tests/System/Net/Http/LoopbackProxyServer.cs [hunk 1]
```diff
@@ -43,6 +44,8 @@ public sealed class LoopbackProxyServer : IDisposable
         public List<ReceivedRequest> Requests => _requests;
         public Uri Uri => _uri;
 
+        public event ErrorEventHandler Errors;
```
Comment (davidsh) [inline src/Common/tests/System/Net/Http/LoopbackProxyServer.cs]: We typically don't expose public fields.  Instead we expose a public property that wraps a private field.

See the other properties "Connections" and "Requests" as examples.

That said, we haven't used `event` as a pattern in our test code before. At most, we would call FailFast() or use NetEventSource logging (use test event source).

**Comment by davidsh** [comment]
It's possible this PR will also fix #32809

File: src/Common/tests/System/Net/Http/LoopbackProxyServer.cs [hunk 2]
```diff
@@ -63,27 +66,46 @@ private void Start()
...
                         {
                             try
                             {
                                 await ProcessConnection(s).ConfigureAwait(false);
                             }
-                            catch (Exception)
+                            catch (Exception ex)
                             {
-                                // Ignore exceptions.
+                                Errors?.Invoke(this, new ErrorEventArgs(ex));
```
Comment (stephentoub) [inline src/Common/tests/System/Net/Http/LoopbackProxyServer.cs]: Currently no one is registering with the event.  What's the purpose of having it if no one listening to it?

File: src/Common/tests/System/Net/Http/LoopbackProxyServer.cs [hunk 3]
```diff
@@ -94,21 +116,21 @@ private async Task ProcessConnection(Socket s)
         {
             Interlocked.Increment(ref _connections);
 
-            using (var ns = new NetworkStream(s))
+            using (var ns = new NetworkStream(s, true))
```
Comment (stephentoub) [inline src/Common/tests/System/Net/Http/LoopbackProxyServer.cs]: Nit: `true` => `ownsSocket: true`

File: src/Common/tests/System/Net/Http/LoopbackProxyServer.cs [hunk 4]
```diff
@@ -218,41 +240,53 @@ private async Task ProcessConnectMethod(NetworkStream clientStream, string remot
...
                     // Ignore rude disconnects from either side.
+                    // Close sockets to abort the other task.
+                    clientStream.Close();
+                    serverStream.Close();
+                }
+                catch
+                {
+                    clientStream.Close();
+                    serverStream.Close();
+                    throw;
```
Comment (stephentoub) [inline src/Common/tests/System/Net/Http/LoopbackProxyServer.cs]: Seems like this would be cleaner as:
```C#
catch (Exception ex)
{
    clientStream.Close();
    serverStream.Close();
    if (!IsRudeDisconnect(ex))
    {
        throw;
    }
}
```
rather than duplicating the code, having the extra catch block, etc.

File: src/Common/tests/System/Net/Http/LoopbackProxyServer.cs [hunk 5]
```diff
@@ -218,41 +240,53 @@ private async Task ProcessConnectMethod(NetworkStream clientStream, string remot
...
                 }
             });
 
-            await Task.WhenAny(new[] { clientCopyTask, serverCopyTask }).ConfigureAwait(false);
+            await Task.WhenAll(new[] { clientCopyTask, serverCopyTask }).ConfigureAwait(false);
```
Comment (stephentoub) [inline src/Common/tests/System/Net/Http/LoopbackProxyServer.cs]: Is there any situation where the client or server copy task failing could cause the other one to hang indefinitely?  I've not looked to see whether that's a possibility here, but it's often the case when two tasks are related in a client/server fashion, and it's why we have the WhenAllOrAnyFailed helper (https://github.com/dotnet/corefx/blob/0a9a366e290aded3e9bf5d082d6beee5ff560177/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs#L64).

File: src/Common/tests/System/Net/Http/LoopbackProxyServer.cs [hunk 6]
```diff
@@ -218,41 +240,53 @@ private async Task ProcessConnectMethod(NetworkStream clientStream, string remot
...
         }
 
+        static bool IsRudeDisconnect(IOException ex) =>
```
Comment (stephentoub) [inline src/Common/tests/System/Net/Http/LoopbackProxyServer.cs]: Nit: private

File: src/Common/tests/System/Net/Http/LoopbackProxyServer.cs (hunk 2 above)
Comment (scalablecory) [reply src/Common/tests/System/Net/Http/LoopbackProxyServer.cs]: I can get rid of it, but it's useful for troubleshooting issues that are caused by `LoopbackProxyServer` rather than your own test's code. An appropriate compromise may be to use `EventSource` logging as @davidsh suggested.

File: src/Common/tests/System/Net/Http/LoopbackProxyServer.cs (hunk 5 above)
Comment (scalablecory) [reply src/Common/tests/System/Net/Http/LoopbackProxyServer.cs]: Closing the streams disposes of the sockets causing an OperationAborted error to be thrown in the other task, so I don't think this is a problem here.

File: src/Common/tests/System/Net/Http/LoopbackProxyServer.cs (hunk 2 above)
Comment (davidsh) [reply src/Common/tests/System/Net/Http/LoopbackProxyServer.cs]: Adding this `Event` mechanism introduces a new design pattern into our testing logic.  We  should use the existing test logging mechanism we already have with the System.Net.Test EventSource we've defined. That is how we can log and review these unexpected errors.

Comment (scalablecory) [reply src/Common/tests/System/Net/Http/LoopbackProxyServer.cs]: Agreed and updated.

File: src/Common/tests/System/Net/Http/LoopbackProxyServer.cs (hunk 4 above)
Comment (scalablecory) [reply src/Common/tests/System/Net/Http/LoopbackProxyServer.cs]: Refactored this to remove duplication.

File: src/Common/tests/System/Net/Http/LoopbackProxyServer.cs [hunk 7]
```diff
@@ -218,39 +239,67 @@ private async Task ProcessConnectMethod(NetworkStream clientStream, string remot
...
+                    return;
+                }
+
+                // ask the other task to end by disposing, causing OperationAborted.
+
+                try
+                {
+                    clientSocket.Close();
+                }
+                catch(ObjectDisposedException)
```
Comment (davidsh) [inline src/Common/tests/System/Net/Http/LoopbackProxyServer.cs]: nit: add space after "catch"

File: src/Common/tests/System/Net/Http/LoopbackProxyServer.cs [hunk 8]
```diff
@@ -218,39 +239,67 @@ private async Task ProcessConnectMethod(NetworkStream clientStream, string remot
...
 
-            await Task.WhenAny(new[] { clientCopyTask, serverCopyTask }).ConfigureAwait(false);
+            await Task.WhenAll(new[] { clientCopyTask, serverCopyTask }).ConfigureAwait(false);
+
+            /// <summary>Closes sockets to cause both tasks to end, and eats connection reset/aborted errors.</summary>
+            void HandleExceptions(Exception ex)
+            {
+                SocketError sockErr = (ex.InnerException as SocketException)?.SocketErrorCode ?? SocketError.Success;
+
+                // if aborted, the other task failed and is asking this task to end.
```
Comment (davidsh) [inline src/Common/tests/System/Net/Http/LoopbackProxyServer.cs]: nit: style.  We typically start sentences with capital letter. And we avoid extra white-space where possible. We don't use a white-space line between this comment and the code block that it refers to.

So, this would look like the below to conform to existing style of CoreFx networking code:

```c#
// If aborted, the other task failed and is asking this task to end.
if (sockErr == SocketError.OperationAborted)
{
    return;
}
```

Comment (davidsh) [reply src/Common/tests/System/Net/Http/LoopbackProxyServer.cs]: Same comment applies to other places in PR.

File: src/Common/tests/System/Net/Http/LoopbackProxyServer.cs [hunk 9]
```diff
@@ -206,10 +227,10 @@ private async Task<bool> ProcessRequest(StreamReader reader, StreamWriter writer
             }
         }
 
-        private async Task ProcessConnectMethod(NetworkStream clientStream, string remoteHost, int remotePort)
+        private async Task ProcessConnectMethod(Socket clientSocket, NetworkStream clientStream, string remoteHost, int remotePort)
         {
             // Open connection to destination server.
-            Socket serverSocket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
+            using Socket serverSocket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
```
Comment (davidsh) [inline src/Common/tests/System/Net/Http/LoopbackProxyServer.cs]: What does the 'using' do here?  Usually we see it in a scope with statements in braces, i.e.  

```c#
using (var socket = new Socket(...);
{
    // Use the socket.
}

// Now the socket is disposed.
```

I don't recall this single-line pattern being used before in CoreFx.  @stephentoub Can you comment on this?

**Comment by davidsh** [comment]
There are build failures in NETFX:

>src\Common\tests\System\Net\Http\LoopbackProxyServer.cs(297,43): error CS1501: No overload for method 'Throw' takes 1 arguments
src\Common\tests\System\Net\Http\LoopbackProxyServer.cs(84,33): error CS0103: The name 'EventSourceTestLogging' does not exist in the current context
src\Common\tests\System\Net\Http\LoopbackProxyServer.cs(98,21): error CS0103: The name 'EventSourceTestLogging' does not exist in the current context
src\Common\tests\System\Net\Http\LoopbackProxyServer.cs(107,21): error CS0103: The name 'EventSourceTestLogging' does not exist in the current context
src\Common\tests\System\Net\Http\LoopbackProxyServer.cs(297,43): error CS1501: No overload for method 'Throw' takes 1 arguments

And MacOS:

>src/Common/tests/System/Net/Http/LoopbackProxyServer.cs(84,33): error CS0103: The name 'EventSourceTestLogging' does not exist in the current context
src/Common/tests/System/Net/Http/LoopbackProxyServer.cs(98,21): error CS0103: The name 'EventSourceTestLogging' does not exist in the current context
src/Common/tests/System/Net/Http/LoopbackProxyServer.cs(107,21): error CS0103: The name 'EventSourceTestLogging' does not exist in the current context
eng/common/tools.sh(426,): error : Build failed (exit code '1').
Bash exited with code '1'.

The NETFX failures are probably because this method signature doesn't exist.  Since we build NETFX for the test code right now, we might need to pick a lowest common denominator for the LoopbackProxyServer changes being proposed in this PR.

File: src/Common/tests/System/Net/Http/LoopbackProxyServer.cs (hunk 9 above)
Comment (scalablecory) [reply src/Common/tests/System/Net/Http/LoopbackProxyServer.cs]: @davidsh syntax sugar introduced in C# 8; it [creates an implicit scope](https://github.com/dotnet/csharplang/blob/37efea9c833309421d9d8c35ac60b9b1c96d2037/proposals/csharp-8.0/using.md#using-declaration).

Comment (davidsh) [reply src/Common/tests/System/Net/Http/LoopbackProxyServer.cs]: Ok.

Personally, I think this makes the code less readable.  It's similar to why we always use braces for statement blocks in almost all cases even when it's a single statement.

This would be the first time we introduced this new syntax in the code.  I don't see the advantage of using this pattern since it makes the code harder to understand at first glance.

**Comment by scalablecory** [comment]
AZP failing may be dotnet/core-eng#6579

**Comment by scalablecory** [comment]
CI failures are in unrelated code.
