### PR TITLE
Fix LargeArrayBuilder.CopyTo returning incorrect end-of-copy position

### LINKED ISSUE #23680: LINQ bug: ConcatNIterator.LazyToArray() produces incorrect results
Here's a repro: https://github.com/gulbanana/repro-corefx-concat-toarray
```
banana@forsyth MINGW64 /c/code/repro-corefx-concat-toarray (master)
$ dotnet run -f netcoreapp1.0                                      
A B C                                                              
                                                               
banana@forsyth MINGW64 /c/code/repro-corefx-concat-toarray (master)
$ dotnet run -f netcoreapp2.0                                      
A B A                                                              
```

The problem occurs when using Concat multiple times and then calling ToArray().
```c#
using System;
using System.Collections.Generic;
using System.Linq;

class Program
{
    class A { public override string ToString() => "A"; }
    class B { public override string ToString() => "B"; }
    class C { public override string ToString() => "C"; }

    static void Main(string[] args)
    {
        var results = new List<A> { new A() }
            .Concat(new List<object> { new B() })
            .Concat(new List<C> { new C() })
            .ToArray();

        Console.WriteLine(string.Join(' ', results));
    }
}
```

This program should print "A B C", but it instead prints "A B A". I believe the problem is in the specialised implementation of concatenation for 3+-enumerables-of-collections. I ran into it in an actual project (an IEnumerable<BaseType> containing multiple subclass instances) but I've worked around the bug by using `ToList()` instead.

[EDIT] Add C# syntax highlight by @karelz

### PR DESCRIPTION
**Pull request by OmarTawfik**
Porting #23817 to release 2.0 branch.
Fixes #23680

### CODE REVIEW

**Comment by OmarTawfik** [comment]
@dotnet-bot test this

**Comment by OmarTawfik** [comment]
@dotnet-bot  test this please

**Comment by stephentoub** [comment]
@dotnet/dnceng, do you know what's going on with these build failures?
https://ci.dot.net/job/dotnet_corefx/job/release_2.0.0/job/osx10.12_debug_prtest/602/
https://ci.dot.net/job/dotnet_corefx/job/release_2.0.0/job/osx10.12_release_prtest/611/
https://ci.dot.net/job/dotnet_corefx/job/release_2.0.0/job/tizen_armel_cross_debug_prtest/573/

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by Chrisboh** [comment]
@dagood Do you mind taking a look into what is going on here?

**Comment by dagood** [comment]
Taking a look to see if it's unrelated to the current Jenkins overall issues.

**Comment by dagood** [comment]
I'm able to repro on my dev machine by checking out this branch (macOS 10.12.6). `dotnet` exits with code 134 (SIGABRT) when trying to compile the same three projects:

 * src/System.IO.FileSystem/src/System.IO.FileSystem.csproj
 * src/System.Collections/src/System.Collections.csproj
 * src/System.Private.Xml.Linq/src/System.Private.Xml.Linq.csproj

I'm not familiar with how to debug a SIGABRT, but it doesn't appear CI-related.

File: src/Common/src/System/Collections/Generic/LargeArrayBuilder.cs [hunk 1]
```diff
@@ -216,25 +231,35 @@ public CopyPosition CopyTo(CopyPosition position, T[] array, int arrayIndex, int
...
-                {
-                    Array.Copy(buffer, column, array, arrayIndex, copyCount);
+            return new CopyPosition(row, copied).Normalize(buffer.Length);
 
-                    arrayIndex += copyCount;
-                    count -= copyCount;
-                    column += copyCount;
-                }
-            }
+            int CopyToCore(T[] sourceBuffer, int sourceIndex)
```
Comment (dagood) [inline src/Common/src/System/Collections/Generic/LargeArrayBuilder.cs]: Moving this to `private int CopyToCore(T[], int, T[] array, int arrayIndex, int count)` in the class lets the build command pass on my dev box. Seems like a product bug that compiling this crashes on OSX.

Comment (stephentoub) [reply src/Common/src/System/Collections/Generic/LargeArrayBuilder.cs]: Are we using different compiler versions in release/2.0 vs master?

Comment (dagood) [reply src/Common/src/System/Collections/Generic/LargeArrayBuilder.cs]: Looking at `Tools/tool-runtime/project.csproj` `Microsoft.Net.Compilers.netcore`:
 * release/2.0.0: `2.0.0-rc`
 * master: `2.0.0-rc4`

Comment (stephentoub) [reply src/Common/src/System/Collections/Generic/LargeArrayBuilder.cs]: @dagood, do you know why we're still using old(er) preview bits?  At the very least I would have thought we'd be using a shipped compiler, or if not, it'd be because we're using something cutting edge.

@OmarTawfik, in the name of moving this forward, can you avoid using the local function?

@agocke, you implemented local functions, right?  Does this crash sound familiar at all?

Comment (dagood) [reply src/Common/src/System/Collections/Generic/LargeArrayBuilder.cs]: > @dagood, do you know why we're still using old(er) preview bits?

There's an upgrade going on in https://github.com/dotnet/buildtools/pull/1661, but I don't have any broader context on why certain versions are being used.

Comment (OmarTawfik) [reply src/Common/src/System/Collections/Generic/LargeArrayBuilder.cs]: @stephentoub I'll move to a class function for now.

**Comment by OmarTawfik** [comment]
@stephentoub @dagood both NT builds are now failing because of this test `System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetAscii_Invalid`.
It might be related to #21344. @tarekgh did you see this before? it is passing locally.

**Comment by tarekgh** [comment]
> System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetAscii_Invalid.
It might be related to #21344. @tarekgh did you see this before? it is passing locally.

This 2.0 branch so this test expected to fail when running on Windows versions (I think rs2 or up). we fixed the test on the master branch. so you can ignore this failure

**Comment by OmarTawfik** [comment]
cc @karelz @joshfree

**Comment by danmosemsft** [comment]
approved
