### PR TITLE
Fix broken string resources in System.Directory.AccountManagement

### LINKED ISSUE #21496: [porting] all APIs in System.DirectoryServices.AccountManagement throw due to invalid resource in static constructor
```
  Discovering: System.DirectoryServices.AccountManagement.Tests
  Discovered:  System.DirectoryServices.AccountManagement.Tests
  Starting:    System.DirectoryServices.AccountManagement.Tests
     System.DirectoryServices.AccountManagement.Tests.GroupPrincipalTest.TestExtendedPrincipal [FAIL]
        System.TypeInitializationException : The type initializer for 'System.DirectoryServices.AccountManagement.Strin
  gResources' threw an exception.
        ---- System.Resources.MissingManifestResourceException : Could not find any resources appropriate for the speci
  fied culture or the neutral culture.  Make sure "System.DirectoryServices.AccountManagement.StringResources.resources
  " was correctly embedded or linked into assembly "System.DirectoryServices.AccountManagement" at compile time, or tha
  t all the satellite assemblies required are loadable and fully signed.
        Stack Trace:
              at System.DirectoryServices.AccountManagement.PrincipalContext.ReadServerConfig(String serverName, Server
  Properties& properties)
              at System.DirectoryServices.AccountManagement.PrincipalContext.DoServerVerifyAndPropRetrieval()
              at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name
  , String container, ContextOptions options, String userName, String password)
              at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name
  , String container, String userName, String password)
              at System.DirectoryServices.AccountManagement.Tests.PrincipalTest.RefreshContext()
              at System.DirectoryServices.AccountManagement.Tests.PrincipalTest..ctor()
              at System.DirectoryServices.AccountManagement.Tests.ComputerPrincipalTest..ctor()
           ----- Inner Stack Trace -----
              at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
              at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2
  localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
              at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIf
  NotExists, Boolean tryParents, StackCrawlMark& stackMark)
              at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists
  , Boolean tryParents)
              at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
              at System.DirectoryServices.AccountManagement.StringResources..cctor()
     System.DirectoryServices.AccountManagement.Tests.UserPrincipalTest.TestExtendedPrincipal [FAIL]
        System.TypeInitializationException : The type initializer for 'System.DirectoryServices.AccountManagement.Strin
  gResources' threw an exception.
        ---- System.Resources.MissingManifestResourceException : Could not find any resources appropriate for the speci
  fied culture or the neutral culture.  Make sure "System.DirectoryServices.AccountManagement.StringResources.resources
  " was correctly embedded or linked into assembly "System.DirectoryServices.AccountManagement" at compile time, or tha
  t all the satellite assemblies required are loadable and fully signed.
        Stack Trace:
              at System.DirectoryServices.AccountManagement.PrincipalContext.ReadServerConfig(String serverName, Server
  Properties& properties)
              at System.DirectoryServices.AccountManagement.PrincipalContext.DoServerVerifyAndPropRetrieval()
              at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name
  , String container, ContextOptions options, String userName, String password)
              at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name
  , String container, String userName, String password)
              at System.DirectoryServices.AccountManagement.Tests.PrincipalTest.RefreshContext()
              at System.DirectoryServices.AccountManagement.Tests.PrincipalTest..ctor()
              at System.DirectoryServices.AccountManagement.Tests.ComputerPrincipalTest..ctor()
           ----- Inner Stack Trace -----
              at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
              at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2
  localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
              at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIf
  NotExists, Boolean tryParents, StackCrawlMark& stackMark)
              at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists
  , Boolean tryParents)
              at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
              at System.DirectoryServices.AccountManagement.StringResources..cctor()
     System.DirectoryServices.AccountManagement.Tests.ComputerPrincipalTest.AddExistingPrincipal [FAIL]
        System.TypeInitializationException : The type initializer for 'System.DirectoryServices.AccountManagement.Strin
  gResources' threw an exception.
        ---- System.Resources.MissingManifestResourceException : Could not find any resources appropriate for the speci
  fied culture or the neutral culture.  Make sure "System.DirectoryServices.AccountManagement.StringResources.resources
  " was correctly embedded or linked into assembly "System.DirectoryServices.AccountManagement" at compile time, or tha
  t all the satellite assemblies required are loadable and fully signed.
        Stack Trace:
              at System.DirectoryServices.AccountManagement.PrincipalContext.ReadServerConfig(String serverName, Server
  Properties& properties)
              at System.DirectoryServices.AccountManagement.PrincipalContext.DoServerVerifyAndPropRetrieval()
              at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name
  , String container, ContextOptions options, String userName, String password)
              at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name
  , String container, String userName, String password)
              at System.DirectoryServices.AccountManagement.Tests.PrincipalTest.RefreshContext()
              at System.DirectoryServices.AccountManagement.Tests.PrincipalTest..ctor()
              at System.DirectoryServices.AccountManagement.Tests.ComputerPrincipalTest..ctor()
           ----- Inner Stack Trace -----
              at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
              at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2
  localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
              at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIf
  NotExists, Boolean tryParents, StackCrawlMark& stackMark)
              at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists
  , Boolean tryParents)
              at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
              at System.DirectoryServices.AccountManagement.StringResources..cctor()
     System.DirectoryServices.AccountManagement.Tests.GroupPrincipalTest.IsMemberOfTest [FAIL]
        System.TypeInitializationException : The type initializer for 'System.DirectoryServices.AccountManagement.Strin
  gResources' threw an exception.
        ---- System.Resources.MissingManifestResourceException : Could not find any resources appropriate for the speci
  fied culture or the neutral culture.  Make sure "System.DirectoryServices.AccountManagement.StringResources.resources
  " was correctly embedded or linked into assembly "System.DirectoryServices.AccountManagement" at compile time, or tha
  t all the satellite assemblies required are loadable and fully signed.
        Stack Trace:
              at System.DirectoryServices.AccountManagement.PrincipalContext.ReadServerConfig(String serverName, Server
  Properties& properties)
              at System.DirectoryServices.AccountManagement.PrincipalContext.DoServerVerifyAndPropRetrieval()
              at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name
  , String container, ContextOptions options, String userName, String password)
              at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name
  , String container, String userName, String password)
              at System.DirectoryServices.AccountManagement.Tests.PrincipalTest.RefreshContext()
              at System.DirectoryServices.AccountManagement.Tests.PrincipalTest..ctor()
              at System.DirectoryServices.AccountManagement.Tests.GroupPrincipalTest..ctor()
           ----- Inner Stack Trace -----
              at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
              at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2
  localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
              at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIf
  NotExists, Boolean tryParents, StackCrawlMark& stackMark)
              at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists
  , Boolean tryParents)
              at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
              at System.DirectoryServices.AccountManagement.StringResources..cctor()
     System.DirectoryServices.AccountManagement.Tests.ComputerPrincipalTest.TestExtendedPrincipal [FAIL]
        System.TypeInitializationException : The type initializer for 'System.DirectoryServices.AccountManagement.Strin
  gResources' threw an exception.
        ---- System.Resources.MissingManifestResourceException : Could not find any resources appropriate for the speci
  fied culture or the neutral culture.  Make sure "System.DirectoryServices.AccountManagement.StringResources.resources
  " was correctly embedded or linked into assembly "System.DirectoryServices.AccountManagement" at compile time, or tha
  t all the satellite assemblies required are loadable and fully signed.
        Stack Trace:
              at System.DirectoryServices.AccountManagement.PrincipalContext.ReadServerConfig(String serverName, Server
  Properties& properties)
              at System.DirectoryServices.AccountManagement.PrincipalContext.DoServerVerifyAndPropRetrieval()
              at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name
  , String container, ContextOptions options, String userName, String password)
              at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name
  , String container, String userName, String password)
              at System.DirectoryServices.AccountManagement.Tests.PrincipalTest.RefreshContext()
              at System.DirectoryServices.AccountManagement.Tests.PrincipalTest..ctor()
              at System.DirectoryServices.AccountManagement.Tests.ComputerPrincipalTest..ctor()
           ----- Inner Stack Trace -----
              at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
              at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2
  localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
              at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIf
  NotExists, Boolean tryParents, StackCrawlMark& stackMark)
              at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists
  , Boolean tryParents)
              at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
              at System.DirectoryServices.AccountManagement.StringResources..cctor()
     System.DirectoryServices.AccountManagement.Tests.UserPrincipalTest.AddExistingPrincipal [FAIL]
        System.TypeInitializationException : The type initializer for 'System.DirectoryServices.AccountManagement.Strin
  gResources' threw an exception.
        ---- System.Resources.MissingManifestResourceException : Could not find any resources appropriate for the speci
  fied culture or the neutral culture.  Make sure "System.DirectoryServices.AccountManagement.StringResources.resources
  " was correctly embedded or linked into assembly "System.DirectoryServices.AccountManagement" at compile time, or tha
  t all the satellite assemblies required are loadable and fully signed.
        Stack Trace:
              at System.DirectoryServices.AccountManagement.PrincipalContext.ReadServerConfig(String serverName, Server
  Properties& properties)
              at System.DirectoryServices.AccountManagement.PrincipalContext.DoServerVerifyAndPropRetrieval()
              at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name
  , String container, ContextOptions options, String userName, String password)
              at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name
  , String container, String userName, String password)
              at System.DirectoryServices.AccountManagement.Tests.PrincipalTest.RefreshContext()
              at System.DirectoryServices.AccountManagement.Tests.PrincipalTest..ctor()
              at System.DirectoryServices.AccountManagement.Tests.UserPrincipalTest..ctor()
           ----- Inner Stack Trace -----
              at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
              at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2
  localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
              at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIf
  NotExists, Boolean tryParents, StackCrawlMark& stackMark)
              at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists
  , Boolean tryParents)
              at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
              at System.DirectoryServices.AccountManagement.StringResources..cctor()
     System.DirectoryServices.AccountManagement.Tests.GroupPrincipalTest.AddExistingPrincipal [FAIL]
        System.TypeInitializationException : The type initializer for 'System.DirectoryServices.AccountManagement.Strin
  gResources' threw an exception.
        ---- System.Resources.MissingManifestResourceException : Could not find any resources appropriate for the speci
  fied culture or the neutral culture.  Make sure "System.DirectoryServices.AccountManagement.StringResources.resources
  " was correctly embedded or linked into assembly "System.DirectoryServices.AccountManagement" at compile time, or tha
  t all the satellite assemblies required are loadable and fully signed.
        Stack Trace:
              at System.DirectoryServices.AccountManagement.PrincipalContext.ReadServerConfig(String serverName, Server
  Properties& properties)
              at System.DirectoryServices.AccountManagement.PrincipalContext.DoServerVerifyAndPropRetrieval()
              at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name
  , String container, ContextOptions options, String userName, String password)
              at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name
  , String container, String userName, String password)
              at System.DirectoryServices.AccountManagement.Tests.PrincipalTest.RefreshContext()
              at System.DirectoryServices.AccountManagement.Tests.PrincipalTest..ctor()
              at System.DirectoryServices.AccountManagement.Tests.GroupPrincipalTest..ctor()
           ----- Inner Stack Trace -----
              at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
              at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2
  localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
              at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIf
  NotExists, Boolean tryParents, StackCrawlMark& stackMark)
              at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists
  , Boolean tryParents)
              at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
              at System.DirectoryServices.AccountManagement.StringResources..cctor()
     System.DirectoryServices.AccountManagement.Tests.ComputerPrincipalTest.ComputerPrincipalConstructorTest [FAIL]
        System.TypeInitializationException : The type initializer for 'System.DirectoryServices.AccountManagement.Strin
  gResources' threw an exception.
        ---- System.Resources.MissingManifestResourceException : Could not find any resources appropriate for the speci
  fied culture or the neutral culture.  Make sure "System.DirectoryServices.AccountManagement.StringResources.resources
  " was correctly embedded or linked into assembly "System.DirectoryServices.AccountManagement" at compile time, or tha
  t all the satellite assemblies required are loadable and fully signed.
  Finished:    System.DirectoryServices.AccountManagement.Tests
        Stack Trace:
              at System.DirectoryServices.AccountManagement.PrincipalContext.ReadServerConfig(String serverName, Server
  Properties& properties)
              at System.DirectoryServices.AccountManagement.PrincipalContext.DoServerVerifyAndPropRetrieval()
              at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name
  , String container, ContextOptions options, String userName, String password)
              at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name
  , String container, String userName, String password)
              at System.DirectoryServices.AccountManagement.Tests.PrincipalTest.RefreshContext()
              at System.DirectoryServices.AccountManagement.Tests.PrincipalTest..ctor()
              at System.DirectoryServices.AccountManagement.Tests.ComputerPrincipalTest..ctor()
           ----- Inner Stack Trace -----
              at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
              at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2
  localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
              at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIf
  NotExists, Boolean tryParents, StackCrawlMark& stackMark)
              at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists
  , Boolean tryParents)
              at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
              at System.DirectoryServices.AccountManagement.StringResources..cctor()
     System.DirectoryServices.AccountManagement.Tests.GroupPrincipalTest.GroupPrincipalConstructorTest [FAIL]
        System.TypeInitializationException : The type initializer for 'System.DirectoryServices.AccountManagement.Strin
  gResources' threw an exception.
        ---- System.Resources.MissingManifestResourceException : Could not find any resources appropriate for the speci
  fied culture or the neutral culture.  Make sure "System.DirectoryServices.AccountManagement.StringResources.resources
  " was correctly embedded or linked into assembly "System.DirectoryServices.AccountManagement" at compile time, or tha
  t all the satellite assemblies required are loadable and fully signed.
        Stack Trace:
              at System.DirectoryServices.AccountManagement.PrincipalContext.ReadServerConfig(String serverName, Server
  Properties& properties)
              at System.DirectoryServices.AccountManagement.PrincipalContext.DoServerVerifyAndPropRetrieval()
              at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name
  , String container, ContextOptions options, String userName, String password)
              at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name
  , String container, String userName, String password)
              at System.DirectoryServices.AccountManagement.Tests.PrincipalTest.RefreshContext()
              at System.DirectoryServices.AccountManagement.Tests.PrincipalTest..ctor()
              at System.DirectoryServices.AccountManagement.Tests.GroupPrincipalTest..ctor()
           ----- Inner Stack Trace -----
              at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
              at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2
  localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
              at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIf
  NotExists, Boolean tryParents, StackCrawlMark& stackMark)
              at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists
  , Boolean tryParents)
              at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
              at System.DirectoryServices.AccountManagement.StringResources..cctor()
```

### PR DESCRIPTION
**Pull request by hughbe**
Fixes #21496

The first commit cleans up existing tests to make them readable :D

### CODE REVIEW

File: src/System.DirectoryServices.AccountManagement/tests/ExtendedUserPrincipal.cs [hunk 1]
```diff
@@ -2,68 +2,36 @@
...
 {
     [DirectoryRdnPrefix("CN")]
     [DirectoryObjectClass("User")]
     public class ExtendedUserPrincipal : UserPrincipal, IExtendedPrincipalTest
     {
-        public ExtendedUserPrincipal(PrincipalContext context)
-            : base(context)
+        public ExtendedUserPrincipal(PrincipalContext context) : base(context) { }
+        
+        public static new ExtendedUserPrincipal FindByIdentity(PrincipalContext context,string identityValue)
```
Comment (danmosemsft) [inline src/System.DirectoryServices.AccountManagement/tests/ExtendedUserPrincipal.cs]: nit: space before comma
