### PR TITLE
Fix SortedSet constructors to use default Comparer

### LINKED ISSUE #5149: System.Collections.Generic: SortedSet constructors not properly validating passed IComparer<T>
The SortedSet constructors:
- ```new SortedSet(IComparer< T> comparer)```
- ```new SortedSet(IEnumerable< T> collection, IComparer< T> comparer)```

are not consistent with their behavior when ```comparer``` is null.

The docs for [the comparer constructor](https://msdn.microsoft.com/en-us/library/dd395024(v=vs.110).aspx) state that a null comparer should throw an ArgumentNullException. However, the code actually performs a check on the comparer if it is null and sets it to the default comparer if it is.

The docs for [the enumerable and comparer constructor](https://msdn.microsoft.com/en-us/library/dd394885(v=vs.110).aspx) neglect to mention any behavior for when the comparer is null. The code will throw a NullReferenceException on [line 148 of SortedSet.cs](https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/SortedSet.cs) when it attempts to call ```Compare``` on the null Comparer that was passed as input.

Suggested Solution:
Behavior for null Comparers should be consistent across constructors. Modify the ```SortedSet(IEnumerable< T> collection, IComparer< T> comparer)``` constructor to use the default Comparer when the passed comparer is null.

### PR DESCRIPTION
**Pull request by ianhays**
tests coming in #754

resolves #5149

### CODE REVIEW

File: src/System.Collections/src/System/Collections/Generic/SortedSet.cs [hunk 1]
```diff
@@ -145,7 +145,7 @@ public SortedSet(IEnumerable<T> collection, IComparer<T> comparer)
                     int index = 1;
                     for (int i = 1; i < count; i++)
                     {
-                        if (comparer.Compare(els[i], els[i - 1]) != 0)
+                        if (_comparer.Compare(els[i], els[i - 1]) != 0)
```
Comment (JonHanna) [inline src/System.Collections/src/System/Collections/Generic/SortedSet.cs]: I'd assume that the reason `comparer` is used is to avoid the repeated field access. Maybe assign `comparer = _comparer` (with a comment because it would look a bit strange) and keep is line as is?

Comment (ianhays) [inline src/System.Collections/src/System/Collections/Generic/SortedSet.cs]: Sure. Didn't think the overhead introduced by the extra layer of indirection to access the field would be tangible, but considering the comment overhead is 0 I'll switch to that :)

**Comment by JonHanna** [comment]
Looks good. It's still not as documented, but this is probably better than as documented so the docs should match the behaviour (which apart from this bug fix is the behaviour in other framework versions after all).

File: src/System.Collections/src/System/Collections/Generic/SortedSet.cs (hunk 1 above)
Comment (JonHanna) [inline src/System.Collections/src/System/Collections/Generic/SortedSet.cs]: I was thinking of the comment being more to answer "why assign _comparer to comparer when _comparer comes from comparer?".

**Comment by JonHanna** [comment]
@dotnet-bot test this, please.

File: src/System.Collections/src/System/Collections/Generic/SortedSet.cs [hunk 2]
```diff
@@ -143,6 +143,7 @@ public SortedSet(IEnumerable<T> collection, IComparer<T> comparer)
                 {
                     Array.Sort(els, 0, count, _comparer);
```
Comment (bartonjs) [inline src/System.Collections/src/System/Collections/Generic/SortedSet.cs]: For consistency (always reading the local), I'd suggest moving your line to before this one, and changing this to pass the normalized local (vs reading the field).

Heck, for maximum consistency it seems like you want to replace the local/argument at the first line of this method, and then just use that consistently.

Comment (ianhays) [inline src/System.Collections/src/System/Collections/Generic/SortedSet.cs]: Thanks! Moved it up before the Sort and modified it to use the local comparer.

**Comment by bartonjs** [comment]
LGTM
