### PR TITLE
Fix several code generator issues.

### LINKED ISSUE #19733: Fix several codegen issues
1. Remove the attribute class from the code generator
2. Add TimeSpan support in codegen
3. Pass the namespace information when load generated assembly

### PR DESCRIPTION
**Pull request by huanwu**
Fix the following issues.
1. Remove the attribute class from the generator
2. Add TimeSpan support in codegen
3. Pass the namespace information when load generated assembly

Fix #19733 

@shmao @zhenlan @mconnew

### CODE REVIEW

File: src/Microsoft.XmlSerializer.Generator/src/Microsoft/XmlSerializer/Generator/XmlSerializationWriter.cs [hunk 1]
```diff
@@ -2080,6 +2080,14 @@ private void WriteValue(object value)
                     {
                         Writer.Write(((int)value).ToString(null, NumberFormatInfo.InvariantInfo));
                     }
+                    else if (type == typeof(TimeSpan))
```
Comment (zhenlan) [inline src/Microsoft.XmlSerializer.Generator/src/Microsoft/XmlSerializer/Generator/XmlSerializationWriter.cs]: Should this section be moved to line 2077?

File: src/Microsoft.XmlSerializer.Generator/src/Microsoft.XmlSerializer.Generator.csproj [hunk 2]
```diff
@@ -222,8 +153,15 @@
...
     <Compile Include="Sgen.cs" />
+    <Compile Include="System\Xml\Serialization\SoapAttributesExtensions.cs" />
+    <Compile Include="System\Xml\Serialization\XmlAnyElementAttributeExtensions.cs" />
+    <Compile Include="System\Xml\Serialization\XmlArrayItemAttributeExtensions.cs" />
+    <Compile Include="System\Xml\Serialization\XmlChoiceIdentifierAttributeExtensions.cs" />
+    <Compile Include="System\Xml\Serialization\XmlElementAttributeExtension.cs" />
+    <Compile Include="System\Xml\Serialization\XmlRootAttributeExtensions.cs" />
   </ItemGroup>
   <ItemGroup>
+    <Reference Include="System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=MSIL" />
```
Comment (zhenlan) [inline src/Microsoft.XmlSerializer.Generator/src/Microsoft.XmlSerializer.Generator.csproj]: Why do we need this assembly reference?

File: src/System.Private.Xml/src/System/Xml/Serialization/XmlRootAttribute.cs [hunk 3]
```diff
@@ -88,9 +88,19 @@ internal bool IsNullableSpecified
...
+        {
+            return this.IsNullableSpecified;
+        }
+
         internal string Key
         {
             get { return (_ns == null ? String.Empty : _ns) + ":" + ElementName + ":" + _nullable.ToString(); }
         }
+
+        internal string GetKey()
```
Comment (huanwu) [inline src/System.Private.Xml/src/System/Xml/Serialization/XmlRootAttribute.cs]: It is to make the code be consistent in both xml and codegen project so we don't have to add if else condition.

File: src/Microsoft.XmlSerializer.Generator/src/Microsoft/XmlSerializer/Generator/XmlSerializationWriter.cs (hunk 1 above)
Comment (huanwu) [inline src/Microsoft.XmlSerializer.Generator/src/Microsoft/XmlSerializer/Generator/XmlSerializationWriter.cs]: I can make that change. The code was ported from the desktop.

File: src/Microsoft.XmlSerializer.Generator/src/Microsoft.XmlSerializer.Generator.csproj (hunk 2 above)
Comment (huanwu) [inline src/Microsoft.XmlSerializer.Generator/src/Microsoft.XmlSerializer.Generator.csproj]: It is not required. Will remove it.

**Comment by huanwu** [comment]
@dotnet-bot Innerloop netfx Windows_NT Debug x86 Build and Test

**Comment by huanwu** [comment]
@dotnet-bot test Innerloop netfx Windows_NT Debug x86 Build and Test

**Comment by huanwu** [comment]
@dotnet-bot test Innerloop netfx Windows_NT Release x64 Build and Test

File: src/System.Private.Xml/src/System/Xml/Serialization/XmlRootAttribute.cs (hunk 3 above)
Comment (zhenlan) [inline src/System.Private.Xml/src/System/Xml/Serialization/XmlRootAttribute.cs]: I see. Thanks.

File: src/Microsoft.XmlSerializer.Generator/src/Microsoft/XmlSerializer/Generator/XmlSerializationWriter.cs (hunk 1 above)
Comment (zhenlan) [inline src/Microsoft.XmlSerializer.Generator/src/Microsoft/XmlSerializer/Generator/XmlSerializationWriter.cs]: I saw the netfx is actually using `switch/case` instead of `if/else`
https://referencesource.microsoft.com/#System.Xml/System/Xml/Serialization/XmlSerializationWriter.cs,3049

File: src/Microsoft.XmlSerializer.Generator/src/Microsoft.XmlSerializer.Generator.csproj [hunk 4]
```diff
@@ -105,57 +81,18 @@
     <Compile Include="$(SourceDir)\System\Xml\Serialization\Types.cs">
       <Link>System\Xml\Serialization\Types.cs</Link>
     </Compile>
-    <Compile Include="$(SourceDir)\System\Xml\Serialization\XmlAnyAttributeAttribute.cs">
-      <Link>System\Xml\Serialization\XmlAnyAttributeAttribute.cs</Link>
```
Comment (shmao) [inline src/Microsoft.XmlSerializer.Generator/src/Microsoft.XmlSerializer.Generator.csproj]: Can you please remove the `#ifdef` from the files that are excluded? For example, `XmlAnyAttributeAttribute.cs` still has the following code

```
 #if XMLSERIALIZERGENERATOR
 namespace Microsoft.XmlSerializer.Generator
 #else
 namespace System.Xml.Serialization
 #endif
```

File: src/Microsoft.XmlSerializer.Generator/src/System/Xml/Serialization/SoapAttributesExtensions.cs [hunk 5]
```diff
@@ -0,0 +1,25 @@
+﻿using System;
```
Comment (shmao) [inline src/Microsoft.XmlSerializer.Generator/src/System/Xml/Serialization/SoapAttributesExtensions.cs]: Add copy right header at the beginning. It'd be good to use CodeFormatter to scan the project and fix the issues like this.

File: src/Microsoft.XmlSerializer.Generator/src/System/Xml/Serialization/SoapAttributesExtensions.cs [hunk 6]
```diff
@@ -0,0 +1,25 @@
...
+using System.Text;
+using System.Threading.Tasks;
+
+namespace System.Xml.Serialization
+{
+    internal static class SoapAttributesExtensions
+    {
+        internal static SoapAttributeFlags GetSoapFlags(this SoapAttributes soapAtt)
+        {
+            return (SoapAttributeFlags)soapAtt.GetType().GetProperty("SoapFlags", BindingFlags.NonPublic | BindingFlags.Instance).GetValue(soapAtt);
```
Comment (shmao) [inline src/Microsoft.XmlSerializer.Generator/src/System/Xml/Serialization/SoapAttributesExtensions.cs]: Do we want to cache the property?

File: src/System.Private.Xml/src/System/Xml/Serialization/SoapAttributes.cs [hunk 7]
```diff
@@ -101,6 +101,11 @@ internal SoapAttributeFlags SoapFlags
             }
         }
 
+        internal SoapAttributeFlags GetSoapFlags()
+        {
+            return this.SoapFlags;
```
Comment (shmao) [inline src/System.Private.Xml/src/System/Xml/Serialization/SoapAttributes.cs]: `this` can be omitted.

File: src/Microsoft.XmlSerializer.Generator/src/Microsoft.XmlSerializer.Generator.csproj (hunk 4 above)
Comment (huanwu) [inline src/Microsoft.XmlSerializer.Generator/src/Microsoft.XmlSerializer.Generator.csproj]: Will do.

File: src/Microsoft.XmlSerializer.Generator/src/Microsoft/XmlSerializer/Generator/XmlSerializationWriter.cs (hunk 1 above)
Comment (huanwu) [inline src/Microsoft.XmlSerializer.Generator/src/Microsoft/XmlSerializer/Generator/XmlSerializationWriter.cs]: Yes, I compared the code in desktop and found the code in core is a little different from desktop, which all use if/else instead of switch/case. I don't know why they change the format when port the code in core. It is out of scope of this checkin. We can review later. Now I just need make sure it will generate the right code when type is TimeSpan.

File: src/Microsoft.XmlSerializer.Generator/src/Microsoft/XmlSerializer/Generator/XmlSerializationWriter.cs [hunk 8]
```diff
@@ -2074,20 +2074,21 @@ private void WriteValue(object value)
...
                     }
-                    else if (type == typeof(TimeSpan))
-                    {
-                        Writer.Write(" new ");
-                        Writer.Write(type.FullName);
-                        Writer.Write("(");
-                        Writer.Write(((TimeSpan)value).Ticks.ToString(CultureInfo.InvariantCulture));
-                        Writer.Write(")");
-                    }
+
```
Comment (shmao) [inline src/Microsoft.XmlSerializer.Generator/src/Microsoft/XmlSerializer/Generator/XmlSerializationWriter.cs]: Remove the empty line.

File: src/Microsoft.XmlSerializer.Generator/src/Microsoft.XmlSerializer.Generator.csproj [hunk 9]
```diff
@@ -222,6 +153,12 @@
     <Compile Include="Microsoft\XmlSerializer\Generator\XmlSerializationReader.cs" />
     <Compile Include="Microsoft\XmlSerializer\Generator\XmlSerializationWriter.cs" />
     <Compile Include="Sgen.cs" />
+    <Compile Include="System\Xml\Serialization\SoapAttributesExtensions.cs" />
```
Comment (shmao) [inline src/Microsoft.XmlSerializer.Generator/src/Microsoft.XmlSerializer.Generator.csproj]: The file is for SGen only. Should the file be under `Microsoft\XmlSerializer\Generator`?

File: src/Microsoft.XmlSerializer.Generator/src/System/Xml/Serialization/SoapAttributesExtensions.cs [hunk 10]
```diff
@@ -0,0 +1,35 @@
...
+// See the LICENSE file in the project root for more information.
+
+using System;
+using System.Collections.Generic;
+using System.Linq;
+using System.Reflection;
+using System.Text;
+using System.Threading.Tasks;
+
+namespace System.Xml.Serialization
```
Comment (shmao) [inline src/Microsoft.XmlSerializer.Generator/src/System/Xml/Serialization/SoapAttributesExtensions.cs]: Should the namespace be `Microsoft.XmlSerializer.Generator`?

File: src/Microsoft.XmlSerializer.Generator/src/System/Xml/Serialization/XmlChoiceIdentifierAttributeExtensions.cs [hunk 11]
```diff
@@ -0,0 +1,38 @@
...
+
+            return (MemberInfo)s_MemberInfoPropertyInfo.GetValue(xmlChoiceIdentifierAtt);
+        }
+
+        internal static void SetMemberInfo(this XmlChoiceIdentifierAttribute xmlChoiceIdentifierAtt, MemberInfo memberInfo)
+        {
+            if (s_MemberInfoPropertyInfo == null)
+            {
+                s_MemberInfoPropertyInfo = typeof(XmlChoiceIdentifierAttribute).GetProperty("MemberInfo", BindingFlags.NonPublic | BindingFlags.Instance);
+            }
```
Comment (shmao) [inline src/Microsoft.XmlSerializer.Generator/src/System/Xml/Serialization/XmlChoiceIdentifierAttributeExtensions.cs]: The code is duplicated. Can you please extract the code into a method/property?
