### PR TITLE
Fix client certificate lifetime handling in tests

### LINKED ISSUE #9543: Test failure: Manual_CertificateSentMatchesCertificateReceived_Success
The test as currently written fails sporadically on Windows.  If, however, `GC.Collect(); GC.WaitForPendingFinalizers();` is added inside the loop here: https://github.com/dotnet/corefx/blob/483aa5a3012fe78ea001ece1b0404b18c0b90a29/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.ClientCertificates.cs#L117
the `reuseClient==false` test fails deterministically for me with the error "The client certificate credentials were not recognized".  It appears something is getting finalized and preventing the same certificate instance from being used with subsequent HttpClientHandler instances.

### PR DESCRIPTION
**Pull request by davidsh**
This was a difficult bug to track down. Our use of importing PFX files into the
tests has problems due to a combination of issues. The summary is that these
issues cause the private key (which is written to a temp file on disk) to get
corrupted/deleted. This is why we would get random errors about "invalid client
credentials" when using client certificates in HttpClient (or SslStream).

Thanks to @bartonjs for helping me work thru this.

The lifetime of the temp file containing the private key is associated with the managed
X509Certificate2 object that is created. However, our use of X509Certificate2Collection
followed by the use of the .Find() API in [GetEligibleClientCertificate](https://github.com/dotnet/corefx/blob/10aa8277de2521fb1e6a5b42d053ad8cc947be81/src/Common/src/System/Net/Security/CertificateHelper.cs#L55-L59) causes new managed objects to get created including both a new collection object and
new certificate objects wrapping the existing native PCCERT_CONTEXT of the old managed
certificate object. This causes lifetime issues for the temp file containing the private
key since the old managed objects are GC'd.

In terms of fixing this for the tests, I've optimized the Configuration.Certificates
helper and removed constructs that we don't actually use in our tests. Switching from
using .Import() on the collection object to actually creating the X509Certificate2
object directly helps with managing the lifetime of the certificate.

I will be doing a follow-up PR to optimze GetEligibleClientCertificate() to switch from
using .Find() and instead directly query the certificates in the original collection.
This will result in less managed objects being created as well as avoid additional private
key lifetime issues for certificates imported that use the default X509KeyStorage.DefaultKeySet
flags.

I also fixed a problem with the test which was always failing on NETFX.

Closes #9543

### CODE REVIEW

**Comment by davidsh** [comment]
@dotnet-bot test Outerloop Windows x64 Debug Build
@dotnet-bot test Outerloop Linux x64 Debug Build
@dotnet-bot test Outerloop NETFX x86 Debug Build
@dotnet-bot test Outerloop UWP CoreCLR x64 Debug Build

**Comment by davidsh** [comment]
@dotnet-bot test Outerloop Windows x64 Debug Build
@dotnet-bot test Outerloop Linux x64 Debug Build
@dotnet-bot test Outerloop NETFX x86 Debug Build
@dotnet-bot test Outerloop UWP CoreCLR x64 Debug Build

File: src/Common/tests/System/Net/Configuration.Certificates.cs [hunk 1]
```diff
@@ -35,68 +35,55 @@ static Certificates()
...
-            public static X509Certificate2Collection GetSelfSignedClientCertificateCollection() => GetCertificateCollection("testselfsignedclienteku.contoso.com.pfx");
+                return certs;
+            }
 
-            private static X509Certificate2Collection GetCertificateCollection(string certificateFileName)
+            private static X509Certificate2 GetCertificate(string certificateFileName)
             {
                 // On Windows, .NET Core applications should not import PFX files in parallel to avoid a known system-level race condition.
                 // This bug results in corrupting the X509Certificate2 certificate state.
                 Assert.True(m.WaitOne(MutexTimeout), "Cannot acquire the global certificate mutex.");
```
Comment (stephentoub) [inline src/Common/tests/System/Net/Configuration.Certificates.cs]: Now that you've updated the certs, does this race condition still exist, or can we remove this mutex?

**Comment by davidsh** [comment]
Unrelated CI failures (mostly Nano related).

File: src/Common/tests/System/Net/Configuration.Certificates.cs (hunk 1 above)
Comment (davidsh) [reply src/Common/tests/System/Net/Configuration.Certificates.cs]: The race condition on the import of the PFX seems to be a different problem than the one I solved by updating the certs (to remove the friendlyname of private key).  I'm still investigating to see if we can remove the mutex.

**Comment by davidsh** [comment]
cc: @dotnet/ncl

**Comment by davidsh** [comment]
>There are cert-related failures on Unix. Are those related to your having updated certs?

No.  The System.Security.Cryptography.X509Certificates.Tests don't use the System.Net testdata certs nor the System.Net.Configuration.Certificates.cs logic.

File: src/Common/tests/System/Net/Configuration.Certificates.cs (hunk 1 above)
Comment (davidsh) [reply src/Common/tests/System/Net/Configuration.Certificates.cs]: Update:  turns out I hadn't retested removing the Mutex since my very latest changes here. I'm able to remove it now and the tests pass.

**Comment by davidsh** [comment]
@dotnet-bot test Outerloop Windows x64 Debug Build
@dotnet-bot test Outerloop Linux x64 Debug Build
@dotnet-bot test Outerloop NETFX x86 Debug Build
@dotnet-bot test Outerloop UWP CoreCLR x64 Debug Build

**Comment by bartonjs** [comment]
Seemingly, it's either 2024 now or those machines no longer trust the Symantec/VeriSign CA which issued that cert.

The failures are in the xunit log, but I don't see how to get that anymore.

**Comment by davidsh** [comment]
Since these failures are not related to the PR, I'm merging it.
