### PR TITLE
GetNumberGroupSizes test fails on OSX Yosemite.

### LINKED ISSUE #4667: NumberFormatInfoNumberGroupSizes.TestNumberGroupSizesLocale failing on OS X
```
20:31:33    System.Globalization.Tests.NumberFormatInfoNumberGroupSizes.TestNumberGroupSizesLocale(locale: "ur-IN") [FAIL]
20:31:33       Assert.Equal() Failure
20:31:33       Expected: Int32[] [3]
20:31:33       Actual:   Int32[] [3, 2]
20:31:33       Stack Trace:
20:31:33             at System.Globalization.Tests.NumberFormatInfoNumberGroupSizes.TestNumberGroupSizesLocale(String locale)
```

### PR DESCRIPTION
**Pull request by eerhardt**
The culture data for ur-IN is different on OSX El Capitan than on Yosemite.  Thus we have a failing test that is expecting the wrong data.

This fix gets the current OSX Kernel version by P/Invoking sysctlbyname("kern.osrelease") and compares it to 15.0 (El Capitan).

Fix #4667 

@tarekgh @stephentoub @mellinoe

### CODE REVIEW

**Comment by tarekgh** [comment]
LGTM. 

I think in the future we need to change such tests to read the underlying OS data and compare against it. I know this is not trivial but I think doing that will not require us to change the test when the data change.

File: src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs [hunk 1]
```diff
@@ -93,5 +97,22 @@ internal static int[] GetCurrencyNegativePatterns(CultureInfo cultureInfo)
...
+                sysctlbyname("kern.osrelease", bytes, ref bytesLength, null, 0);
+                string versionString = Encoding.UTF8.GetString(bytes);
+                return Version.Parse(versionString);
+            }
+            
+            return new Version(0, 0, 0);
+        }
+        
+        [DllImport("libc")]
+        private static extern int sysctlbyname(string ctlName, byte[] oldp, ref ulong oldpLen, byte[] newp, ulong newpLen);
```
Comment (stephentoub) [inline src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs]: The lengths are size_t, so would oldpLen and newpLen be better as ref IntPtr and IntPtr? And should this be SetLastError = true as well?  Separately we should think through how we want to handle this kind of P/Invoking in tests.

File: src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs [hunk 2]
```diff
@@ -93,5 +97,22 @@ internal static int[] GetCurrencyNegativePatterns(CultureInfo cultureInfo)
...
             throw DateTimeFormatInfoData.GetCultureNotSupportedException(cultureInfo);
         }
+        
+        private static Version GetOSXKernelVersion()
+        {
+            if (s_isOSX)
+            {
+                ulong bytesLength = 256;
+                byte[] bytes = new byte[bytesLength];
+                sysctlbyname("kern.osrelease", bytes, ref bytesLength, null, 0);
```
Comment (stephentoub) [inline src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs]: Assert this returns 0?

File: src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs (hunk 1 above)
Comment (stephentoub) [inline src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs]: Also, I wonder if we're going to run into this in other places, and if so whether we should centralize this check somewhere to make it available to other tests in the future.

It'd also be nice if we could avoid needing such a P/Invoke in the tests, and instead have such version information exposed from RuntimeInformation, such that tests like this could then just use it. cc: @Priya91

**Comment by stephentoub** [comment]
A few comments, but otherwise LGTM.  Thanks.

File: src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs [hunk 3]
```diff
@@ -10,6 +11,7 @@ internal static class NumberFormatInfoData
         private static bool s_isWindows = RuntimeInformation.IsOSPlatform(OSPlatform.Windows);
         private static int s_WindowsVersion = DateTimeFormatInfoData.GetWindowsVersion();
         private static bool s_isOSX = RuntimeInformation.IsOSPlatform(OSPlatform.OSX);
+        private static Version s_OSXKernelVersion = GetOSXKernelVersion();
```
Comment (justinvp) [inline src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs]: Should these be `readonly`?

**Comment by stephentoub** [comment]
Since there are only nits (from me and Justin) and I'd like to try to get the OS X CI run unblocked, I'm going to merge this, and the nits can be addressed subsequently.

File: src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs (hunk 1 above)
Comment (eerhardt) [inline src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs]: > The lengths are size_t, so would oldpLen and newpLen be better as ref IntPtr and IntPtr?

Since this code is OSX specific, I thought the ABI was already constant? Which is why we don't need shims for OSX specific native calls in the product.

> And should this be SetLastError = true as well?

Added.

> Also, I wonder if we're going to run into this in other places, and if so whether we should centralize this check somewhere to make it available to other tests in the future.

I like using the rule "2nd time pays for generality".  So if/when we need it somewhere else, we can refactor it there at that time.

> It'd also be nice if we could avoid needing such a P/Invoke in the tests, and instead have such version information exposed from RuntimeInformation

#4334 adds a RuntimeInformation.OSDescription string, which will look something like `Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46`, which could be parsed by this test (once the API is added).  However, I didn't think it would be good to rely on the structure of this string.

Comment (stephentoub) [inline src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs]: > However, I didn't think it would be good to rely on the structure of this string.

@weshaggard, without exposing version information, how are developers supposed to do this kind of thing?  I keep hearing "they should instead use feature detection"... how does that work in a case like this?

Comment (tarekgh) [inline src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs]: I want to emphasize for the globalization in general, the developers shouldn't assume any specific data and should behave according to what we/OS provide. so in real scenarios they shouldn't need to check the OS version. I can understand we add this in our testing to validate what we are reading but I have suggested in the future we shouldn't write the test like that and instead the test should read the OS data and validate it against what the framework is providing.

Comment (weshaggard) [inline src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs]: +1 for @tarekgh's suggestion, I think we should actually file a bug against these tests and remove the explicit version checks. Please do not parse the OSDescription as that is definitely going to fail over time.

Comment (stephentoub) [inline src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs]: > the test should read the OS data and validate it against what the framework is providing.

FWIW, I'm not convinced that's much better.  Then we're essentially just writing the same code twice and validating that we got the same answer in both cases, in the code in the product that reads it and in the code in the test that reads it.  While it would help to catch bugs due to typos and the like, if we misunderstand the structure of the data or how it's meant to be interpreted, we're likely to make that mistake in both places.

This is also just one example of a much larger issue: the underlying OS adds features or makes changes, there's no good way in managed code to do feature detection, and the underlying systems actually advertise that those features are available starting in a particular version, yet we don't expose such version information in a consumable fashion and instead state that developers shouldn't use version numbers for this purpose.  For example, the man page for getrandom (http://man7.org/linux/man-pages/man2/getrandom.2.html) states it "was introduced in version 3.17 of the Linux kernel"... so what's our recommendation for that case?

Comment (tarekgh) [inline src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs]: >  if we misunderstand the structure of the data or how it's meant to be interpreted, we're likely to make that mistake in both places.

This is possible but still current way of testing is not helping with this issue either. usually people very activate in complaining about the globalization data so if we run in such case most likely someone will report it even our test didn't catch it. the current way the test is written means any change in the OS side we have to go and fix the test again and again which I don't think this is good to do. 

> This is also just one example of a much larger issue
I agree with you we may run into other scenarios which may need checking the OS type and version but I wanted to clarify for this specific globalization issue, this is not really needed because if any dev write code depend on that will broken sooner or later.

Comment (stephentoub) [inline src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs]: > means any change in the OS side we have to go and fix the test again and again which I don't think this is good to do. 

At least from my perspective, that's the lesser of two evils.  While I agree it's not ideal, at least then we're forced to make a human judgement about the data that's coming back from our API, validate that it makes sense, and then lock that in to the test by verifying the known state as valid for a particular version.

Comment (tarekgh) [inline src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs]: Note that we are currently very small set of data. if we add more and more such tests we'll run into such issues all the time, Also I am expecting in the near future we'll run the tests on different versions of the same OS and at that time we'll have to make the test more complicated to handle all possible versions we run on. we are currently suffering from this way of testing in the desktop because of the legacy tests written assuming some specific data and that is not valid anymore. the cost maintaining such test is really high especially when the test cover more cases. 
if we make the test read the OS data we'll not need to visit the issue again. if we have any bug in reading the data, that most likely will be reported and we'll fix it once for good.

Comment (stephentoub) [inline src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs]: > if we have any bug in reading the data, that most likely will be reported and we'll fix it once for good.

Then what's the point of having the test?  I'm saying that a bit facetiously, but we're basically saying that we're going to do the same thing twice and verify we got the same results each time.  

But let's say we do that: how do we write the regression test for the reported failure?

Comment (tarekgh) [inline src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs]: We don't need to write a regression test if we fixed the issue. that is my point, if we start writing the test way depend on the OS and on the data, we'll go into the same situation we have with the legacy tests. other example of this can be broken even if we test again some specific version and specific data is, someone on Windows install custom culture override the data. I know this scenario is not popular but possible.

by the way I wrote a test on Windows which do what I am saying and covering much more areas and was reliable when running on different Windows versions.

I see your point but I am seeing the heavy cost down the road too if we continue with the current approach. 

Also let's focus now on the original issue which is do we really need to provide the devs with aw ay to check specific OS type and version.

Comment (stephentoub) [inline src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs]: > by the way I wrote a test on Windows which do what I am saying and covering much more areas and was reliable when running on different Windows versions.

Reliable, sure. Accurate in detecting failure, who knows ;)

Anyway, I've made my points, and I know you understand them.  It seems we just fundamentally disagree.

I believe we need to expose OS version information.  We're not doing so out of fear that developers may misuse it.  So be it.  If we don't provide it, developers are going to find worse, less reliable, less efficient ways to get at it, making the end result worse than if we'd just provided it in the first place.

Comment (eatdrinksleepcode) [inline src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs]: If I may interject...

I agree with @stephentoub: doing the same thing in the tests that you do in the code and then asserting that you get the same result is not a particularly valuable test. However, @tarekgh's point about the underlying data changing is also well taken. Choosing between "the lesser of two evils" seems to be the only choice in the current setup.

May I suggest that the reason for this difficulty is that these unit tests have a dependency on an external system over which the tests have no control: namely, the underlying OS. This results in a situation where the test does not control its input data, which is counter to the usual goals for unit tests (well-known inputs produce well-known outputs). The typical way to achieve this goal is to stub the external dependency to use well-known data; in this case, stub the underlying system calls to return representative data sets.

The downside of using such stubs is that the tests now only provide confidence that the code works given the well-known input data in the tests; there needs to be a corresponding confidence that the OS will actually supply data like what is in the tests in order to complete the chain. This can be accomplished using a form of contract test: a test that is specifically designed to validate that the external dependency returns the data (the "contract") that you expect in your unit tests. The key is that because these contract tests will only fail when the external dependency changes, and the external dependency in this case is the OS which will not change very often in CI, they don't need to run in CI. They only really need to be run any time the external dependency changes (which in the case of CoreFX would be when a new OS or OS version is added to the supported list).

This makes the tests much more valuable because it means that we can essentially test all of the expected scenarios from all OSs with normal CI _and_ local developer builds. Having CI for all possible OSs is not necessary, and a local developer doesn't have to wait for a full CI run to know if he has broken a scenario from an OS other than what is available to him.

Contract tests also address another point that @stephentoub brought up:

>> how do we write the regression test for the reported failure?

> We don't need to write a regression test if we fixed the issue.

If I understand correctly, inherent in @tarekgh's response is that you will know if you fixed the issue by running the tests _on the OS on which the issue was found_. By using contract tests, you can instead add a new contract to the unit tests that _represents_ that OS, then fix the issue, which will cause that test to pass, all on your local machine, regardless of its OS. The only thing you need the OS in question for is to establish the contract.

The downside to this approach is that running unit tests alone on an OS is not sufficient to determine whether that OS is fully supported by the framework. But that is simple to overcome: simply run the contract tests as well. In this way, the activities of everyday development are separated from the activity of supporting a new OS (or OS version), which IMHO is a good thing.

Stubbing the underlying OS is probably not a common approach; I don't know if there are any tests currently in CoreFX that take this approach. But for a framework with cross-platform ambitions like CoreFX, I think it is an approach worth considering.

Comment (weshaggard) [inline src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs]: Thanks for the feedback @eatdrinksleepcode it is a very insightful approach. I'm not sure how difficult it will be for that level of abstraction in the culture data but it would certainly be something we should consider, as I agree that both of the existing approaches aren't ideal. That said given the options of checking the OS version verse just asking the OS for the data I prefer the latter, if anything. I have similar concerns with tests that check the resource strings as they are very fragile in general and essentially hard coding the strings and expect them to never change or be localized. 

@stephentoub please decouple this issue from providing an API for getting the OS version. We have had that conversation numerous times but if you want to continue that discussion please file a separate issue explicitly for that.

Comment (stephentoub) [inline src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs]: > please decouple this issue

https://github.com/dotnet/corefx/issues/4741

Comment (eerhardt) [inline src/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoData.cs]: I know we've beaten this issue over and over on this thread, but I just wanted to respond to a few points.

> "just asking the OS for the data"

It isn't that simple. On Windows it might be that simple to just call a native method to get the culture data, but on Unix we are using ICU, and then doing our own logic on top of it where necessary.  One such example is https://github.com/dotnet/coreclr/blob/master/src/corefx/System.Globalization.Native/localeNumberData.cpp#L258 where we turn an ICU string number pattern into one of our own enum values. This parsing logic isn't simple, and to @stephentoub's point, if the test had to do the same thing, we wouldn't really be testing anything.  Note there are other cases like this, just poke around under coreclr/src/corefx/System.Globalization.Native to see them.

Building on this point, @eatdrinksleepcode, you bring up a really good idea and is the real way to solve this issue IMO. However, it would be a lot of work to get some sort of stub in place. A good chunk of the code we are testing here is native code built around ICU. We would need to inject the stub lower than that native code in order to keep it under test. Some day we might be able to build something like this, but I just don't think we have the time/resources right now.
