### PR TITLE
Increasing mutex time, ensuring the mutex is released

### LINKED ISSUE #19430: SslStream test failing to access Mutex
@cipop, this looks like fall out from your recent change:
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release_prtest/3093/consoleText
```
System.Net.Security.Tests.SslStreamStreamToStreamTest_Async.SslStream_StreamToStream_Successive_ClientWrite_Sync_Success [FAIL]
        Cannot acquire the global certificate mutex.
        Expected: True
        Actual:   False
        Stack Trace:
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release_prtest/src/Common/tests/System/Net/Configuration.Certificates.cs(38,0): at System.Net.Test.Common.Configuration.Certificates.GetCertificateCollection(String certificateFileName)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release_prtest/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(391,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest_Async.DoHandshake(SslStream clientSslStream, SslStream serverSslStream)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release_prtest/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(78,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest.SslStream_StreamToStream_Successive_ClientWrite_Sync_Success()
     System.Net.Security.Tests.SslStreamStreamToStreamTest_BeginEnd.SslStream_StreamToStream_Authentication_Success [FAIL]
        Cannot acquire the global certificate mutex.
        Expected: True
        Actual:   False
        Stack Trace:
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release_prtest/src/Common/tests/System/Net/Configuration.Certificates.cs(38,0): at System.Net.Test.Common.Configuration.Certificates.GetCertificateCollection(String certificateFileName)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release_prtest/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(404,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest_BeginEnd.DoHandshake(SslStream clientSslStream, SslStream serverSslStream)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release_prtest/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(36,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest.SslStream_StreamToStream_Authentication_Success()
```

### PR DESCRIPTION
**Pull request by CIPop**
Also fixing parallel test execution script.

Fixes #19430

### CODE REVIEW

**Comment by CIPop** [comment]
@dotnet-bot help

**Comment by CIPop** [comment]
@dotnet-bot test outerloop netcoreapp Windows 10 Debug
@dotnet-bot test outerloop netcoreapp Ubuntu16.04 Debug
@dotnet-bot test outerloop netcoreapp OSX10.12 Debug
@dotnet-bot test outerloop netcoreapp OSX10.12 Release

File: src/Common/tests/System/Net/Configuration.Certificates.cs [hunk 1]
```diff
@@ -45,14 +45,24 @@ private static X509Certificate2Collection GetCertificateCollection(string certif
             {
                 // On Windows, .Net Core applications should not import PFX files in parallel to avoid a known system-level race condition.
                 // This bug results in corrupting the X509Certificate2 certificate state.
-                Assert.True(m.WaitOne(MutexTimeout), "Cannot acquire the global certificate mutex.");
-
-                var certCollection = new X509Certificate2Collection();
-                certCollection.Import(Path.Combine(TestDataFolder, certificateFileName), CertificatePassword, X509KeyStorageFlags.DefaultKeySet);
+                try
+                {
+                    Assert.True(m.WaitOne(MutexTimeout), "Cannot acquire the global certificate mutex.");
```
Comment (kouvel) [inline src/Common/tests/System/Net/Configuration.Certificates.cs]: If this assertion fails, it would still call `ReleaseMutex()`, which would throw and hide the assertion failure exception.

File: src/Common/tests/System/Net/Configuration.Certificates.cs [hunk 2]
```diff
@@ -45,14 +45,24 @@ private static X509Certificate2Collection GetCertificateCollection(string certif
...
 
-                m.ReleaseMutex();
+                    var certCollection = new X509Certificate2Collection();
+                    certCollection.Import(Path.Combine(TestDataFolder, certificateFileName), CertificatePassword, X509KeyStorageFlags.DefaultKeySet);
```
Comment (kouvel) [inline src/Common/tests/System/Net/Configuration.Certificates.cs]: If this throws, I assume the `Debug.Fail()` would crash the process on debug builds, in which case it would not call `ReleaseMutex()` and that may in turn unnecessarily cause `AbandonedMutexException` to be thrown in a parallel run (if the mutex happens to be opened in a parallel run as well).

If you want to use `Debug.Fail`, I would suggest something like this:
```c#
try
{
    // Assert.True(WaitOne)
}
catch(AbandonedMutexException)
{
}

try
{
    try
    {
        // Locked code
    }
    finally
    {
        // ReleaseMutex
    }
}
catch(Exception ex)
{
    // Debug.Fail
}
```

File: src/Common/tests/System/Net/Configuration.Certificates.cs (hunk 1 above)
Comment (kouvel) [inline src/Common/tests/System/Net/Configuration.Certificates.cs]: Actually, it would just hit the `Debug.Fail` and stop there on debug builds

File: src/Common/tests/System/Net/Configuration.Certificates.cs (hunk 2 above)
Comment (kouvel) [inline src/Common/tests/System/Net/Configuration.Certificates.cs]: Another issue is the rethrow would cause the stack trace of the original exception to be lost. I suggest rethrowing an new exception, passing in the original exception as the inner exception so that the stack trace is retained.

Comment (CIPop) [inline src/Common/tests/System/Net/Configuration.Certificates.cs]: I've tested this and made it crash by forcing an exception. The second instance won't throw the exception.  I think that's because GC will still run the finalizer at some point before the process crashes.

In release this won't be a problem (the `finally` always gets executed).

Comment (kouvel) [inline src/Common/tests/System/Net/Configuration.Certificates.cs]: > I think that's because GC will still run the finalizer at some point before the process crashes.

I assume you're talking about the finally block, it seems odd to me that it can run before the catch block finishes executing. If I have code below the Debug.Fail in the catch block, I wouldn't expect that to run either, and so the finally block shouldn't run either otherwise the code would run in incorrect program order. Not sure what's happening here, but there are tests that verify abandoning global mutexes cross-process.

**Comment by CIPop** [comment]
Outerloop failures are caused by other issues:

- Win10 is triggered but not executing (@mmitche I believe this is known)
- OSX issues: #20126, #20040, #20128
- Ubuntu issue: #20040

File: src/Common/tests/System/Net/Configuration.Certificates.cs (hunk 2 above)
Comment (CIPop) [inline src/Common/tests/System/Net/Configuration.Certificates.cs]: > I assume you're talking about the finally block, it seems odd to me that it can run before the catch block finishes executing

No, I'm talking about the mutex finalizer (not the `finally` block). 
I get the AbandonedMutexException only when the process is killed via something like Task Manager.

MSDN is not clear on the semantics. The Albahari C# in a Nutshell book is saying that "Closing or disposing a Mutex automatically releases it". A normal application shutdown will run all finalizers of Disposable objects.

This seems to be in-line with the behavior that I'm observing: a "normal" application termination will not hold the mutex even if ReleaseMutex is not called.

Comment (kouvel) [inline src/Common/tests/System/Net/Configuration.Certificates.cs]: Ah ok, finalizers don't specially run on graceful/normal shutdown in .NET Core, especially for reachable objects, that documentation reflects what the .NET Framework does. As far as I'm aware, finalizers also don't specially run on abrupt shutdown / crashes either. If Debug.Fail crashes the process as expected, that would be somewhat equivalent to killing the process. I'll try it out later and see what's going on.

Comment (CIPop) [inline src/Common/tests/System/Net/Configuration.Certificates.cs]: Thanks for clarifying! Then it might be worth investigating. 

I've already tested abrupt shutdown/crash: that will indeed cause the described issue. `Debug.Fail` seems to be the only particularity in this case.

File: src/Common/tests/System/Net/Configuration.Certificates.cs (hunk 1 above)
Comment (stephentoub) [inline src/Common/tests/System/Net/Configuration.Certificates.cs]: But on release builds wouldn't it end up trying to release a mutex it doesn't own?

File: src/Common/tests/System/Net/Configuration.Certificates.cs [hunk 3]
```diff
@@ -45,14 +45,24 @@ private static X509Certificate2Collection GetCertificateCollection(string certif
             {
                 // On Windows, .Net Core applications should not import PFX files in parallel to avoid a known system-level race condition.
                 // This bug results in corrupting the X509Certificate2 certificate state.
-                Assert.True(m.WaitOne(MutexTimeout), "Cannot acquire the global certificate mutex.");
-
-                var certCollection = new X509Certificate2Collection();
-                certCollection.Import(Path.Combine(TestDataFolder, certificateFileName), CertificatePassword, X509KeyStorageFlags.DefaultKeySet);
+                try
```
Comment (CIPop) [inline src/Common/tests/System/Net/Configuration.Certificates.cs]: Yes, that's correct but the lock wasn't added now.

We've considered what you're proposing in the original PR but that change would have required major changes in all test code to ensure that they don't dispose of the certificates.

Comment (stephentoub) [inline src/Common/tests/System/Net/Configuration.Certificates.cs]: > to ensure that they don't dispose of the certificates.

No, that's why I said "and handing back copies of it".

Comment (bartonjs) [inline src/Common/tests/System/Net/Configuration.Certificates.cs]: new X509Certificate2(aCertFromAPfxWithoutPersistKeySet).Dispose() invalidates the private key for all holders.  There's no safe clone operation for certs with private keys other than persist (which fills the hard drive slowly unless manual cleanup code is added) or ephemeral (which isn't in netfx so they can't use it).

Comment (stephentoub) [inline src/Common/tests/System/Net/Configuration.Certificates.cs]: > new X509Certificate2(aCertFromAPfxWithoutPersistKeySet).Dispose() invalidates the private key for all holders

Ugh

> There's no safe clone operation for certs with private keys other than persist (which fills the hard drive slowly unless manual cleanup code is added)

Why can't it be persisted, loaded, and then after it's loaded the temp file deleted?

Comment (stephentoub) [inline src/Common/tests/System/Net/Configuration.Certificates.cs]: > new X509Certificate2(aCertFromAPfxWithoutPersistKeySet).Dispose()

Also, you're saying that if I do:
```C#
X509Certificate2 orig = ...;
X509Certificate2 clone = new X509Certificate2(orig);
orig.Dispose();
```
then `clone` is no longer usable?  That's... well.. 😦

File: src/Common/tests/System/Net/Configuration.Certificates.cs (hunk 1 above)
Comment (CIPop) [inline src/Common/tests/System/Net/Configuration.Certificates.cs]: In that case the finally block will throw "Object synchronization method was called from an unsynchronized block of code." which will still crash the process (which is what we want but with the wrong error message). 

Please reopen the bug if we should change that (we'd need to change the 2.0 port as well).

Comment (kouvel) [inline src/Common/tests/System/Net/Configuration.Certificates.cs]: Yes

File: src/Common/tests/System/Net/Configuration.Certificates.cs (hunk 3 above)
Comment (bartonjs) [inline src/Common/tests/System/Net/Configuration.Certificates.cs]: > Or you're saying the only way to do it would be to store it to something in the store itself?

No, while you need to use PersistKeySet if you want to add it to a store, that flag just means "don't delete the keyfile on the SafeHandle release".  Opening the first instance with PersistKeySet and manually opening a CngKey for the private key and calling Delete on it at shutdown would work to allow safe clones.  But what's going to actually end up calling delete? There's not a Main() here to put a finally in.

And `orig` is... maybe usable in your sample.  If it's a public only, private via the store, private via EphemeralKeySet or private via PersistKeySet; then it works fine.  If it's private via perphemeral import then private key operations start failing, but public key operations still succeed.

(This message brought to you by: Sunburn.  Sunburn, the body's way of saying "you're a software developer, why did you go outside?" and "stay indoors")

File: src/Common/tests/System/Net/Configuration.Certificates.cs (hunk 1 above)
Comment (kouvel) [inline src/Common/tests/System/Net/Configuration.Certificates.cs]: I think it would be good to change, as hiding assertion failure exceptions makes the test more difficult to diagnose, though not by much in this case. Probably not critical but maybe as cleanup.

**Comment by bartonjs** [comment]
@CIPop A thing that I thought of somewhat recently is that you can do parallel load as long as you can guarantee that the desired filename is taken.  It may have the side effect of leaving a file permanently on disk.

```C#
// Ideally this would get disposed by something on shutdown, but maybe it's fine.
s_keepalive = LoadCertificate();
```

Since that loaded before any of the other calls to the PFX the file on disk always exists, so it never hits the parallel "first" load problem.

**Comment by CIPop** [comment]
Thanks @bartonjs . We've seen the issue one more time in Win7 with (I assume) the new lock in place. Since it may be caused by something else, I'll wait for a dump before I make any other changes to the loader.
