### PR TITLE
Http2LoopbackConnection: Wait for pending ACK before setting up for new ignored settings frames

### LINKED ISSUE #39082: Http2_InitialWindowSize_ClientDoesNotExceedWindows test sporadically failing CI
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38804~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190701.1/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2~2FHttp2_InitialWindowSize_ClientDoesNotExceedWindows

e.g.
```
Windows.81.Amd64.Open-x64-Debug
Get Repro environment
Unhandled Exception of Type Xunit.Sdk.FalseException
Message :
Assert.False() Failure
Expected: False
Actual:   True
Stack Trace :
   at System.Net.Test.Common.Http2LoopbackConnection.ExpectSettingsAck() in /_/src/Common/tests/System/Net/Http/Http2LoopbackConnection.cs:line 199
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.Http2_InitialWindowSize_ClientDoesNotExceedWindows() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 1193
--- End of stack trace from previous location where exception was thrown ---
```

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
Make the Http2LoopbackConnection.ExpectSettingsAck() method handle outstanding acks more gracefully. This should fix #39082.

### CODE REVIEW

**Comment by davidsh** [comment]
@eiriktsarpalis Regarding https://github.com/dotnet/corefx/pull/39222#issuecomment-508806314, you can't use multiple "/azp" commands in one comment.  We usually use "/azp run" to kick off both inner and outer loop test runs.

File: src/Common/tests/System/Net/Http/Http2LoopbackConnection.cs [hunk 1]
```diff
@@ -185,19 +186,28 @@ private async Task<Frame> ReadFrameAsync(CancellationToken cancellationToken)
...
+        public async Task ExpectSettingsAckAsync(TimeSpan timeout)
         {
             // The timing of when we receive the settings ack is not guaranteed.
             // To simplify frame processing, just record that we are expecting one,
             // and then filter it out in ReadFrameAsync above.
 
-            Assert.False(_ignoreSettingsAck);
-            _ignoreSettingsAck = true;
+            // In case of a pending settings ack, wait for it or time out
+            var currentTask = _ignoredSettingsAckPromise?.Task;
```
Comment (bartonjs) [inline src/Common/tests/System/Net/Http/Http2LoopbackConnection.cs]: Style: This is an improper use of `var` (only allowed with `new`, hard cast, and as-cast as our common interpretation of "obvious": https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md rule 10)

File: src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs [hunk 2]
```diff
@@ -306,7 +306,7 @@ public async Task GetAsync_StreamRefused_RequestIsRetried()
                 (int streamId1, HttpRequestData requestData1) = await connection.ReadAndParseRequestHeaderAsync(readBody: true);
 
                 // Send SETTINGS frame to change stream limit to 0, allowing us to send a REFUSED_STREAM error due to the new limit
-                connection.ExpectSettingsAck();
+                await connection.ExpectSettingsAckAsync(TimeSpan.FromSeconds(30.0));
```
Comment (bartonjs) [inline src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs]: Should all of these 30 second TimeSpans be one static readonly somewhere expressing the recommended default for this?

Comment (bartonjs) [reply src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs]: Also, 30 seconds is a really long time in test-land.

File: src/Common/tests/System/Net/Http/Http2LoopbackConnection.cs [hunk 3]
```diff
@@ -145,9 +145,10 @@ private async Task<Frame> ReadFrameAsync(CancellationToken cancellationToken)
                 throw new Exception("Connection stream closed while attempting to read frame body.");
             }
 
-            if (_ignoreSettingsAck && header.Type == FrameType.Settings && header.Flags == FrameFlags.Ack)
+            if (_ignoredSettingsAckPromise != null && header.Type == FrameType.Settings && header.Flags == FrameFlags.Ack)
             {
-                _ignoreSettingsAck = false;
+                _ignoredSettingsAckPromise?.TrySetResult(false);
```
Comment (bartonjs) [inline src/Common/tests/System/Net/Http/Http2LoopbackConnection.cs]: Why `?.`? You've already checked it for null... is it expected to be a multi-thread race?

File: src/Common/tests/System/Net/Http/Http2LoopbackConnection.cs [hunk 4]
```diff
@@ -185,19 +186,28 @@ private async Task<Frame> ReadFrameAsync(CancellationToken cancellationToken)
...
             // To simplify frame processing, just record that we are expecting one,
             // and then filter it out in ReadFrameAsync above.
 
-            Assert.False(_ignoreSettingsAck);
-            _ignoreSettingsAck = true;
+            // In case of a pending settings ack, wait for it or time out
+            var currentTask = _ignoredSettingsAckPromise?.Task;
+            if (currentTask != null)
+            {
+                if (await Task.WhenAny(currentTask, Task.Delay(timeout)) != currentTask)
```
Comment (scalablecory) [inline src/Common/tests/System/Net/Http/Http2LoopbackConnection.cs]: We have an extension method for this:

```c#
await currentTask.TimeoutAfter(timeout);
```

File: src/Common/tests/System/Net/Http/Http2LoopbackConnection.cs [hunk 5]
```diff
@@ -185,19 +186,28 @@ private async Task<Frame> ReadFrameAsync(CancellationToken cancellationToken)
...
             _connectionSocket = null;
             _connectionStream = null;
-            _ignoreSettingsAck = false;
+            _ignoredSettingsAckPromise = null;
 
             return (oldSocket, oldStream);
         }
 
-        public void ExpectSettingsAck()
+        public async Task ExpectSettingsAckAsync(TimeSpan timeout)
```
Comment (scalablecory) [inline src/Common/tests/System/Net/Http/Http2LoopbackConnection.cs]: The code calling this method doesn't appear to need a customizeable timeout. It's reasonable to remove this param. Alternately, something like this would reduce the noise elsewhere:

```c#
public async Task ExpectSettingsAckAsync(int millisecondsTimeout = 30000)
```

**Comment by scalablecory** [comment]
A simpler way to implement this would be to change `_ignoreSettingsAck` to an `int` of how many ACKs to expect, in the event that we send multiple settings frames, rather than a `bool`.

File: src/Common/tests/System/Net/Http/Http2LoopbackConnection.cs (hunk 5 above)
Comment (scalablecory) [reply src/Common/tests/System/Net/Http/Http2LoopbackConnection.cs]: Also can we add a comment for this method? Calls it it look a lot like we're waiting for a settings ACK rather than just telling the connection that one will be coming in the future.

File: src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs (hunk 2 above)
Comment (eiriktsarpalis) [reply src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs]: That's merely reflecting how timeouts are passed in general in that particular test suite, e.g. https://github.com/dotnet/corefx/blob/c663f3ff12bcd95c54e9106aee218671d06fd675/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs#L85

File: src/Common/tests/System/Net/Http/Http2LoopbackConnection.cs (hunk 4 above)
Comment (eiriktsarpalis) [reply src/Common/tests/System/Net/Http/Http2LoopbackConnection.cs]: Thanks

**Comment by davidsh** [comment]
@eiriktsarpalis Thanks for working on the PR!

One feedback I'd like to give is for style things like the best formats for git commit messages and titles. This helps reviewers like us be more efficient. It also makes the PR review process easier to track since your git commit message translates into the PR title itself.

This is a good reference: https://chris.beams.io/posts/git-commit/

File: src/Common/tests/System/Net/Http/Http2LoopbackConnection.cs (hunk 5 above)
Comment (eiriktsarpalis) [reply src/Common/tests/System/Net/Http/Http2LoopbackConnection.cs]: It's reflecting the style already present in the class, e.g. https://github.com/dotnet/corefx/blob/c663f3ff12bcd95c54e9106aee218671d06fd675/src/Common/tests/System/Net/Http/Http2LoopbackConnection.cs#L115

File: src/Common/tests/System/Net/Http/Http2LoopbackConnection.cs (hunk 3 above)
Comment (eiriktsarpalis) [reply src/Common/tests/System/Net/Http/Http2LoopbackConnection.cs]: It's not really meant to be thread safe, so can remove.

**Comment by eiriktsarpalis** [comment]
> A simpler way to implement this would be to change _ignoreSettingsAck to an int of how many ACKs to expect, in the event that we send multiple settings frames, rather than a bool.

I didn't want to break the current invariant of not allowing more than one frame at a time.

**Comment by scalablecory** [comment]
> > A simpler way to implement this would be to change _ignoreSettingsAck to an int of how many ACKs to expect, in the event that we send multiple settings frames, rather than a bool.
> 
> I didn't want to break the current invariant of not allowing more than one ignored settings frame at a time.

HTTP2 allows multiple outstanding settings updates; I think it'd be good to support in our loopback code to allow testing of that. At the same time, it would also be useful to have a feature that explicitly waits until all settings have been ACKed.

**Comment by scalablecory** [comment]
@karelz do you know why @eiriktsarpalis is unable to run /azp commands?

**Comment by stephentoub** [comment]
@safern, @ViktorHofer, can you help with fixing permissions?

**Comment by ViktorHofer** [comment]
Sent out a mail.

**Comment by safern** [comment]
it seems like he's part of the .NET Foundation and the Microsoft team, but he doesn't have write access to the corefx repo, so that's why he can't trigger a build. I think he needs to be added to the github dotnet-corefx team... @danmosemsft @terrajobst might be able to help with that? Sent out an email as well.

**Comment by ViktorHofer** [comment]
Should we send our yet another mail just to make sure? 😂

**Comment by danmosemsft** [comment]
I don't sufficiently understand  our permissions groups  : need Immo.

**Comment by eiriktsarpalis** [comment]
Trying again,

/azp run

**Comment by safern** [comment]
> Trying again,
>
> /azp run

The comment can't have anything else, but /azp run in order to work.

**Comment by scalablecory** [comment]
@eiriktsarpalis can you think of how this might be modified to allow for multiple outstanding settings frames? I don't think we need support for it immediately, but want to at least make sure this code won't need to be rewritten to allow for that.

**Comment by eiriktsarpalis** [comment]
@scalablecory it should be pretty simple, however it will make the test assertions weaker in the sense that they would not fail if the client never sent back acks.

**Comment by eiriktsarpalis** [comment]
@scalablecory I've got [this](https://github.com/eiriktsarpalis/corefx/commit/c1aac69084172df9e742f3c3e410bdb94e11dbdc). Let me know if preferable and will create a PR with that change instead.

**Comment by davidsh** [comment]
>@scalablecory I've got this. Let me know if preferable and will create a PR with that change instead.

>It should be pretty simple, however it will make the test assertions weaker in the sense that they would not fail if the client never sent back acks.

I would prefer we go with the current approach here in this PR for now. I think we can consider something more complex (like supporting multiple acks) in a later PR.

**Comment by eiriktsarpalis** [comment]
Ok, merging ahead then.
